### ISSUE TITLE
'Task' object has no attribute 'FROM_ARGS' using 'local_action' module

### ISSUE THREAD

**Issue by Jaskaranbir** [ansible/ansible#41469]
##### SUMMARY

Using `include_role` module with `local_action` in ***main playbook*** causes error: `ERROR! Unexpected Exception, this is probably a bug: 'Task' object has no attribute 'FROM_ARGS'`

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

local_action

##### ANSIBLE VERSION

```
ansible 2.5.4
  config file = /vagrant/ansible.cfg
  configured module search path = ['/home/core/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/bin/active_python/lib/python3.6/site-packages/ansible
  executable location = /opt/bin/active_python/bin/ansible
  python version = 3.6.0 (default, Jan 23 2017, 17:33:57) [GCC 4.0.4]
```

##### CONFIGURATION

(Installed Ansible using PIP, so it had no default configuration).
```
COLOR_CHANGED(/vagrant/ansible.cfg) = yellow
COLOR_DEBUG(/vagrant/ansible.cfg) = dark gray
COLOR_DEPRECATE(/vagrant/ansible.cfg) = purple
COLOR_DIFF_ADD(/vagrant/ansible.cfg) = green
COLOR_DIFF_LINES(/vagrant/ansible.cfg) = cyan
COLOR_DIFF_REMOVE(/vagrant/ansible.cfg) = red
COLOR_ERROR(/vagrant/ansible.cfg) = red
COLOR_HIGHLIGHT(/vagrant/ansible.cfg) = white
COLOR_OK(/vagrant/ansible.cfg) = green
COLOR_SKIP(/vagrant/ansible.cfg) = cyan
COLOR_UNREACHABLE(/vagrant/ansible.cfg) = red
COLOR_VERBOSE(/vagrant/ansible.cfg) = blue
COLOR_WARN(/vagrant/ansible.cfg) = bright purple
DEFAULT_HOST_LIST(/vagrant/ansible.cfg) = ['/vagrant/inventory/vagrant.yml']
DEFAULT_MANAGED_STR(/vagrant/ansible.cfg) = Please do not modify this file directly as it is managed by Ansible and could be overwritten.
DEFAULT_REMOTE_USER(/vagrant/ansible.cfg) = core
HOST_KEY_CHECKING(/vagrant/ansible.cfg) = False
RETRY_FILES_ENABLED(/vagrant/ansible.cfg) = False
```

##### OS / ENVIRONMENT

CoreOS Stable 1745.5.0 (running the playbook locally)
Ansible installed using PIP
Python: [ActivePython 3.6](https://www.activestate.com/activepython/downloads)

##### STEPS TO REPRODUCE

Try the following playbook (that's my main playbook):

```yaml
---
- name: Test-Playbook
  hosts: test-host
  become: false
  tasks:
    - name: SomeTest-Task
      local_action:
        module: include_role
       # Role doesn't matter (could be an empty yaml role file, error still occurs)
        name: roles/somerole
```

The following however, works:

```yaml
---
- name: Test-Playbook
  hosts: test-host
  become: false
  tasks:
    - name: SomeTest-Task
      include_role:
        name: roles/somerole
      delegate_to: 127.0.0.1
```

Why am I defining sub-tasks? Because the main task is generating some file for multiple hosts, and sub tasks depict which files are generated for which hosts (using the roles defined). If this is a bad practice, please let me know.

I prefer `local_action` instead of `delegate_to` because its more declarative here in my opinion.

##### EXPECTED RESULTS

The playbook to succeed.

##### ACTUAL RESULTS

Failed with error: `ERROR! Unexpected Exception, this is probably a bug: 'Task' object has no attribute 'FROM_ARGS'`

```
TASK [SomeTest-Task] *************************************************************************************************************************************************************************
task path: /vagrant/playbook.yml:8
ok: [test-host] => {
    "changed": false,
    "include_variables": {
        "name": "somerole"
    }
}
ERROR! Unexpected Exception, this is probably a bug: 'Task' object has no attribute 'FROM_ARGS'
the full traceback was:

Traceback (most recent call last):
  File "/opt/bin/active_python/bin/ansible-playbook", line 118, in <module>
    exit_code = cli.run()
  File "/opt/bin/active_python/lib/python3.6/site-packages/ansible/cli/playbook.py", line 122, in run
    results = pbex.run()
  File "/opt/bin/active_python/lib/python3.6/site-packages/ansible/executor/playbook_executor.py", line 159, in run
    result = self._tqm.run(play=play)
  File "/opt/bin/active_python/lib/python3.6/site-packages/ansible/executor/task_queue_manager.py", line 289, in run
    play_return = strategy.run(iterator, play_context)
  File "/opt/bin/active_python/lib/python3.6/site-packages/ansible/plugins/strategy/linear.py", line 332, in run
    variable_manager=self._variable_manager
  File "/opt/bin/active_python/lib/python3.6/site-packages/ansible/playbook/included_file.py", line 151, in process_include_results
    for from_arg in new_task.FROM_ARGS:
AttributeError: 'Task' object has no attribute 'FROM_ARGS'
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@Jaskaranbir Thanks for reporting this issue. I am able to reproduce this on Stable-2.5 but not on Stable-2.6 and 2.7-devel. I think this is fixed via 0b0bb65198f 

cc @sivel

**Comment by bcoca** [comment]
fyi, include/imports are always 'local' so making it `local_action` is a noop, the same with `delegate_to`, it is ignored for include_X (for imports it gets inherited by the imported tasks).

**Comment by sivel** [comment]
This issue was resolved in 3d5a7d6dc2e50575872f1dc15fc4f8016dac5db5 and will be included in the upcoming 2.6 release.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
