### PR TITLE
VMware: Fix module vmware_host

### LINKED ISSUE #44772: vmware_host: Module exits if re-run when host is not in a cluster and just in a datacenter
##### SUMMARY
If a ESXi host is configured to be just in a datacenter in the vCenter inventory and not a cluster the module will add the ESXi host with a status of ok.  When the module is re-run it exits rather than returns a state of Ok.

When preparing additional ESXi hosts we need to do the configuration outside of a production cluster at the datacenter level. Once configured then it is moved into a production cluster where NSX will auto-configure things like VXLAN vmkernel ports.

There maybe occasions where the playbook needs to be re-run during configuration and having the playbook continue is required for this.

FYI when the ESXi host is configured to be in a cluster the module will add the host with a status of Ok. When the module is re-run then the module will return a state of Ok and the playbook continues.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_host.py

##### ANSIBLE VERSION
```
ansible 2.6.2
  config file = /root/code/vmware-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
Ansible run environment: CentOS7
Target vCenter: 6.7
Target ESXi 6.7

##### STEPS TO REPRODUCE
```yaml
- name: 'Add ESXi host to vCenter'
  connection: 'local'
  vmware_host:
    hostname: '{{ vcenter }}'
    username: '{{ ansible_vcenter_username }}'
    password: '{{ ansible_vcenter_password }}'
    datacenter_name: '{{ pod_name }}'
    folder: '{{ dc_name }}/host'
    esxi_hostname: '{{ ansible_host }}'
    esxi_username: '{{ esxi_root_account }}'
    esxi_password: '{{ esxi_password }}'
    state: 'present'
    validate_certs: '{{ validate_certs }}'
```

##### EXPECTED RESULTS
Module returns a status of Ok and playbook continues

##### ACTUAL RESULTS
```
TASK [add_esxi_to_vcenter_datacenter : Add ESXi host to vCenter] ******************************************************************************************************************************************************************************************************************
fatal: [<ESXI HOSTNAME>]: FAILED! => {"changed": false, "msg": "Failed to add host <ESXI HOSTNAME> to vCenter: The name '<ESXI HOSTNAME>' already exists."}
```

### PR DESCRIPTION
**Pull request by ckotte**
##### SUMMARY
- An ESXi host cannot be added, removed, or re-connected if it's located under a folder instead of a cluster
- Fixes https://github.com/ansible/ansible/issues/44772 if you connect the ESXi host under a datacenter
- moves the host to a new location (from cluster to folder, or vice versa)
- fetches SSL thumbprint automatically, if `ssl_thumbprint` isn't set, without executing the tasks again if failed because of SSL verify fault
- connects the host if it's disconnected (enabled by default)

##### ISSUE TYPE
- Bugfix Pull Request
- Feature Pull Request

##### COMPONENT NAME
vmware_host

##### ANSIBLE VERSION
```
# ansible --version
ansible 2.6.3
  config file = /root/ansible-vmware/ansible.cfg
  configured module search path = [u'/root/ansible-vmware/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### ADDITIONAL INFORMATION
before:
```
TASK [esxi : Add ESXi host to vCenter] *********************************************************************************************************************************************************************************************
fatal: [esxi_host -> jump_server]: FAILED! => {"changed": false, "msg": "Failed to add host esxi_host to vCenter: (vim.fault.DuplicateName) {\n   dynamicType = <unset>,\n   dynamicProperty = (vmodl.DynamicProperty) [],\n   msg = \"The name 'esxi_host' already exists.\",\n   faultCause = <unset>,\n   faultMessage = (vmodl.LocalizableMessage) [],\n   name = 'esxi_host',\n   object = 'vim.HostSystem:host-2640'\n}"}
```
```
TASK [esxi : Remove ESXi host from vCenter] *********************************************************************************************************************************************************************************************
fatal: [esxi_host -> jump_server]: FAILED! => {"changed": false, "msg": "'vim.ComputeResource' object has no attribute 'runtime'"}
```
```
TASK [esxi : Reconnect ESXi host] *********************************************************************************************************************************************************************************************
fatal: [esxi_host -> jump_server]: FAILED! => {"changed": false, "msg": "Failed to reconnect host esxi_host to vCenter: A specified parameter was not correct: cnxSpec"}
```
after:
```paste below
TASK [esxi : Add ESXi host to vCenter] *******************************************************************************************************************************************************************************************************
changed: [esxi_host -> jump_server]
```

### CODE REVIEW

**Comment by ckotte** [comment]
> The test `ansible-test sanity --test validate-modules` [[explain](https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/validate-modules.html)] failed with 1 error:
> 
> ```
> lib/ansible/modules/cloud/vmware/vmware_host.py:0:0: E309 version_added for new option (folder_name) should be 2.8. Currently 2.6
> ```

Changed version_added from 2.6 to 2.8. Looks like adding an ESXi host to a folder didn't even work in 2.6.

**Comment by Akasurde** [comment]
> > The test `ansible-test sanity --test validate-modules` [[explain](https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/validate-modules.html)] failed with 1 error:
> > ```
> > lib/ansible/modules/cloud/vmware/vmware_host.py:0:0: E309 version_added for new option (folder_name) should be 2.8. Currently 2.6
> > ```
> 
> Changed version_added from 2.6 to 2.8. Looks like adding an ESXi host to a folder didn't even work in 2.6.

No, error is suggesting that you are adding new parameter to Ansible module, currently documentation is indicating that it is being added in 2.6 but current development cycle is 2.8. 

I would recommend to add new `aliases` rather than renaming parameter altogether for backward compatibility.

**Comment by ckotte** [comment]
> I would recommend to add new `aliases` rather than renaming parameter altogether for backward compatibility.

Ok. Makes sense. I will do that.

I still think that the folder feature didn't work. There was also no test created for it. I will add that too once I figured out how to do it...

**Comment by mattclay** [comment]
CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/86604/86/tests

**Comment by ckotte** [comment]
> CI failure in integration tests: https://app.shippable.com/github/ansible/ansible/runs/86604/86/tests

I know. Looks like you cannot add an ESXi host to a folder with vcsim. I need more time to investigate.

**Comment by ckotte** [comment]
It's not possible to test the connection of an ESXi host to a folder with vcsim.

File: lib/ansible/modules/cloud/vmware/vmware_host.py [hunk 1]
```diff
@@ -50,11 +50,12 @@
     - "For example, if there is a datacenter 'dc1' under folder called 'Site1' then, this value will be '/Site1/dc1/host'."
     - "Here 'host' is an invisible folder under VMware Web Client."
     - "Another example, if there is a nested folder structure like '/myhosts/india/pune' under
-       datacenter 'dc2', then C(folder) value will be '/dc2/host/myhosts/india/pune'."
+       datacenter 'dc2', then C(folder_name) value will be '/dc2/host/myhosts/india/pune'."
     - "Other Examples: "
     - "  - '/Site2/dc2/Asia-Cluster/host'"
     - "  - '/dc3/Asia-Cluster/host'"
     version_added: "2.6"
+    aliases: ['folder_name']
```
Comment (tchernomax) [inline lib/ansible/modules/cloud/vmware/vmware_host.py:66]: I am ok to change "folder" to "folder_name" as the option for the datacenter name is "datacenter_name".
But if you do, do it everywhere (option name and python variable) and add an alias "folder" for retro-compatibility.

File: lib/ansible/modules/cloud/vmware/vmware_host.py [hunk 2]
```diff
@@ -283,11 +284,13 @@ def reconnect_host_to_vcenter(self):
...
-            reconnecthost_args['cnxSpec'] = self.get_host_connect_spec()
 
             for count in range(0, 2):
                 try:
-                    task = self.host.ReconnectHost_Task(**reconnecthost_args)
+                    if self.folder:
+                        task = self.host.host[0].ReconnectHost_Task(**reconnecthost_args)
+                    elif self.cluster:
+                        task = self.host.ReconnectHost_Task(**reconnecthost_args)
                     success, result = wait_for_task(task)
```
Comment (tchernomax) [inline lib/ansible/modules/cloud/vmware/vmware_host.py]: IMHO it would be simpler to set self.host as a HostSystem object.
And add a self.host_parent_compute_resource variable for the parent ComputeResource (when self.folder).

the host_parent_compute_resource would only be used for Destroy_Task as: https://www.vmware.com/support/developer/vc-sdk/visdk25pubs/ReferenceGuide/vim.HostSystem.html
> Invoking destroy on a HostSystem of standalone type throws a NotSupported fault. A standalone HostSystem can be destroyed only by invoking destroy on its parent ComputeResource.

**Review by tchernomax — CHANGES_REQUESTED** [review]

File: lib/ansible/modules/cloud/vmware/vmware_host.py (hunk 1 above)
Comment (dagwieers) [reply lib/ansible/modules/cloud/vmware/vmware_host.py:66]: I would leave it like this. I don't see what `_name` adds except maybe confusion. Obviously it's the folder you have to provide. I would leave it at `C(folder)` in the description.

**Review by dagwieers — CHANGES_REQUESTED** [review]

File: lib/ansible/modules/cloud/vmware/vmware_host.py (hunk 1 above)
Comment (tchernomax) [reply lib/ansible/modules/cloud/vmware/vmware_host.py:66]: that's also ok for me to leave it like this

Comment (ckotte) [reply lib/ansible/modules/cloud/vmware/vmware_host.py:66]: The "problem" with all the vmware modules is that they are not consistent. One module uses e.g. datacenter_name and the other uses only datacenter and so on.

Comment (dagwieers) [reply lib/ansible/modules/cloud/vmware/vmware_host.py:66]: I think we need to have consistency for all the VMware-related modules wrt. this. And my proposal is to not use `_name` for the standard parameters. (We can have them as aliases though)

Comment (dagwieers) [reply lib/ansible/modules/cloud/vmware/vmware_host.py:66]: I will put it on the agenda for next week's meeting.

**Comment by ckotte** [comment]
Ok. I had the impression that parameters with _name are more used (datacenter _name, cluster_name, switch_name, etc. pp. ). I'm fine if we can achieve consistency.So, for example, you recommend to change datacenter_name to datacenter and (only) add an alias for backward compatibility?

File: lib/ansible/modules/cloud/vmware/vmware_host.py (hunk 1 above)
Comment (ckotte) [reply lib/ansible/modules/cloud/vmware/vmware_host.py:66]: Ok. I had the impression that parameters with _name are more used (datacenter _name, cluster_name, switch_name, etc. pp. ). I'm fine if we can achieve consistency.So, for example, you recommend to change datacenter_name to datacenter and (only) add an alias for backward compatibility?

**Comment by tchernomax** [comment]
@ckotte maybe you can separate this PR in two:
* rename
* fix

**Comment by ckotte** [comment]
> @ckotte maybe you can separate this PR in two:
> 
> * rename
> * fix

I just added an alias on top of the fix. I don't want to create and manage another branch and PR just for this little fix. I also use that module already in my "production" playbook and I want to use `folder_name` because almost everything other parameter also uses `_name`.

"They" just need to establish a "vmware-related module standard parameter (and alias) naming scheme".

File: lib/ansible/modules/cloud/vmware/vmware_host.py (hunk 1 above)
Comment (dagwieers) [reply lib/ansible/modules/cloud/vmware/vmware_host.py:66]: I think that's how it starts to diverge, impressions of what other people use ;-)
No worries, a standard is what we need, and any standard will do. Join the next VMware meeting (ansible/community#233) to voice your opinion !

File: lib/ansible/modules/cloud/vmware/vmware_host.py (hunk 2 above)
Comment (tchernomax) [reply lib/ansible/modules/cloud/vmware/vmware_host.py]: @ckotte What do you think ?

Comment (ckotte) [reply lib/ansible/modules/cloud/vmware/vmware_host.py]: > @ckotte What do you think ?

Yes, I haven't had time for this yet.  Could you provide me some example code?

Comment (tchernomax) [reply lib/ansible/modules/cloud/vmware/vmware_host.py]: @ckotte https://paste.gnome.org/pck6vwny2

Comment (ckotte) [reply lib/ansible/modules/cloud/vmware/vmware_host.py]: Thx. I needed to update the remove method as well.
```
if self.folder:
    task = self.host_parent_compute_resource.Destroy_Task()
elif self.cluster:
    task = self.host.Destroy_Task()
changed, result = wait_for_task(task)
```
(You mentioned this in the first post already)

**Review by tchernomax — APPROVED** [review]
LGTM

File: lib/ansible/modules/cloud/vmware/vmware_host.py (hunk 1 above)
Comment (ckotte) [reply lib/ansible/modules/cloud/vmware/vmware_host.py:66]: Changed back to folder, but leave alias.

**Comment by ckotte** [comment]
@tchernomax @Akasurde Could you please review the module again? I added update functionality and I needed to basically refactor the module.

**Comment by corbinstuard** [comment]
What's holding this PR up? I'm currently experiencing the issue where adding a host that is already connected errors out instead or returning 'ok':

```
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_vmware_host_payload_vglXIB/__main__.py", line 258, in add_host_to_vcenter
    success, result = wait_for_task(task)
  File "/tmp/ansible_vmware_host_payload_vglXIB/ansible_vmware_host_payload.zip/ansible/module_utils/vmware.py", line 68, in wait_for_task
    raise_from(TaskError(error_msg, host_thumbprint), task.info.error)
  File "/tmp/ansible_vmware_host_payload_vglXIB/ansible_vmware_host_payload.zip/ansible/module_utils/six/__init__.py", line 744, in raise_from
    raise value

fatal: [10.1.2.71 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "add_connected": true,
            "cluster_name": null,
            "datacenter_name": "dispersive",
            "esxi_hostname": "10.1.2.71",
            "esxi_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "esxi_ssl_thumbprint": "",
            "esxi_username": "root",
            "folder": "/dispersive/host",
            "hostname": "10.1.2.19",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "state": "present",
            "username": "administrator@vsphere.local",
            "validate_certs": false
        }
    },
    "msg": "Failed to add host 10.1.2.71 to vCenter: The name '10.1.2.71' already exists."
```

**Comment by ckotte** [comment]
@akashihi Could you please approve this PR? I don't get any review since October 2018!!

**Comment by Akasurde** [comment]
Closing and re-opening for CI trigger.

**Comment by Akasurde** [comment]
@ckotte Thanks for the contribution.
