### ISSUE TITLE
unexpected keyword argument 'private_key_file' on included play

### ISSUE THREAD

**Issue by rrtj3** [ansible/ansible#3113]
Testing a playbook that I have that works on 1.1 on latest 1.2-git, and am having an issue with including a playbook in another playbook like so:

Main playbook:

``` yaml

---

- hosts: 127.0.0.1
  connection: local
  user: itssa
  sudo: false
  gather_facts: false
  serial: 1


  tasks:

    # Bunch of other tasks above this.

    - name: Wait for post-install ssh to become available
      local_action: wait_for host=rrt80.pvt.hawaii.edu port=22 state=started timeout=1800 delay=120

- include: initial_play_include.yml
```

initial_play_include.yml playbook:

``` yaml

---

- hosts: initialsetup
  user: itssa
  sudo: true
  gather_facts: false
  serial: 1

  vars_prompt:
    - name: "root_password"
      prompt: "Enter root password for VM"
      private: yes
      confirm: yes

  tasks:
    - name: Set root user password
      shell: echo '${root_password}' | /usr/bin/passwd --stdin root

    # More tasks....

```

Once ansible-playbook gets to the included playbook I now get a traceback on the first included task in it:

PLAY [initialsetup] **********************************************************\* 

TASK: [Set root user password] ***********************************************\* 
fatal: [rrt80.pvt.hawaii.edu] => Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ansible/runner/**init**.py", line 344, in _executor
    if self.inventory.basedir() is not None:
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 423, in _executor_internal
    else:
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 559, in _executor_internal_inner
    "(/sbin/md5sum -q %s 2>/dev/null)" % path,  # ?
  File "/usr/lib/python2.6/site-packages/ansible/runner/connection.py", line 36, in connect
    conn = utils.plugins.connection_loader.get(transport, self.runner, host, port, user=user, password=password)
  File "/usr/lib/python2.6/site-packages/ansible/utils/plugins.py", line 170, in get
TypeError: __init__() got an unexpected keyword argument 'private_key_file'

I found that if I set 'sudo: true' in the first playbook that it works as expected. Which is ok for me, but thought I should note that this used to work. If it's not a behavior that one can expect to work it should probably give a nice warning.

**Comment by mpdehaan** [comment]
It should work, I'll see why an unexpected argument might be getting passed.

**Comment by mpdehaan** [comment]
I'm not seeing this error on my end.

Is there a chance you have an unclean install where some files are getting picked up from your python path?

I see all the connection plugin constructors are taking (_args, *_kwargs) or explicitly take this parameter.

The second play doesn't specify a connection type so it should be loading whatever you have for the default and I'm curious as to how sudo would play a role.

**Comment by rrtj3** [comment]
Hmm. Ok. I don't think I've got any old installations laying around. I just to 'make rpm' and install those, then uninstall, etc... to switch between versions. I'll see if I can poke some more into this.

**Comment by mpdehaan** [comment]
Yep, that would be good.  I'm unable to reproduce this one and _suspect_ more people would be yelling about this error if they were getting it, but would like to track down before the release if possible.

**Comment by rrtj3** [comment]
Sorry, am on vacation and won't be able to get to this before 06/10 release.

**Comment by mpdehaan** [comment]
Please let me know if this still occurs for you in 1.3 if so we can reopen this.
