### ISSUE TITLE
Error creating directories using file modules.

### ISSUE THREAD

**Issue by mananmehra** [ansible/ansible#14227]
Ansible Version - 2.0, 2.0.0.2
Module - File
Description - Trying to create directories more than 1 level deep gives following error:

There was an issue creating /dir1/dir2 as requested: 'module' object has no attribute 'EEXISTS'

If i remove dir2, it works. This command use to work with ansible version 1.9.2

**Comment by bcoca** [comment]
# Module Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved two separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by geerlingguy** [comment]
Btw, this is a duplicate of https://github.com/ansible/ansible-modules-core/issues/2473
