### ISSUE TITLE
Error Accessing Windows Machine: "ssl: 'Session' object has no attribute 'merge_environment_settings'"

### ISSUE THREAD

**Issue by mwhite14** [ansible/ansible#15973]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
  ansible 2.0.2.0
  config file = /home/ubuntu/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

   Default configuration
##### OS / ENVIRONMENT

```
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty

```
##### SUMMARY

After upgrading to Ansible 2.0.2 my Windows playbooks throw an Error when trying to access the target machine.
##### STEPS TO REPRODUCE

```
    ansible_user: administrator
    ansible_ssh_pass: pa$$word
    ansible_port: 5986
    ansible_connection: winrm
```
##### EXPECTED RESULTS

```
To access the windows target.
```
##### ACTUAL RESULTS

```
TASK [setup] *******************************************************************
<10.0.15.203> ESTABLISH WINRM CONNECTION FOR USER: administrator on PORT 5986 TO 10.0.15.203
fatal: [10.0.15.203]: FAILED! => {"failed": true, "msg": "ssl: 'Session' object has no attribute 'merge_environment_settings'"}
```

**Comment by mwhite14** [comment]
The previous version of Ansible I was on is 2.0.0.2

**Comment by jhawkesworth** [comment]
Bit of a guess, but I notice you have set 

`ansible_ssh_pass`

I think the new form should be

`ansible_password`

Please can you 

1/ try changing the inventory as above

2/ run with -vvvvvvv to see if there is any further debug information available.

3/ please advise the version of pywinrm you are using (pip list should show this)

4/ please advise windows version(s) you are targetting.

**Comment by mwhite14** [comment]
1) Changed it and still had same error

2) Output of -vvvvvvv:

```
TASK [setup] *******************************************************************
<10.0.15.234> ESTABLISH WINRM CONNECTION FOR USER: administrator on PORT 5986 TO 10.0.15.234
<10.0.15.234> WINRM CONNECT: transport=ssl endpoint=https://10.0.15.234:5986/wsman
<10.0.15.234> WINRM CONNECTION ERROR: 'Session' object has no attribute 'merge_environment_settings'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/connection/winrm.py", line 134, in _winrm_connect
    protocol.send_message('')
  File "/usr/local/lib/python2.7/dist-packages/winrm/protocol.py", line 205, in send_message
    return self.transport.send_message(message)
  File "/usr/local/lib/python2.7/dist-packages/winrm/transport.py", line 160, in send_message
    self.session = self.build_session()
  File "/usr/local/lib/python2.7/dist-packages/winrm/transport.py", line 120, in build_session
    settings = session.merge_environment_settings(url=self.endpoint, proxies={}, stream=None,
AttributeError: 'Session' object has no attribute 'merge_environment_settings'

fatal: [10.0.15.234]: FAILED! => {"failed": true, "msg": "ssl: 'Session' object has no attribute 'merge_environment_settings'"}
```

3) 

```
pywinrm (0.2.0)
```

4) Windows Server 2012 R2 RTM 64bit

**Comment by mwhite14** [comment]
**Solved**: Downgrading pywinrm to 0.1.0 fixed the issue. I have no idea how I got a version past the last official release.

**Comment by jhawkesworth** [comment]
Possibly because there are test builds of 0.2.0 in test pypi - see discussion here: https://groups.google.com/forum/#!topic/ansible-project/vEl-mrvFkrY

My guess is you had a version but were missing one of the dependencies - possibly requests-kerberos as that has been upgraded recently.

If you fancy trying the latest pywinrm I was able to install the test builds as follows:

 pip install requests-kerberos --upgrade
 pip install pywinrm[kerberos]==0.2rc4 -i https://testpypi.python.org/pypi --extra-index-url https://pypi.python.org/pypi

Otherwise, since your problem is solved, I'll close the issue.

**Comment by apintocr** [comment]
To install a working pywinrm version try:
    `pip install pywinrm==0.1.1`
That fixed this issues for me.

**Comment by jhawkesworth** [comment]
So... pywinrm 0.2.0 has been released and is well worth trying as it runs noticeably quicker.
I use this on ubuntu 14.04 pointing at Windows 10 and Server 2012 R2 hosts, so it is possible to get the newer version working using ansible 2.1.1 and latest devel.

I think 

pip install pywinrm --upgrade 

will now get you the latest version.  If that doesn't work for you please run a pip list and I'll compare the versions I have installed.

Hope this helps,

Jon

**Comment by gainskills** [comment]
@jhawkesworth 
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

#ansible --version
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

#python --version
Python 2.7.6

pywinrm 0.2.1 still failed with the same error.
Followed @apintocr 's note, It works after installed pywinrm0.1.1

**Comment by jhawkesworth** [comment]
I think something else is not quite right in your set up - I have been using pywinrm 0.2.0 since it came out.
Looking back at the conversation above I notice the original poster used
ansible_ssh_pass: pa$$word
but the ansible_ssh_* variables were deprecated in ansible 2, so instead use

ansible_password: pa$$word

(see the note here http://docs.ansible.com/ansible/intro_windows.html#inventory in the setup instructions)

please can you try using the new names for the connection parameters with pywinrm 0.2.x ?
Its well worth using the later version if at all possible as the testing I've done showed it to be much faster (at least against Windows Server 2008R2 and Windows Server 2012R2).

Jon

**Comment by gainskills** [comment]
@jhawkesworth  Thanks for your comment.
I did the testing by new names, here is my hosts content:

[windows]
10.10.6.12 ansible_user="_usrname_" ansible_password="_passwd_" ansible_port="5986" ansible_connection="winrm"

It doesn't work with pywinrm 0.2.1 but works with pywinrm0.1.1.
Thanks,

**Comment by donnieatbowie** [comment]
Hi. +1 regarding the 0.1.1 solution. 0.2.x doesn't work for me as well.

**Comment by jhawkesworth** [comment]
I suggest moving your connection-related settings (ansible_user, ansible_password, ansible_port, ansible_connection etc) to group_vars (instead of setting against the host vars).

I have connection settings set up in group_vars and have had no problems with any of the 0.2.x versions of pywinrm.

**Comment by donnieatbowie** [comment]
it is within group vars indeed.
