### PR TITLE
New module: Support manipulating XML files [files/xml]

### LINKED ISSUE #52: Get ansible-xml part of ansible core
XML Module should become part of Ansible core as that's really something belonging to core. Lets use this ticket to track the progress on getting it part of Ansible core.

### LINKED ISSUE #74: Update in code documentation
See 
https://github.com/ansible/ansible-modules-core/pull/4122#discussion-diff-69840959
https://github.com/ansible/ansible-modules-core/pull/4122#discussion-diff-69841138
https://github.com/ansible/ansible-modules-core/pull/4122#discussion-diff-69841295
https://github.com/ansible/ansible-modules-core/pull/4122#discussion_r69841679
https://github.com/ansible/ansible-modules-core/pull/4122#discussion-diff-69841743

### LINKED ISSUE #75: Update Python style
See 
https://github.com/ansible/ansible-modules-core/pull/4122#discussion-diff-69841931
https://github.com/ansible/ansible-modules-core/pull/4122#discussion_r69841931
https://github.com/ansible/ansible-modules-core/pull/4122#discussion_r69842054
https://github.com/ansible/ansible-modules-core/pull/4122#discussion-diff-69842304
https://github.com/ansible/ansible-modules-core/pull/4122#discussion_r69842304
https://github.com/ansible/ansible-modules-core/pull/4122#discussion_r69842409
https://github.com/ansible/ansible-modules-core/pull/4122#discussion_r69842471
https://github.com/ansible/ansible-modules-core/pull/4122#discussion-diff-69842514
https://github.com/ansible/ansible-modules-core/pull/4122#discussion_r69842514
https://github.com/ansible/ansible-modules-core/pull/4122#discussion-diff-69842591
https://github.com/ansible/ansible-modules-core/pull/4122#discussion_r69842591
https://github.com/ansible/ansible-modules-core/pull/4122#discussion-diff-69842697
https://github.com/ansible/ansible-modules-core/pull/4122#discussion_r69842697
https://github.com/ansible/ansible-modules-core/pull/4122#discussion-diff-69842897
https://github.com/ansible/ansible-modules-core/pull/4122#discussion_r69842897
https://github.com/ansible/ansible-modules-core/pull/4122#discussion-diff-69842945
https://github.com/ansible/ansible-modules-core/pull/4122#discussion_r69842945

### LINKED ISSUE #102: XML namespace issue
Hi, 

I have encounter issue with parser for XML when there is XML namespace while using xpath. 

Removing namespace fix an issue and I can then set rest of the values with xpath.  

**xmlns="http://java.sun.com/xml/ns/javaee"**

Original: 

`<web-app xmlns="http://java.sun.com/xml/ns/javaee" metadata-complete="true" version="3.0" xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">`

Working: 
`<web-app metadata-complete="true" version="3.0" xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">`

I think this might be a bug. 

All the best. 

Stefan

### LINKED ISSUE #107: Undefined namespace prefix\
My XML begins with the following name space: 
```
<data sql-datasource xmlns:data="http://jfreereport.sourceforge.net/namespaces/datasources/sql">
      <data property name="user"></data:property name="user">
      <data property name="password">encrypted:</data:property>
</data sql-datasource>
```

When I attempt to check the module to set the password: 

```
 - name: Modify Main Report
    xml:
      path: ./checkout/tmp/datasources/sql-ds.xml
      xpath: /sql-datasource/url
      namespaces: 
          data: "http://jfreereport.sourceforge.net/namespaces/datasources/sql"
      value: test
```
I get an error 

`failed: [localhost] (item=file-ds.xml) => {"failed": true, "item": "checkout/tmp/datasources/sql-ds.xml", "msg": "Xpath /data:sql-datasource causes a failure: Undefined namespace prefix`

### LINKED ISSUE #112: xpath does not reference a node on XML with long attributes ?
Hi, 

I have a problem for get value from XML file when file has long attributes on xpath.
If i delete attribute for LogonResponse and W-API-Session, it's work, but with, it not work.
 
**My XML file** 

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<LogonResponse xmlns="http://www.ibm.com/xmlns/systems/power/firmware/web/mc/2012_10/" xmlns:ns2="http://www.w3.org/XML/1998/namespace/k2" schemaVersion="V1_5_0">
    <Metadata>
        <Atom/>
    </Metadata>
    <X-API-Session kb="ROR" kxe="false">xcBN8vwYN6J0diUPAI-iMf79p7LPkwnjQW97GwH7u-Ylt1z4cbzRaJex_AHQlltQAlx0wRtrYrbMFZX16sIenrC6WPLMeW7-POOO6YMHvh9WqbDfdEfOYIyh5q7cbYCH8rakIyA8YXT91g6h6sL2dmoElAi2upRgi-ISYadETOcrI0Sym-z6jFNPtWpUIC8_dZ3D9X0gnpwFoYz-w9JsMAUv223736x4vpAHe6jfkxM=</X-API-Session>
</LogonResponse>
```

**My tasks in ansible** 

```
- name: Register x_api_session
  xml:
    xmlstring: "{{ lookup('file', '/tmp/test.xml') }}"
    xpath: /LogonResponse/X-API-Session
    content: 'text'
  register: session

```
**Error output :** 

> fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Xpath /LogonResponse/X-API-Session does not reference a node!"}

I do not know if this is a bug or not or a misunderstanding on my part ... 

Can you help me ?

Regards,

### LINKED ISSUE #114: '_ElementStringResult' object has no attribute 'attrname'
When running the integration tests from this project on the Ansible CI framwork on CentOS-6 (with native lxml v2.2.3) we get the following error:

    Couldn't delete xpath target: /business/rating/@subjective ('_ElementStringResult' object has no attribute 'attrname')

Here is the detailed output:

```
TASK [xml : Remove '/business/rating/@subjective'] *****************************
task path: /root/ansible/test/integration/targets/xml/tasks/test-remove-attribute.yml:7
Using module file /root/ansible/lib/ansible/modules/files/xml.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1496840875.06-126128364675744 `" && echo ansible-tmp-1496840875.06-126128364675744="` echo /root/.ansible/tmp/ansible-tmp-1496840875.06-126128364675744 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpYpbF4J TO /root/.ansible/tmp/ansible-tmp-1496840875.06-126128364675744/xml.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1496840875.06-126128364675744/ /root/.ansible/tmp/ansible-tmp-1496840875.06-126128364675744/xml.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/tmp/ansible-test-coverage-2aVbEu/coverage/injector.py /root/.ansible/tmp/ansible-tmp-1496840875.06-126128364675744/xml.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1496840875.06-126128364675744/" > /dev/null 2>&1 && sleep 0'
fatal: [testhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "add_children": null, 
            "attribute": null, 
            "content": null, 
            "count": false, 
            "ensure": "absent", 
            "input_type": "yaml", 
            "namespaces": {}, 
            "path": "/tmp/ansible-xml-beers.xml", 
            "pretty_print": false, 
            "print_match": false, 
            "set_children": null, 
            "state": "absent", 
            "value": null, 
            "xmlstring": "", 
            "xpath": "/business/rating/@subjective"
        }
    }, 
    "msg": "Couldn't delete xpath target: /business/rating/@subjective ('_ElementStringResult' object has no attribute 'attrname')"
}
```

### LINKED ISSUE #115: Older lxml versions have no predictable element attribute order
So it appears that the tests in this module expect a predictable element attribute order, which is only added since lxml v3.0alpha1. For example CentOS-6 natively ships with lxml v2.2.3.

For the effort of upstreaming this module, we opted to filter out these tests when the lxml version is not greater or equal to 3. The module still works fine, we simply are not comparing as smart as we should.

### LINKED ISSUE #116: Fails on python3 due to unicode-related errors
During the effort of upstreaming this module, we found that the module fails on Python 3 due to unicode-related problems.

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_xi97wmbt/ansible_module_xml.py", line 732, in <module>
    main()
  File "/tmp/ansible_xi97wmbt/ansible_module_xml.py", line 658, in main
    add_children = decode(module.params['add_children'])
  File "/tmp/ansible_xi97wmbt/ansible_module_xml.py", line 608, in decode
    if not value or isinstance(value, unicode):
NameError: name 'unicode' is not defined

fatal: [testhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_xi97wmbt/ansible_module_xml.py\", line 732, in <module>\n    main()\n  File \"/tmp/ansible_xi97wmbt/ansible_module_xml.py\", line 658, in main\n    add_children = decode(module.params['add_children'])\n  File \"/tmp/ansible_xi97wmbt/ansible_module_xml.py\", line 608, in decode\n    if not value or isinstance(value, unicode):\nNameError: name 'unicode' is not defined\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
```

### LINKED ISSUE #117: How to create multiple nodes?
Hi,

This is a support question (or feature request), rather than error report but how can I create structure like:
>         <error-page>
>             <error-code>404</error-code>
>             <location>/error/404.html</location>
>         </error-page>
>         <error-page>
>             <error-code>500</error-code>
>             <location>/error/500.html</location>
>         </error-page>

I have tried several ideas from with_items lists to add_children, but I was not able to crate such structure. I am using latest Ansible with latest xml library that is available here.

Thank you in advance!

### PR DESCRIPTION
**Pull request by dagwieers**
##### SUMMARY
This is another attempt to get the xml module upstream.
https://github.com/cmprescott/ansible-xml/

Prior submissions at: #16147, ansible/ansible-modules-core#4112 and ansible/ansible-modules-core#4122

This PR includes:
- The code has been re-licensed to GPLv3+. cmprescott/ansible-xml#113
- 55 integration tests (tested in run-mode and check-mode)
- Add return values to documentation
- Added python 3 support (revised unicode support)
- Improved and simplified check-mode support
- Fixed one idempotency bug
- Fixed a bug related to check-mode support (incorrectl reported no change)

Once merged we can collaborate on the module and tests in this project:
- Migrate and fix [open issues](https://github.com/cmprescott/ansible-xml/issues/)
- Merge [existing PRs](https://github.com/cmprescott/ansible-xml/pulls/)
- Add diff support !!  --  *Ideal in combination with check-mode*
- Add backup support

This fixes cmprescott/ansible-xml#52,
and this fixes cmprescott/ansible-xml#74,
and this fixes cmprescott/ansible-xml#75,
but his also fixes cmprescott/ansible-xml#108,
and this fixes cmprescott/ansible-xml#109,
and this fixes cmprescott/ansible-xml#116,

Due to the addition of a namespace example and a documentation note (as stated in cmprescott/ansible-xml#118),
this fixes cmprescott/ansible-xml#102,
and it fixes cmprescott/ansible-xml#107,
and fixes cmprescott/ansible-xml#112,
and also fixes cmprescott/ansible-xml#117,
and fixes cmprescott/ansible-xml#118.

Due to an improved lxml version check,
this fixes cmprescott/ansible-xml#114
and fixes cmprescott/ansible-xml#115.,

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

xml

##### ANSIBLE VERSION
v2.4

### CODE REVIEW

**Comment by dagwieers** [comment]
@abadger I would appreciate if you could look at how this module currently handles unicode (also wrt. Python 3) and bring this in line with what we nowadays expect for Ansible modules.

**Comment by dagwieers** [comment]
@gundalow @mattclay I have the integration tests ready, but they fail on docker lacking python-lxml. Installing it via pip in the playbook is not possible as it requires compilation, and adding it to the Dockerfile doesn't currently allow me to test with my modifications. #25324

**Comment by bbaassssiiee** [comment]
This module would be a great addition creating capabilities for deploying entersprise (java) applications.

**Comment by abadger** [comment]
I think there will be quite a few problems with it wrt bytes/unicode and python3.

The general rules are:
* You never want to mix bytes and text types. 
* You want to be explicit in whether you're dealing with bytes or text whenever dealing with io.

I see that according to comments in the code, lxml needs to use text strings too.  That probably means that the easiest way to code this module to be unicode safe is to transform everything into text (as opposed to turning it into native strings as is done in other modules).  Using to_text is the best way to do this.  the decode function that I see i nthis module could probably be done via ansible.module_utils.basic.json_dict_bytes_to_unicode instead but that function needs to move somewhere else in the future so it's not a requirement that the code use it.

**Comment by mattclay** [comment]
@dagwieers For the lxml requirement, add tasks to the start of the test:

- For FreeBSD, use the pkgng module to install the py27-lxml package.
- Install lxml using the pip module. That will take care of macOS.

The pip install will no-op if lxml is already installed. This way we only install it when needed.

With those changes the tests should pass CI.

**Comment by dagwieers** [comment]
@mattclay Thanks, this is looking good !

**Comment by richardcs** [comment]
Just made the [PR](https://github.com/ansible/ansible/pull/26404) for a windows version of things that does XML files on windows. @jhawkesworth provided a lot of input and the interface is the same with aliases. I tend to think the argument for the xml to be added should be 'fragment' since that's a well understood concept in the XML community. It does feel a little strange to propagate details about XML up to ansible, but using XPath is pretty heady stuff too.

**Comment by dagwieers** [comment]
Every contributor has agreed to re-licensing this code, so this is ready to be merged.

**Comment by dagwieers** [comment]
@mattclay I assume the pylint tests are run for Python 3, whereas the xml module at this time is Python 2 only and would need some special love to make it work with Python 3. ~(I am not the guy to do that though)~ Python 3 now !

**Comment by mattclay** [comment]
@dagwieers Yes, pylint is run using Python 3 on Shippable. All new modules need to support both python 2.x and 3.x.

/cc @abadger

**Comment by resmo** [comment]
shipit

File: lib/ansible/modules/files/xml.py [hunk 1]
```diff
@@ -0,0 +1,757 @@
...
+    elif LooseVersion('.'.join(map(str, etree.LXML_VERSION))) < LooseVersion('2.3.0'):
+        module.fail_json(msg='The xml ansible module requires lxml 2.3.0 or newer installed on the managed machine')
+    elif LooseVersion('.'.join(map(str, etree.LXML_VERSION))) < LooseVersion('3.0.0'):
+        module.warn('Using lxml version lower than 3.0.0 does not guarantee predictable element attribute order.')
+
+    # Check if the file exists
+    if xml_string:
+        infile = BytesIO(xml_string.encode('utf-8'))
+    elif os.path.isfile(xml_file):
+        infile = open(xml_file, 'r')
```
Comment (abadger) [inline lib/ansible/modules/files/xml.py]: This needs to be 'rb' so that it's bytes just like the BytesIO above.

File: lib/ansible/modules/files/xml.py [hunk 2]
```diff
@@ -0,0 +1,757 @@
...
+    pretty_print = module.params['pretty_print']
+    content = module.params['content']
+    input_type = module.params['input_type']
+    print_match = module.params['print_match']
+    count = module.params['count']
+
+    # Check if we have lxml 2.3.0 or newer installed
+    if not HAS_LXML:
+        module.fail_json(msg='The xml ansible module requires the lxml python library installed on the managed machine')
+    elif LooseVersion('.'.join(map(str, etree.LXML_VERSION))) < LooseVersion('2.3.0'):
```
Comment (abadger) [inline lib/ansible/modules/files/xml.py]: Not necessary but this map and the one on 690 are better written as:
``` python
elif LooseVersion('.'.join(to_native(ver_field) for ver_field in etree.LXML_VERSION)) < LooseVersion('2.3.0'):

File: lib/ansible/modules/files/xml.py [hunk 3]
```diff
@@ -0,0 +1,757 @@
...
+        infile = BytesIO(xml_string.encode('utf-8'))
+    elif os.path.isfile(xml_file):
+        infile = open(xml_file, 'r')
+    else:
+        module.fail_json(msg="The target XML source does not exist: %s" % xml_file)
+
+    # Try to parse in the target XML file
+    try:
+        parser = etree.XMLParser(remove_blank_text=pretty_print)
+        x = etree.parse(infile, parser)
```
Comment (abadger) [inline lib/ansible/modules/files/xml.py]: Maybe document, doc, or root would be a better name for this variable?

File: lib/ansible/modules/files/xml.py [hunk 4]
```diff
@@ -0,0 +1,757 @@
...
+    except etree.XMLSyntaxError:
+        e = get_exception()
+        module.fail_json(msg="Error while parsing path: %s" % e)
```
Comment (abadger) [inline lib/ansible/modules/files/xml.py]: Not necessary but exception handling (since this is ansible-2.4+) cna be written as:
```
    except etree.XMLSyntaxError as e:
        module.fail_json(msg="Error while parsing path: %s" % to_native(e))
```

File: lib/ansible/modules/files/xml.py (hunk 2 above)
Comment (dagwieers) [reply lib/ansible/modules/files/xml.py]: Would that be the same as:
```python
elif LooseVersion('.'.join(map(to_native, etree.LXML_VERSION))) < LooseVersion('2.3.0'):
```
i.e. simply replacing str() with to_native().

File: lib/ansible/modules/files/xml.py [hunk 5]
```diff
@@ -0,0 +1,757 @@
...
+    else:
+        module.fail_json(msg="Invalid child input type: %s. Type must be either xml or yaml." % in_type)
+
+
+def children_to_nodes(module=None, children=[], type='yaml'):
+    """turn a str/hash/list of str&hash into a list of elements"""
+    return [child_to_element(module, child, type) for child in children]
+
+
+def finish(module, tree, xpath, namespaces, changed=False, msg="", hitcount=0, matches=[]):
```
Comment (abadger) [inline lib/ansible/modules/files/xml.py]: Shouldn't use a mutable container as default arg in python.  If you ever add to the container you then find that you're sharing a single opy of that container everytime the function in python.  You can do one of these two instead:
``` python
# If you don't need to add to the container now.  This just prevents doing something stupid when the code is changed in the future.
 def finish(module, tree, xpath, namespaces, changed=False, msg="", hitcount=0, matches=tuple()): 

# if matches needs to be a mutable container.  This creates a fresh list everytime the function is called.
def finish(module, tree, xpath, namespaces, changed=False, msg="", hitcount=0, matches=None): 
    if matches is None:
        matches = []
```

Comment (abadger) [reply lib/ansible/modules/files/xml.py]: This applies to the other functions where a list is the default value as well.

File: lib/ansible/modules/files/xml.py [hunk 6]
```diff
@@ -0,0 +1,757 @@
...
+            parser = etree.XMLParser()
+            node = etree.parse(infile, parser)
+            return node.getroot()
+        except etree.XMLSyntaxError:
+            e = get_exception()
+            module.fail_json(msg="Error while parsing child element: %s" % e)
+    elif in_type == 'yaml':
+        if isinstance(child, string_types):
+            return etree.Element(child)
+        elif isinstance(child, dict):
```
Comment (abadger) [inline lib/ansible/modules/files/xml.py]: In general, it's better to use``` collections.MutableMapping``` in isinstance as that allows duck-typing.

File: lib/ansible/modules/files/xml.py [hunk 7]
```diff
@@ -0,0 +1,757 @@
...
+            value = element.get(key)
+            child.update({key: value})
+        elements.append({element.tag: child})
+
+    finish(module, tree, xpath, namespaces, changed=False, msg=len(elements), hitcount=len(elements), matches=elements)
+
+
+def child_to_element(module, child, in_type):
+    if in_type == 'xml':
+        infile = BytesIO(child.encode('utf-8'))
```
Comment (abadger) [inline lib/ansible/modules/files/xml.py]: Instead of child.encode(), use to_bytes(child, errors='surrogate_or_strict").  to_bytes() protect against calling encode() on something that is already a byte string. (calling encode on a byte string can sometimes traceback).

File: lib/ansible/modules/files/xml.py [hunk 8]
```diff
@@ -0,0 +1,757 @@
...
+def set_target_inner(module, tree, xpath, namespaces, attribute, value):
+    changed = False
+
+    try:
+        if not is_node(tree, xpath, namespaces):
+            changed = check_or_make_target(module, tree, xpath, namespaces)
+    except Exception:
+        e = get_exception()
+        module.fail_json(msg="Xpath %s causes a failure: %s\n%s\n  -- tree is %s" %
+                             (xpath, e, traceback.format_exc(e), etree.tostring(tree, pretty_print=True)))
```
Comment (abadger) [inline lib/ansible/modules/files/xml.py]: Instead of including a stacktrace in the message, better to put it into the exception field:
```
 module.fail_json(msg="Xpath %s causes a failure: %s\n  -- tree is %s" %
                             (xpath, to_native(e), etree.tostring(tree, pretty_print=True)),
                             exception=traceback.format_exc())
```

File: lib/ansible/modules/files/xml.py [hunk 9]
```diff
@@ -0,0 +1,755 @@
...
+HAS_LXML = True
+try:
+    from lxml import etree
+except ImportError:
+    HAS_LXML = False
+
+try:
+    import json
+except ImportError:
+    import simplejson as json
```
Comment (abadger) [inline lib/ansible/modules/files/xml.py]: Since we're now targetting python-2.6+ we can just ```import json```

File: lib/ansible/modules/files/xml.py [hunk 10]
```diff
@@ -0,0 +1,755 @@
...
+_xpstr = "('(?:.*)'|\"(?:.*)\")"
+
+_re_splitSimpleLast = re.compile("^(.*)/(" + _nsIdent + ")$")
+_re_splitSimpleLastEqValue = re.compile("^(.*)/(" + _nsIdent + ")/text\\(\\)=" + _xpstr + "$")
+_re_splitSimpleAttrLast = re.compile("^(.*)/(@(?:" + _nsIdent + "))$")
+_re_splitSimpleAttrLastEqValue = re.compile("^(.*)/(@(?:" + _nsIdent + "))=" + _xpstr + "$")
+
+_re_splitSubLast = re.compile("^(.*)/(" + _nsIdent + ")\\[(.*)\\]$")
+
+_re_splitOnlyEqValue = re.compile("^(.*)/text\\(\\)=" + _xpstr + "$")
```
Comment (abadger) [inline lib/ansible/modules/files/xml.py]: Unless there's a reason, I'd put all these toplevel variable definitions right after the imports.

They're also constants so they probably should be uppercase but I won't block on that.

Comment (abadger) [reply lib/ansible/modules/files/xml.py]: I see... it's putting them near split_xpath_last which is where they're used.  Maybe move both the variables and the split_xpath_last function up to below the imports.

File: lib/ansible/modules/files/xml.py [hunk 11]
```diff
@@ -0,0 +1,755 @@
...
+        # requesting an attribute to exist
+        return (m.group(1), [(m.group(2), None)])
+    m = _re_splitSimpleAttrLastEqValue.match(xpath)
+    if m:
+        # requesting an attribute to exist with a value
+        return (m.group(1), [(m.group(2), _extract_xpstr(m.group(3)))])
+
+    m = _re_splitSubLast.match(xpath)
+    if m:
+        content = map(lambda x: x.strip(), m.group(3).split(" and "))
```
Comment (abadger) [inline lib/ansible/modules/files/xml.py]: Another map that can be a list comprehension:
```
content = [x.strip() for x in m.group(3).split(" and ")]
```

**Comment by abadger** [comment]
Okay, I'm done with my review once those last few things are fixed and shippable finally gets done testing the changes, I'll merge.  (If I don't notice that shippable is finished, feel free to ping me on IRC).

File: lib/ansible/modules/files/xml.py (hunk 11 above)
Comment (dagwieers) [reply lib/ansible/modules/files/xml.py]: What's wrong with maps ?

**Comment by abadger** [comment]
Merged to devel for 2.4.0 release.  Thanks to @cmprescott @dagwieers and the many others who have worked on this until it could go in!

**Comment by dagwieers** [comment]
Thanks @abadger !
