### ISSUE TITLE
vmware_deploy_ovf selecting wrong datastore in a multi-datacenter environment

### ISSUE THREAD

**Issue by davedow15** [ansible/ansible#63920]
issue type: Bug Report
ansible version: 2.8.3
component name: vmware_deploy_ovf.py and vmware.py

vmware_deploy_ovf isn't retrieving the correct datastore from vmware.py when there are multiple datacenters using datastores that with the same name.

Datacenter1
--> datastore1 (moid: datastore-524)
Datacenter2
--> datastore1 (moid: datastore-525)

Even though we specified "Datacenter2" in our Ansible script, we determined that vmware_deploy_ovf was working with the datastore from Datacenter1 because the underlying python code doesn't specify the datacenter - just the datastore name.

We printed out the import_spec in vmware_deploy_ovf to figure this out.  Note that in our example, we we're looking for datastore-525, but got datastore-524.

```
"msg": "*****************import_spec: 
(vim.OvfManager.CreateImportSpecResult) 
{\n   dynamicType = <unset>,\n   
dynamicProperty = (vmodl.DynamicProperty) [],\n   
importSpec = <unset>,\n   
fileItem = (vim.OvfManager.FileItem) [],\n   
warning = (vmodl.MethodFault) [],\n   
error = (vmodl.MethodFault) [\n      
(vim.fault.UnsupportedDatastore) {\n         dynamicType = <unset>,\n         dynamicProperty = (vmodl.DynamicProperty) [],\n         
msg = 'The virtual machine is not supported on the target datastore.',\n         faultCause = <unset>,\n         
faultMessage = (vmodl.LocalizableMessage) [],\n        
datastore = 'vim.Datastore:datastore-524'\n   
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@davedow15: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/vmware/vmware_deploy_ovf.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_deploy_ovf.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @goneri @lparkes @pgbidkar @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@davedow15 Thanks for reporting this issue. Could you please try PR https://github.com/ansible/ansible/pull/62513 in 2.8.6 or https://github.com/ansible/ansible/pull/58627 for 2.9 release and let me know ? Thanks.

needs_info
has_pr

**Comment by davedow15** [comment]
We tried 2.8.6 yesterday and the deploy failed in a different way.
I’m going to confirm that I have 62513 in my 2.8.6 deployment package (it should be in there).
58627 looks like that may fix our problem, but that’s in 2.9 and 2.9 isn’t ready yet.
When is 2.9 going GA? The last time I checked, it was October 31st.
Thank You!
Dave

-------------------------
Dave Dow
NetApp HCI - Cloud Infrastructure Business Unit
(c) 303-641-4144

**Comment by davedow15** [comment]
Hi Abhijeet,
It appears that 2.8.6 has regressed or my playbook (that runs on 2.8.3) isn’t supported by 2.8.6.

When running with 2.8.3, I get the error specified in this bug.

"msg": "Failure validating OVF import spec: The provided network mapping between OVF networks and the system network is not supported by any host."
And like I mentioned in the bug, it’s because it’s trying to deploy to the datastore in the wrong datacenter (because the datastore names are the same in both datacenters – but have different MOIDs).

When running with 2.8.6 (& 2.9), I get the following error message:


fatal: [localhost]: FAILED! => {

    "changed": false,

    "module_stderr": "/Users/dddd/.ansible/tmp/ansible-tmp-1572370628.432378-47516492567897/AnsiballZ_vmware_deploy_ovf.py:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses\n  import imp\nTraceback (most recent call last):\n  File \"/Users/dddd/.ansible/tmp/ansible-tmp-1572370628.432378-47516492567897/AnsiballZ_vmware_deploy_ovf.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/Users/dddd/.ansible/tmp/ansible-tmp-1572370628.432378-47516492567897/AnsiballZ_vmware_deploy_ovf.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/dddd/.ansible/tmp/ansible-tmp-1572370628.432378-47516492567897/AnsiballZ_vmware_deploy_ovf.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py\", line 169, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/var/folders/3g/jkk4zqf93hq976rfb57w37qw0000gp/T/ansible_vmware_deploy_ovf_payload_se412mts/__main__.py\", line 685, in <module>\n  File \"/var/folders/3g/jkk4zqf93hq976rfb57w37qw0000gp/T/ansible_vmware_deploy_ovf_payload_se412mts/__main__.py\", line 677, in main\n  File \"/var/folders/3g/jkk4zqf93hq976rfb57w37qw0000gp/T/ansible_vmware_deploy_ovf_payload_se412mts/__main__.py\", line 465, in upload\n  File \"/var/folders/3g/jkk4zqf93hq976rfb57w37qw0000gp/T/ansible_vmware_deploy_ovf_payload_se412mts/__main__.py\", line 372, in get_lease\n  File \"/var/folders/3g/jkk4zqf93hq976rfb57w37qw0000gp/T/ansible_vmware_deploy_ovf_payload_se412mts/__main__.py\", line 342, in get_objects\n  File \"/var/folders/3g/jkk4zqf93hq976rfb57w37qw0000gp/T/ansible_vmware_deploy_ovf_payload_se412mts/ansible_vmware_deploy_ovf_payload.zip/ansible/module_utils/vmware.py\", line 186, in find_network_by_name\n  File \"/var/folders/3g/jkk4zqf93hq976rfb57w37qw0000gp/T/ansible_vmware_deploy_ovf_payload_se412mts/ansible_vmware_deploy_ovf_payload.zip/ansible/module_utils/vmware.py\", line 132, in find_object_by_name\n  File \"/var/folders/3g/jkk4zqf93hq976rfb57w37qw0000gp/T/ansible_vmware_deploy_ovf_payload_se412mts/ansible_vmware_deploy_ovf_payload.zip/ansible/module_utils/vmware.py\", line 566, in get_all_objs\nAttributeError: 'NoneType' object has no attribute 'rootFolder'\n",

    "module_stdout": "",

    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",

    "rc": 1

}

And when I try running on the first Datacenter (which works fine with 2.8.3), it fails the same way.

Here is the playbook:

hosts: localhost
gather_facts: false
connection: 'local'

tasks:

  - name: Import Deploy OVA
    vmware_deploy_ovf:
      hostname: "10.111.111.111"
      username: "administrator@vsphere.local"
      password: "blahblah"
      validate_certs: no
      ovf: "deploy2.11_vm.ova"
      networks:
        "Deploy VM Network": "VDS 01-VM_Network"
      cluster: "Cluster-01"
      datacenter: "Datacenter-01"
      datastore: "Datastore-01"
      disk_provisioning: "thin"
      name: "ddtest"
      folder: "Datacenter-01/vm"
      properties:
        ipAddress: "10.111.113.111"
        gateway: "10.111.181.254"
        proxy_url: ""
        netMask: "255.255.255.0"
        password: "blahskdf"
        product_company: "MyCompany"
        primaryDNS: "10.11.33.44"
        secondaryDNS: ""
        hostName: "testhostname"
        searchDomains: "aaaaa.net"
      power_on: yes
      wait_for_ip_address: true
      allow_duplicates: no

Please let me know if there’s anything else I can try.
Thank You!
Dave

-------------------------
Dave Dow
NetApp HCI - Cloud Infrastructure Business Unit
(c) 303-641-4144

**Comment by davedow15** [comment]
I developed a fix for this bug and tested it on my system.
I tried pushing a branch that is forked off of devel, but I'm getting Authentication failed.
Can you please let me know how I can get authorization to push a branch up to the repo so I can submit a PR for review?
Or, if it's easier, I can send you the fix and you can submit it (it's super-simple,  just a few lines of code).
Please let me know.
Thanks!  Dave
