### PR TITLE
Backport #59614 to stable-2.8

### PR DESCRIPTION
**Pull request by albers**
##### SUMMARY
#62513 introduced a regression, which was fixed by @Akasurde in #59614. Unfortunately, the fix was only included in the 2.9 branch.

As a result, the *vmware_deploy_ovf* module is broken in the current 2.8.6 release. Usage yields 

> AttributeError: 'NoneType' object has no attribute 'ovfManager'

This PR backports @Akasurde's fix to the 2.8 release branch.

@Akasurde PTAL

Backport of https://github.com/ansible/ansible/pull/59614

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
vmware_deploy_ovf

##### ADDITIONAL INFORMATION
The error occurs because `self.si` is no longer [initialized in the constructor](https://github.com/ansible/ansible/pull/62513/files#diff-72b54aa6d5b8129f70a84475868e149cL295-R304) but still being used.

The fix changes usage of `self.si` to `self.content`, which is initialized in the parent constructor.

### CODE REVIEW

**Comment by Akasurde** [comment]
!component =lib/ansible/modules/cloud/vmware/vmware_deploy_ovf.py

**Review by Akasurde — APPROVED** [review]
LGTM,

**Comment by Akasurde** [comment]
@albers I am extremely sorry that I was not careful while backporting the changes. I will more careful next time. Sorry for the inconvenience.
Thanks for the contribution,

**Comment by Akasurde** [comment]
@albers Thanks for the contribution.
