### PR TITLE
ec2_vpc_route_table: Update matching_count parsing on find_subnets fu…

### LINKED ISSUE #38570: ec2_vpc_route_table fails with "AttributeError: 'dict' object has no attribute 'tags'" on route table creation
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2_vpc_route_table

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/vagrant/repo/v2-ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### CONFIGURATION

```
ANSIBLE_SSH_ARGS(/home/vagrant/repo/v2-ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
DEFAULT_HOST_LIST(/home/vagrant/repo/v2-ansible/ansible.cfg) = [u'/home/vagrant/repo/v2-ansible/environment/test']
DEFAULT_REMOTE_USER(/home/vagrant/repo/v2-ansible/ansible.cfg) = {{ ansible_username | default('ansible') }}
HOST_KEY_CHECKING(/home/vagrant/repo/v2-ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/vagrant/repo/v2-ansible/ansible.cfg) = False
```
##### OS / ENVIRONMENT

Debian 9.1
`Linux dojo 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux`

##### SUMMARY

The `ec2_vpc_route_table` module crashes on route table creation. The AWS Console shows that the route table is created successfully however.

The error appears to be related to the `tags` attribute not being recognized. The AWS Console shows that the route table is tagged successfully however.

Subsequent runs fail in the same fashion. 

Omitting the `tags` parameter creates an untagged route table, but still crashes the same way.

##### STEPS TO REPRODUCE

Create a new route table:

```yaml
- name: Create subnet routes
  ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpcs.0.id }}"
    region: "{{ ec2_region }}"
    tags:
      Name: "{{ subnet_name }}"
    subnets:
      - "{{ subnet_name }}"
    routes:
      - dest: "{{ cidr_ip_all }}"
        gateway_id: "{{ igw.internet_gateways.0.internet_gateway_id }}"
```

##### EXPECTED RESULTS

Route table is created without errors. This works in `2.4.3`.
##### ACTUAL RESULTS

MODULE FAILURE

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_hbuePJ/ansible_module_ec2_vpc_route_table.py", line 724, in <module>
    main()
  File "/tmp/ansible_hbuePJ/ansible_module_ec2_vpc_route_table.py", line 716, in main
    result = ensure_route_table_present(connection, module)
  File "/tmp/ansible_hbuePJ/ansible_module_ec2_vpc_route_table.py", line 674, in ensure_route_table_present
    associated_subnets = find_subnets(connection, module, vpc_id, subnets)
  File "/tmp/ansible_hbuePJ/ansible_module_ec2_vpc_route_table.py", line 295, in find_subnets
    matching_count = len([1 for s in subnets_by_name if s.tags.get('Name') == name])
AttributeError: 'dict' object has no attribute 'tags'

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_hbuePJ/ansible_module_ec2_vpc_route_table.py\", line 724, in <module>\n    main()\n  File \"/tmp/ansible_hbuePJ/ansible_module_ec2_vpc_route_table.py\", line 716, in main\n    result = ensure_route_table_present(connection, module)\n  File \"/tmp/ansible_hbuePJ/ansible_module_ec2_vpc_route_table.py\", line 674, in ensure_route_table_present\n    associated_subnets = find_subnets(connection, module, vpc_id, subnets)\n  File \"/tmp/ansible_hbuePJ/ansible_module_ec2_vpc_route_table.py\", line 295, in find_subnets\n    matching_count = len([1 for s in subnets_by_name if s.tags.get('Name') == name])\nAttributeError: 'dict' object has no attribute 'tags'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}

```

### PR DESCRIPTION
**Pull request by ZuZuD**
…nction. Fix #38570

##### SUMMARY

Fix #38570. Tags for the list of subnets are now parsed properly. I was able to reproduce the initial issue and this PR fixed it. 

I don't understand how this could have worked initially if someone can shed some light on this I would appreciate.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
 
ec2_vpc_route_table

##### ANSIBLE VERSION

```
ansible --version
ansible 2.6.0
```

##### ADDITIONAL INFORMATION

Also fixed a typo in the function comment.

### CODE REVIEW

File: lib/ansible/modules/cloud/amazon/ec2_vpc_route_table.py [hunk 1]
```diff
@@ -294,7 +294,7 @@ def find_subnets(connection, module, vpc_id, identified_subnets):
             module.fail_json_aws(e, msg="Couldn't find subnet with names %s" % subnet_names)
 
         for name in subnet_names:
-            matching_count = len([1 for s in subnets_by_name if s.tags.get('Name') == name])
+            matching_count = len([1 for s in subnets_by_name if s['Tags'][0].get('Value') == name])
```
Comment (willthames) [inline lib/ansible/modules/cloud/amazon/ec2_vpc_route_table.py]: How could this happen? I clearly stuffed this bit up in the boto3 conversion and no-one noticed. 

I don't think this improvement will work unless the first tag is always the Name tag, which seems unlikely.

This should probably be 

```
matching_count = len([1 for s in subnets_by_name for t in s.get('Tags', []) if t['Name'] == 'Name' and t['Value'] == name])
```

Could you add a test for this situation into test/integration/targets/ec2_vpc_route_table/tasks/main.yml (tests would hopefully have caught both the original error and the flaw in this solution)

**Review by willthames — CHANGES_REQUESTED** [review]

**Comment by ZuZuD** [comment]
Indeed I missed something @willthames! I added the tests and corrected a bug with the ternary operator used to give an appropriate subnet name:

```json 
        {
            "assign_ipv6_address_on_creation": false,
            "availability_zone": "us-east-1b",
            "available_ip_address_count": 251,
            "cidr_block": "10.228.231.0/24",
            "default_for_az": false,
            "id": "subnet-b92fce97",
            "ipv6_cidr_block_association_set": [],
            "map_public_ip_on_launch": false,
            "state": "available",
            "subnet_id": "subnet-b92fce97",
            "tags": {
                "Name": "public-b",
                "Public": "False"
            },
            "vpc_id": "vpc-45a0ec3e"
        },
```

**Review by s-hertel — APPROVED** [review]

**Comment by s-hertel** [comment]
Hm. The ternary operator without explicit bool is working exactly the same as with the bool for me. Looks good though. This should be backported to 2.5 as well.

**Review by ryansb — APPROVED** [review]
