### ISSUE TITLE
Unexpected Exception: cannot import name linear - ansible 2.1.1.0 ubuntu 16.04

### ISSUE THREAD

**Issue by ngmariusz** [ansible/ansible#18380]
##### ISSUE TYPE
-  Bug Report

##### COMPONENT NAME
strategy: debug

##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### OS / ENVIRONMENT

```
Ubuntu 16.04
```
##### STEPS TO REPRODUCE

BAD
```
- name:  what ever with strategy linear (other than debug?)
  hosts: all
  strategy: linear
  tasks:
    - name:  do sth
      debug:

- name:  debug run
  hosts: all
  strategy: debug
  gather_facts: no
  vars:
    var1: value1
  tasks:
    - name: wrong variable
      ping: data={{ wrong_var }}
```

GOOD
```
- name:  debug run
  hosts: all
  strategy: debug
  gather_facts: no
  vars:
    var1: value1
  tasks:
    - name: wrong variable
      ping: data={{ wrong_var }}

- name:  what ever with strategy linear (other than debug?)
  hosts: all
  strategy: linear
  tasks:
    - name:  do sth
      debug:
```

GOOD
```
- name:  what ever with strategy debug
  hosts: all
  strategy: debug
  tasks:
    - name:  do sth
      debug:

- name:  debug run
  hosts: all
  strategy: debug
  gather_facts: no
  vars:
    var1: value1
  tasks:
    - name: wrong variable
      ping: data={{ wrong_var }}
```

##### ACTUAL RESULTS

```
ERROR! Unexpected Exception: cannot import name linear
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 92, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 146, in run
    result = self._tqm.run(play=play)
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 233, in run
    strategy = strategy_loader.get(new_play.strategy, self)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 333, in get
    self._module_cache[path] = self._load_module_source('.'.join([self.package, name]), path)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 319, in _load_module_source
    module = imp.load_source(name, path, module_file)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/strategy/debug.py", line 9, in <module>
    from ansible.plugins.strategy import linear
ImportError: cannot import name linear

```

**Comment by alikins** [comment]
I can reproduce this with 2.1.0.0-1, but https://github.com/ansible/ansible/releases/tag/v2.1.2.0-1 has a fix for it.

```
commit f956ff961982e4372363052c108f0c5d18f8de62
Author: James Cammarata <jimi@sngx.net>
Date:   Fri Aug 5 10:06:50 2016 -0500

    Tweak the way the debug strategy imports the linear strategy parent

    Due to the way we load plugins, internally to Python there can be issues when
    the debug strategy is loaded after the linear strategy. To work around this,
    we're changing the import line for the linear strategy to avoid the problem.

    Related to #16825

    (cherry picked from commit 1714279b5e18cdc3f684e5ea3af5416b5f0c8c67)
```

Failing in v2.1.1.0-1:

```
[fedora-23:ansible (v2.1.1.0-1-branch %)]$ ansible --version
ansible 2.1.1.0 (detached HEAD ref: refs/) last updated 2016/11/07 10:47:42 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 242368e99b) last updated 2016/11/07 10:47:45 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 14887a9ea8) last updated 2016/11/07 10:47:45 (GMT -400)
  config file = /home/adrian/.ansible.cfg
  configured module search path = Default w/o overrides
[fedora-23:ansible (v2.1.1.0-1-branch %)]$ ansible-playbook -vvv repro/debug_strategy_exception_18380/test.yml 
Using /home/adrian/.ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available


PLAYBOOK: test.yml *************************************************************
2 plays in repro/debug_strategy_exception_18380/test.yml

PLAY [what ever with strategy linear (other than debug?)] **********************

TASK [setup] *******************************************************************
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: adrian
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1478533679.76-262739075839941 `" && echo ansible-tmp-1478533679.76-262739075839941="` echo $HOME/.ansible/tmp/ansible-tmp-1478533679.76-262739075839941 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpbppt8N TO /home/adrian/.ansible/tmp/ansible-tmp-1478533679.76-262739075839941/setup
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_US.utf8 LC_ALL=en_US.utf8 LC_MESSAGES=en_US.utf8 /usr/bin/python /home/adrian/.ansible/tmp/ansible-tmp-1478533679.76-262739075839941/setup; rm -rf "/home/adrian/.ansible/tmp/ansible-tmp-1478533679.76-262739075839941/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [do sth] ******************************************************************
task path: /home/adrian/src/ansible/repro/debug_strategy_exception_18380/test.yml:5
ok: [localhost] => {
    "msg": "Hello world!"
}

PLAY [debug run] ***************************************************************
ERROR! Unexpected Exception: cannot import name linear
the full traceback was:

Traceback (most recent call last):
  File "/home/adrian/src/ansible/bin/ansible-playbook", line 92, in <module>
    exit_code = cli.run()
  File "/home/adrian/src/ansible/lib/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/home/adrian/src/ansible/lib/ansible/executor/playbook_executor.py", line 146, in run
    result = self._tqm.run(play=play)
  File "/home/adrian/src/ansible/lib/ansible/executor/task_queue_manager.py", line 233, in run
    strategy = strategy_loader.get(new_play.strategy, self)
  File "/home/adrian/src/ansible/lib/ansible/plugins/__init__.py", line 333, in get
    self._module_cache[path] = self._load_module_source('.'.join([self.package, name]), path)
  File "/home/adrian/src/ansible/lib/ansible/plugins/__init__.py", line 319, in _load_module_source
    module = imp.load_source(name, path, module_file)
  File "/home/adrian/src/ansible/lib/ansible/plugins/strategy/debug.py", line 9, in <module>
    from ansible.plugins.strategy import linear
ImportError: cannot import name linear
```

Working in v2.1.2.0-1

```
[fedora-23:ansible (v2.1.2.0-1-branch %)]$ ansible --version
ansible 2.1.2.0 (v2.1.2.0-1-branch 29f2f26278) last updated 2016/11/07 10:48:20 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 17ee1cfaf9) last updated 2016/11/07 10:48:25 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD d312f34d9b) last updated 2016/11/07 10:48:25 (GMT -400)
  config file = /home/adrian/.ansible.cfg
  configured module search path = Default w/o overrides
[fedora-23:ansible (v2.1.2.0-1-branch %)]$ ansible-playbook -vvv repro/debug_strategy_exception_18380/test.yml 
Using /home/adrian/.ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available


PLAYBOOK: test.yml *************************************************************
2 plays in repro/debug_strategy_exception_18380/test.yml

PLAY [what ever with strategy linear (other than debug?)] **********************

TASK [setup] *******************************************************************
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: adrian
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1478533712.25-213983787408682 `" && echo ansible-tmp-1478533712.25-213983787408682="` echo $HOME/.ansible/tmp/ansible-tmp-1478533712.25-213983787408682 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpHUcOHO TO /home/adrian/.ansible/tmp/ansible-tmp-1478533712.25-213983787408682/setup
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/adrian/.ansible/tmp/ansible-tmp-1478533712.25-213983787408682/ /home/adrian/.ansible/tmp/ansible-tmp-1478533712.25-213983787408682/setup && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_US.utf8 LC_ALL=en_US.utf8 LC_MESSAGES=en_US.utf8 /usr/bin/python /home/adrian/.ansible/tmp/ansible-tmp-1478533712.25-213983787408682/setup; rm -rf "/home/adrian/.ansible/tmp/ansible-tmp-1478533712.25-213983787408682/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [do sth] ******************************************************************
task path: /home/adrian/src/ansible/repro/debug_strategy_exception_18380/test.yml:5
ok: [localhost] => {
    "msg": "Hello world!"
}

PLAY [debug run] ***************************************************************

TASK [wrong variable] **********************************************************
task path: /home/adrian/src/ansible/repro/debug_strategy_exception_18380/test.yml:15
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'wrong_var' is undefined\n\nThe error appears to have been in '/home/adrian/src/ansible/repro/debug_strategy_exception_18380/test.yml': line 15, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: wrong variable\n      ^ here\n"}
Debugger invoked
(debug) aborted
```

**Comment by alikins** [comment]
iow, already fixed in latest 2.1 release (2.1.2 and later)  as well as 2.2 and devel
