### ISSUE TITLE
docker_container: create_host_config() got an unexpected keyword argument 'init'

### ISSUE THREAD

**Issue by mrtyler** [ansible/ansible#42162]
This is a repost of #42137 by @dlibanori, because @felixfontein suggested that there was a problem with the original bug report. Please close one in favor of the other.

##### SUMMARY
Ansible 2.6.0 raises an error when trying to run `docker_container`: `create_host_config() got an unexpected keyword argument 'init'`

The same stanza works in Ansible 2.5.5.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

docker_container

##### ANSIBLE VERSION

```
2.6.0
```

##### CONFIGURATION

Running in molecule 1.2.5. Full context: https://github.com/gpii-ops/ansible-gpii-version-updater

##### OS / ENVIRONMENT

N/A

...probably. But just in case, I'm seeing this on MacOS High Sierra with Python 2.7.15 and CentOS 7 with Python 2.7.5.

##### STEPS TO REPRODUCE

```yaml
- name: Run version-updater container
  docker_container:
    name: version-updater
    image: gpii/version-updater:latest
    state: started
    restart: yes
    restart_policy: always
    volumes:
      - /home/deploy/gpii-ci-ssh:/home/app/.ssh:ro,Z
```

In case it's helpful, here's the relevant stanza in full context: https://github.com/gpii-ops/ansible-gpii-version-updater/blob/master/tasks/configure.yml#L29

##### EXPECTED RESULTS

Here's the relevant output with ansible 2.5.5:

```
TASK [ansible-gpii-version-updater : Run version-updater container] ************
changed: [ansible-gpii-version-updater]
```

##### ACTUAL RESULTS

Here's the relevant output with ansible 2.6.0:

```
TASK [ansible-gpii-version-updater : Run version-updater container] ************
fatal: [ansible-gpii-version-updater]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_Rrvdub/ansible_module_docker_container.py\", line 2081, in <module>\r\n    main()\r\n  File \"/tmp/ansible_Rrvdub/ansible_module_docker_container.py\", line 2076, in main\r\n    cm = ContainerManager(client)\r\n  File \"/tmp/ansible_Rrvdub/ansible_module_docker_container.py\", line 1703, in __init__\r\n    self.present(state)\r\n  File \"/tmp/ansible_Rrvdub/ansible_module_docker_container.py\", line 1723, in present\r\n    new_container = self.container_create(self.parameters.image, self.parameters.create_parameters)\r\n  File \"/tmp/ansible_Rrvdub/ansible_module_docker_container.py\", line 825, in create_parameters\r\n    host_config=self._host_config(),\r\n  File \"/tmp/ansible_Rrvdub/ansible_module_docker_container.py\", line 931, in _host_config\r\n    return self.client.create_host_config(**params)\r\n  File \"/usr/lib/python2.7/site-packages/docker/api/container.py\", line 157, in create_host_config\r\n    return utils.create_host_config(*args, **kwargs)\r\nTypeError: create_host_config() got an unexpected keyword argument 'init'\r\n", "msg": "MODULE FAILURE", "rc": 1}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/docker/docker_container.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_container.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chouseknecht @cove @dusdanig @joshuaconner @kassiansun @softzilla @zfil
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by robertdebock** [comment]
Same problem here, debug logs [here](https://travis-ci.org/robertdebock/ansible-role-bootstrap/jobs/398513311).

**Comment by felixfontein** [comment]
Can you check which version of the `docker` Python library you installed? On my machines (where `docker_container` seems to work), I have `docker==3.3.0` (`pip show docker`).

**Comment by mrtyler** [comment]
I'm pretty sure I do not have the `docker` library installed:

```
$ pip show docker
$ python -c 'import docker'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named docker
```

Also, the only difference between my success case and my failure case was `pip install ansible==2.5.5`, as verified by comparing `pip list` before and after the downgrade.

**Comment by felixfontein** [comment]
In @robertdebock's logs it seems that `docker-py` (version 1.10.6) is installed. [docker-py](https://pypi.org/project/docker-py/) is no longer maintained (last release from November 2016), you should install [docker](https://pypi.org/project/docker/) instead. Both provide a `docker` Python module.

Spontaneously, I would say your problem is caused by #34547. There is a [check included to avoid this](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/docker_common.py#L191), but the check is not sufficient as the code passes the `init` parameter on in any case, while the test only fires if `module.params.get("init")` is truish.

To fix this, [there should probably be a check here](https://github.com/suzuki-shunsuke/ansible/blob/d120b04184a03733e86c182fcaaf52f879c2bb29/lib/ansible/modules/cloud/docker/docker_container.py#L924) to remove `init` from `params` if it is not truish.

**Comment by felixfontein** [comment]
@mrtyler You probably also have `docker-py` installed, then (on the target machines, not on the machine where ansible runs -- for `docker_container`, the library is only needed and used on the target machines).

**Comment by felixfontein** [comment]
Actually, there seems to be a fix for this (on the first glance), but it has never been merged: #40839

**Comment by resmo** [comment]
resolved_by_pr #40839

**Comment by robertdebock** [comment]
@felixfontein indeed, using `docker` instead of `docker-py` solves the issue for me. Thanks!

**Comment by albix** [comment]
When I switch to `docker` instead of `docker-py` the `docker_login` module complains about the missing `docker-py` package. Nevertheless `docker_container` works 
 
```sh
TASK [kubernetes : login to docker hub] **********************************************************************************************************************************************
fatal: [example.com]: FAILED! => {"changed": false, "msg": "Failed to import docker-py - No module named docker. Try `pip install docker-py`"}
```

**Comment by pschiffe** [comment]
Also `docker_network` module requires `docker-py` in ansible 2.6

**Comment by felixfontein** [comment]
@albix The error message sounds like the `docker` package is not installed (or Python/Ansible was not able to find it). Both the `docker` and the `docker-py` packages provide a Python module called `docker`, and if `import docker` doesn't work, none of these two seems to be installed. The error message (`Failed to import docker-py`) is not helpful, because both `docker-py` and `docker` should work.

@pschiffe Why do you think so? (I've never used it so far, but I cannot see from the code that it needs `docker-py`.)

**Comment by pschiffe** [comment]
@felixfontein I've just tried it. Managed OS is CentOS 7, and I've tried to remove `python-docker-py` rpm package to workaround this issue, but it failed on the `docker_network` module. With `python-docker-py` rpm package installed it fails on the `docker_container` module issue described above. Now I've just downgraded ansible to 2.5.5 and it works as usual. Below is my task and it's output.

```
- name: create a network for a mariadb container
  docker_network:
    name: '{{ mariadb_network_name }}'
    driver_options:
      com.docker.network.driver.mtu: '1458'
    state: present
```

```
TASK [mariadb-docker : create a network for a mariadb container] **************************************
fatal: [apps01]: FAILED! => {"changed": false, "msg": "Failed to import docker-py - No module named docker. Try `pip install docker-py`"}
```

**Comment by felixfontein** [comment]
@pschiffe After removing `python-docker-py`, did you install the `docker` Python module (with `pip install docker`)? The error message you get sounds like you have neither `docker-py` nor `docker` installed.
Can you post your output of `pip show docker`?

**Comment by felixfontein** [comment]
I was able to run your task without the `docker-py` module, but with the `docker` module installed. For `pip show docker-py`, I get no output (i.e. it is not installed), and for `pip show docker`, I get
```
Name: docker
Version: 3.4.1
Summary: A Python library for the Docker Engine API.
Home-page: https://github.com/docker/docker-py
Author: Joffrey F
Author-email: joffrey@docker.com
License: Apache License 2.0
Location: /usr/lib/python3.6/site-packages
Requires: six, docker-pycreds, requests, websocket-client
Required-by: 
```

**Comment by felixfontein** [comment]
`docker_login` also works fine for me with `docker` and without `docker-py`.

**Comment by iamrenejr** [comment]
I am experiencing the same issue.

Previously, my Ansible version was 2.6.0. Running the following task:

```
- name: Jenkins | Start Jenkins container
  docker_container:
    name: jenkins
    image: jenkins/jenkins:lts
    state: started
    ports:
     - "8080:8080"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /usr/bin/docker:/usr/bin/docker
```

Crashed with an error:

```
fatal: [web-backup]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 52.221.184.236 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_20Ld91/ansible_module_docker_container.py\", line 2081, in <module>\r\n    main()\r\n  File \"/tmp/ansible_20Ld91/ansible_module_docker_container.py\", line 2076, in main\r\n    cm = ContainerManager(client)\r\n  File \"/tmp/ansible_20Ld91/ansible_module_docker_container.py\", line 1703, in __init__\r\n    self.present(state)\r\n  File \"/tmp/ansible_20Ld91/ansible_module_docker_container.py\", line 1723, in present\r\n    new_container = self.container_create(self.parameters.image, self.parameters.create_parameters)\r\n  File \"/tmp/ansible_20Ld91/ansible_module_docker_container.py\", line 825, in create_parameters\r\n    host_config=self._host_config(),\r\n  File \"/tmp/ansible_20Ld91/ansible_module_docker_container.py\", line 931, in _host_config\r\n    return self.client.create_host_config(**params)\r\n  File \"/usr/local/lib/python2.7/dist-packages/docker/api/container.py\", line 157, in create_host_config\r\n    return utils.create_host_config(*args, **kwargs)\r\nTypeError: create_host_config() got an unexpected keyword argument 'init'\r\n", "msg": "MODULE FAILURE", "rc": 1}
```

After I downgraded Ansible to 2.5.5, this error went away.

**Comment by OutdoorTree90990** [comment]
Same here, had to reverse my project due to the 2.6 upgrade for https://plexguide.com - rewrote project and locked at 2.55 - I get numerous questions about 2.6 due to the init error

https://plexguide.com/threads/init-issues-6-004.1493/

This is just information to assist others.

**Comment by geerlingguy** [comment]
I ran into this today as well, I’ll check and see if I’m using docker-py or docker.

**Comment by felixfontein** [comment]
@geerlingguy You'll need `docker >= 2.3.0` until this is fixed (i.e. #40839 is merged and a new version containing it released).

**Comment by OutdoorTree90990** [comment]
This comment is off, but between ansible 2.6, dockerpy (call it the dockerpy-of-death) and that error likes to show up; some serious fixes need to be made to either catch or prevent the errors for ansible.

**Comment by alter** [comment]
2.6.1 the same issue, rollback to 2.5.5 helped.

**Comment by geerlingguy** [comment]
Switching to `docker` from `docker-py` fixed it for me; builds are passing on this project https://travis-ci.org/geerlingguy/php-apache-container/builds/402407239

**Comment by pschiffe** [comment]
@felixfontein sorry for super late answer, but you are right, I didn't have any python docker bindings installed. In Fedora there are now `python2-docker` and `python3-docker` rpm packages, but CentOS has only `python34-docker` rpm package and an old `python-docker-py` rpm package for python 2 - https://bugzilla.redhat.com/show_bug.cgi?id=1598818

So for me the workaround would be to install python docker bindings via pip, but I didn't want to pollute the environment with pip if not really necessary. Using ansible with python 3 should be a viable way as well, but I didn't go there for now. So I've just downgraded ansible to 2.5.5 until this fix will be present in 2.6.

Thank you @felixfontein very much for helping me sort that out.

**Comment by felixfontein** [comment]
@pschiffe You can of course also patch `ansible`. Simply commenting out `init` being passed into `host_config_params` in `modules/cloud/docker/docker_container.py` does the trick. Of course that won't work well if you're not the only one using that playbook ;)

**Comment by ikke-t** [comment]
I experience this against rhel hosts as well. I run ansible from fedora 28, so it's 2.6 something. But on RHEL, I removed python-docker-py, which removes also docker-compose due dependency. Then I try yum install python-docker, it tries to install the python-docker-py back. It seems the only way to go around this on RHELs would be using pip atm. Which I don't like due the maintenance reason.

**Comment by ikke-t** [comment]
just to report back, it works on RHEL also by pip install docker. It should come through package though.

**Comment by pschiffe** [comment]
@felixfontein right, thanks for the tip.

**Comment by TomasTomecek** [comment]
@ikke-t please contact Red Hat support if you wish to have a more recent version of docker-py in RHEL. The reason we have 1.10.6 is just that no one requested a newer version.

**Comment by ronjakoi** [comment]
@TomasTomecek 1.10.6 is the latest upstream version: https://pypi.org/project/docker-py/#history

**Comment by pschiffe** [comment]
@ronjakoi for some reason, `docker-py` pip package has an old version of https://github.com/docker/docker-py . The latest version of that library is in `docker` pip package - https://pypi.org/project/docker/#history

**Comment by felixfontein** [comment]
The `docker-py` package was renamed to `docker` for version 2.0 (see docker/docker-py#1310) to unify the naming across the Docker SDK for various languages. It is just too bad that both pypi pages don't mention this... (Also the Ansible docs haven't been much more helpful... that's improved by #42457 though.)

**Comment by cfloersch** [comment]
It should be noted that the docker_container module requires the newer docker library while the docker_login module requires the older docker-py library. Both libraries cannot be installed at the same time. As such a playbook cannot both login to a registry and create a container image with Ansible 2.6.1

**Comment by felixfontein** [comment]
@cfloersch That's not true. All of the `docker_*` modules work with the new libraries. For `docker_login`, we already discussed this in this issue, and I explicitly verified that it does work with the latest `docker` library. The documentation in Ansible < 2.6.2 is misleading (this will be fixed in the next release as well as this issue).

**Comment by cfloersch** [comment]
@felixfontein That's interesting because I just ran this on Ansible 2.6.1 and it failed to run docker_login when docker-py was not installed.

Here are the two messages I got as I tested:

1) Try and install both:
Cannot have both the docker-py and docker python modules installed together as they use the same namespace and cause a corrupt installation. Please uninstall both packages, and re-install only the docker-py or docker python module

2) Try and uninstall docker-py and install docker
Failed to import docker-py - No module named docker. Try `pip install docker-py`

**Comment by felixfontein** [comment]
@cfloersch You cannot have both installed, that's correct. But you apparently uninstalled both. The error message "No module named docker" means that none of them is installed. If you make sure you only have `docker` installed (and not `docker-py`), it should work.
Ansible 2.6.1 (and earlier) always mention docker-py in all messages and documentation (this has been cleaned up and will appear in Ansible 2.6.2); the problem is that docker-py was renamed to docker for version 2.0, but unfortunately there's no hint about this on the pypi package sites. This causes a lot of (unnecessary) confusion... docker is simply a newer version of docker-py, and the github archive for the library is still called [docker-py](https://github.com/docker/docker-py/).

**Comment by cfloersch** [comment]
So I do have docker 3.4.0 installed. 

[root@pcast]# pip list
... trimmed for brevity ...
dnspython (1.12.0)
docker (3.4.0)
docker-pycreds (0.3.0)
... trimmed for brevity ...

Does it need to be installed on both the tower and the target machine? Or just the target machine?

**Comment by felixfontein** [comment]
It only needs to be installed on the target machine. The docker modules are executed on the target machine, not on the control machine.
Anyway: what happens if you start Python (the one used by Ansible on the remote node) and run `import docker`? That should work fine if you have either `docker-py` or `docker` installed. If it doesn't work, there's something wrong (I'd guess neither `docker-py` nor `docker` is installed, but I don't know about pip's internals, so maybe removing `docker-py` will somehow destroy/disable `docker`?).

**Comment by ronjakoi** [comment]
I had the problem described by @cfloersch [here](https://github.com/ansible/ansible/issues/42162#issuecomment-407459778). I think it was fixed when I did `pip uninstall docker docker-py && pip install --force-reinstall docker` or something like that.

**Comment by felixfontein** [comment]
@ronjakoi I think the `pip install --force-reinstall docker` is necessary. I just tried this out. First, I had `docker` installed:
``` .py
>>> import docker
>>> docker.version
'3.4.1'
```
Then I installed `docker-py`:
``` .py
>>> import docker
>>> docker.version
'1.10.6'
```
Then I uninstalled `docker-py`:
``` .py
>>> import docker
>>> docker.version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'docker' has no attribute 'version'
```
Finally, I force-reinstalled `docker`:
``` .py
>>> import docker
>>> docker.version
'3.4.1'
```
Looks like uninstalling `docker-py` breaks `docker`. That's *really* annoying...

**Comment by felixfontein** [comment]
@cfloersch @ronjakoi I tried to improve the situtation by adding some clarifying remarks here: #43238

**Comment by cfloersch** [comment]
So after some debugging I finally got it working. Apparently, I had to manually remove docker-pycreds as well as docker-py and docker before force reinstalling.

```python
>>> import docker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
   .. TRIMMED ..
    import dockerpycreds
ImportError: No module named dockerpycreds
```

All of these machines had been using the older libraries with Ansible 2.5.x and as such I had to remove ALL of the older libraries.

**Comment by Hnasar** [comment]
I needed to uninstall docker-py and docker-compose, and THEN install docker, and then things worked.

**Comment by TheLastCicada** [comment]
I can confirm `pip install --force-reinstall docker` was necessary on my Ubuntu 14.04 setup as well.  Just uninstalling `docker-py` and installing `docker` with pip ended up with the error saying `docker-py` was needed.  The `--force-reinstall` resolved the issue.

**Comment by felixfontein** [comment]
Everyone: Ansible 2.6.2 was released today, which contains a fix for this issue.

**Comment by ephracis** [comment]
I know this issue is closed but I am getting it on RHEL Atomic Host. Does this mean that it does not support Ansible 2.6 or later?

(There is no pip on Atomic.)

**Comment by felixfontein** [comment]
@ephracis Which version of Ansible are you using? This bug has been introduced in Ansible 2.6.0, and was fixed in 2.6.2, so all 2.7.x versions, 2.6.x for x >= 2, and all 2.5.x versions and earlier should be fine. (Except if there's a different bug.)

**Comment by ephracis** [comment]
I was using 2.6.0. Upgraded to 2.7.5 and it works now. 👍

**Comment by felixfontein** [comment]
@ephracis great to hear that it now works for you! :)

**Comment by SerenaFeng** [comment]
In my situation, the ansible is 2.7.3, it failed with the docker-py 1.7.0, Upgrade docker-py to 1.10.6, it works.

**Comment by felixfontein** [comment]
@SerenaFeng what was the exact error message you got with docker-py 1.7.0?

**Comment by felixfontein** [comment]
@SerenaFeng the docker-py 1.7.x incompatibility should be fixed by #55496. Upgrading to everything newer than docker-py 1.8.0 should fix the problem as well. Also, when you're upgrading, please remove the docker-py module and install the docker module (docker-py was renamed to docker starting with version 2.0.0). Note that you can't have both installed at the same time, then both will be broken. Also note that 2.0.0 drops support for Python 2.6, so if you only have Python 2.6, please stick to docker-py 1.10.6 :)
