### ISSUE TITLE
syslog_json output plugin is broken

### ISSUE THREAD

**Issue by captainwasabi** [ansible/ansible#69686]
##### SUMMARY
Output callback syslog_json is broken
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
syslog_json

##### ANSIBLE VERSION

```
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = [u'debug', u'syslog_json']
DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 30
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
```

##### OS / ENVIRONMENT

Centos 7.8

##### STEPS TO REPRODUCE

just set the output callback to use syslog_json

```
ANSIBLE_STDOUT_CALLBACK=syslog_json ansible-playbook -vvv -i inv_file.yml playbooks.yml
```

##### EXPECTED RESULTS

it wouldn't throw an exception

##### ACTUAL RESULTS

```
ERROR! Unexpected Exception, this is probably a bug: 'CallbackModule' object has no attribute '_load_name'
the full traceback was:

Traceback (most recent call last):  File "/bin/ansible-playbook", line 123, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 127, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 99, in run
    self._tqm.load_callbacks()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 134, in load_callbacks
    self._stdout_callback = callback_loader.get(self._stdout_callback)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 578, in get
    obj = obj(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/callback/syslog_json.py", line 70, in __init__
    self.set_options()
  File "/usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.py", line 99, in set_options
    self._plugin_options = C.config.get_plugin_options(get_plugin_class(self), self._load_name, keys=task_keys, variables=var_options, direct=direct)
AttributeError: 'CallbackModule' object has no attribute '_load_name'

```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by imjoseangel** [comment]
This issue was introduced in commit https://github.com/ansible/ansible/commit/2ef7759be1515b82495217e718152735ed589f33#diff-6a381f499eba393581968ee868ecf560 and can be fixed like:

```python
    def set_options(self, task_keys=None, var_options=None, direct=None):

        super(CallbackModule, self).set_options(task_keys=task_keys, var_options=var_options, direct=direct)

        self.syslog_host = self.get_option("server")
        self.syslog_port = int(self.get_option("port"))
        self.syslog_facility = self.get_option("facility")

        self.logger = logging.getLogger('ansible logger')
        self.logger.setLevel(logging.DEBUG)

        self.handler = logging.handlers.SysLogHandler(
            address=(self.syslog_host, self.syslog_port),
            facility=self.syslog_facility
        )
        self.logger.addHandler(self.handler)
        self.hostname = socket.gethostname()
```

@captainwasabi Is it going to be fixed in 2.9 or in collections? Do you want me to launch a PR?

**Comment by imjoseangel** [comment]
Fixed in PR https://github.com/ansible-collections/community.general/pull/408

**Comment by mkrizek** [comment]
Closing this in favor of https://github.com/ansible-collections/community.general/issues/407 which is the correct place to report this now. Thanks!

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
