### ISSUE TITLE
NoAuthHandlerFound from ec2_ami using python2.6 on Ubuntu 10.04

### ISSUE THREAD

**Issue by swordeh** [ansible/ansible#10293]
Hi,

Very much aware I am trying to do something on soon to be a unsupported OS, but unfortunately right now I don't have a choice.

I'm trying to use Ansible to create an AMI of a machine I am provisioning, however I seem to be running into the same issue with python 2.6 on Ubuntu 10.04. When running the exact same role I've worked on under 12.04 and 14.04 with python 2.7, it works flawlessly.

My code is:

```
- name: "Create an AMI based on instance ID gathered."
  ec2_ami:
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"
    instance_id: "{{ instance_id.stdout }}"
    region: eu-west-1
    wait: yes
    name: "mi-build-python26"
    no_reboot: yes
  register: instance
  tags:
    - aws
```

When running this on 10.04, I get the following error:

I'd used debug to make sure that my variables are being set correctly, which they are. 

```
failed: [default] => {"failed": true, "parsed": false}
SUDO-SUCCESS-lymqzsgpkszkyxustggvpkmskgqsiipz
Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1424357479.62-95350531772866/ec2_ami", line 2030, in <module>
    main()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1424357479.62-95350531772866/ec2_ami", line 251, in main
    ec2 = ec2_connect(module)
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1424357479.62-95350531772866/ec2_ami", line 2017, in ec2_connect
    except boto.exception.NoAuthHandlerFound, e:
AttributeError: 'module' object has no attribute 'NoAuthHandlerFound'
```

Would appreciate any input on this.

Cheers

**Comment by bcoca** [comment]
this seems like a boto error, boto is the underlying library that is used to communicate with aws.

I would suggest running this as a 'local' action on your workstation/machine you run ansible from.

Even though this is a boto issue, I'm keeping the ticket open because we should handle the exception.

**Comment by swordeh** [comment]
Thanks @bcoca - I'm now running this as a local action and it works fine!

**Comment by bcoca** [comment]
closing this in favor of the PR
