### ISSUE TITLE
cannot get remote_user in a callback plugin (hipchat)

### ISSUE THREAD

**Issue by ibogomolov** [ansible/ansible#35047]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
cli.options and play modules

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = /Users/ibogomolov/ansible/ansible.cfg
  configured module search path = [u'/Users/ibogomolov/ansible/externals/roles/library', u'/Users/ibogomolov/ansible-roles/library']
  ansible python module location = /Users/ibogomolov/homebrew/lib/python2.7/site-packages/ansible
  executable location = /Users/ibogomolov/homebrew/bin/ansible
  python version = 2.7.13 (default, Nov 10 2017, 15:32:22) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION
ALLOW_WORLD_READABLE_TMPFILES(/Users/ibogomolov/ansible/ansible.cfg) = True
DEFAULT_ACTION_PLUGIN_PATH(/Users/ibogomolov/ansible/ansible.cfg) = [u'/Users/ibogomolov/ansible/action_plugins']
DEFAULT_CALLBACK_PLUGIN_PATH(/Users/ibogomolov/ansible/ansible.cfg) = [u'/Users/ibogomolov/ansible/callback_plugins', u'/Users/ibogomolov/ansible/shared/callback_
DEFAULT_CALLBACK_WHITELIST(/Users/ibogomolov/ansible/ansible.cfg) = ['hipchat2']
DEFAULT_FORKS(/Users/ibogomolov/ansible/ansible.cfg) = 50
DEFAULT_GATHERING(/Users/ibogomolov/ansible/ansible.cfg) = explicit
DEFAULT_MODULE_PATH(/Users/ibogomolov/ansible/ansible.cfg) = [u'/Users/ibogomolov/ansible/externals/roles/library']
DEFAULT_ROLES_PATH(/Users/ibogomolov/ansible/ansible.cfg) = [u'/Users/ibogomolov/ansible/roles', u'/Users/ibogomolov/ansible/externals/roles', u'/Users/ibogomolov
HOST_KEY_CHECKING(/Users/ibogomolov/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT
Mac OS 10.11.6

##### SUMMARY
I am developing a callback plugin to print messages to hipchat when playbook starts and finishes, and some additional info like who is running the playbook. To get the username I tried 2 ways:

1. cli.options.remote_user -- it outputs "None" in v2_playbook_on_play_start, v2_playbook_on_start and v2_playbook_on_task_start.

2. play.remote_user -- it outputs "None" if no remote_user is defined in the play. See code below.
I think it should be set to current user if not defined. At least that's the behavior.
```
    def v2_playbook_on_play_start(self, play):
        print(play.remote_user)
```
```
- hosts: tool
  become: yes
  become_user: root
  gather_facts: yes
  roles:
```

How do I get username which runs the playbook or play in a callback plugin?

I looked at hipchat callback plugin in this repo (https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/callback/hipchat.py) and it's not working with Ansible 2.4:
```
PLAY [tool] ******************************************************************************************** 
[WARNING]: Failure using method (v2_playbook_on_play_start) in callback plugin (<ansible.plugins.callback.hipchat.CallbackModule object at 0x10dd0f5d0>): 'Play' object has no attribute 'playbook'
```

##### EXPECTED RESULTS
cli.options.remote_user and/or play.remote_user should return current user which runs the playbook/play.

##### ACTUAL RESULTS
"None" is returned. My guess the vars are not populated.

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
This is possible. The slack callback that is included with ansible does it currently:

https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/callback/slack.py#L92-L94
https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/callback/slack.py#L155

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
