### ISSUE TITLE
Nagios cmdfile not working with python 2.4

### ISSUE THREAD

**Issue by broferek** [ansible/ansible#1194]
On my nagios server, I run a python 2.4.3. 
But when it comes to looking for the default cmdfile with the nagios module, I have the following python error :
   File "/var/tmp/ansible-1349168631.04-19012043596969/nagios", line 167, in which_cmdfile
     return line.partition('=')[2].strip()
 AttributeError: 'str' object has no attribute 'partition'

When using the partition function with a python 2.6.6, it works fine.

**Comment by broferek** [comment]
daniel_hozac: should just be replaced with line.split('=')[1].strip()

**Comment by mpdehaan** [comment]
If you want to message someone on github, it's like this @broferek 

@dhozac 

Though this is really @tbielawa's module

Send us a pull request if you'd like to fix it or otherwise Tim maybe you'd like to fix?

**Comment by mpdehaan** [comment]
Easy enough!  Thank you!

**Comment by broferek** [comment]
https://github.com/ansible/ansible/pull/1200

Just sent the pull request. 
For my first comment, I was just making a reference to a discussion we've had with Daniel on the IRC channel to give the solution to the issue
