### ISSUE TITLE
Docker modules don't work with latest docker-py (2.0+)

### ISSUE THREAD

**Issue by berlic** [ansible/ansible#20380]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
docker_container, docker_image, other docker modules

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /vagrant/cloudocker/ansible.cfg
  configured module search path = ['./library/']
```

##### CONFIGURATION
Standard configuration

##### OS / ENVIRONMENT
On target Docker host
```
# pip list
...
docker (2.0.1)
...
```

##### SUMMARY
Although `docker-py` is installed Ansible gives:

> Failed to import docker-py - cannot import name Client. Try `pip install docker-py`

##### STEPS TO REPRODUCE
`pip install docker-compose` this will install latest version of docker-compose, which is dependent on `docker-py` 2.0+ (named `docker` on pypi from now on). 

`docker_image` calls stops working after this.

Quotes from `docker-py` release notes:

> **Breaking changes**
>
> docker.Client has been renamed to docker.APIClient
> ...
> The name of the pip package is now docker (was: docker-py). New versions of this library will only be published as docker from now on.
> ...

So [this](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/docker_common.py#L34) gives error.

**Comment by yuriidanyliak** [comment]
It affected us as well. 

The workaround, if you use `angstwad.docker_ubuntu` playbook is to lock versions prior `2.0.1`

```yaml
    - role: angstwad.docker_ubuntu
      docker_group_members: ['{{ ssh_user }}']
      pip_version_docker_py: '1.10.6'
      pip_version_docker_compose: '1.9.0'
      tags: ['docker']
```

Also, I've got to remove all pip packages from host machine:

    pip list | grep -v pip | awk '{print $1}' | while read i; do sudo pip uninstall -y "$i"; done

**Comment by Asara** [comment]
Thanks @yuriidanyliak 

This was driving me nuts last night.

**Comment by Geethree** [comment]
Same here. Spent a few hours pulling out my hair prior to realizing that docker-compose and docker api have been updated....

**Comment by sivel** [comment]
This was recently resolved in the devel branch as part of https://github.com/ansible/ansible/pull/19633 / https://github.com/ansible/ansible/commit/e2a1ce2916e9b87fe1ad4a1011c04ef8d2faf046 and will be included in the 2.3.0 release.

**Comment by Geethree** [comment]
#19633

**Comment by benairs3** [comment]
@yuriidanyliak where I put those lines? I have the same problem here

**Comment by yuriidanyliak** [comment]
@benairs3 `site.yml`

**Comment by benairs3** [comment]
@yuriidanyliak I don't have this site.yml file. I work with vagrant, and ansible. I have my main.yml in /roles/bootstrap_containers/tasks/mani.yml 
Is here when vagrant running crashes. Is there where I have to put those lines? I'm so lost ...

**Comment by yuriidanyliak** [comment]
@benairs3, I don't know where you are installing `docker-py` in your configs, but the original idea is to lock `docker-py` to version prior to `2.0.1`

**Comment by Geethree** [comment]
Or switch to 2.3.0 devel... or modify your lib/ansible/module_utils/docker_common.py if you absolutely need the fix, can't pin versions or use the devel branch..
https://github.com/ansible/ansible/commit/e2a1ce2916e9b87fe1ad4a1011c04ef8d2faf046

**Comment by Geethree** [comment]
Or switch to 2.3.0 devel... or modify your lib/ansible/module_utils/docker_common.py https://github.com/ansible/ansible/commit/e2a1ce2916e9b87fe1ad4a1011c04ef8d2faf046  if you absolutely need the fix, can't pin versions or use the devel branch..
