### ISSUE TITLE
On Ansible stable-2.2 setup module fails with /proc mounted with hidepid=2

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#20225]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

The `setup` module.

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

Default configuration.

##### OS / ENVIRONMENT

Ubuntu 16.04, `/proc` mounted with `hidepid=2`, user account used by Ansible cannot read `/proc` entries other than their own.

##### SUMMARY

The `setup` module fails when it cannot read `/proc` to find out what service manager is installed on the system.  The error appears to be introduced after https://github.com/ansible/ansible/commit/cfbb58adaeb3a7814667dbdc18272bffff5f8ef8 was cherry-picked to `stable-2.2` branch. The `devel` branch seems to be unaffected.

##### STEPS TO REPRODUCE

Make sure that your `/proc` is mounted with at least `hidepid=1` and the user used by Ansible cannot read `/proc` entries not owned by it. Make sure that Ansible does not use `sudo` by default.

Execute command `ansible <hostname> -m setup`

```yaml

```

##### EXPECTED RESULTS

The `setup` module returns host facts.

##### ACTUAL RESULTS

```
fatal: [hostname]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to fileshare.deb8.gumed.edu.pl closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_70AFmc/ansible_module_setup.py\", line 134, in <module>\r\n    main()\r\n  File \"/tmp/ansible_70AFmc/ansible_module_setup.py\", line 126, in main\r\n    data = get_all_facts(module)\r\n  File \"/tmp/ansible_70AFmc/ansible_modlib.zip/ansible/module_utils/facts.py\", line 3518, in get_all_facts\r\n  File \"/tmp/ansible_70AFmc/ansible_modlib.zip/ansible/module_utils/facts.py\", line 3457, in ansible_facts\r\n  File \"/tmp/ansible_70AFmc/ansible_modlib.zip/ansible/module_utils/facts.py\", line 168, in __init__\r\n  File \"/tmp/ansible_70AFmc/ansible_modlib.zip/ansible/module_utils/facts.py\", line 339, in get_service_mgr_facts\r\nAttributeError: 'NoneType' object has no attribute 'endswith'\r\n", "msg": "MODULE FAILURE"}
```

**Comment by bcoca** [comment]
backported fix from devel 4b495d7e43360fc5f45dc84dbd2f6034c4148d21
