### ISSUE TITLE
yum module fails with 'dict object' has no attribute '\\x00$' when used in loop and with dict lookup

### ISSUE THREAD

**Issue by mmilata** [ansible/ansible#15649]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel f2980fc565) last updated 2016/04/28 14:44:57 (GMT +000)
  lib/ansible/modules/core: (detached HEAD e78ee3b128) last updated 2016/04/28 14:46:09 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD ca310f3d15) last updated 2016/04/28 14:46:13 (GMT +000)
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

No configuration.
##### OS / ENVIRONMENT

Reproduced on Fedora 23. I'm connecting to localhost, however the error happens before connection attempt is made.
##### SUMMARY

Running the attached playbook produces the rather cryptic error `'dict object' has no attribute '\\x00$'`. The bug appears to be related to:
- yum module (dnf, apt too),
- loops,
- dictionary lookup in the name argument to the module,

as taking any out of the equation does not reproduce the error.
##### STEPS TO REPRODUCE

Run following playbook:

```

---
- hosts: all
  gather_facts: false
  vars:
    package_map:
      foo: bar
    packages:
    - foo
  tasks:
  - yum: name={{ package_map[item] }}
    with_items: "{{ packages }}"
```

`ansible-playbook -i hosts reproduce.yml -vvvv`
##### EXPECTED RESULTS

Package `bar` to be installed using `yum`.
##### ACTUAL RESULTS

```
No config file found; using defaults
Loaded callback default of type stdout, v2.0

PLAYBOOK: reproduce.yml ********************************************************
1 plays in reproduce.yml

PLAY [all] *********************************************************************

TASK [yum] *********************************************************************
task path: /home/fedora/ansible-reproducer/reproduce.yml:12
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute '\\x00$'"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @reproduce.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```

**Comment by nitzmahone** [comment]
Module Repo Information
=======================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

   * Find the module at http://docs.ansible.com/list_of_all_modules.html
   * Open the documentation page for that module
   * If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
   * Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by kustodian** [comment]
This shouldn't be closed, since this bug report isn't a bug in the `yum` module, but in core. This was also introduced with 2.1 because of item squashing changes. Everything worked in versions <=2.0.

**Comment by abadger** [comment]
After having looked at the associated PR and this bug... the bug itself could be fixed by having a try: except around squashing.  If any exceptions are thrown, do not squash.  That's a simple change because squashing is simply an optimization (one that we're discussing whether to deprecate since users can give the field a list [ using filters to construct the list if necessary ] instead of relying on squashing).

This is probably a good thing to do regardless of whether we accept that PR as there could be other cornercases i nthe squashing code and we can recover from any of those in the same manner.

**Comment by szjur** [comment]
Hi

I had this task in my role that worked perfectly in 1.8.4 and with 2.0.2 it spat out 'dict object' has no attribute '\x00$'.
`- name: Install lastest version of the same grsec kernel that is already installed
  apt: name=linux-image-{{grsecurity.latest_kernel_versions[item]}}-{{item}} state=installed update_cache=yes cache_valid_time=180 force=no install_recommends=no`
`when: grsecurity_proc.stat.exists and ansible_kernel|match(".*-{{item}}$")`
`with_items:`
`- flavour1`
`- flavour2`
`- flavour3`
`register: grsec_kernel`

The vars used above were stored in the defaults:

`latest_grsec_kernel_version: '3.14.70-1'`
`grsecurity: {`
`....`
`latest_kernel_versions: {`
`flavour1: "{{latest_grsec_kernel_version}}",`
`flavour2: "{{latest_grsec_kernel_version}}",`
`flavour3: "{{latest_grsec_kernel_version}}",`
`}`
`}`

With de3f01315253eda754b9651abbf0fb7f73b08eb3 the error stopped appearing but it didn't install any package either (it was coloured green indicating no changes were done and indeed no package was installed).

Amazingly it works this way in stock 2.0.2 (without the above patch):

`- name: Install lastest version of the same grsec kernel that is already installed
  apt: name=linux-image-{{grsecurity.latest_kernel_versions[item.flavour]}}-{{item.flavour}} state=installed update_cache=yes cache_valid_time=180 force=no install_recommends=no`
`when: grsecurity_proc.stat.exists and ansible_kernel|match(".*-{{item.flavour}}$")`
`with_items:`
`- { flavour: flavour1 }`
`- { flavour: flavour1 }`
`- { flavour: flavour1 }`
`register: grsec_kernel`

Is it just me misusing 2.0.2 or it works not the way you intended? Some simpler cases using with_items: seem to work with non-dict-style items. I guess that it is this dict being used here that gives ansible a headache: {{grsecurity.latest_kernel_versions[item]}}-{{item}}.

**Comment by abadger** [comment]
@szjur Can you apply this commit in addition to https://github.com/ansible/ansible/commit/de3f01315253eda754b9651abbf0fb7f73b08eb3 and let us know if it works:  https://github.com/ansible/ansible/commit/b75895df9beab38d7a9631af9188bbae5d180953  ?

I think what's happening is that the squashing function modifies the task.args in addition to returning the new list of squashed values.  The fix I applied earlier returned the original list of values in case of an error but did not restore the task.args.  This should fix that.

I did something similar to what you're doing with dnf and it errored for me.  I think with apt, you're specifying update_cache so it's silently updating the cache and nothing else instead of explicitly throwing an error.

**Comment by szjur** [comment]
I applied b75895df9beab38d7a9631af9188bbae5d180953 on top of de3f01315253eda754b9651abbf0fb7f73b08eb3 and it now works again with non-dict items :-) I will remove my workaround from the playbook then as I like to keep things simple. Thanks!

**Comment by abadger** [comment]
Excellent.  The fix ha sbeen merged to the stable-2.1 branch and devel.  We'll most likely get it into 2.1.0 but will decide on Monday (it will be in 2.1.1 if it doesn't make it into 2.1.0)

**Comment by abadger** [comment]
This fix made it into 2.1.0.  Closing ticket.
