### ISSUE TITLE
ec2_eip module doesn't know public_ip

### ISSUE THREAD

**Issue by danvaida** [ansible/ansible#7803]
##### Environment:

Host running Ansible from: FC19 x86_64 & Destination host: Wheezy 7 x86_64
##### Summary:

For convenience and fanciness :) I am trying to display the assigned EIP.
As described in the documentation:
http://docs.ansible.com/ec2_eip_module.html
##### Steps To Reproduce:

Here are the relevant tasks from my playbook that generate this issue:

``` yaml
- name: add EIP to the instance
    local_action: ec2_eip in_vpc=yes instance_id={{ item.id }} region={{ region }}
    with_items: ec2.instances
    register: eip

  - name: output the IP
    debug: msg= "Allocated IP inside the VPC is {{ eip.public_ip }}"
```
##### Expected Results:

Display of the EIP added to the EC2 instance.
##### Actual Results:

``` yaml
TASK: [add EIP to the instance] *********************************************** 
changed: [localhost] => (item={u'kernel': u'aki-52a34525', u'root_device_type': u'ebs', u'private_dns_name': u'ip-10-0-0-141.eu-west-1.compute.internal', u'public_ip': u'54.76.138.13', u'private_ip': u'10.0.0.141', u'id': u'i-3c7adf7f', u'ebs_optimized': True, u'state': u'running', u'virtualization_type': u'paravirtual', u'architecture': u'x86_64', u'ramdisk': None, u'key_name': u'ansible-ec2', u'image_id': u'ami-630fcb14', u'public_dns_name': u'ec2-54-76-138-13.eu-west-1.compute.amazonaws.com', u'state_code': 16, u'placement': u'eu-west-1a', u'ami_launch_index': u'0', u'dns_name': u'ec2-54-76-138-13.eu-west-1.compute.amazonaws.com', u'region': u'eu-west-1', u'launch_time': u'2014-06-17T12:02:49.000Z', u'instance_type': u'c3.2xlarge', u'root_device_name': u'/dev/sda', u'hypervisor': u'xen'})

TASK: [output the IP] ********************************************************* 
fatal: [localhost] => One or more undefined variables: 'dict object' has no attribute 'public_ip'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/dvaida/provision.retry

localhost                  : ok=3    changed=3    unreachable=1    failed=0
```

**Comment by jimi-c** [comment]
This is a consequence of the fact that you're using with_items above. The registered result instead contains an "items" entry which contains a result per item from the original execution. Because of this, you will need to also use with_items with your debug statement:

<pre>
  - name: output the IPs
    debug: msg="Allocated IP inside the VPC is {{ item.public_ip }}"
    with_items: eip.items
</pre>

If you have any further questions regarding this, please let us know. Thanks!

**Comment by danvaida** [comment]
Argh! Must've been too tired to see that one. Thanks!

**Comment by danvaida** [comment]
@jimi-c seems that it didn't fix it:

```
TASK: [output the IP] ********************************************************* 
fatal: [localhost] => One or more undefined variables: 'unicode object' has no attribute 'public_ip'
```

And quite curiously, here is the debug output:

```
TASK: [debug var=eip] ********************************************************* 
ok: [localhost] => {
    "eip": {
        "changed": true, 
        "msg": "All items completed", 
        "results": [
            {
                "changed": true, 
                "invocation": {
                    "module_args": "in_vpc=yes instance_id=i-e65bfca5 region=eu-west-1", 
                    "module_name": "ec2_eip"
                }, 
                "item": {
                    "ami_launch_index": "0", 
                    "architecture": "x86_64", 
                    "dns_name": "ec2-54-76-223-22.eu-west-1.compute.amazonaws.com", 
                    "ebs_optimized": true, 
                    "hypervisor": "xen", 
                    "id": "i-e65bfca5", 
                    "image_id": "ami-630fcb14", 
                    "instance_type": "c3.2xlarge", 
                    "kernel": "aki-52a34525", 
                    "key_name": "ansible-ec2", 
                    "launch_time": "2014-06-19T13:57:35.000Z", 
                    "placement": "eu-west-1a", 
                    "private_dns_name": "ip-10-0-0-150.eu-west-1.compute.internal", 
                    "private_ip": "10.0.0.150", 
                    "public_dns_name": "ec2-54-76-223-22.eu-west-1.compute.amazonaws.com", 
                    "public_ip": "54.76.223.22", 
                    "ramdisk": null, 
                    "region": "eu-west-1", 
                    "root_device_name": "/dev/sda", 
                    "root_device_type": "ebs", 
                    "state": "running", 
                    "state_code": 16, 
                    "virtualization_type": "paravirtual"
                }, 
                "public_ip": "54.76.224.89"
            }
        ]
    }
}

TASK: [output the IP] ********************************************************* 
fatal: [localhost] => with_items expects a list or a set
```

The true EIP of the instance is 54.76.224.89.

**Comment by jimi-c** [comment]
My apologies, I believe it should be `with_items: eip.results` (not .items).

**Comment by danvaida** [comment]
Hey. Thanks for the quick response. Yes, that is obvious thing to do. It is now working nicely. Perhaps someone should update this here as well: http://docs.ansible.com/ec2_eip_module.html

Fun fact: while hammering AWS, I even got this output :)

```
TASK: [add EIP to the instance] *********************************************** 
failed: [localhost] => (item={u'kernel': u'aki-52a34525', u'root_device_type': u'ebs', u'private_dns_name': u'ip-10-0-0-197.eu-west-1.compute.internal', u'public_ip': u'54.72.182.252', u'private_ip': u'10.0.0.197', u'id': u'i-4e5afd0d', u'ebs_optimized': True, u'state': u'running', u'virtualization_type': u'paravirtual', u'architecture': u'x86_64', u'ramdisk': None, u'key_name': u'ansible-ec2', u'image_id': u'ami-630fcb14', u'public_dns_name': u'ec2-54-72-182-252.eu-west-1.compute.amazonaws.com', u'state_code': 16, u'placement': u'eu-west-1a', u'ami_launch_index': u'0', u'dns_name': u'ec2-54-72-182-252.eu-west-1.compute.amazonaws.com', u'region': u'eu-west-1', u'launch_time': u'2014-06-19T13:49:01.000Z', u'instance_type': u'c3.2xlarge', u'root_device_name': u'/dev/sda', u'hypervisor': u'xen'}) => {"failed": true, "item": {"ami_launch_index": "0", "architecture": "x86_64", "dns_name": "ec2-54-72-182-252.eu-west-1.compute.amazonaws.com", "ebs_optimized": true, "hypervisor": "xen", "id": "i-4e5afd0d", "image_id": "ami-630fcb14", "instance_type": "c3.2xlarge", "kernel": "aki-52a34525", "key_name": "ansible-ec2", "launch_time": "2014-06-19T13:49:01.000Z", "placement": "eu-west-1a", "private_dns_name": "ip-10-0-0-197.eu-west-1.compute.internal", "private_ip": "10.0.0.197", "public_dns_name": "ec2-54-72-182-252.eu-west-1.compute.amazonaws.com", "public_ip": "54.72.182.252", "ramdisk": null, "region": "eu-west-1", "root_device_name": "/dev/sda", "root_device_type": "ebs", "state": "running", "state_code": 16, "virtualization_type": "paravirtual"}}
msg: Address '54.76.224.0' not found.
```

Thanks for your help!

**Comment by mabushey** [comment]
This no longer works.

```
  - name: aws | allocate EIP and associate it with the instance
    ec2_eip:
      region: "{{ region }}"
      device_id: "{{ item.id }}"
    with_items: "{{ blog_ec2.tagged_instances }}"
    register: blog_eip
```
```
  - name: aws | debug output of eip
    debug: var=blog_eip.results
...
            "public_ip": "52.37.135.17"
```
```
  - name: output the IPs
    debug: msg="Allocated IP inside the VPC is {{ item.public_ip }}"
    with_items: blog_eip.results

TASK [output the IPs] ********************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'public_ip'\n\nThe error appears to have been in '/home/michael/gumgum/ansible/playbook/tasks/aws_provision_blog-01.yml': line 121, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: output the IPs\n    ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'public_ip'"} 
```
This is works with Ansible 2.4:
```
  - name: aws | debug output of eip
    debug: var=item
    with_items: "{{ blog_eip.results|map(attribute='public_ip')|list }}"

TASK [aws | debug output of eip -2] ***************************************
ok: [localhost] => (item=52.37.135.17) => {
    "changed": false, 
    "item": "52.37.135.17"
}
```
