### ISSUE TITLE
host_vars not merged between multiple host files

### ISSUE THREAD

**Issue by gregorg** [ansible/ansible#13397]
##### Issue Type:

Bug Report
##### Ansible Version:

Introduced in v2.0.0-0.3.beta1, bug not present in v2.0.0-0.2.alpha2.
##### Ansible Configuration:

in ansible.cfg, use a directory as inventory

```
inventory = hosts/
```

Debian Jessie.
##### Summary:

I've configured 2 host files in hosts/ directory: hosts/a and hosts/b. Both contains groups, and one host is configured into 2 groups in 2 host files, with one host var for each.

hosts/a : 

```
[groupA]
test datacenter=PA3
```

hosts/b : 

```
[groupB]
test bay=202
```

playbook test.yml: 

```
- name: TEST
  hosts: test
  gather_facts: yes

  tasks:
  - name: debug
    debug: var=hostvars[inventory_hostname].datacenter
    ignore_errors: True

  - name: debug
    debug: var=hostvars[inventory_hostname].bay
    ignore_errors: True
```

With Ansible v1.9 or previous to v2.0.0-0.3.beta1, both host vars are accessible, but since this version only one random host vars (datacenter or bay) is accessible.

Tried with both hash_behaviour merge and replace.
##### Expected Results:

```
PLAY [TEST] ********************************************************************

TASK [setup] *******************************************************************
ok: [test]

TASK [debug] *******************************************************************
ok: [test] => {
    "changed": false, 
    "hostvars[inventory_hostname].datacenter": "PA3"
}

TASK [debug] *******************************************************************
ok: [test] => {
    "changed": false, 
    "hostvars[inventory_hostname].bay": "202"
}

PLAY RECAP *********************************************************************
test               : ok=3    changed=0    unreachable=0    failed=0   

```
##### Actual Results:

```
PLAY [TEST] ********************************************************************

TASK [setup] *******************************************************************
ok: [test]

TASK [debug] *******************************************************************
ok: [test] => {
    "changed": false, 
    "hostvars[inventory_hostname].datacenter": "PA3"
}

TASK [debug] *******************************************************************
fatal: [test]: FAILED! => {"failed": true, "msg": "ERROR! 'dict object' has no attribute 'bay'"}
...ignoring

PLAY RECAP *********************************************************************
test               : ok=3    changed=0    unreachable=0    failed=0   

```

**Comment by jimi-c** [comment]
Bisected to here:

<pre>
a2bc6b4b265f13ab099c50c2ccf768c64ec7eacf is the first bad commit
commit a2bc6b4b265f13ab099c50c2ccf768c64ec7eacf
Author: Marius Gedminas <marius@gedmin.as>
Date:   Thu Sep 24 12:43:33 2015 +0300
    Bugfix: if you define __eq__, you should define __ne__ too
:040000 040000 972800abe433c516308dfae89b918bce5c16016d 9d9d27d211febd0111f25653d4ab06c8e98a988c M  lib
:040000 040000 d28712031e6c5c170b55ea76319ac0ee988a5293 75818f43d034a8b91d87c1a3a22035a81a253d0b M  test
</pre>

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by gregorg** [comment]
Hi,

I'm sorry but this bug is not fully fixed. Even with hash_behaviour=merge, both variables aren't accessible. If groupA and groupB are both renamed to for example groupC, both vars are accessible.

**Comment by jimi-c** [comment]
Well that's odd, I know I tested this yesterday and it worked, but now I'm seeing your example fail again.

**Comment by jimi-c** [comment]
Adding some debug prints, the host are being properly merged in the dir.py code:

<pre>
merged host:
^ groups are: [groupA, groupB]
^ vars are: {u'datacenter': u'PA3', u'bay': 202}
</pre>

Yet it's failing to find datacenter in the first debug for me:

<pre>
TASK [debug] *******************************************************************
fatal: [test]: FAILED! => {"failed": true, "msg": "ERROR! 'dict object' has no attribute 'datacenter'"}
...ignoring
</pre>

**Comment by itldo** [comment]
Is hash_behavior intended to apply to hosts mentioned among different inventories?

BTW I've updated my host variable integration tests at
 https://github.com/itldo/ansible_test_var/blob/master/example_results
which still show problems between static and dynamic inventories.

Other example tests are failing but nobody has described what the intended behavior for some of these should be.

**Comment by jimi-c** [comment]
Hash behavior will only impact this if the vars contain sub-dictionaries. Beyond that the expected behavior is that duplicate hosts found in a dir inventory are merged. This appears to be a bug in the way we've been determining host equality, for which I'm about to push a fix.

For the record, here's your example running with this patch:

<pre>
PLAY [TEST] ********************************************************************
TASK [debug] *******************************************************************
task path: /root/testing/13397/test.yml:7
ok: [test] => {
    "changed": false, 
    "hostvars[inventory_hostname].datacenter": "PA3", 
    "invocation": {
        "module_args": {
            "var": "hostvars[inventory_hostname].datacenter"
        }, 
        "module_name": "debug"
    }
}
TASK [debug] *******************************************************************
task path: /root/testing/13397/test.yml:11
ok: [test] => {
    "changed": false, 
    "hostvars[inventory_hostname].bay": "202", 
    "invocation": {
        "module_args": {
            "var": "hostvars[inventory_hostname].bay"
        }, 
        "module_name": "debug"
    }
}
PLAY RECAP *********************************************************************
test                       : ok=2    changed=0    unreachable=0    failed=0   
</pre>

**Comment by jimi-c** [comment]
@gregorg / @itldo Let us know if you see any further problems. Thanks!

**Comment by itldo** [comment]
@jimi-c Cool, my tests are passing now (except for one that checks for what happens when the same variable is set in different inventories).
I'm able to include dynamic hosts in static groups without clobbering their host variables.
Thanks very much.

**Comment by gregorg** [comment]
It passed for me too, with 2 files and 1 dynamic inventory, gj guys ! :+1: and thank you!

**Comment by jimi-c** [comment]
Great, thanks for the follow-up!
