### ISSUE TITLE
"AttributeError: 'unicode' object has no attribute 'name'"

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#28906]
##### ISSUE TYPE

 - Bug Report
 
##### COMPONENT NAME

win_template

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.0 (devel 79dcb3a3fa) last updated 2017/08/31 19:20:44 (GMT -500)
  config file = None
  configured module search path = [u'/Users/tanner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tanner/projects/ansible.git/ansible/lib/ansible
  executable location = /Users/tanner/projects/ansible.git/ansible/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### OS / ENVIRONMENT
Management host macOS 10.12.6
Managed host Windows7

##### SUMMARY

win_template errors with "AttributeError: 'unicode' object has no attribute 'name'"

##### STEPS TO REPRODUCE

```yaml
- name: dump all variables
  win_template: 
    src: dump_variables.j2
    dest: C:\temp\ansible_variables.txt
```
The template file
```yaml
Module Variables ("vars"):
--------------------------------
{{ vars | to_nice_json }} 

Environment Variables ("environment"):
--------------------------------
{{ environment | to_nice_json }} 

GROUP NAMES Variables ("group_names"):
--------------------------------
{{ group_names | to_nice_json }}

GROUPS Variables ("groups"):
--------------------------------
{{ groups | to_nice_json }}

HOST Variables ("hostvars"):
--------------------------------
{{ hostvars | to_nice_json }} 
```

##### EXPECTED RESULTS

Ansible variables would get dumped.

##### ACTUAL RESULTS

```
TASK [win_gsis-workstation : dump all variables] *******************************
task path: /Users/tanner/projects/ansible.git/playbooks.git/roles/win_workstation/tasks/main.yml:26
fatal: [S1557]: FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "AttributeError: 'unicode' object has no attribute 'name'"
}
fatal: [S1616C]: FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "AttributeError: 'unicode' object has no attribute 'name'"
}
```

**Comment by basictheprogram** [comment]
git bisect says this is the commit that caused the problem:
```
1e785d4117bc5961c2dd85c74dec5179d54cb676 is the first bad commit
commit 1e785d4117bc5961c2dd85c74dec5179d54cb676
Author: Felipe Garcia Bulsoni <fgbulsoni@gmail.com>
Date:   Wed Aug 30 11:51:28 2017 -0300

    FcoeNetworkFactsModule for HPE OneView (#28728)

    * Add FcoeNetworkFactsModule for retrieving HPE OneView FCoE Networks

    - Allow querying for FCoE Network resources in HPE OneView
    - Adds unit tests to new module

    * Fix "required: no"

:040000 040000 674732496af0537c53ad39b0e2facd4f8b17e3f2 d405c62ff890b816578f26fc37d9f9cfb977ac84 M	lib
:040000 040000 65afe98916fa87a9b0b9b401d41938ede41279bf 3ef017cb7fcfd6524ba56d1fc5613d702580a895 M	test
```

**Comment by ansibot** [comment]
cc @jhawkesworth
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jborean93** [comment]
I can confirm this is an issue under the core engine and not just windows and can replicate by just running

`ansible localhost -m debug -a var=hostvars`

or

`ansible localhost -m debug -a var=vars`

It produces the output

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'unicode' object has no attribute 'name'
localhost | FAILED! => {
    "failed": true, 
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
```

Looks like the commit https://github.com/ansible/ansible/commit/0571014f2fe016f0055a61e56b1c56b129939420 "may" have broken this as when i revert the behaviour works as expected. Looking into it further the host list from `_inventory.hosts` is no longer a dict but just a string so there is no attribute `name` to get the details for.

I have applied the following diff locally and it works fine after that but want to get further clarification from someone more experienced before I raise a PR

```
index f174b2969..27d086a95 100644
--- a/lib/ansible/vars/hostvars.py
+++ b/lib/ansible/vars/hostvars.py
@@ -106,7 +106,7 @@ class HostVars(collections.Mapping):
 
     def __iter__(self):
         for host in self._inventory.hosts:
-            yield host.name
+            yield host
 
     def __len__(self):
         return len(self._inventory.hosts)
@@ -114,6 +114,5 @@ class HostVars(collections.Mapping):
     def __repr__(self):
         out = {}
         for host in self._inventory.hosts:
-            name = host.name
-            out[name] = self.get(name)
+            out[host] = self.get(host)
         return repr(out)
```

@bcoca

**Comment by bcoca** [comment]
closed via #28987
