### PR TITLE
Fix #17920

### LINKED ISSUE #17920: vv() got an unexpected keyword argument 'color'
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

ansible-playbook using statically included files
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Running ansible from the stable-2.1 branch fails after commit 6db31bb4c6f8b6338a38ae602d3b4f5ca8cbce5b was merged
##### STEPS TO REPRODUCE

1. Create playbook that uses include
2. clone ansible and use current stable-2.1 branch (currently at commit `6db31bb4c6f8b6338a38ae602d3b4f5ca8cbce5b`)
3. run playbook

##### EXPECTED RESULTS

Playbook runs
##### ACTUAL RESULTS

Ansible exits at start of playbook with

```
ERROR! Unexpected Exception: vv() got an unexpected keyword argument 'color'
```

### PR DESCRIPTION
**Pull request by cinerama70**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

ansible core
##### ANSIBLE VERSION

```
ansible 2.1.2.0 (bug-17920 402935caab) last updated 2016/10/06 16:11:41 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 4602021670) last updated 2016/10/06 16:12:28 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD d312f34d9b) last updated 2016/10/06 16:12:35 (GMT +000)
  config file = /home/stephane/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

6db31bb4c6f8b6338a38ae602d3b4f5ca8cbce5b broke the stable-2.1
branch because an incorrect version of
https://github.com/ansible/ansible/pull/17918 got applied. Fixes #17920 

```
```

### CODE REVIEW

**Comment by cinerama70** [comment]
This got fixed here:

https://github.com/ansible/ansible/commit/972379c9072e1debeefce7a7bf99ffbe1e9217c4
