### ISSUE TITLE
conditional check failure: 'bool' object has no attribute 'strip'

### ISSUE THREAD

**Issue by phemmer** [ansible/ansible#76490]
### Summary

When using `jinja2_native=true`, `failed_when` statements generate the error `'bool' object has no attribute 'strip'`

### Issue Type

Bug Report

### Component Name

conditional

### Ansible Version

```console
$ ansible --version
ansible 2.10.16
  config file = /tmp/ansibletest/ansible.cfg
  configured module search path = ['/home/phemmer/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/phemmer/.local/lib/python3.10/site-packages/ansible
  executable location = /home/phemmer/.local/bin/ansible
  python version = 3.10.0 (default, Oct  4 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_JINJA2_NATIVE(/tmp/ansibletest/ansible.cfg) = True
```

### OS / Environment

Fedora 35

### Steps to Reproduce

```yaml (paste below)
cat > ansible.cfg <<'EOF'
[defaults]
jinja2_native=true
EOF

cat > test.yml <<'EOF'
- hosts: localhost
  tasks:
    - debug:
        msg: hello world
      failed_when: 0 == 1
EOF

ansbile-playbook test.yml
```

### Expected Results

No error

### Actual Results

```console
PLAY [localhost] *************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************
ok: [localhost]

TASK [debug] *****************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check '0 == 1' failed. The error was: 'bool' object has no attribute 'strip'"}

PLAY RECAP *******************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by phemmer** [comment]
This looks to be caused by https://github.com/ansible/ansible/pull/76261

**Comment by mkrizek** [comment]
This should be fixed in Ansible `2.11` and `2.12`.

**Comment by phemmer** [comment]
Yeah, I closed the issue because I noticed I was running the wrong ansible version. sorry about the noise.
