### ISSUE TITLE
stdout can not be retried for ansible v2.0

### ISSUE THREAD

**Issue by huikang** [ansible/ansible#13591]
I have the following code working for ansible 1.9.4. 

```
register: haproxy_user
  changed_when: "{{ results.stdout.find('localhost | SUCCESS => ') != -1 and (results.stdout.split('localhost | S\
UCCESS => ')[1]|from_json).changed }}"
  until: "{{ results.stdout.split()[2] == 'SUCCESS' }} "
  retries: 10
  delay: 5
```

However, after I upgrading to v2.0. It returns the error as

```
TASK [mariadb : Creating  mysql user] ***********************************
fatal: [10.0.0.1]: FAILED! => {"failed": true, "msg": "ERROR! 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'stdout'"}
```

Can anyone help? Thanks.

My system is 
 ansible 2.0.0
 ubuntu 15.04

**Comment by abadger** [comment]
where is your playbook getting result from?

**Comment by huikang** [comment]
From ansible's mysql_user module. It creates a new user in the database. Thanks. -Hui

**Comment by abadger** [comment]
Could you give us more of your playbook?  In what you pasted initially, I only see you registering haproxy_user, not results.

**Comment by huikang** [comment]
@abadger Sorry about the confusion. The code is

```
- name: Creating haproxy mysql user
  mysql_user:
      login_host: '10.0.0.1'
      login_port: '3066'
      login_user: 'root'
      login_password: 'passwor9'
      name: 'haproxy'
  register: haproxy_user
  changed_when: "{{ haproxy_user.stdout.find('localhost | SUCCESS => ') != -1 and (haproxy_user.stdout.split('localhost | SUCCESS => ')[1]|from_json).changed }}"
  until: haproxy_user.stdout.split()[2] == 'SUCCESS'
  retries: 10
  delay: 5
```

The failure is caused by the above until statement.

The code runs without any problem for ansible 1.9.4. But it fails using ansible 2.0.
- Hui

**Comment by huikang** [comment]
@abadger just to check if you have found out anything. Thanks.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
