### PR TITLE
VMware: fix inventory plugin

### LINKED ISSUE #56413: vmware_vm_inventory plugin: 'InventoryModule' object has no attribute 'content'
##### SUMMARY
Trying to use vmware inventiry plugin.... throws  'InventoryModule' object has no attribute 'content'

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_vm_inventory

##### ANSIBLE VERSION
```
ansible 2.9.0.dev0
  config file = /root/.ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /ansible/lib/ansible
  executable location = /ansible/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(env: ANSIBLE_INVENTORY) = [u'/root/ansible_hosts']
DEPRECATION_WARNINGS(/root/.ansible.cfg) = False
HOST_KEY_CHECKING(/root/.ansible.cfg) = False
INVENTORY_ENABLED(/root/.ansible.cfg) = [u'vmware_vm_inventory', u'aws_ec2', u'script', u'ini']
```

##### OS / ENVIRONMENT
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

Linux 8f1aeaad8c36 4.19.34-coreos #1 SMP Mon Apr 22 20:32:34 -00 2019 x86_64 x86_64 x86_64 GNU/Linux
##### STEPS TO REPRODUCE

```
Setup ixca-cm-esxi17.vmware.yml...
---
plugin: vmware_vm_inventory
strict: False
hostname: ixca-cm-esxi17.lbj.is.keysight.com
username: zabbix
password: XXXXXX
validate_certs: False
with_tags: False
...

Run... 
ansible-inventory -vvv -i ./ixca-cm-esxi17.vmware.yml --list

```

##### EXPECTED RESULTS
List of VMs from ESXi server

##### ACTUAL RESULTS

```
[root@8f1aeaad8c36 ansible]# ansible-inventory -vvvv -i ./ixca-cm-esxi17.vmware.yml --list
ansible-inventory 2.9.0.dev0
  config file = /root/.ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /ansible/lib/ansible
  executable location = /ansible/bin/ansible-inventory
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /root/.ansible.cfg as config file
setting up inventory plugins
aws_ec2 declined parsing /ansible/ixca-cm-esxi17.vmware.yml as it did not pass it's verify_file() method
script declined parsing /ansible/ixca-cm-esxi17.vmware.yml as it did not pass it's verify_file() method
 [WARNING]:  * Failed to parse /ansible/ixca-cm-esxi17.vmware.yml with vmware_vm_inventory plugin: 'InventoryModule' object has no attribute 'content'

  File "/ansible/lib/ansible/inventory/manager.py", line 268, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/ansible/lib/ansible/plugins/inventory/vmware_vm_inventory.py", line 334, in parse
    cacheable_results = self._populate_from_source(source_data, using_current_cache)
  File "/ansible/lib/ansible/plugins/inventory/vmware_vm_inventory.py", line 398, in _populate_from_source
    self._populate_host_properties(vm_obj, current_host)
  File "/ansible/lib/ansible/plugins/inventory/vmware_vm_inventory.py", line 451, in _populate_host_properties
    if self.content.customFieldsManager:

 [WARNING]:  * Failed to parse /ansible/ixca-cm-esxi17.vmware.yml with ini plugin: Invalid host pattern '---' supplied, '---' is normally a sign this is a YAML file.

  File "/ansible/lib/ansible/inventory/manager.py", line 268, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/ansible/lib/ansible/plugins/inventory/ini.py", line 138, in parse
    raise AnsibleParserError(e)

 [WARNING]: Unable to parse /ansible/ixca-cm-esxi17.vmware.yml as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

{
    "_meta": {
        "hostvars": {}
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    }
}

```

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY
* Fixed regression introduced in #56071
* Added test to check if hostvars are populated
* Fix toml installation logic

Fixes: #56413

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/plugins/inventory/vmware_vm_inventory.py
test/integration/targets/inventory_vmware_vm_inventory/runme.sh
test/integration/targets/inventory_vmware_vm_inventory/test_vmware_vm_inventory.yml

### CODE REVIEW

File: test/integration/targets/inventory_vmware_vm_inventory/runme.sh [hunk 1]
```diff
@@ -38,33 +40,42 @@ trap cleanup INT TERM EXIT
...
+fi
+echo "Cache is working"
+
 # Get inventory using YAML
 ansible-inventory -i ${VMWARE_CONFIG} --list --yaml
 
 # Install TOML for --toml
-${PYTHON} -m pip install toml
+${PYTHON} -m pip freeze | grep toml > /dev/null 2>&1
+if [ $? -ne 0 ]; then
```
Comment (goneri) [inline test/integration/targets/inventory_vmware_vm_inventory/runme.sh:66]: I would prefer this do be done before, could we move this requirements in ./test/runner/requirements/integration.cloud.vcenter.txt ?

**Review by goneri — APPROVED** [review]
