### ISSUE TITLE
sefcontext module : AttributeError: fcontextRecords instance has no attribute 'set_reload'

### ISSUE THREAD

**Issue by frenchy59** [ansible/ansible#23841]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

sefcontext
##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  6 2017, 23:53:20) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### OS / ENVIRONMENT

Ansible running on MacOS Sierra (also got the issue when running on centOS7)
RHEL6.5 on the managed host
##### SUMMARY

trying to add a basic sefcontext - SElinux file context definition, exactly as described in example in : https://docs.ansible.com/ansible/sefcontext_module.html
```yaml
    - sefcontext:
        target: '/srv/git_repos(/.*)?'
        setype: httpd_git_rw_content_t
        state: present
```
and get following error when executing the playbook :
```
fatal: [192.168.33.15]: FAILED! => {"changed": false, "failed": true, "msg": "AttributeError: fcontextRecords instance has no attribute 'set_reload'\n"}
```
These required packages are already installed on the RHEL6.5 managed host :
libselinux-python-2.0.94-5.3.el6_4.1.x86_64
policycoreutils-python-2.0.83-19.39.el6.x86_64

and /srv/git_repos directory has been created.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: 192.168.33.15
  remote_user: root
  tasks:
    - sefcontext:
        target: '/srv/git_repos(/.*)?'
        setype: httpd_git_rw_content_t
        state: present
```

##### EXPECTED RESULTS

I expect the below command to be run
semanage fcontext -a -t httpd_git_rw_content_t '/srv/git_repos(/.*)?'

##### ACTUAL RESULTS

```
fatal: [192.168.33.15]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "ftype": "a", 
            "reload": true, 
            "selevel": null, 
            "setype": "httpd_git_rw_content_t", 
            "seuser": null, 
            "state": "present", 
            "target": "/srv/git_repos(/.*)?"
        }
    }, 
    "msg": "AttributeError: fcontextRecords instance has no attribute 'set_reload'\n"
}
```

```
TASK [sefcontext] ************************************************************************************************************************************
task path: /Users/Desktop/test2.yml:5
Using module file /Library/Python/2.7/site-packages/ansible/modules/system/sefcontext.py
<192.168.33.15> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.33.15> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/.ansible/cp/593f27bb91 192.168.33.15 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<192.168.33.15> (0, '/root\n', 'OpenSSH_7.4p1, LibreSSL 2.5.0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 3433\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<192.168.33.15> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.33.15> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/.ansible/cp/593f27bb91 192.168.33.15 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1492736575.85-122247316048000 `" && echo ansible-tmp-1492736575.85-122247316048000="` echo /root/.ansible/tmp/ansible-tmp-1492736575.85-122247316048000 `" ) && sleep 0'"'"''
<192.168.33.15> (0, 'ansible-tmp-1492736575.85-122247316048000=/root/.ansible/tmp/ansible-tmp-1492736575.85-122247316048000\n', 'OpenSSH_7.4p1, LibreSSL 2.5.0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 3433\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<192.168.33.15> PUT /var/folders/bd/4k4wj0sd23j9z1l0f9n0jfxr0000gn/T/tmpVUOvrm TO /root/.ansible/tmp/ansible-tmp-1492736575.85-122247316048000/sefcontext.py
<192.168.33.15> SSH: EXEC sftp -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/.ansible/cp/593f27bb91 '[192.168.33.15]'
<192.168.33.15> (0, 'sftp> put /var/folders/bd/4k4wj0sd23j9z1l0f9n0jfxr0000gn/T/tmpVUOvrm /root/.ansible/tmp/ansible-tmp-1492736575.85-122247316048000/sefcontext.py\n', 'OpenSSH_7.4p1, LibreSSL 2.5.0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 3433\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug2: Remote version: 3\r\ndebug2: Server supports extension "posix-rename@openssh.com" revision 1\r\ndebug2: Server supports extension "statvfs@openssh.com" revision 2\r\ndebug2: Server supports extension "fstatvfs@openssh.com" revision 2\r\ndebug3: Sent message fd 8 T:16 I:1\r\ndebug3: SSH_FXP_REALPATH . -> /root size 0\r\ndebug3: Looking up /var/folders/bd/4k4wj0sd23j9z1l0f9n0jfxr0000gn/T/tmpVUOvrm\r\ndebug3: Sent message fd 8 T:17 I:2\r\ndebug3: Received stat reply T:101 I:2\r\ndebug1: Couldn\'t stat remote file: No such file or directory\r\ndebug3: Sent message SSH2_FXP_OPEN I:3 P:/root/.ansible/tmp/ansible-tmp-1492736575.85-122247316048000/sefcontext.py\r\ndebug3: Sent message SSH2_FXP_WRITE I:4 O:0 S:32768\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 4 32768 bytes at 0\r\ndebug3: Sent message SSH2_FXP_WRITE I:5 O:32768 S:25184\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 5 25184 bytes at 32768\r\ndebug3: Sent message SSH2_FXP_CLOSE I:4\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<192.168.33.15> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.33.15> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/.ansible/cp/593f27bb91 192.168.33.15 '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1492736575.85-122247316048000/ /root/.ansible/tmp/ansible-tmp-1492736575.85-122247316048000/sefcontext.py && sleep 0'"'"''
<192.168.33.15> (0, '', 'OpenSSH_7.4p1, LibreSSL 2.5.0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 3433\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<192.168.33.15> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.33.15> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/.ansible/cp/593f27bb91 -tt 192.168.33.15 '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1492736575.85-122247316048000/sefcontext.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1492736575.85-122247316048000/" > /dev/null 2>&1 && sleep 0'"'"''
<192.168.33.15> (0, '\r\n{"msg": "AttributeError: fcontextRecords instance has no attribute \'set_reload\'\\n", "failed": true, "invocation": {"module_args": {"target": "/srv/git_repos(/.*)?", "selevel": null, "seuser": null, "setype": "httpd_git_rw_content_t", "reload": true, "state": "present", "ftype": "a"}}}\r\n', 'OpenSSH_7.4p1, LibreSSL 2.5.0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 3433\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to 192.168.33.15 closed.\r\n')
fatal: [192.168.33.15]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "ftype": "a", 
            "reload": true, 
            "selevel": null, 
            "setype": "httpd_git_rw_content_t", 
            "seuser": null, 
            "state": "present", 
            "target": "/srv/git_repos(/.*)?"
        }
    }, 
    "msg": "AttributeError: fcontextRecords instance has no attribute 'set_reload'\n"
}
	to retry, use: --limit @/XX/XX/test2.retry
```

**Comment by ansibot** [comment]
cc @dagwieers
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
Could you first upgrade your RHEL6 to a newer release ?
It may be related to a specific version of those packages as it was tested on RHEL6 and RHEL7 specifically.

**Comment by frenchy59** [comment]
I have installed a fresh RHEL 6.8 (on managed host) and that works now.
libselinux-python-2.0.94-7.el6.x86_64
policycoreutils-python-2.0.83-29.el6.x86_64

Are you planning to make it work with RHEL 6.5 ?

**Comment by dagwieers** [comment]
I have no plans. But I do accept patches adding backward compatibility with older libs.

**Comment by jasontibbitts** [comment]
I know this is an old ticket, but I just found that updating the policycoreutils (and related python module) package in Fedora 27 from policycoreutils-2.7-1.fc27.x86_64 to policycoreutils-2.7-3.fc27.x86_64 causes the sefcontext module to fail with exactly the same error.

I am running ansible 2.4.2.0 (via Fedora's ansible-2.4.2.0-1.fc27.noarch package, which isn't patched in any relevant way).

I've filed https://bugzilla.redhat.com/show_bug.cgi?id=1527745 on the Fedora side; certainly a minor package update shouldn't be breaking ansible.

**Comment by jasontibbitts** [comment]
The Fedora issue is fixed with policycoreutils-2.7-4.fc27.

**Comment by ansibot** [comment]
Thank you very much for your interest in Ansible. Ansible has migrated much of the content into separate repositories to allow for more rapid, independent development. We are closing this issue/PR because this content has been moved to one or more collection repositories.

* lib/ansible/modules/system/sefcontext.py -> https://galaxy.ansible.com/community/general

For further information, please see:
https://github.com/ansible/ansibullbot/blob/master/docs/collection_migration.md
