### ISSUE TITLE
Unit test fails if you don't have access to mount info

### ISSUE THREAD

**Issue by tima** [ansible/ansible#3613]
I monitor the state and stability of the devel HEAD using a Jenkins install here. It's been showing red for a month or more. The problem is that our "sudo" accounts cannot access mount info I'm guessing for some security reasons. Does anyone have a suggestion for ignoring that failing test so it's not perpetually marked broken?

Here is the error getting produced for the record:

Stacktrace

00:00:33.804 ======================================================================
00:00:33.805 FAIL: test_one (TestPlayBook.TestPlaybook)
00:00:33.805 ----------------------------------------------------------------------
00:00:33.805 Traceback (most recent call last):
00:00:33.805  File "/.statelite/tmpfs/data/VCS/est-ax010-d/logs01/jenkins/workspace/ansible-devel/test/TestPlayBook.py", line 165, in test_one
00:00:33.805    assert utils.jsonify(expected, format=True) == utils.jsonify(actual,format=True)
00:00:33.805 AssertionError:
00:00:33.805 -------------------- >> begin captured stdout << ---------------------
00:00:33.805 ['start', ['play start', ['all']], ['failed', ['localhost', {'msg': 'Traceback (most recent call last):\n  File "/home/tpettd/.ansible/tmp/ansible-1373490994.23-103315157514215/setup", line 3048, in <module>\n    main()\n  File "/home/tpettd/.ansible/tmp/ansible-1373490994.23-103315157514215/setup", line 2132, in main\n    data = run_setup(module)\n  File "/home/tpettd/.ansible/tmp/ansible-1373490994.23-103315157514215/setup", line 2070, in run_setup\n    facts = ansible_facts()\n  File "/home/tpettd/.ansible/tmp/ansible-1373490994.23-103315157514215/setup", line 2060, in ansible_facts\n    facts.update(Hardware().populate())\n  File "/home/tpettd/.ansible/tmp/ansible-1373490994.23-103315157514215/setup", line 505, in populate\n    self.get_mount_facts()\n  File "/home/tpettd/.ansible/tmp/ansible-1373490994.23-103315157514215/setup", line 629, in get_mount_facts\n    statvfs_result = os.statvfs(fields[1])\nOSError: [Errno 13] Permission denied: \'/root/.ssh\'\n', 'failed': True, 'parsed': False, 'invocation': {'module_name': 'setup', 'module_args': ''}}, False]], ['task start', ['test basic success command', False]]]
00:00:33.805 **ACTUAL**
00:00:33.805 {
00:00:33.805    "localhost": {
00:00:33.805        "changed": 0,
00:00:33.805        "failures": 1,
00:00:33.805        "ok": 0,
00:00:33.805        "skipped": 0,
00:00:33.805        "unreachable": 0
00:00:33.805    }
00:00:33.805 }
00:00:33.805 **EXPECTED**
00:00:33.805 {
00:00:33.805    "localhost": {
00:00:33.805        "changed": 9,
00:00:33.805        "failures": 0,
00:00:33.805        "ok": 11,
00:00:33.805        "skipped": 1,
00:00:33.805        "unreachable": 0
00:00:33.805    }
00:00:33.805 }
00:00:33.805
00:00:33.805 --------------------- >> end captured stdout << ----------------------

<tim/>

**Comment by bcoca** [comment]
which version? this should be patched in current devel.

On Sun, Jul 21, 2013 at 10:49 PM, Timothy Appnel
notifications@github.comwrote:

> g for some security reasons. Does anyone have a suggestion for ignoring
> that failing test so it's not perpetually marked broken?
> 
> Here is the error getting produced for the record:

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by tima** [comment]
I'll give it a try. I've been vacation and didn't get to file that ticket as Michael requested before I left. 

<tim/>

**Comment by mpdehaan** [comment]
Thanks!

**Comment by mpdehaan** [comment]
Yeah this is statvfs stuff, the fix was made in the setup module and should be fine on the development branch, let me know if not.

**Comment by tima** [comment]
Still dying. Different error though.

"AttributeError: 'LinuxHardware' object has no attribute 'fail_json'"

TestPlayBook.TestPlaybook.test_one (from nosetests)
Failing for the past 10 builds (Since #282 )
Took 0.37 sec.
Error Message

-------------------- >> begin captured stdout << ---------------------
['start', ['play start', ['all']], ['failed', ['localhost', {'msg': 'Traceback (most recent call last):\n  File "/home/tpettd/.ansible/tmp/ansible-1374498681.9-11108634040372/setup", line 3078, in <module>\n    main()\n  File "/home/tpettd/.ansible/tmp/ansible-1374498681.9-11108634040372/setup", line 2146, in main\n    data = run_setup(module)\n  File "/home/tpettd/.ansible/tmp/ansible-1374498681.9-11108634040372/setup", line 2084, in run_setup\n    facts = ansible_facts()\n  File "/home/tpettd/.ansible/tmp/ansible-1374498681.9-11108634040372/setup", line 2074, in ansible_facts\n    facts.update(Hardware().populate())\n  File "/home/tpettd/.ansible/tmp/ansible-1374498681.9-11108634040372/setup", line 505, in populate\n    self.get_mount_facts()\n  File "/home/tpettd/.ansible/tmp/ansible-1374498681.9-11108634040372/setup", line 639, in get_mount_facts\n    self.fail_json(msg=e.strerror)\nAttributeError: \'LinuxHardware\' object has no attribute \'fail_json\'\n', 'failed': True, 'parsed': False, 'invocation': {'module_name': 'setup', 'module_args': ''}}, False]], ['task start', ['test basic success command', False]]]
**ACTUAL**
{
    "localhost": {
        "changed": 0, 
        "failures": 1, 
        "ok": 0, 
        "skipped": 0, 
        "unreachable": 0
    }
}
**EXPECTED**
{
    "localhost": {
        "changed": 9, 
        "failures": 0, 
        "ok": 11, 
        "skipped": 1, 
        "unreachable": 0
    }
}

--------------------- >> end captured stdout << ----------------------

Stacktrace

  File "/efs/dist/python/core/2.6.5/exec/lib/python2.6/unittest.py", line 279, in run
    testMethod()
  File "/.statelite/tmpfs/data/VCS/est-ax010-d/logs01/jenkins/workspace/ansible-devel/test/TestPlayBook.py", line 167, in test_one
    assert utils.jsonify(expected, format=True) == utils.jsonify(actual,format=True)

-------------------- >> begin captured stdout << ---------------------
['start', ['play start', ['all']], ['failed', ['localhost', {'msg': 'Traceback (most recent call last):\n  File "/home/tpettd/.ansible/tmp/ansible-1374498681.9-11108634040372/setup", line 3078, in <module>\n    main()\n  File "/home/tpettd/.ansible/tmp/ansible-1374498681.9-11108634040372/setup", line 2146, in main\n    data = run_setup(module)\n  File "/home/tpettd/.ansible/tmp/ansible-1374498681.9-11108634040372/setup", line 2084, in run_setup\n    facts = ansible_facts()\n  File "/home/tpettd/.ansible/tmp/ansible-1374498681.9-11108634040372/setup", line 2074, in ansible_facts\n    facts.update(Hardware().populate())\n  File "/home/tpettd/.ansible/tmp/ansible-1374498681.9-11108634040372/setup", line 505, in populate\n    self.get_mount_facts()\n  File "/home/tpettd/.ansible/tmp/ansible-1374498681.9-11108634040372/setup", line 639, in get_mount_facts\n    self.fail_json(msg=e.strerror)\nAttributeError: \'LinuxHardware\' object has no attribute \'fail_json\'\n', 'failed': True, 'parsed': False, 'invocation': {'module_name': 'setup', 'module_args': ''}}, False]], ['task start', ['test basic success command', False]]]
**ACTUAL**
{
    "localhost": {
        "changed": 0, 
        "failures": 1, 
        "ok": 0, 
        "skipped": 0, 
        "unreachable": 0
    }
}
**EXPECTED**
{
    "localhost": {
        "changed": 9, 
        "failures": 0, 
        "ok": 11, 
        "skipped": 1, 
        "unreachable": 0
    }
}

--------------------- >> end captured stdout << ----------------------

Standard Output

['start', ['play start', ['all']], ['failed', ['localhost', {'msg': 'Traceback (most recent call last):\n  File "/home/tpettd/.ansible/tmp/ansible-1374498681.9-11108634040372/setup", line 3078, in <module>\n    main()\n  File "/home/tpettd/.ansible/tmp/ansible-1374498681.9-11108634040372/setup", line 2146, in main\n    data = run_setup(module)\n  File "/home/tpettd/.ansible/tmp/ansible-1374498681.9-11108634040372/setup", line 2084, in run_setup\n    facts = ansible_facts()\n  File "/home/tpettd/.ansible/tmp/ansible-1374498681.9-11108634040372/setup", line 2074, in ansible_facts\n    facts.update(Hardware().populate())\n  File "/home/tpettd/.ansible/tmp/ansible-1374498681.9-11108634040372/setup", line 505, in populate\n    self.get_mount_facts()\n  File "/home/tpettd/.ansible/tmp/ansible-1374498681.9-11108634040372/setup", line 639, in get_mount_facts\n    self.fail_json(msg=e.strerror)\nAttributeError: \'LinuxHardware\' object has no attribute \'fail_json\'\n', 'failed': True, 'parsed': False, 'invocation': {'module_name': 'setup', 'module_args': ''}}, False]], ['task start', ['test basic success command', False]]]
**ACTUAL**
{
    "localhost": {
        "changed": 0, 
        "failures": 1, 
        "ok": 0, 
        "skipped": 0, 
        "unreachable": 0
    }
}
**EXPECTED**
{
    "localhost": {
        "changed": 9, 
        "failures": 0, 
        "ok": 11, 
        "skipped": 1, 
        "unreachable": 0
    }
}

**Comment by bcoca** [comment]
my bad, since I could not reproduce error I only checked that the query
still worked.

sending pr now as this module uses 'global module' instead of passing
it/inheriting to self (which is what i used for error handling).

**Comment by mpdehaan** [comment]
Thanks @bcoca!

**Comment by tima** [comment]
Yes that fixed the unit test from dying badly. The test still fails for me because we are blocked from even reading mount info.

00:00:36.083 ======================================================================
00:00:36.083 FAIL: test_one (TestPlayBook.TestPlaybook)
00:00:36.083 ----------------------------------------------------------------------
00:00:36.083 Traceback (most recent call last):
00:00:36.083   File "/.statelite/tmpfs/data/VCS/est-ax010-d/logs01/jenkins/workspace/ansible-devel/test/TestPlayBook.py", line 167, in test_one
00:00:36.083     assert utils.jsonify(expected, format=True) == utils.jsonify(actual,format=True)
00:00:36.083 AssertionError: 
00:00:36.083 -------------------- >> begin captured stdout << ---------------------
00:00:36.083 ['start', ['play start', ['all']], ['failed', ['localhost', {u'msg': u'Permission denied', u'failed': True, 'invocation': {'module_name': 'setup', 'module_args': ''}}, False]], ['task start', ['test basic success command', False]]]
00:00:36.083 **ACTUAL**
00:00:36.083 {
00:00:36.083     "localhost": {
00:00:36.083         "changed": 0, 
00:00:36.083         "failures": 1, 
00:00:36.083         "ok": 0, 
00:00:36.083         "skipped": 0, 
00:00:36.083         "unreachable": 0
00:00:36.083     }
00:00:36.083 }
00:00:36.083 **EXPECTED**
00:00:36.083 {
00:00:36.083     "localhost": {
00:00:36.083         "changed": 9, 
00:00:36.083         "failures": 0, 
00:00:36.083         "ok": 11, 
00:00:36.083         "skipped": 1, 
00:00:36.083         "unreachable": 0
00:00:36.083     }
00:00:36.083 }
00:00:36.083 
00:00:36.083 --------------------- >> end captured stdout << ----------------------

So I'm back to my original question, is there a way to skip a unit test locally?

**Comment by mpdehaan** [comment]
There are some command line params about which tests to run but I'm not
sure there's an exclude.

The fact that you are still getting a permission denied error leaves me
inclined to say there is still something to fix here and we'll take care of
it.

That's the better option.  It should _not_ fail here, but simply not return
this info.

**Comment by mpdehaan** [comment]
Just pushed a fix to not raise an error, due to limited time it is _not_
well tested at this point.

Just replaced the error call with a continue.

**Comment by tima** [comment]
That did it. The last build Jenkins did went green. Thanks.

**Comment by mpdehaan** [comment]
Excellent!
