### ISSUE TITLE
All async tasks now fail with TypeError in latest devel version

### ISSUE THREAD

**Issue by tepwil** [ansible/ansible#11240]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 2.0.0 (devel aed429554d) last updated 2015/06/11 15:40:21 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 9acc7c402f) last updated 2015/06/11 15:40:23 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 2f967a949f) last updated 2015/06/11 15:40:24 (GMT +000)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/11 15:40:25 (GMT +000)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/11 15:40:27 (GMT +000)
  configured module search path = None
##### Ansible Configuration:

N/A
##### Environment:

Amazon Linux 3.14.42-31.38.amzn1.x86_64
##### Summary:

After upgrading to the latest devel version of Ansible, all of my async tasks now fail returning the following error:

```
TypeError: _low_level_execute_command() got an unexpected keyword argument 'task_vars'
```

Using _git bisect_ I was able to identify that this bug was introduced in the following commit ee5e166563ca01a556a921b177a632ea5c2f1a44
##### Steps To Reproduce:

I've created a simple playbook that consistently demonstrates the failure:

```
$ cat async-test.yml

---
- name: Asynchronous failure
  hosts: localhost
  tasks:
  - name: Fire and forget date command
    command: date
    async: 1
    poll: 0
    ignore_errors: yes
```
##### Expected Results:

I expect the playbook execution to pass:

```
$ ansible-playbook async-test.yml 

PLAY: Asynchronous Failure ******************************************************

TASK [Execute Date Command Asynchronously] **************************************
ok: [localhost]

PLAY RECAP **********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```
##### Actual Results:

```
$ ansible-playbook async-test.yml  -vvv

1 plays in async-test.yml

PLAY: Asynchronous Failure ******************************************************

TASK [Execute Date Command Asynchronously] **************************************
ESTABLISH LOCAL CONNECTION FOR USER: ec2-user
127.0.0.1 EXEC mkdir -p $HOME/.ansible/tmp/ansible-tmp-1434038295.97-184683661368150 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1434038295.97-184683661368150 && echo $HOME/.ansible/tmp/ansible-tmp-1434038295.97-184683661368150
127.0.0.1 PUT /tmp/tmpJDl0Cp TO /home/ec2-user/.ansible/tmp/ansible-tmp-1434038295.97-184683661368150/command
127.0.0.1 EXEC chmod a+rx /home/ec2-user/.ansible/tmp/ansible-tmp-1434038295.97-184683661368150/command
127.0.0.1 PUT /tmp/tmpIIT1ex TO /home/ec2-user/.ansible/tmp/ansible-tmp-1434038295.97-184683661368150/async_wrapper
127.0.0.1 EXEC chmod a+rx /home/ec2-user/.ansible/tmp/ansible-tmp-1434038295.97-184683661368150/async_wrapper
127.0.0.1 PUT /tmp/tmp0UWJN6 TO /home/ec2-user/.ansible/tmp/ansible-tmp-1434038295.97-184683661368150/arguments
fatal: [localhost]: FAILED! => {"failed": true, "exception": "Traceback (most recent call last):\n  File \"/home/ec2-user/ansible/lib/ansible/executor/process/worker.py\", line 118, in run\n    executor_result = TaskExecutor(host, task, job_vars, new_connection_info, self._new_stdin, self._loader, shared_loader_obj).run()\n  File \"/home/ec2-user/ansible/lib/ansible/executor/task_executor.py\", line 107, in run\n    res = self._execute()\n  File \"/home/ec2-user/ansible/lib/ansible/executor/task_executor.py\", line 262, in _execute\n    result = self._handler.run(task_vars=variables)\n  File \"/home/ec2-user/ansible/lib/ansible/plugins/action/async.py\", line 60, in run\n    result = self._low_level_execute_command(cmd=async_cmd, task_vars=task_vars, tmp=None)\nTypeError: _low_level_execute_command() got an unexpected keyword argument 'task_vars'\n", "stdout": ""}

PLAY RECAP **********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```

**Comment by lberruti** [comment]
Please close: commit 98fee17 fixed the issue.

I'm a bit depressed: my pull request fixed this P1 issue in the same identical way (2158661 vs 98fee17) 4 days ago.

@bcoca, @jimi-c: am I doing something wrong?

**Comment by jimi-c** [comment]
@lberruti sorry, didn't see your PR on this, I just noticed the error when looking into another async issue and fixed it at that time. I'm actually working through our backlog of issues from the oldest to find issues that have been fixed by v2.

@tepwil If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
