### ISSUE TITLE
document that os_network requires openstacksdk >= 0.29

### ISSUE THREAD

**Issue by dominikholler** [ansible/ansible#64841]
##### SUMMARY

os_network requires openstacksdk >= 0.29, while the documentation says openstacksdk >= 0.12.0 is required.
The required paraneter 'dns_domain' is added to openstacksdk in https://github.com/openstack/openstacksdk/commit/a3e846e2b9301f4ae725e97b21b4313bfcc81d10#diff-73529bc87d3ebb2e7a65ef0fe3028033

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

os_network

##### ANSIBLE VERSION

```paste below
ansible 2.9.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```
Create network on openstack with os_network.

##### EXPECTED RESULTS

Network is created.

##### ACTUAL RESULTS

Network is not created, if openstacksdk < 0.29 is insalled

```paste below
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: create_network() got an unexpected keyword argument 'dns_domain'
fatal: [localhost]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1573589970.12-1758058213670/AnsiballZ_os_network.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1573589970.12-1758058213670/AnsiballZ_os_network.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1573589970.12-1758058213670/AnsiballZ_os_network.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.cloud.openstack.os_network', init_globals=None, run_name='__main__', alter_sys=False)\n  File \"/usr/lib64/python2.7/runpy.py\", line 180, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_os_network_payload_zKuLeY/ansible_os_network_payload.zip/ansible/modules/cloud/openstack/os_network.py\", line 255, in <module>\n  File \"/tmp/ansible_os_network_payload_zKuLeY/ansible_os_network_payload.zip/ansible/modules/cloud/openstack/os_network.py\", line 237, in main\nTypeError: create_network() got an unexpected keyword argument 'dns_domain'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/openstack/os_network.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/openstack/os_network.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Shrews @cloudnull @dagnello @emonty @gtema @juliakreger @mnaser @odyssey4me @rcarrillocruz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by odyssey4me** [comment]
Actually, the issue is caused by https://github.com/ansible/ansible/commit/6c74e29618a6872bc0da66e4992cfcd9cebf6acc which did not include a bump of the minimum openstacksdk version to include support for the dns_domain parameter.

**Comment by odyssey4me** [comment]
bug_resolved
