### ISSUE TITLE
Ansible Windows incompatible with Python3

### ISSUE THREAD

**Issue by jfenwick** [ansible/ansible#23940]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible/lib/ansible/plugins/shell/powershell.py

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /home/vagrant/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

[defaults]
host_key_checking = False

##### OS / ENVIRONMENT

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

##### SUMMARY

Commands that use the powershell module cannot be run on python3.

##### STEPS TO REPRODUCE

Run any playbook on python3

```yaml
---
- name: Test
  vars:
    username: foo
  hosts: windows
  tasks:

    - name: Check if chocolatey is installed
      win_stat:
        path: "C:\\ProgramData\\chocolatey\\choco.exe"
      register: chocoInstall
```

##### EXPECTED RESULTS

For Ansible to be able to connect to a Windows computer.

##### ACTUAL RESULTS

vagrant@vagrant:~/ansible$ ansible-playbook -i inventories/development test.yaml -vvv
Using /home/vagrant/.ansible.cfg as config file

PLAYBOOK: test.yaml ************************************************************
1 plays in test.yaml

PLAY [Test] ********************************************************************

TASK [setup] *******************************************************************
Using module file /usr/local/lib/python3.5/dist-packages/ansible/modules/core/windows/setup.ps1
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ansible/executor/task_executor.py", line 126, in run
    res = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/ansible/executor/task_executor.py", line 502, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python3.5/dist-packages/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/usr/local/lib/python3.5/dist-packages/ansible/plugins/action/__init__.py", line 581, in _execute_module
    tmp = self._make_tmp_path(remote_user)
  File "/usr/local/lib/python3.5/dist-packages/ansible/plugins/action/__init__.py", line 221, in _make_tmp_path
    cmd = self._connection._shell.mkdtemp(basefile, use_system_tmp, tmp_mode)
  File "/usr/local/lib/python3.5/dist-packages/ansible/plugins/shell/powershell.py", line 114, in mkdtemp
    return self._encode_script('''(New-Item -Type Directory -Path $env:temp -Name "%s").FullName | Write-Host -Separator '';''' % basefile)
  File "/usr/local/lib/python3.5/dist-packages/ansible/plugins/shell/powershell.py", line 256, in _encode_script
    return ' '.join(cmd_parts)
TypeError: sequence item 6: expected str instance, bytes found

fatal: [foo.bar.com]: FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
	to retry, use: --limit @/home/vagrant/ansible/test.retry

PLAY RECAP *********************************************************************
foo.bar.com  : ok=0    changed=0    unreachable=0    failed=1   

```
ansible-playbook -i inventories/development test.yaml -vvv
```

**Comment by j1n6** [comment]
It would be nice to fix this. also affect Ansible 2.3.1

**Comment by jhawkesworth** [comment]
Please try using latest devel version of ansible and report back - I am fairly certain there has been some fixing done during 2.4 development.

needs_info

**Comment by j1n6** [comment]
Thanks for the quick reply. I will test and get back to you tomorrow. 

When will 2.4 be release?

**Comment by jhawkesworth** [comment]
@activars  According to the roadmap here: https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_4.rst the plan is for August/September 2017.

**Comment by akamac** [comment]
@activars @jhawkesworth Any way to work around the issue in 2.3.1 release? win_copy module fails for me with the same error.

**Comment by jhawkesworth** [comment]
@akamac - likely the simplest thing to do would be install a 2.7.x python and configure ansible to use that.  Either that or run from source, see below

**Comment by jhawkesworth** [comment]
It is fairly easy to have a 'from source' ansible version side-by-side with a released version.  The main thing to remember is you need to run
 `source hacking/env-setup` 

from the root of the source tree in order to use devel version of ansible.  

You can always check which version you are running by running `ansible --version`.  

As time passes you can keep up to date with the latest changes in devel by running

`git fetch origin; git rebase origin/devel`

in your ansible source code folder.

Some potentially useful links:
http://docs.ansible.com/ansible/latest/intro_installation.html#running-from-source

**Comment by akamac** [comment]
@jhawkesworth Thanks! Looks like dev version has the same issue. If I run ansible from 2.7 venv, I get: ` UNREACHABLE! => {"changed": false, "msg": "kerberos: 'module' object has no attribute 'util', plaintext: 'module' object has no attribute 'util'", "unreachable": true}`

**Comment by jhawkesworth** [comment]
@akamac I have no experience of running from a venv - is a side-by-side install of python27 with existing python3 a possibility for you, just to rule out potential for issues under a venv?

**Comment by j1n6** [comment]
2.3.1 isn't going to be compatible on windows, there are two issues I'm aware of:
 - python3 compatibility 
 - pycrypto is an old dependency that cannot be installed on windows

I'm not sure how many other issues could be discovered. 

You can also try develop branch, but that's too much hassle for a user with busy timetable :) 

I suggest ansible team should run some sort of matrix test to find out outstanding issues on different python version and OS.

**Comment by akamac** [comment]
I can confirm everything is working as of commit a7fd806fde22c14226ea1dba2158a5d53ec32d37

**Comment by jhawkesworth** [comment]
Since @akamac has confirmed this is working in 2.4 devel I'm going to close this one, as the fixes will be available in the next release of ansible.
If there are further specific issues, please create new a issue.
