### ISSUE TITLE
ansible 2.0.0.1 vars_prompt problem

### ISSUE THREAD

**Issue by usterk** [ansible/ansible#13914]
I'm running syntax check on playbook

```
- name: Test
  hosts: 127.0.0.1

  vars_prompt:
    - name: "answer"
      prompt: "Question?"
```

and I'm getting: 

```
# ansible-playbook --syntax-check --list-tasks -i inventory/localhost test.yml -vvvUsing /var/lib/jenkins/jobs/Ansible check syntax/workspace/ansible.cfg as config file
1 plays in test.yml
Unexpected Exception: 'NoneType' object has no attribute 'send_callback'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.0.0.1-py2.7.egg/EGG-INFO/scripts/ansible-playbook", line 85, in <module>
    sys.exit(cli.run())
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.0.0.1-py2.7.egg/ansible/cli/playbook.py", line 150, in run
    results = pbex.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.0.0.1-py2.7.egg/ansible/executor/playbook_executor.py", line 115, in run
    self._tqm.send_callback('v2_playbook_on_vars_prompt', vname, private, prompt, encrypt, confirm, salt_size, salt, default)
AttributeError: 'NoneType' object has no attribute 'send_callback'
```

I'm doing this on: Ubuntu 14.04.3 LTS

Syntax check on this file is working with ansible-2.0.0-0.7.rc2.
I'm swiching versions with: 
`make install`

**Comment by bcoca** [comment]
fixed in a196c7d737db14ba7dc238be901a5bf108e135c0
