### ISSUE TITLE
Error to manage RedHat 4 or 5.6

### ISSUE THREAD

**Issue by candymanz** [ansible/ansible#1529]
I Have install ansible in Debian and all is ok.
I can manage a Debian with no problem.

But when i want to manage RedHat Entreprise 5.6 and 4
I have this error : 

 ansible all -m ping

 FAILED >> {
 "failed": true,
    "msg": "Traceback (most recent call last):\r\n\n  File \"/home/adminn/.ansible/tmp/ansible-1352204366.62-260359853897483/ping\", line 63, in ?\r\n\n    import simplejson as json\r\n\nImportError: No module named simplejson\r\n",
    "parsed": false
}

Best regard.

**Comment by arrfab** [comment]
As stated on the http://ansible.cc/docs/gettingstarted.html page, you need python 2.6 on managed nodes _or_ at least the python-simplejson package for python 2.4 (yum install python-simplejson). That will work for RHEL/CentOS 5.x .
RHEL4.x/CentOS4.x are EOL and so not supported anymore and i'll doubt you'll find the minimum requirements already packaged sanely for those old machines ...

**Comment by candymanz** [comment]
Thank for you answer.
I have install in my REDHAt 5.6 the package  python-json  but :: 

FAILED => failed to parse: Traceback (most recent call last):

  File "/home/adminn/.ansible/tmp/ansible-1352205892.86-237481232547533/ping", line 347, in ?

```
main()
```

  File "/home/adminn/.ansible/tmp/ansible-1352205892.86-237481232547533/ping", line 40, in main

```
module.exit_json(ping='pong')
```

  File "/home/adminn/.ansible/tmp/ansible-1352205892.86-237481232547533/ping", line 299, in exit_json

```
print self.jsonify(kwargs)
```

  File "/home/adminn/.ansible/tmp/ansible-1352205892.86-237481232547533/ping", line 295, in jsonify

```
return json.dumps(data)
```

AttributeError: 'module' object has no attribute 'dumps'

Best regard.

**Comment by candymanz** [comment]
Sorry i have install not the good package now it work with  : python-simplejson-2.0.9-8.el5.x86_64.rpm

Thank you

**Comment by Marc-Morata-Fite** [comment]
You can run the following command to install it in your centos servers:

ansible  all  -i~/ansible/hosts -m raw -a "yum install -y python-simplejson"
