### ISSUE TITLE
netconf_rpc module does not work with nxos

### ISSUE THREAD

**Issue by mikewiebe** [ansible/ansible#63255]
##### SUMMARY
In latest `devel` and `ansible 2.9` release the `netconf_config` module generates an error indicating the connection was not properly established.

The module works in `ansible 2.8.5` and earlier.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
netconf_rpc

##### ANSIBLE VERSION
```paste below
ansible 2.10.0.dev0
  config file = /Users/mwiebe/Projects/nxos_ansible/fix_ansible/test/integration/ansible.cfg
  configured module search path = [u'/Users/mwiebe/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mwiebe/Projects/nxos_ansible/fix_ansible/lib/ansible
  executable location = /Users/mwiebe/Projects/nxos_ansible/fix_ansible/bin/ansible
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]

```

##### CONFIGURATION
```paste below
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = [u'/Users/mwiebe/Projects/nxos_ansible/fix_ansible/test/integration/targets']
PARAMIKO_HOST_KEY_AUTO_ADD(env: ANSIBLE_PARAMIKO_HOST_KEY_AUTO_ADD) = True
PERSISTENT_COMMAND_TIMEOUT(env: ANSIBLE_PERSISTENT_COMMAND_TIMEOUT) = 1000
PERSISTENT_CONNECT_TIMEOUT(env: ANSIBLE_PERSISTENT_CONNECT_TIMEOUT) = 1000

```

##### STEPS TO REPRODUCE
The following playbook can be used to recreate the issue
```yaml
---
- name: NETCONF NXOS 
  hosts: nxos_netconf
  gather_facts: no
 
  tasks:
    - name: Copy running config to startup config 
      netconf_rpc:
        rpc: copy_running_config_src 
        xmlns: "http://cisco.com/ns/yang/cisco-nx-os-device"
        content: |
          <startup-config/>
```

##### EXPECTED RESULTS
Don't crash

##### ACTUAL RESULTS
```paste below
The full traceback is:
Traceback (most recent call last):
  File "/Users/mwiebe/.ansible/tmp/ansible-local-16019zpWu6V/ansible-tmp-1570566293.76-151779983257535/AnsiballZ_netconf_rpc.py", line 102, in <module>
    _ansiballz_main()
  File "/Users/mwiebe/.ansible/tmp/ansible-local-16019zpWu6V/ansible-tmp-1570566293.76-151779983257535/AnsiballZ_netconf_rpc.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/mwiebe/.ansible/tmp/ansible-local-16019zpWu6V/ansible-tmp-1570566293.76-151779983257535/AnsiballZ_netconf_rpc.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.network.netconf.netconf_rpc', init_globals=None, run_name='__main__', alter_sys=False)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 192, in run_module
    fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_netconf_rpc_payload_lzplg3/ansible_netconf_rpc_payload.zip/ansible/modules/network/netconf/netconf_rpc.py", line 264, in <module>
  File "/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_netconf_rpc_payload_lzplg3/ansible_netconf_rpc_payload.zip/ansible/modules/network/netconf/netconf_rpc.py", line 240, in main
  File "/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_netconf_rpc_payload_lzplg3/ansible_netconf_rpc_payload.zip/ansible/module_utils/network/netconf/netconf.py", line 119, in dispatch
  File "/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_netconf_rpc_payload_lzplg3/ansible_netconf_rpc_payload.zip/ansible/module_utils/network/netconf/netconf.py", line 41, in get_connection
  File "/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_netconf_rpc_payload_lzplg3/ansible_netconf_rpc_payload.zip/ansible/module_utils/network/netconf/netconf.py", line 55, in get_capabilities
  File "/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_netconf_rpc_payload_lzplg3/ansible_netconf_rpc_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__
ansible.module_utils.connection.ConnectionError: 'NoneType' object has no attribute 'server_capabilities'
```

NOTE: This is caused by changes introduced in https://github.com/ansible/ansible/pull/59153.

If I add back this line (https://github.com/ansible/ansible/pull/59153/files#diff-56dab94b0b71fafc9c5ebcd9814136d5L104) it no longer crashes but this is not the right way to fix the problem.  I imagine this just needs to right logic to establish the connection when needed.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/network/netconf/netconf_rpc.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/netconf/netconf_rpc.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @NilashishC @Qalthos @danielmellado @ganeshrn @justjais @trishnaguha @wisotzky
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@mikewiebe, just so you are aware we have a dedicated Working Group for network.
You can find other people interested in this in `#ansible-network` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Qalthos** [comment]
Does #63463 do anything for this?

**Comment by mikewiebe** [comment]
@Qalthos This fix works in my testing.  Thanks!

**Comment by ganeshrn** [comment]
resolved_by_pr #63463
