### ISSUE TITLE
lvm module should have vg_options optional (edited title)

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#7266]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible-playbook 1.6 (devel 9da06274a8)
```

ansible-playbook 1.6 (devel 9da06274a8)
##### Environment:

Ansible: Ubuntu 10.04

Remote: Ubuntu 12.04
##### Summary:

vg_options should be optional, but it appears to be required due to bad params parsing.

Possibly introduced by https://github.com/ansible/ansible/commit/5776c95497b7a0795ca26fc19188a186a43b6a2d#diff-d97e54a5db788df1ed70a89a5b2267fa 

https://github.com/ansible/ansible/blame/devel/library/system/lvg#L119

Should this be protected in a 
    if self.module.params.get('vg_options', None):

```
TASK: [squid | /var/spool/squid3/ Partition] ********************************** 
fatal: [foo.example.com] => failed to parse: Traceback (most recent call last):
  File "/tmp/ansible/ansible-tmp-1399127419.16-36323948467636/lvg", line 1410, in <module>
    main()
  File "/tmp/ansible/ansible-tmp-1399127419.16-36323948467636/lvg", line 119, in main
    vgoptions = module.params.get('vg_options', '').split()
AttributeError: 'NoneType' object has no attribute 'split'


FATAL: all hosts have already failed -- aborting

```
##### Steps To Reproduce:

```
- name: "/var/spool/squid3/ Partition"
  lvg: vg=squid pvs=/dev/vdb
```
##### Expected Results:

No backtrce
##### Actual Results:

Backtrace as detailed above

**Comment by mpdehaan** [comment]
Not sure if that's a typo or what, but "bbb" is not a good name for the ticket title.

A better title would be "lvm module should have vg_options optional" so I'm going to update the description to match.

**Comment by gundalow** [comment]
Not sure what happened to the title, apologies. Thanks for correcting it.

**Comment by srgvg** [comment]
It's not mentioned why this was closed, either way it's a dupe of #6859.

**Comment by jimi-c** [comment]
@sergevanginderachter thanks, we'll keep this closed.
