### ISSUE TITLE
Relative paths don't work correctly when running multiple playbooks from one playbook

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#12524]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.0 (devel 41756be4d3) last updated 2015/09/25 10:05:38 (GMT -500)
##### Ansible Configuration:

No changes from defaults.
##### Environment:

Mac OS X 10.10.4
##### Summary:

I have a setup where I have one playbook that includes other playbooks.

If I run `ansible-playbook` with the parent playbook, which includes other playbooks, the relative pathing for tasks _inside_ the other playbooks seems to get stuck or messed up.

If I run `ansible-playbook` with the child playbooks directly (one-by-one), relative pathing works as expected.
##### Steps To Reproduce:

This can be reproduced using the example LAMP infrastructure example found here, in the Ansible for DevOps book repository: https://github.com/geerlingguy/ansible-for-devops/tree/master/lamp-infrastructure

I have a directory layout like this:

```
lamp-infrastructure/
  playbooks/
    memcached/
      main.yml
    varnish/
      templates/
        default.vcl.j2
      main.yml
  configure.yml
```

Inside `configure.yml` (a 'master' playbook which simply includes the two children playbooks):

``` yaml

---
- include: playbooks/varnish/main.yml
- include: playbooks/memcached/main.yml
```

If I run the varnish or memcached `main.yml` playbooks directly, everything works fine:

```
ansible-playbook -i inventories/vagrant/inventory playbooks/varnish/main.yml -u vagrant --ask-pass
...
TASK [Copy Varnish default.vcl.] ***********************************************
changed: [192.168.2.2]
...
PLAY RECAP *********************************************************************
192.168.2.2                : ok=18   changed=3    unreachable=0    failed=0 
```

However, if I run the `configure.yml` playbook that includes the two main.yml playbooks, it seems Ansible mixes up the paths for tasks like `copy`.

```
ansible-playbook -i inventories/vagrant/inventory configure.yml -u vagrant --ask-pass
...
TASK [Copy Varnish default.vcl.] ***********************************************
fatal: [192.168.2.2]: FAILED! => {"changed": false, "failed": true, "msg": "IOError: [Errno 2] No such file or directory: u'/Users/jgeerling/Dropbox/Development/GitHub/ansible-for-devops/lamp-infrastructure/playbooks/memcached/templates/default.vcl.j2'"}
Unexpected Exception: 'unicode' object has no attribute 'name'
```

Everything works fine in Ansible <= 1.9.3, but fails in Ansible 2.0.0.
##### Expected Results:

Playbook completes successfully whether run standalone or as part of the master `configure.yml` playbook.
##### Actual Results:

Playbook completes successfully when run standalone.

Playbook results in relative pathing error when run as part of the master `configure.yml` playbook:

```
TASK [Copy Varnish default.vcl.] ***********************************************
fatal: [192.168.2.2]: FAILED! => {"changed": false, "failed": true, "msg": "IOError: [Errno 2] No such file or directory: u'/Users/jgeerling/Dropbox/Development/GitHub/ansible-for-devops/lamp-infrastructure/playbooks/memcached/templates/default.vcl.j2'"}
Unexpected Exception: 'unicode' object has no attribute 'name'
```

**Comment by jimi-c** [comment]
Closing This Ticket
===================

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by geerlingguy** [comment]
This seems to have done the trick, thanks!

**Comment by goozbach** [comment]
I am also having the same issue still

https://github.com/goozbach-ansible/broken-paths for a test case.

running:

```
$ ansible --version
ansible 2.0.0 (devel 8c29910587) last updated 2015/10/14 13:03:17 (GMT -600)
  lib/ansible/modules/core: (detached HEAD 84b1a1a2b7) last updated 2015/10/14 13:03:21 (GMT-600)
  lib/ansible/modules/extras: (detached HEAD 8ce3104bc5) last updated 2015/10/14 13:03:21 (GMT-600)
  config file = /Users/derekcarter/.ansible.cfg
  configured module search path = None
```

Platform: OSX

Just did a `pull --rebase devel` today. So I'm running the latest devel

**Comment by jimi-c** [comment]
Reopening to investigate.

**Comment by jimi-c** [comment]
# Closing This Ticket (again)

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by goozbach** [comment]
Looks good! THANKS!

**Comment by ahill00** [comment]
Having this issue again.

```
$ ansible --version
ansible 2.0.0 (devel 59b67a2f68) last updated 2015/11/06 12:46:23 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 22c2789b72) last updated 2015/10/28 23:03:02 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD c685b3d387) last updated 2015/10/28 23:03:10 (GMT -400)
  config file =
  configured module search path = Default w/o overrides
```
