### ISSUE TITLE
Unexpected failure during copy module execution

### ISSUE THREAD

**Issue by rmfitzpatrick** [ansible/ansible#16497]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

`ansible 2.2.0 (devel 52d4079184) last updated 2016/06/29 10:22:47 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 2f0f04437b) last updated 2016/06/29 10:22:49 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD d25c487ac8) last updated 2016/06/29 10:22:50 (GMT -400)`
##### CONFIGURATION

no special settings
##### OS / ENVIRONMENT

rhel/centos/ubuntu/ol
##### SUMMARY

when using the copy module the following traceback occurs:

```
File "[...]/lib/ansible/plugins/action/__init__.py", line 842, in _find_needle
    task_dir = os.path.dirname(self._task.get_path())
  File "[...]/lib/ansible/playbook/task.py", line 103, in get_path
    return "%s:%s" % (self._ds._data_source, self._ds._line_number)
AttributeError: \'dict\' object has no attribute \'_data_source\'\n'
```
##### STEPS TO REPRODUCE

use the copy module from localhost to remotely managed machine with the ansible command (NOT ansible-playbook)
##### EXPECTED RESULTS

File would be copied from localhost to remote machine
##### ACTUAL RESULTS

Task failed with no file transmission.

**Comment by jctanner** [comment]
Confirmed via bisect and local revert that this was caused by 2bb7feec6d223cae5a3dc20900e4e87f0074735b

**Comment by jctanner** [comment]
A cleaner traceback ...

```
No config file found; using defaults
Loaded callback minimal of type stdout, v2.0
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/jtanner/workspace/issues/AP-copy_traceback/ansible/lib/ansible/executor/task_executor.py", line 124, in run
    res = self._execute()
  File "/home/jtanner/workspace/issues/AP-copy_traceback/ansible/lib/ansible/executor/task_executor.py", line 447, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/jtanner/workspace/issues/AP-copy_traceback/ansible/lib/ansible/plugins/action/copy.py", line 96, in run
    source = self._find_needle('files', source)
  File "/home/jtanner/workspace/issues/AP-copy_traceback/ansible/lib/ansible/plugins/action/__init__.py", line 842, in _find_needle
    task_dir = os.path.dirname(self._task.get_path())
  File "/home/jtanner/workspace/issues/AP-copy_traceback/ansible/lib/ansible/playbook/task.py", line 103, in get_path
    return "%s:%s" % (self._ds._data_source, self._ds._line_number)
AttributeError: 'dict' object has no attribute '_data_source'

el6host | FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

**Comment by jctanner** [comment]
Addressed by 7c690f04e25e5db28462391df64745ff642e654d

**Comment by rmfitzpatrick** [comment]
Verified.  Thanks!
