### ISSUE TITLE
setup fails on RHEL5 in devel - AttributeError: 'module' object has no attribute 'subversion'

### ISSUE THREAD

**Issue by stewartm** [ansible/ansible#14704]
##### Issue Type:

- Bug Report
##### Ansible Version:

```
[ansible@testbox ansible]$ ansible --version
ansible 2.1.0 (devel f99ed97c40) last updated 2016/02/29 13:48:41 (GMT +100)
  lib/ansible/modules/core: (detached HEAD 262e2a3302) last updated 2016/02/29 13:23:47 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD e0be11da08) last updated 2016/02/29 13:23:48 (GMT +100)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Environment:

RHEL 6.4 on Ansible server
RHEL 5.8 on Ansible managed host
##### Summary:

setup module fails to run on RHEL 5.8:

```
testnode | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1456756619.44-1762345300278/setup\", line 5324, in ?\r\n    main()\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1456756619.44-1762345300278/setup\", line 140, in main\r\n    data = run_setup(module)\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1456756619.44-1762345300278/setup\", line 84, in run_setup\r\n    facts = ansible_facts(module)\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1456756619.44-1762345300278/setup\", line 5259, in ansible_facts\r\n    facts.update(Facts().populate())\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1456756619.44-1762345300278/setup\", line 2376, in __init__\r\n    self.get_python_facts()\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1456756619.44-1762345300278/setup\", line 2994, in get_python_facts\r\n    self.facts['python'] = {\r\nAttributeError: 'module' object has no attribute 'subversion'\r\n", 
    "msg": "MODULE FAILURE", 
    "parsed": false
}
```

Looks like has been introduced in 7158eb489f1817adc01177f9d6d67417883e080b 

sys.subversion does  not exist in python 2.4.3 (sadly, the latest in the RHEL 5.8 repo)

**Comment by sivel** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
