### PR TITLE
Fix flush_cache on redis cache

### LINKED ISSUE #31148: Redis facts cache error with --flush-cache
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

plugin/cache/redis

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### CONFIGURATION

```
root@ansible:/etc/ansible# ansible-config dump --only-changed
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = redis
CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 86400
DEFAULT_BECOME(/etc/ansible/ansible.cfg) = True
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = debian
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/etc/ansible/ansible.cfg) = /root/.ansible-retry
```

##### OS / ENVIRONMENT

Running on Debian Jessie :
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.9 (jessie)
Release:	8.9
Codename:	jessie
```
pip installed python-redis:
redis==2.10.5

##### STEPS TO REPRODUCE

Run ansible playbook with flush cache:
```
root@ansible:/etc/ansible# touch empty_playbook.yml
root@ansible:/etc/ansible# ansible-playbook --flush-cache -i environments/cadastre-am/hosts empty_playbook.yml 
ERROR! Unexpected Exception, this is probably a bug: 'CacheModule' object has no attribute 'cache'
to see the full traceback, use -vvv
```

```yaml
---
```
I used an empty playbook for testing but also fails with a true one.

##### EXPECTED RESULTS

```
root@ansible:/etc/ansible# ansible-playbook -i environments/cadastre-am/hosts empty_playbook.yml 
ERROR! playbooks must be a list of plays
```
Or the playbook should go on.

##### ACTUAL RESULTS

After upgrading from 2.3.x to 2.4, I runned my usual playbook, 
The play crasshed with this message

```
root@ansible:/etc/ansible# ANSIBLE_STDOUT_CALLBACK=debug ansible-playbook -i environments/cadastre-am/ cadastre-am.yml --flush-cache --diff -vvv
ansible-playbook 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
Using /etc/ansible/ansible.cfg as config file
Parsed /etc/ansible/environments/cadastre-am/hosts inventory source with ini plugin
ERROR! Unexpected Exception, this is probably a bug: 'CacheModule' object has no attribute 'cache'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 106, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 124, in run
    self._flush_cache(inventory, variable_manager)
  File "/usr/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 204, in _flush_cache
    variable_manager.clear_facts(hostname)
  File "/usr/lib/python2.7/dist-packages/ansible/vars/manager.py", line 590, in clear_facts
    del self._fact_cache[hostname]
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/cache/__init__.py", line 260, in __delitem__
    self._plugin.delete(key)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/cache/redis.py", line 119, in delete
    del self.cache[key]
AttributeError: 'CacheModule' object has no attribute 'cache'
```

I tried to fix the line my replacing self.cache with self._cache as mentionned in the cache module, I got another error:
```
root@ansible:/etc/ansible# ANSIBLE_STDOUT_CALLBACK=debug ansible-playbook -i environments/cadastre-am/ cadastre-am.yml --flush-cache --diff -vvv
ansible-playbook 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
Using /etc/ansible/ansible.cfg as config file
Parsed /etc/ansible/environments/cadastre-am/hosts inventory source with ini plugin
ERROR! Unexpected Exception, this is probably a bug: u'app'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 106, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 124, in run
    self._flush_cache(inventory, variable_manager)
  File "/usr/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 204, in _flush_cache
    variable_manager.clear_facts(hostname)
  File "/usr/lib/python2.7/dist-packages/ansible/vars/manager.py", line 590, in clear_facts
    del self._fact_cache[hostname]
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/cache/__init__.py", line 260, in __delitem__
    self._plugin.delete(key)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/cache/redis.py", line 119, in delete
    del self._cache[key]
KeyError: u'app'
```

So it might be much more broken :cry:

### PR DESCRIPTION
**Pull request by alikins**
##### SUMMARY
Fix flush_cache on redis cache

Fix a del on non existent self.cache.

Fixes #31148

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

lib/ansible/plugins/cache/redis.py

##### ANSIBLE VERSION

```
ansible 2.5.0 (redis_cache_delete_31148 35a62f68c9) last updated 2017/10/02 13:54:25 (GMT -400)
  config file = /home/adrian/src/ansible/ansible.cfg
  configured module search path = [u'/home/adrian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/adrian/src/ansible/lib/ansible
  executable location = /home/adrian/src/ansible/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

### CODE REVIEW

**Comment by bcoca** [comment]
shipit

**Review by daxlab — APPROVED** [review]

**Comment by bcoca** [comment]
backported for 2.4.1
