### ISSUE TITLE
Task result not saved when delegate_to points to set_stat var

### ISSUE THREAD

**Issue by jladdjr** [ansible/ansible#44874]
##### SUMMARY
Task result not saved when delegate_to points to set_stat var.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
VariableManager

##### ANSIBLE VERSION

```
ansible 2.7.0.a1.post0 (devel 5bdcaff921) last updated 2018/08/29 16:39:28 (GMT -700)
  config file = None
  configured module search path = [u'/home/centos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/centos/git/ansible-devel/lib/ansible
  executable location = /home/centos/git/ansible-devel/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

`HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False`

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

repro.yml
```yaml
- hosts: all
  tasks:
  - name: Set controller
    set_fact:
      _controller: localhost

  - name: Register
    shell: echo 'foo'
    args:
      executable: /bin/bash
    register: result
    delegate_to: "{{ _controller }}"
    #delegate_to: "localhost"    <---- will pass if you set delegate_to explicitly

  - name: Reference result
    debug:
      msg: '{{ result.stdout }}'
```

`ansible-playbook -i localhost, -c local repro.yml`

##### EXPECTED RESULTS
```
ansible-playbook -v -i localhost, -c local repro.yml
No config file found; using defaults

PLAY [all] **************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************
ok: [localhost]

TASK [Set controller] ***************************************************************************************************************************************************************
ok: [localhost] => {"ansible_facts": {"_controller": "localhost"}, "changed": false}

TASK [Register] *********************************************************************************************************************************************************************
changed: [localhost -> localhost] => {"changed": true, "cmd": "echo 'foo'", "delta": "0:00:00.002690", "end": "2018-08-29 17:16:59.098935", "rc": 0, "start": "2018-08-29 17:16:59.096245", "stderr": "", "stderr_lines": [], "stdout": "foo", "stdout_lines": ["foo"]}

TASK [Reference result] *************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "foo"
}

PLAY RECAP **************************************************************************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0
```

##### ACTUAL RESULTS

```
ansible-playbook -vvvv -i localhost, -c local repro.yml
ansible-playbook 2.7.0.a1.post0 (devel 5bdcaff921) last updated 2018/08/29 16:39:28 (GMT -700)
  config file = None
  configured module search path = [u'/home/centos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/centos/git/ansible-devel/lib/ansible
  executable location = /home/centos/git/ansible-devel/bin/ansible-playbook
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
No config file found; using defaults
setting up inventory plugins
Set default localhost to localhost
Parsed localhost, inventory source with host_list plugin
Loading callback plugin default of type stdout, v2.0 from /home/centos/git/ansible-devel/lib/ansible/plugins/callback/default.pyc

PLAYBOOK: repro.yml *****************************************************************************************************************************************************************
1 plays in repro.yml

PLAY [all] **************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************
task path: /home/centos/git/ansible-devel/reproducer/repro.yml:1
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: centos
<localhost> EXEC /bin/sh -c 'echo ~centos && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/centos/.ansible/tmp/ansible-tmp-1535588141.81-241571427372267 `" && echo ansible-tmp-1535588141.81-241571427372267="` echo /home/centos/.ansible/tmp/ansible-tmp-1535588141.81-241571427372267 `" ) && sleep 0'
Using module file /home/centos/git/ansible-devel/lib/ansible/modules/system/setup.py
<localhost> PUT /home/centos/.ansible/tmp/ansible-local-25788vKZGt9/tmpPWk3sb TO /home/centos/.ansible/tmp/ansible-tmp-1535588141.81-241571427372267/AnsiballZ_setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/centos/.ansible/tmp/ansible-tmp-1535588141.81-241571427372267/ /home/centos/.ansible/tmp/ansible-tmp-1535588141.81-241571427372267/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/centos/.ansible/tmp/ansible-tmp-1535588141.81-241571427372267/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/centos/.ansible/tmp/ansible-tmp-1535588141.81-241571427372267/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [Set controller] ***************************************************************************************************************************************************************
task path: /home/centos/git/ansible-devel/reproducer/repro.yml:3
ok: [localhost] => {
    "ansible_facts": {
        "_controller": "localhost"
    },
    "changed": false
}

TASK [Register] *********************************************************************************************************************************************************************
task path: /home/centos/git/ansible-devel/reproducer/repro.yml:7
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: centos
<localhost> EXEC /bin/sh -c 'echo ~centos && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/centos/.ansible/tmp/ansible-tmp-1535588142.34-136590354087600 `" && echo ansible-tmp-1535588142.34-136590354087600="` echo /home/centos/.ansible/tmp/ansible-tmp-1535588142.34-136590354087600 `" ) && sleep 0'
Using module file /home/centos/git/ansible-devel/lib/ansible/modules/commands/command.py
<localhost> PUT /home/centos/.ansible/tmp/ansible-local-25788vKZGt9/tmp7p3o0o TO /home/centos/.ansible/tmp/ansible-tmp-1535588142.34-136590354087600/AnsiballZ_command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/centos/.ansible/tmp/ansible-tmp-1535588142.34-136590354087600/ /home/centos/.ansible/tmp/ansible-tmp-1535588142.34-136590354087600/AnsiballZ_command.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/centos/.ansible/tmp/ansible-tmp-1535588142.34-136590354087600/AnsiballZ_command.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/centos/.ansible/tmp/ansible-tmp-1535588142.34-136590354087600/ > /dev/null 2>&1 && sleep 0'
changed: [localhost -> localhost] => (item=None) => {
    "changed": true,
    "cmd": "echo 'foo'",
    "delta": "0:00:00.002600",
    "end": "2018-08-29 17:15:42.539613",
    "invocation": {
        "module_args": {
            "_raw_params": "echo 'foo'",
            "_uses_shell": true,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": "/bin/bash",
            "removes": null,
            "stdin": null,
            "warn": true
        }
    },
    "item": null,
    "rc": 0,
    "start": "2018-08-29 17:15:42.537013",
    "stderr": "",
    "stderr_lines": [],
    "stdout": "foo",
    "stdout_lines": [
        "foo"
    ]
}

TASK [Reference result] *************************************************************************************************************************************************************
task path: /home/centos/git/ansible-devel/reproducer/repro.yml:15
fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in '/home/centos/git/ansible-devel/reproducer/repro.yml': line 15, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Reference result\n    ^ here\n"
}
        to retry, use: --limit @/home/centos/git/ansible-devel/reproducer/repro.retry

PLAY RECAP **************************************************************************************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=1
```

**Comment by jladdjr** [comment]
git bisect identifies https://github.com/ansible/ansible/commit/5f98a5a736a81586fc8d4929993f017959d1dc66 as commit that introduced issue

**Comment by sivel** [comment]
I've just submitted a PR that should fix this issue: https://github.com/ansible/ansible/pull/44901
