### ISSUE TITLE
bug related to with_items (and possibly isolated to the yum module) ?

### ISSUE THREAD

**Issue by pol** [ansible/ansible#3802]
After a pull from devel, I get an error on a play task that didn't have an error previously.  I used git bisect to track down the error.

```
git bisect good start: 863b88ba44ac9bb41401d634a2374c7b4d01ff89
git bisect bad start:1c361a99680305097c9b098aeb2413fdfe697064


1a4e6e415ef9fa156aecbd7682d309858542c69b is the first bad commit
commit 1a4e6e415ef9fa156aecbd7682d309858542c69b
Author: Serge van Ginderachter <serge@vanginderachter.be>
Date:   Thu Aug 8 16:21:03 2013 +0200

    Check for ansible_facts in results for with_ tasks

    that loop over a lookup plugin. Fixes #3704 and #3735
```

Here is some reproducing info:

``` yaml
# playbook.yml
# --- SNIP ---

- name: install common Centos packages
  yum: name={{ item }}
  with_items:
    - man
    - acpid
    - curl
    - git
    - ntp
    - pv
    - vim
    - zsh
    - sudo
    - logrotate
    - fail2ban
    - htop
    - wget
    - cronie
    - libselinux-python
  tags:   
    - packages

# --- SNIP ---

# This fails when running the playbook with the following command:

# ansible-playbook playbook.yml -i production --tags "packages" -K -c paramiko

# Error Text: 

# Traceback (most recent call last):
#   File "/usr/local/bin/ansible-playbook", line 259, in <module>
#     sys.exit(main(sys.argv[1:]))
#   File "/usr/local/bin/ansible-playbook", line 205, in main
#     pb.run()
#   File "/Library/Python/2.7/site-packages/ansible/playbook/__init__.py", line 258, in run
#     if not self._run_play(play):
#   File "/Library/Python/2.7/site-packages/ansible/playbook/__init__.py", line 566, in _run_play
#     if not self._run_task(play, task, False):
#   File "/Library/Python/2.7/site-packages/ansible/playbook/__init__.py", line 368, in _run_task
#     facts = res.get('ansible_facts', {})
# AttributeError: 'unicode' object has no attribute 'get'
```

**Comment by jimi-c** [comment]
Reverted that commit, I'll follow up with @sergevanginderachter to get that fixed. Thanks!

**Comment by srgvg** [comment]
OK, this sounds like my patch doesn't work well when using the modules where with_items get merged in one module call (package managers specific)

**Comment by srgvg** [comment]
Tried reproducing this error, but as i don't have a yum using box handy, I tried with apt, but can't reproduce this.

**Comment by srgvg** [comment]
Looking at the code, it seems yum is the only library that sets a 'results' key in his return json, which value is a string and which conflicts here with the 'results' key used with loops, which value is a list.
Updating my patch to test for res['results'] being a list might solve this.

**Comment by srgvg** [comment]
@pol can you test this with the code from #3804  https://github.com/sergevanginderachter/ansible/tree/facts_with_lookups_v2 ?

**Comment by mpdehaan** [comment]
Yes, I am reverting this patch now.

**Comment by mpdehaan** [comment]
cc @jimi1283

**Comment by mpdehaan** [comment]
Ok, that appears to have already been done.   Pre-caffeine.  Good.
