### ISSUE TITLE
postgresql_user no longer works in 1.8

### ISSUE THREAD

**Issue by mguillaume** [ansible/ansible#9638]
##### Ansible Version:

ansible 1.8
  configured module search path = None
##### Environment:

Running from Ubuntu 14.04.1 (in a fresh virtualenv, ansible installed with pip)
Managed OS is Ubuntu 14.04.1
##### Summary:

postgresql_user tasks fail with a stacktrace
##### Steps To Reproduce:

Task:
      postgresql_user: name=test password=test
      sudo_user: postgres
##### Expected Results:

Creates the db user if missing
##### Actual Results:

```
TASK: [DB user] *************************************************
failed: [0.0.0.0] => {"failed": true, "parsed": false}
SUDO-SUCCESS-oisqwddolheudkppwhnhkbgjdwjwzucd
Traceback (most recent call last):
  File "/tmp/ansible-tmp-1417008833.32-259074618651633/postgresql_user", line 2251, in <module> main()
  File "/tmp/ansible-tmp-1417008833.32-259074618651633/postgresql_user", line 481, in main
    role_attr_flags = parse_role_attrs(module.params["role_attr_flags"])
  File "/tmp/ansible-tmp-1417008833.32-259074618651633/postgresql_user", line 405, in parse_role_attrs
    if not flag_set.is_subset(VALID_FLAGS):
AttributeError: 'frozenset' object has no attribute 'is_subset'
```

**Comment by mpdehaan** [comment]
Hi, we're aware of this one and are working on a fix right now which should be available today.   Please stay tuned!

**Comment by abadger** [comment]
This one should be fixed in devel.  Will have a new release shortly.
