### PR TITLE
Vault pass nonutf8 2.2 compat

### LINKED ISSUE #20398: 2.2.1.0 fails while decoding vault key to UTF-8
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

core

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /path/to/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
- pyenv on Debian 9
- Python 2.7.13

##### SUMMARY
Ansible tries to decode the content of the vault key as UTF-8:
```
ERROR! Unexpected Exception: 'utf8' codec can't decode byte 0xe6 in position 1: invalid continuation byte
```

The first few bytes of the vault key are:
```
39 e6 cb
```

##### EXPECTED RESULTS
This worked without issues in 2.2.0.0 (same OS, same Python)

##### ACTUAL RESULTS

```
ERROR! Unexpected Exception: 'utf8' codec can't decode byte 0xe6 in position 1: invalid continuation byte
the full traceback was:

Traceback (most recent call last):
  File "/home/user/.pyenv/versions/ansible/bin/ansible-playbook", line 103, in <module>
    exit_code = cli.run()
  File "/home/user/.pyenv/versions/2.7.13/envs/ansible/lib/python2.7/site-packages/ansible/cli/playbook.py", line 110, in run
    vault_pass = CLI.read_vault_password_file(self.options.vault_password_file, loader=loader)
  File "/home/user/.pyenv/versions/2.7.13/envs/ansible/lib/python2.7/site-packages/ansible/cli/__init__.py", line 589, in read_vault_password_file
    return to_text(vault_pass, errors='surrogate_or_strict')
  File "/home/user/.pyenv/versions/2.7.13/envs/ansible/lib/python2.7/site-packages/ansible/module_utils/_text.py", line 177, in to_text
    return obj.decode(encoding, errors)
  File "/home/user/.pyenv/versions/2.7.13/envs/ansible/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe6 in position 1: invalid continuation byte
```

### PR DESCRIPTION
**Pull request by abadger**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
vault password handling.  Various files have implementation details

##### ANSIBLE VERSION

```
2.2
```

##### SUMMARY
    Retain vault password as bytes in 2.2
    
    Prior to 2.2.1, the vault password was read in as byes and then remained
    bytes all the way through the code.  A bug existed where bytes and text
    were mixed, leading to a traceback with non-ascii passwords.  In devel,
    this was fixed by changing the read in password to text type to match
    with our overall strategy of converting at the borders.  This was
    backported to stable-2.2 for the 2.2.1 release.
    
    On reflection, this should not have been backported as it causes
    passwords which were originally non-utf-8 to become utf-8.  People will
    then have their working 2.2.x vault files become in-accessible.
    
    this commit pipes bytes all the way through the system for vault
    password.  That way if a password is read in as a non-utf-8 character
    sequence, it will continue to work in 2.2.2+.  This change is only for
    the 2.2 branch, not for 2.3 and beyond.
    
    Why not everywhere?  The reason is that non-utf-8 passwords will cause
    problems when vault files are shared between systems or users.  If the
    password is read from the prompt and one user/machine has a latin1
    encoded locale while a second one has utf-8, the non-ascii password
    typed in won't match between machines.  Deal with this by making sure
    that when we encrypt the data, we always use valid utf-8.
    
Fixes #20398

### CODE REVIEW

**Comment by alikins** [comment]
Haven't tested this yet, but the code changes LGTM.

There are submodule ref changes in that diff though.

**Comment by abadger** [comment]
Good spot.  Fixed.

**Comment by mattclay** [comment]
CI failure due to:

```
2017-02-15 22:33:35 ERROR! Unexpected Exception: __init__() got an unexpected keyword argument 'password'
```
