### ISSUE TITLE
nxos_evpn_vni and nxos_interface module failures

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#24167]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

nxos_evpn_vni
nxos_interface

##### ANSIBLE VERSION

```

ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### CONFIGURATION

no changes

##### OS / ENVIRONMENT

RHEL 7.2

##### SUMMARY

I recently upgraded ansible from 2.2 to 2.4 to fix an NXOS module issue where nxos_vlan_vtep_vni was not deleting the interface when putting it on an absent state. However now I get errors when I try to create objects using nxos_evpn_vni and nxos_interface. 

##### STEPS TO REPRODUCE

```
    - name: Configure EVPN
      nxos_evpn_vni:
        vni: "{{ vnid }}"
        route_distinguisher: auto
        route_target_import: auto
        route_target_export: auto
        username: ""
        password: ""
        host: "{{ item }}"
      with_items:
        - "{{ leaf1ip }}"
      register: evpnconfig
      ignore_errors: yes

    - name: Configure fabric forwarding anycast gateway
      nxos_interface:
        interface: vlan {{vlan_id}}
        description: "{{ vlan_name }}"
        transport: cli
        state: present
        username: ""
        password: ""
        host: "{{ item }}"
        fabric_forwarding_anycast_gateway: true
      with_items:
        - "{{ leaf1ip }}"
      ignore_errors: yes
      register: fabforconfig



```

##### EXPECTED RESULTS

Creation of the objects, worked in version 2.2

##### ACTUAL RESULTS

```
TASK [Configure EVPN] ***********************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not iterable
failed: [localhost] (item=x.x.x.x) => {"failed": true, "item": "x.x.x.x", "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_DplDrg/ansible_module_nxos_evpn_vni.py\", line 363, in <module>\n    main()\n  File \"/tmp/ansible_DplDrg/ansible_module_nxos_evpn_vni.py\", line 346, in main\n    result = execute_config(module, candidate)\n  File \"/tmp/ansible_DplDrg/ansible_module_nxos_evpn_vni.py\", line 272, in execute_config\n    result.update(response)\nTypeError: 'NoneType' object is not iterable\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}


TASK [Configure fabric forwarding anycast gateway] ******************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'dict' object has no attribute 'split'
failed: [localhost] (itemx.x.x.x) => {"failed": true, "item": "x.x.x.x", "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_E1__fU/ansible_module_nxos_interface.py\", line 711, in <module>\n    main()\n  File \"/tmp/ansible_E1__fU/ansible_module_nxos_interface.py\", line 637, in main\n    existing, is_default = smart_existing(module, intf_type, normalized_interface)\n  File \"/tmp/ansible_E1__fU/ansible_module_nxos_interface.py\", line 536, in smart_existing\n    existing = get_interface(normalized_interface, module)\n  File \"/tmp/ansible_E1__fU/ansible_module_nxos_interface.py\", line 303, in get_interface\n    attributes = get_manual_interface_attributes(intf, module)\n  File \"/tmp/ansible_E1__fU/ansible_module_nxos_interface.py\", line 228, in get_manual_interface_attributes\n    command_list = body.split('\\n')\nAttributeError: 'dict' object has no attribute 'split'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

```

**Comment by ansibot** [comment]
cc @jedelman8 @GGabriele @rahushen @privateip @rcarrillocruz @mikewiebe
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ghost** [comment]
@trishnaguha Hey, I pulled all the merges you've done. Getting a new module error with nxos_interface using the same configurations listed above. 

```
TASK [Configure fabric forwarding anycast gateway] *****************************
...ignoring
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IndexError: list index out of range
failed: [localhost] (item=) => {"failed": true, "item": "", "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_MAdgpF/ansible_module_nxos_interface.py\", line 944, in <module>\n    main()\n  File \"/tmp/ansible_MAdgpF/ansible_module_nxos_interface.py\", line 858, in main\n    existing, is_default = smart_existing(module, intf_type, normalized_interface)\n  File \"/tmp/ansible_MAdgpF/ansible_module_nxos_interface.py\", line 678, in smart_existing\n    existing = get_interface(normalized_interface, module)\n  File \"/tmp/ansible_MAdgpF/ansible_module_nxos_interface.py\", line 452, in get_interface\n    command_type='cli_show_ascii')[0]\nIndexError: list index out of range\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

**Comment by trishnaguha** [comment]
@donsantos this new issue doesn't seem to be occurred due to the fix merged for the issue you opened for `nxos_interface`. This is a separate issue. 
But according to the traceback it seems you still have the old code running as we are not following the pattern `command_type='cli_show_ascii')[0]` we used to have before.

With refactoring the code has been updated https://github.com/ansible/ansible/commit/2741907cbab3b53c6b5fb25ff5ae8ae7cd179142 .

**Comment by trishnaguha** [comment]
Easier way to work with Github code is
```
$ git clone https://github.com/ansible/ansible
$ cd ansible
$ source hacking/env-setup
```

```
$ ansible --version
```
should point to latest commit on `devel` branch.

```
$ which ansible
```
should point to the path in cloned repository.

**Comment by ghost** [comment]
@trishnaguha silly me realized I was using a different ansible server with 2.2 still installed. Used mine with the latest upgrades and everything works. Thank you!

**Comment by trishnaguha** [comment]
Fantastic!
