### ISSUE TITLE
regression: IPv4/IPv6 filter broken in ansible 2.x (works with 1.9.x)

### ISSUE THREAD

**Issue by nusenu** [ansible/ansible#14829]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.3.1.0
```
##### Environment:

N/A

##### COMPONENT NAME:
filters

##### Summary:

with_together loop does no longer work with empty member when using ansible 2.0.1.0
##### Steps To Reproduce:

On a target with IPv4 IPs but without IPv6 IPs run this task:

```
- name: setup IP list (1/2)
  set_fact:
    ips:
        ipv4: "{{ item.0 }}"
        ipv6: "{{ item.1 }}"
  with_together:
        - "{{ ansible_all_ipv4_addresses }}"
        - "{{ ansible_all_ipv6_addresses }}"
  register: ipsinterm
```

https://github.com/nusenu/ansible-relayor/blob/61a4057895a1c98e8b895e75bc1df30033af502a/tasks/ip-list.yml#L3
##### Expected Results:

No failure.
##### Actual Results:

```
FAILED! => {"failed": true, "msg": "an unexpected type error occurred.
Error was 'bool' object has no attribute '__getitem__'"}
```

https://groups.google.com/d/msgid/ansible-project/56DAB742.8010705%40openmailbox.org

update (2017-06-06): changed version to 2.3.1

**Comment by jimi-c** [comment]
This appears to be an issue with the ipv6 filter, which is returning a boolean rather than filtering addresses. As such, it's causing an error in the template code.

**Comment by nusenu** [comment]
Hi,
thank you for working on this,
is there an approx. ETA for this bug?

**Comment by nusenu** [comment]
Still broken in v2.1.0.0-1

**Comment by nusenu** [comment]
affects ansible 2.2.0.

**Comment by jimi-c** [comment]
Hi @nusenu, sorry to not have this addressed sooner, however I've gone back to the reproducer playbook you shared (and which I saw originally did reproduce the issue) and I'm seeing what I believe is the expected output.
<pre>
[jamesc@jimi 14829]$ cat test.yml 
- hosts: localhost
  gather_facts: yes
  vars:
    tor_maxips: 3
    tor_v4ips: "{{ ansible_all_ipv4_addresses[0:tor_maxips] | ipv4('address') }}"
    ipv4_count: "{{ tor_v4ips | length|int }}"
    v6tmp: "{{ ansible_all_ipv6_addresses|ipv6('public') }}"
    tor_v6ips: "{{ v6tmp[0:ipv4_count|int] }}"
  tasks:
  - debug: var=tor_v4ips
  - debug: var=ipv4_count
  - debug: var=v6tmp
  - debug: var=tor_v6ips
  - name: setup IP list (1/2)
    set_fact:
      ips:
          ipv4: "{{ item.0 }}"
          ipv6: "{{ item.1 }}"
    with_together:
          - "{{ tor_v4ips }}"
          - "{{ tor_v6ips }}"
    register: ipsinterm

[jamesc@jimi 14829]$ ansible-playbook -vv test.yml 
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: test.yml ************************************************************************************************************************************************************************************************
1 plays in test.yml

PLAY [localhost] **************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] ******************************************************************************************************************************************************************************************************
task path: /home/jamesc/testing/14829/test.yml:10
ok: [localhost] => {
    "tor_v4ips": [
        "192.168.1.158", 
        "192.168.122.1"
    ]
}

TASK [debug] ******************************************************************************************************************************************************************************************************
task path: /home/jamesc/testing/14829/test.yml:11
ok: [localhost] => {
    "ipv4_count": "2"
}

TASK [debug] ******************************************************************************************************************************************************************************************************
task path: /home/jamesc/testing/14829/test.yml:12
ok: [localhost] => {
    "v6tmp": []
}

TASK [debug] ******************************************************************************************************************************************************************************************************
task path: /home/jamesc/testing/14829/test.yml:13
ok: [localhost] => {
    "tor_v6ips": []
}

TASK [setup IP list (1/2)] ****************************************************************************************************************************************************************************************
task path: /home/jamesc/testing/14829/test.yml:14
ok: [localhost] => (item=['192.168.1.158', None]) => {"ansible_facts": {"ips": {"ipv4": "192.168.1.158", "ipv6": ""}}, "changed": false, "item": ["192.168.1.158", null]}
ok: [localhost] => (item=[u'192.168.122.1', None]) => {"ansible_facts": {"ips": {"ipv4": "192.168.122.1", "ipv6": ""}}, "changed": false, "item": ["192.168.122.1", null]}

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=0   
</pre>
If the above playbook is missing something, please let me know. Beyond that, I've tested it on stable-2.1, stable-2.2, and devel with the same output above.

**Comment by nusenu** [comment]
reproducer
```
$ ansible --version
ansible 2.2.0.0


$ cat 14829.yml

- hosts: localhost
  gather_facts: yes
  vars:
    tor_maxips: 3
    tor_v4ips: "{{ ansible_all_ipv4_addresses[0:tor_maxips] | ipv4('address') }}"
    ipv4_count: "{{ tor_v4ips | length|int }}"
    v6tmp: "{{ ansible_all_ipv6_addresses|ipv6('public')|ipv6('address') }}"
    tor_v6ips: "{{ v6tmp[0:ipv4_count|int]|ipv6('address') }}"
  tasks:
  - debug: var=tor_v4ips
  - debug: var=ipv4_count
  - debug: var=v6tmp
  - debug: var=tor_v6ips
  - name: setup IP list (1/2)
    set_fact:
      ips:
          ipv4: "{{ item.0 }}"
          ipv6: "{{ item.1 }}"
    with_together:
          - "{{ tor_v4ips }}"
          - "{{ tor_v6ips }}"
    register: ipsinterm

$ ansible-playbook 14829.yml 

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "tor_v4ips": [
        "1.2.3.4"
    ]
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "ipv4_count": "1"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "v6tmp": false
}

TASK [debug] *******************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "{{ v6tmp[0:ipv4_count|int]|ipv6('address') }}: Unexpected templating type error occurred on ({{ v6tmp[0:ipv4_count|int]|ipv6('address') }}): 'bool' object has no attribute '__getitem__'"}
```

**Comment by jimi-c** [comment]
@nusenu I believe this was working by accident in 1.9.x.  Adding these two lines:
<pre>
  - debug: var=ansible_all_ipv6_addresses|ipv6('public')
  - debug: var=ansible_all_ipv6_addresses|ipv6('public')|ipv6('address')
</pre>
gives the output:
<pre>
TASK [debug] *******************************************************************************
task path: /home/jamesc/testing/14829/test2.yml:13
ok: [localhost] => {
    "ansible_all_ipv6_addresses|ipv6('public')": []
}

TASK [debug] ******************************************************************************
task path: /home/jamesc/testing/14829/test2.yml:14
ok: [localhost] => {
    "ansible_all_ipv6_addresses|ipv6('public')|ipv6('address')": false
}
</pre>
However on 1.9.x the output is `"False"` instead of the true boolean `false`, so `v6tmp[0:ipv4_count|int]` gives:
<pre>
ok: [localhost] => {
    "var": {
        "v6tmp[0:ipv4_count|int]": "F"
    }
}
</pre>
So 2.x is turning the value into a proper boolean (which was something we fixed a while back), however I find it odd that the `|ipv6('address')` call is returning a boolean instead of an array (which is true in both cases).

**Comment by nusenu** [comment]
Any update on this one?

**Comment by nusenu** [comment]
for the record: ```ip('public')``` is broken as well (returns boolean instead of [] on targets without **any** IPv6 addresses)

**Comment by nusenu** [comment]
Is this an ansible or python-netaddr bug?
https://pypi.python.org/pypi/netaddr/

**Comment by nusenu** [comment]
same bug applies to ipv4()

**Comment by ansibot** [comment]
@nusenu Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by nusenu** [comment]
##### COMPONENT NAME
IPv4/6 filter
(not sure if that is what you expect)

**Comment by nusenu** [comment]
affects ansible version: 2.3.1.0

**Comment by abadger** [comment]
@drybjed  Is this filter supposed to return a boolean?

**Comment by nusenu** [comment]
great to see some activity on this long standing issue.

Toshio Kuratomi:
> @drybjed  Is this filter supposed to return a boolean?
 

according to documentation it should return a list (in the specific cases an empty list)


https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters_ipaddr.html?#filtering-lists

**Comment by drybjed** [comment]
@abadger In cases like `list_of_items | ipaddr('public')` the filter is supposed to return a list. If you specify `ipv6('public')` filter, and there are no IPv6 addresses, the empty list should be returned. If you test strings, the return value would be either the interpreted IP data, or False if say, you gave an IPv4 address to an `ipv6` filter, or the specific data cannot be correctly interpreted. Examples are in the documentation:

https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters_ipaddr.html?#basic-tests

**Comment by goll** [comment]
Using the reproducer from above I modified the filters using [ipwrap](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters_ipaddr.html#wrapping-ipv6-addresses-in-brackets):

```
- hosts: localhost
  gather_facts: yes
  vars:
    tor_maxips: 3
    tor_v4ips: "{{ ansible_all_ipv4_addresses[0:tor_maxips] | ipv4('address') }}"
    ipv4_count: "{{ tor_v4ips | length }}"
    v6tmp: "{{ ansible_all_ipv6_addresses | ipv6('address') | ipv6('public') }}"
    tor_v6ips: "{{ v6tmp[0:ipv4_count|int] | ipwrap }}"
  tasks:
  - debug: var=tor_v4ips
  - debug: var=ipv4_count
  - debug: var=v6tmp
  - debug: var=tor_v6ips
  - name: setup IP list (1/2)
    set_fact:
      ips:
          ipv4: "{{ item.0 }}"
          ipv6: "{{ item.1 }}"
    with_together:
          - "{{ tor_v4ips }}"
          - "{{ tor_v6ips }}"
    register: ipsinterm
```
results in this output:
```
PLAY [localhost] **************************************************************

TASK [Gathering Facts] ********************************************************
ok: [localhost]

TASK [debug] ******************************************************************
ok: [localhost] => {
    "tor_v4ips": [
        "192.168.50.1",
        "172.16.50.1",
        "10.245.50.1"
    ]
}

TASK [debug] ******************************************************************
ok: [localhost] => {
    "ipv4_count": "3"
}

TASK [debug] ******************************************************************
ok: [localhost] => {
    "v6tmp": [
        "foo:foo:foo:foo:bar:bar:bar:bar",
        "foo:foo:foo:foo:baz:baz:baz:baz"
    ]
}

TASK [debug] ******************************************************************
ok: [localhost] => {
    "tor_v6ips": [
        "[foo:foo:foo:foo:bar:bar:bar:bar]",
        "[foo:foo:foo:foo:baz:baz:baz:baz]"
    ]
}

TASK [setup IP list (1/2)] ****************************************************
ok: [localhost] => (item=['192.168.50.1', '[foo:foo:foo:foo:bar:bar:bar:bar]'])
ok: [localhost] => (item=['172.16.50.1', '[foo:foo:foo:foo:baz:baz:baz:baz]'])
ok: [localhost] => (item=['10.245.50.1', None])

PLAY RECAP ********************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=0   
```

**Comment by goll** [comment]
The filters are not returning lists but booleans, here are my tests with `ansible-2.7.8` and `python-netaddr-0.7.19` on a VM without IPv6:
```
Test playbook:
- hosts: localhost
  gather_facts: yes
  vars:
    tor_maxips: 3
    tor_v4ips: "{{ ansible_all_ipv4_addresses[0:tor_maxips] | ipv4('address') }}"
    ipv4_count: "{{ tor_v4ips | length }}"
    v6tmp: "{{ ansible_all_ipv6_addresses | ipv6('address') | ipv6('public') }}"
    tor_v6ips: "{{ v6tmp[0:ipv4_count|int] | TEST_FUNCTION }}"
  tasks:
  - debug: var=tor_v4ips
  - debug: var=ipv4_count
  - debug: var=v6tmp
  - debug: var=tor_v6ips
  - name: setup IP list (1/2)
    set_fact:
      ips:
          ipv4: "{{ item.0 }}"
          ipv6: "{{ item.1 }}"
    with_together:
          - "{{ tor_v4ips }}"
          - "{{ tor_v6ips }}"
    register: iptest
  - debug:
      var: iptest
```
Test 1 uses `ipaddr` as TEST_FUNCTION:
```
ok: [localhost] => {
    "iptest": {
        "changed": false,
        "msg": "All items completed",
        "results": [
            {
                "_ansible_ignore_errors": null,
                "_ansible_item_label": [
                    "10.0.2.15",
                    false
                ],
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "ansible_facts": {
                    "ips": {
                        "ipv4": "10.0.2.15",
                        "ipv6": false
                    }
                },
                "changed": false,
                "failed": false,
                "item": [
                    "10.0.2.15",
                    false
                ]
            }
        ]
    }
}
```
Test 2 uses `ipv6` as TEST_FUNCTION:
```
ok: [localhost] => {
    "iptest": {
        "changed": false,
        "msg": "All items completed",
        "results": [
            {
                "_ansible_ignore_errors": null,
                "_ansible_item_label": [
                    "10.0.2.15",
                    false
                ],
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "ansible_facts": {
                    "ips": {
                        "ipv4": "10.0.2.15",
                        "ipv6": false
                    }
                },
                "changed": false,
                "failed": false,
                "item": [
                    "10.0.2.15",
                    false
                ]
            }
        ]
    }
}
```
Test 3 uses `ipv6('address')` as TEST_FUNCTION:
```
ok: [localhost] => {
    "iptest": {
        "changed": false,
        "msg": "All items completed",
        "results": [
            {
                "_ansible_ignore_errors": null,
                "_ansible_item_label": [
                    "10.0.2.15",
                    false
                ],
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "ansible_facts": {
                    "ips": {
                        "ipv4": "10.0.2.15",
                        "ipv6": false
                    }
                },
                "changed": false,
                "failed": false,
                "item": [
                    "10.0.2.15",
                    false
                ]
            }
        ]
    }
}
```
Test 4 uses `ipwrap` as TEST_FUNCTION and is the only one that works:
```
ok: [localhost] => {
    "iptest": {
        "changed": false,
        "msg": "All items completed",
        "results": [
            {
                "_ansible_ignore_errors": null,
                "_ansible_item_label": [
                    "10.0.2.15",
                    null
                ],
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "ansible_facts": {
                    "ips": {
                        "ipv4": "10.0.2.15",
                        "ipv6": ""
                    }
                },
                "changed": false,
                "failed": false,
                "item": [
                    "10.0.2.15",
                    null
                ]
            }
        ]
    }
}
```

**Comment by sivel** [comment]
!component =lib/ansible/plugins/filter/ipaddr.py

**Comment by ansibot** [comment]
Thank you very much for your interest in Ansible. Ansible has migrated much of the content into separate repositories to allow for more rapid, independent development. We are closing this issue/PR because this content has been moved to one or more collection repositories.

* lib/ansible/plugins/filter/ipaddr.py -> https://galaxy.ansible.com/ansible/netcommon

For further information, please see:
https://github.com/ansible/ansibullbot/blob/master/docs/collection_migration.md
