### ISSUE TITLE
os_network.py send the 'dns_domain' parameter to the API whenever it have been defined or not

### ISSUE THREAD

**Issue by chris968** [ansible/ansible#64495]
##### SUMMARY
The dns_domain parameter is passed to the API when creating network whenever the parameter was defined or not into the Ansible task.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`os_network`

##### ANSIBLE VERSION
```
ansible-playbook 2.9.0.post0
  config file = /home/nix.tessares.net/caubry/Dev/ansible-office/ansible.cfg
  configured module search path = [u'/home/nix.tessares.net/caubry/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nix.tessares.net/caubry/Dev/ansible-office/ansible/lib/ansible
  executable location = /home/nix.tessares.net/caubry/Dev/ansible-office/ansible/bin/ansible-playbook
  python version = 2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/home/nix.tessares.net/caubry/Dev/ansible-office/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/nix.tessares.net/caubry/Dev/ansible-office/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=120s
ANSIBLE_SSH_CONTROL_PATH(/home/nix.tessares.net/caubry/Dev/ansible-office/ansible.cfg) = ~/.ssh/mux-%%r@%%h:%%p
DEFAULT_BECOME(/home/nix.tessares.net/caubry/Dev/ansible-office/ansible.cfg) = True
DEFAULT_FORKS(/home/nix.tessares.net/caubry/Dev/ansible-office/ansible.cfg) = 25
DEFAULT_GATHERING(/home/nix.tessares.net/caubry/Dev/ansible-office/ansible.cfg) = explicit
DEFAULT_GATHER_SUBSET(/home/nix.tessares.net/caubry/Dev/ansible-office/ansible.cfg) = [u'hardware', u'network', u'virtual']
DEFAULT_GATHER_TIMEOUT(/home/nix.tessares.net/caubry/Dev/ansible-office/ansible.cfg) = 15
DEFAULT_HOST_LIST(env: ANSIBLE_INVENTORY) = [u'/home/nix.tessares.net/caubry/Dev/ansible-office/ansible_hosts']
DEFAULT_ROLES_PATH(/home/nix.tessares.net/caubry/Dev/ansible-office/ansible.cfg) = [u'/home/nix.tessares.net/caubry/Dev/ansible-office/roles']
DEFAULT_SCP_IF_SSH(/home/nix.tessares.net/caubry/Dev/ansible-office/ansible.cfg) = True
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/nix.tessares.net/caubry/Dev/ansible-office/vault_password.txt
PARAMIKO_HOST_KEY_AUTO_ADD(/home/nix.tessares.net/caubry/Dev/ansible-office/ansible.cfg) = True
```

##### OS / ENVIRONMENT
Ubuntu 18.04.3 LTS

##### STEPS TO REPRODUCE
Create a simple network over an openstack API deployed without the DNS integration extension.

```yaml
  - name: Create test network
    os_network:
      name: test
      external: no
      shared: no
```

##### EXPECTED RESULTS
Network created without any error 

##### ACTUAL RESULTS
The ppenstack API thrown an 'unexpected keyword argument' error about the 'dns_domain' parameter.

```
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/usr/lib/python2.7/runpy.py", line 192, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_os_network_payload_rQfk3D/ansible_os_network_payload.zip/ansible/modules/cloud/openstack/os_network.py", line 255, in <module>
  File "/tmp/ansible_os_network_payload_rQfk3D/ansible_os_network_payload.zip/ansible/modules/cloud/openstack/os_network.py", line 237, in main
TypeError: create_network() got an unexpected keyword argument 'dns_domain'

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib/python2.7/runpy.py\", line 192, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_os_network_payload_rQfk3D/ansible_os_network_payload.zip/ansible/modules/cloud/openstack/os_network.py\", line 255, in <module>\n  File \"/tmp/ansible_os_network_payload_rQfk3D/ansible_os_network_payload.zip/ansible/modules/cloud/openstack/os_network.py\", line 237, in main\nTypeError: create_network() got an unexpected keyword argument 'dns_domain'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/openstack/os_network.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/openstack/os_network.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Shrews @cloudnull @dagnello @emonty @gtema @juliakreger @mnaser @odyssey4me @rcarrillocruz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by JonathanGrant** [comment]
Does it only raise an exception if ‘dns_domain’ is not provided in the config? Or does the ‘dns_domain’ kwarg always raise?

Can we just remove the kwarg?

**Comment by tsr-caubry** [comment]
The problem seems come from the version of openstacksdk package version "0.27.0" shipped with Ubuntu 18.04.

**Comment by odyssey4me** [comment]
Actually, the issue is caused by https://github.com/ansible/ansible/commit/6c74e29618a6872bc0da66e4992cfcd9cebf6acc which did not include a bump of the minimum openstacksdk version to include support for the dns_domain parameter. So Ansible 2.9+ is passing a parameter to openstacksdk which openstacksdk does not understand.

**Comment by odyssey4me** [comment]
bug_resolved
