### ISSUE TITLE
vars_prompt: AttributeError: 'NoneType' object has no attribute 'send_callback'

### ISSUE THREAD

**Issue by mathieumd** [ansible/ansible#12682]
With current `devel` branch, the `vars_prompt` is broken, while it is working well with branch `stable-1.9`.

``` yaml

---
- hosts: all
  vars_prompt:
  - name: user_pass
    prompt: "User password?"
    private: yes
# ...
```

``` bash
ansible-playbook -i 'localhost,' site.yml --syntax-check -vvv
```

The error is:

```
Using /home/mathieu/dev/test-ansible/ansible.cfg as config file
4 plays in site.yml
Unexpected Exception: 'NoneType' object has no attribute 'send_callback'
the full traceback was:

Traceback (most recent call last):
  File "/home/mathieu/dev/ansible/bin/ansible-playbook", line 79, in <module>
    sys.exit(cli.run())
  File "/home/mathieu/dev/ansible/lib/ansible/cli/playbook.py", line 138, in run
    results = pbex.run()
  File "/home/mathieu/dev/ansible/lib/ansible/executor/playbook_executor.py", line 104, in run
    self._tqm.send_callback('v2_playbook_on_vars_prompt', vname, private, prompt, encrypt, confirm, salt_size, salt, default)
AttributeError: 'NoneType' object has no attribute 'send_callback'
```

**Comment by bcoca** [comment]
this only fails during  syntax check or when using a `--list-` option

**Comment by serdardalgic** [comment]
I can confirm that this happens again on Ansible 2.0.0.2

```
  vars_prompt:
    - name: "continue"
      prompt: "Are you sure you have the latest certificates on the current machine? All remote certificates will be overriden. Do you want to continue?"
  tasks:
    - assert: {that: "'{{ continue }}' in ['y', 'yes']"}
```

```
$ ansible --version
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

```
$ ansible-playbook update_certificates.yml --list-hosts -vvv
Using /etc/ansible/ansible.cfg as config file
1 plays in update_certificates.yml
Unexpected Exception: 'NoneType' object has no attribute 'send_callback'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 85, in <module>
    sys.exit(cli.run())
  File "/usr/lib/pymodules/python2.7/ansible/cli/playbook.py", line 150, in run
    results = pbex.run()
  File "/usr/lib/pymodules/python2.7/ansible/executor/playbook_executor.py", line 115, in run
    self._tqm.send_callback('v2_playbook_on_vars_prompt', vname, private, prompt, encrypt, confirm, salt_size, salt, default)
AttributeError: 'NoneType' object has no attribute 'send_callback'
```

Please tell me if I'm missing smt.

**Comment by klauern** [comment]
I'm seeing this too:

``` sh
10:53:39 user@host:~/ansible/playbooks
$ ansible-playbook clean-old-logs.yml --list-tasks -vvv
Using /home/user/.ansible.cfg as config file
1 plays in clean-old-logs.yml
Unexpected Exception: 'NoneType' object has no attribute 'send_callback'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 85, in <module>
    sys.exit(cli.run())
  File "/usr/lib/python2.6/site-packages/ansible/cli/playbook.py", line 150, in run
    results = pbex.run()
  File "/usr/lib/python2.6/site-packages/ansible/executor/playbook_executor.py", line 115, in run
    self._tqm.send_callback('v2_playbook_on_vars_prompt', vname, private, prompt, encrypt, confirm, salt_size, salt, default)
AttributeError: 'NoneType' object has no attribute 'send_callback'
```

**Comment by serdardalgic** [comment]
@bcoca you're the one who closed the ticket here, can you check and confirm the situation? Can you reopen this ticket again? Thanks a lot!
