### ISSUE TITLE
winrm.py triggers AttributeError: 'Display' object has no attribute 'debugv'

### ISSUE THREAD

**Issue by rriggs** [ansible/ansible#11823]
Testing out Windows functionality under 2.0 that works in 1.9.2:  

  File "/usr/lib/python2.7/site-packages/ansible/plugins/connections/winrm.py", line 170, in exec_command
    result = self._winrm_exec(cmd_parts[0], cmd_parts[1:], from_exec=True)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connections/winrm.py", line 142, in _winrm_exec
    self._display.debugv('WINRM STDOUT %s' % response.std_out, host=self._play_context.remote_addr)
  AttributeError: 'Display' object has no attribute 'debugv'

There is a similar call to self._display.debug() that has the same problem.

**Comment by jimi-c** [comment]
Hi @rriggs, this was already corrected in commit e87cf4a3cc2d74695b226e6ff073da342f72abf2. Pulling the most recent version of devel should get you past that error.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
