### ISSUE TITLE
vmware.py makes vm can't be found when using vmware_guest.py

### ISSUE THREAD

**Issue by 2333** [ansible/ansible#31868]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

module_utils/vmware.py
vmware_guest

##### ANSIBLE VERSION

```
2.4
```

##### CONFIGURATION

DEFAULT_ACTION_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/plugins/action']
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_LOCAL_TMP(/etc/ansible/ansible.cfg) = /root/.ansible/tmp/ansible-local-291964cSz4b
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/my_modules']
DEFAULT_REMOTE_TMP(/etc/ansible/ansible.cfg) = $HOME/.ansible/tmp
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

CentOS release 6.9
python version = 2.7.12 (default, Aug  3 2016, 15:23:26) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
vsphere 5.5

##### SUMMARY

I used vmware_guest module to operate vmwares, but it didn't work after I updated ansible to 2.4(used to be 2.3.2 and my command works fine). According to traceback, the problem should be vm cann't be found, and getvm function is written in module_util/wmare.py, so I think it maybe a bug or the way of using this module has changed?
##### STEPS TO REPRODUCE

I found that the in vmware.py, find_vm_bu_id function, searchpath used to be "datacenter + folder", as in my case, it's "DataCenter/vm". Now, `search = folder`.
And after I add in vmware_guest module:

```python
if datacenter:
    folder = datacenter + folder
```
It works well again.

my command is:

```yaml
ansible localhost -m vmware_guest -a "name=vmname state=poweredoff validate_certs=false hostname=10.10.1.250 username=administrator password=password datacenter=DataCenter"
```

##### EXPECTED RESULTS

```
localhost | SUCCESS => {
    "changed": true, 
    "failed": false
}
```
##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'name'
localhost | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible__ThQth/ansible_module_vmware_guest.py\", line 1503, in <module>\n    main()\n  File \"/tmp/ansible__ThQth/ansible_module_vmware_guest.py\", line 1494, in ma
in\n    result = pyv.deploy_vm()\n  File \"/tmp/ansible__ThQth/ansible_module_vmware_guest.py\", line 1189, in deploy_vm\n    dcpath = compile_folder_path_for_object(datacenter)\n  File \"/tmp/ansible__ThQth/ansible_modlib.zip/ansible/module_utils/vmware.py\", line 237, in compile_folder_path_for_object\nAttributeError: 'NoneType' object has no attribute 'name'\n",     "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}

**Comment by ansibot** [comment]
cc @akasurde @dagwieers @dav1x @jctanner @nerzhul
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@2333 Thanks for reporting this issue. This is fixed in [PR](https://github.com/ansible/ansible/pull/32671). Let me know if it works for you.

**Comment by Akasurde** [comment]
Closing this issue as PR is merged. If issue persists, please feel free to re-open.

**Comment by 2333** [comment]
@Akasurde Thanks for fix it, I 'll check it out soon.
