### ISSUE TITLE
Unable to run adhoc commands after checking out the latest devel branch 

### ISSUE THREAD

**Issue by linuxbsdfreak** [ansible/ansible#12590]
Loaded callback minimal of type stdout, v2.0
Unexpected Exception: Values instance has no attribute 'start_at_task'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible", line 79, in <module>
    sys.exit(cli.run())
  File "/usr/lib/python2.7/site-packages/ansible/cli/adhoc.py", line 162, in run
    result = self._tqm.run(play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 213, in run
    if self._options.start_at_task is not None and play_context.start_at_task is None:
AttributeError: Values instance has no attribute 'start_at_task'

command is

ansible -i inventory 'nmygroup' -m ping  -vvvv

Could you please look at this at the earliest?

**Comment by halberom** [comment]
Caused by commit dcb8caf9e812cafd352d094538086677ae32ebb5,  you can (as a temp workaround) checkout the commit before it 57adf11262470e.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
