### ISSUE TITLE
SSL certificate validation not using system proxy settings

### ISSUE THREAD

**Issue by dan-v** [ansible/ansible#7413]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
(commit 71a870a)
##### Environment:

Running Ansible from Mint 16 and managing Ubuntu 12.04.
##### Summary:

The python socket used to validate certificates does not take the system proxy settings into account. This becomes a problem when the only way to access the internet is through a proxy (e.g. corporate setting). This results in "[Errno 113] No route to host." This is a pain with apt_repository because there is no option currently to set 'validate_certs=no'.
##### Steps To Reproduce:
1. Managed ansible server configured with http proxy settings (http_proxy=http://proxy:8080/ and https_proxy=http://proxy:8080/).
2. Run task to add any apt_repository PPA
##### Expected Results:

Successfully add PPA repository
##### Actual Results:

Fails with following:

<pre>
    failed: [host] => {"failed": true, "item": ""}
    msg: Failed to validate the SSL certificate for launchpad.net:443. Use validate_certs=no or make sure your managed systems have a valid CA certificate installed. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible

    FATAL: all hosts have already failed -- aborting
</pre>

**Comment by markaolson** [comment]
I upgraded to Ansible 1.6.1 and now I am seeing the same error from apt_repository.

Running Ansible from Ubuntu 13.10 and managing Ubuntu 12.04 

I'm also behind a corporate proxy

**Comment by mpdehaan** [comment]
We need to look into why there isn't the ability to pass validate_certs=no here.

It should be surfaced.

That being said, some upgrades the cert handling code are in progress.

cc @jimi-c

**Comment by mpdehaan** [comment]
related to #7322

**Comment by jimi-c** [comment]
Actually, I don't believe this is related to #7322, so re-opening. The patch above introduces the new feature of proxy support for the SSL certificate validation step, and also includes support for basic auth to the proxy. I have tested it with the following command:

<pre>
https_proxy='http://testing:testing@myproxy:3128' ansible -m get_url -a "url=https://www.google.com force=yes dest=/dev/null" -i localhost, all -c local -vv
<localhost> REMOTE_MODULE get_url url=https://www.google.com force=yes dest=/dev/null
localhost | success >> {
    "changed": true, 
    "dest": "/dev/null", 
    "gid": 0, 
    "group": "root", 
    "md5sum": "7abcd8c2ce92b723d5eb1fb82e96355c", 
    "mode": "0666", 
    "msg": "OK (unknown bytes)", 
    "owner": "root", 
    "secontext": "system_u:object_r:null_device_t:s0", 
    "sha256sum": "", 
    "size": 0, 
    "src": "/tmp/tmpJA3lST", 
    "state": "file", 
    "uid": 0, 
    "url": "https://www.google.com"
}
</pre>

@dan-v if you'd like to test it out and see if it resolves your issue.

**Comment by dan-v** [comment]
@jimi-c the fix for #7413 seems to work for the SSL issue. Now that I'm past that, it seems as though the module is not respecting the proxy settings. I have http_proxy and https_proxy set in /etc/environment which worked fine in 1.5. Even if I explicitely set http_proxy and https_proxy on the task it still does not work.

<pre>
failed: [rdocker.mcp.com] => {"failed": true, "item": "", "traceback": "Traceback (most recent call last):\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1400522282.69-145654680614360/apt_key\", line 158, in download_key\n    return rsp.read()\nAttributeError: 'NoneType' object has no attribute 'read'\n"}
msg: error getting key id from url: https://get.docker.io/gpg
</pre>

**Comment by jimi-c** [comment]
@dan-v now that sounds like the same issue as #7322. If you agree, I'll go ahead and merge this in and continue working on that issue.

**Comment by dan-v** [comment]
@jimi-c that does sound like the same issue as #7322. Thanks!

**Comment by jimi-c** [comment]
Great, I've merged in the above patch, so this issue should be resolved. Thanks!

**Comment by ghost** [comment]
Is the documentation not updated for this? It still has a note which states: "This module doesn’t yet support configuration for proxies."
http://docs.ansible.com/get_url_module.html

**Comment by jimi-c** [comment]
@zahlenofzahlen that does seem to be an oversight, as it has not been true for quite a long time.
