### ISSUE TITLE
tuple' object has no attribute 'items'

### ISSUE THREAD

**Issue by dmwilcox** [ansible/ansible#15693]
Issue broke my larger ansible playbook -- I recreated a small piece below to demonstrate the issue.  tldr; It appears to be due to how arguments are checked and an item is coming out as a tuple instead of a dictionary.

I tried various combinations of command and shell modules with the creates= on the same line or on a second line ala 'creates: <dir>' per the documentation to no avail.  A work around would be much appreciated, thank you.
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

Tried it on the former, upgraded and recreated as the logs show below on the latter.  Issue exists with both and a dead simple task list.

```
$ ansible --version
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = /usr/share/ansible
AND
$ ansible --version
ansible 2.0.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = /usr/share/ansible
```
##### CONFIGURATION

Default install no changes -- installed in a virtual environment for python2.  I can try this outside of a virtualenv if that is useful.
##### OS / ENVIRONMENT

Managing and Managed:
Debian and Debian
##### SUMMARY

Existing playbooks that used to work in 1.9 and 2.0 broke.  Appears to be related to how command/shell module arguments are handled and constructed into commands to run on the managed host.
##### STEPS TO REPRODUCE

```
virtualenv -p /usr/bin/python2.7 venv_py2
source venv_py2/bin/activate
pip install ansible

echo '- hosts: web
  vars:
    - virtualenv_path: "/srv/test"

  tasks:
    - name: setup_virtualenv
      command: virtualenv -p /usr/bin/python3 {{ virtualenv_path }} creates={{ virtualenv_path }}
' > test.yml

echo '[web]
<PUT YOUR HOST IP HERE>' > hosts

ansible-playbook -K -i hosts -s test.yml
SUDO password: 

PLAY [web] *********************************************************************

TASK [setup] *******************************************************************
ok: [YOUR_HOST]

TASK [setup_virtualenv] ********************************************************
fatal: [YOUR_HOST]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/user/.ansible/tmp/ansible-tmp-1462222673.49-133179241489332/command\", line 2426, in <module>\r\n    main()\r\n  File \"/home/user/.ansible/tmp/ansible-tmp-1462222673.49-133179241489332/command\", line 118, in main\r\n    module = CommandModule(argument_spec=dict())\r\n  File \"/home/user/.ansible/tmp/ansible-tmp-1462222673.49-133179241489332/command\", line 756, in __init__\r\n    self._check_arguments(check_invalid_arguments)\r\n  File \"/home/user/.ansible/tmp/ansible-tmp-1462222673.49-133179241489332/command\", line 1303, in _check_arguments\r\n    for (k,v) in self.params.items():\r\nAttributeError: 'tuple' object has no attribute 'items'\r\n", "msg": "MODULE FAILURE", "parsed": false}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @test.retry

PLAY RECAP *********************************************************************
YOUR_HOST      : ok=1    changed=0    unreachable=0    failed=1   
```

**Comment by sivel** [comment]
I believe this is indicative of having an Ansible 1.9 command module located in /usr/share/ansible.  Changes were made to how modules parse their arguments which required changes to the command module.

If you remove the configuration from ansible.cfg to no longer specify `/usr/share/ansible` this problem should go away.

**Comment by dmwilcox** [comment]
Brilliant!  Thank you!

This works for my test case, I'll try a few things today (apt-get purge for one) and report back.  I thought I was in the clear since I installed 2.0.x in a virtualenv --  because debian8 only has 1.9 which is installed (and I presumed, wrongly, unused).
