### ISSUE TITLE
[ansible 2.6] os_user requires openstacksdk>=0.12.0 

### ISSUE THREAD

**Issue by cdelgehier** [ansible/ansible#42588]
##### SUMMARY
I can't create user with ansible 2.6 with an openstacksdk-0.9.17 (pike)

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
os_user

##### ANSIBLE VERSION

```
(ansible) [root@jenkins sds]# ansible --version
ansible 2.6.1
  config file = /home/jarvis/stuff/workspace/r-KH2QK7URI4/products/sds/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jarvis/stuff/workspace/r-KH2QK7URI4/ansible/lib/python2.7/site-packages/ansible
  executable location = /home/jarvis/stuff/workspace/r-KH2QK7URI4/ansible/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```
```
(ansible_2.5) [root@jenkins sds]# ansible --version
ansible 2.5.0
  config file = /home/jarvis/stuff/workspace/r-KH2QK7URI4/products/sds/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jarvis/stuff/workspace/r-KH2QK7URI4/ansible_2.5/lib/python2.7/site-packages/ansible
  executable location = /home/jarvis/stuff/workspace/r-KH2QK7URI4/ansible_2.5/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### OS / ENVIRONMENT
```
[root@3f05d3575ea0 /]# yum repolist|grep -i openstack
centos-openstack-pike/x86_64 CentOS-7 - OpenStack pike                    2706+2
[root@3f05d3575ea0 /]# rpm -qf /usr/lib/python2.7/site-packages/openstack
python2-openstacksdk-0.9.17-1.el7.noarch
```
##### STEPS TO REPRODUCE

Create a user with `os_user` in ansible 2.6 with the python2-openstacksdk-0.9.17-1.el7.noarch package

##### EXPECTED RESULTS
Works with 0.9.17

##### ACTUAL RESULTS
It works with ansible 2.5, it needs an upgrade to `openstacksdk==0.12.0` for ansible 2.6
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'module' object has no attribute 'version'
failed: [node1] (item={u'password': u'DEMO_PASS', u'name': u'demo'}) => {"attempts": 5, "changed": false, "item": {"name": "demo", "password": "DEMO_PASS"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_SugagJ/ansible_module_os_user.py\", line 283, in <module>\n    main()\n  File \"/tmp/ansible_SugagJ/ansible_module_os_user.py\", line 202, in main\n    sdk, cloud = openstack_cloud_from_module(module)\n  File \"/tmp/ansible_SugagJ/ansible_modlib.zip/ansible/module_utils/openstack.py\", line 121, in openstack_cloud_from_module\nAttributeError: 'module' object has no attribute 'version'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```
"version" is `sdk.version.__version__`
https://github.com/ansible/ansible/blob/stable-2.6/lib/ansible/module_utils/openstack.py#L121

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/openstack/os_user.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/openstack/os_user.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagnello @emonty @juliakreger @omgjlk @rcarrillocruz @shrews @thingee
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mrunge** [comment]
Seems to be the same issue as https://github.com/ansible/ansible/issues/42189

**Comment by mrunge** [comment]
It also fails with openstacksdk-0.14

**Comment by gtema** [comment]
it is a normal process, that with upgrade of one component, requirements for others also increase. You can't expect, that ansible 2.(whatever) would always require `openstacksdk==0.9.17`. openstacksdk is not tied to the openstack release cycle.

On the other hand I am not able to reproduce your error, see https://github.com/ansible/ansible/issues/42189#issuecomment-404800883

**Comment by cdelgehier** [comment]
This answer seems to me easy, but ok
Maybe a precision of the version would not be too much ...
https://docs.ansible.com/ansible/devel/modules/os_user_module.html#requirements

**Comment by mrunge** [comment]
I would love to see requirements in ansible packaging specified. Looking at https://src.fedoraproject.org/rpms/ansible/blob/master/f/ansible.spec
there is no mention of openstacksdk at all; however openstacksdk is *required* to use os_* functionality in ansible.

While adding the package requirements to downstream packaging would solve this kind off issue here, it should be out of scope for upstream Ansible.

**Comment by gtema** [comment]
@mrunge, of course you would not find openstacksdk in the ansible spec, since it is not the ansible dependency, but module dependency. This is how it works in ansible - each module might have it's own "dynamic" dependencies. Otherwise it would not be feasible to provide one Ansible that fits everybody.
Compare i.e. https://docs.ansible.com/ansible/latest/modules/gc_storage_module.html#gc-storage-module and https://docs.ansible.com/ansible/latest/modules/os_flavor_facts_module.html#os-flavor-facts-module - they do have different requirements.

**Comment by mrunge** [comment]
@gtema when installing ansible via distro package, you'll get the modules as well. You don't need to specify the modules you want. Thus you should get the requirements for modules as well.
I can't see, how both linked requirements are contradicting each other.

**Comment by gtema** [comment]
no, this is not how it works. Sure, you get all the modules. But in order to use those modules you might need additional dependencies to be installed locally (or in some cases on remote targets). Distro package provides only things required for ansible itself to function, but not for each individual module. Try using AWS modules from ansible without installing boto3 library.

**Comment by mrunge** [comment]
I totally get how it works; you're distributing ansible with modules, but leave out requirements for the modules. When a user needs this or that module, then the user has to take care of providing requirements for these modules.
I have seen the warnings, reported by ansible, when a library is not installed.

I'm saying, it should be packaged differently, so that the step of a user in charge to download/install/provide necessary libraries is taken care by the distribution.

**Comment by gtema** [comment]
Than it is a totally wrong place for the discussion. For me this is kinda
core Ansible discussion.

**Comment by mrunge** [comment]
Right, that's what I said like 30 mins ago.

Ideally, upstream and downstream should collaborate on those things.
