### ISSUE TITLE
eos_config not handling sockets properly

### ISSUE THREAD

**Issue by kromanow94** [ansible/ansible#30698]
Hello!

I've been on this issue for few days, did a lot of network debugging, read a lot of issues contributing to this one, but this seems to be rather not documented.

We have a role that is configuring switches with eos_config. It worked perfectly on ansible 2.1.0.0, but upgrading to 2.3.2.0 creates errors.

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

eos_config

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = <...>
  configured module search path = <...>
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```
We can't use 2.4 because it's not compatible with our modules.
(CallbackModule' object has no attribute 'set_options')

##### OS / ENVIRONMENT

The ansible role is run inside container based on openjdk:8-jdk.

In out environment seven switches exists and only some of them (but every time random) are getting problems with sockets.

##### CONFIGURATION

```
[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=1800s -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
control_path = %(directory)s/ansible-ssh-%%h-%%p-%%r
```
##### ACTUAL RESULTS

Upgrading to 2.3.2.0 produces this problem at first:
```
failed: [...] (item=...) => {"failed": true, "item": "...", "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell"}
```
So I've came up to solution with configuration shown below.

##### CONFIGURATION

```
[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=1800s -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
control_path = %(directory)s/ansible-ssh-%%h-%%p-%%r

[paramiko_connection]
host_key_auto_add = True
```
Environment:

```
ANSIBLE_HOST_KEY_CHECKING=false
```
##### ACTUAL RESULTS

It works at first run, but for some switches every other run shows error:
```
 "err": "[Errno 111] Connection refused", "failed": true, "item": "<hostname>", "msg": "unable to connect to socket"
```

If I delete the sockets manually and run the playbook again, it works once. Then I have to remove them again.

##### STEPS TO REPRODUCE

1. Have a few switches to configure (seven in our env).
2. Run configure_eos.yml 

configure_eos.yaml
```
- name: enable vlan for control plane nodes
  eos_config:
    auth_pass: "{{ pass }}"
    authorize: yes
    host: "{{ hostvars[item]['switch_host'] }}"
    lines: "{{ ... }}"
    parents: "{{ ... }}"
    password: "{{ another_pass}}"
    username: "{{ user }}"
  with_items:
    - "{{ groups[network_provision_control_plane_group_name] | os_group_switches }}"
  run_once: true
  when: network_provision_configure_control_plane

- name: enable vlan for tenant nodes
  eos_config:
    auth_pass: "{{ pass }}"
    authorize: yes
    host: "{{ hostvars[item]['switch_host'] }}"
    lines: "{{ ... }}"
    parents: "{{ ... }}"
    password: "{{ another_pass }}"
    username: "{{ user }}"
  with_items:
    - "{{ play_hosts | os_group_switches }}"
  run_once: true

```

##### EXPECTED RESULTS

Both tasks are successful for every switch.

##### SUMMARY
For what I did notice is that sockets sometimes are not deleted automatically on abandoning connection (something with EOF possibly?).
Deleting sockets allows to run the playbook

**Comment by ansibot** [comment]
cc @Qalthos @ganeshrn @gundalow @privateip @rcarrillocruz @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ganeshrn** [comment]
Please follow the troubleshooting steps mentioned [here](docs.ansible.com/ansible/latest/network_debug_troubleshooting.html#unable-to-open-shell)

Also, you can enable the logging by setting `log_path` value in the configuration file. The additional logs in the file will give more information about the cause of failure.

**Comment by kromanow94** [comment]
Sorry for delay.
The logs are here:
https://gist.github.com/krzysztofromanowski94/8fa06a2335147e37fcae6a009fe17e30
I did also find this to be kind of relative to https://github.com/ansible/ansible/issues/22319

**Comment by ansibot** [comment]
cc @kedarX
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ganeshrn** [comment]
Sorry for the delayed response, unfortunately I missed tracking this issue.
Based on the shared logs it seems you are forcing the connection to be closed `2017-09-25 15:07:04,847 p=45863 u=root |  closing shell due to sigalarm` that's probably the reason for socket not getting closed gracefully. 

There are number changes in the underlying connection handling since 2.3 and I am not able to reproduce the issue on the latest release version.

Can you please upgrade to latest stable release version and check if the issue is still seen.

needs_info

**Comment by kromanow94** [comment]
We were finally able to move to newest ansible. Problem no longer occurs.
