### ISSUE TITLE
2.0.0.2 Loop Error AttributeError: 'list' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by diarworld** [ansible/ansible#14369]
**Issue Type**: Bug Report
**Ansible Version**: 2.0.0.2-1ppa~trusty

**Ansible Configuration**: Default

**Environment**: Ubuntu 14.04, Target systems Ubuntu 14.04

**Summary**:

I have playbook for adding and modifying user at remote Ubuntu hosts. Playbook worked correctly till I upgrade ansible to 2.0.0.2 version. Following code in my playbook:

```
- name: Add RSA keys to the remote host for users
  authorized_key: user="{{ item.name }}"
                  key="{{ lookup('file', item.pubkeys) }}"
  when:
    item.state == "present"
  with_items:
    users
```

group vars.yml:

```
users:
  - { name: 'diarworld', state: 'present', comment: '"Dmitry Ibragimov"', pass: 'EncodedString', pubkeys: ['diarworld_rsa.pub', 'diarworld_prod_rsa.pub'] }
  - { name: 'test123', state: 'present', comment: '"Test User"', pass: 'EncodedString', pubkeys: ['test_rsa.pub'] }
```

This code worked correctly with **1.7.2+dfsg-1~ubuntu14.04.1** ansible version. But after upgrade to **2.0.0.2-1ppa~trusty** I got error:

```
fatal: [test.machine.com]: FAILED! => {"failed": true, "stdout": ""}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'list' object has no attribute 'startswith'
```

Full strace:

```
fatal: [test.machine.com]: FAILED! => {"failed": true, "stdout": ""}
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ansible/executor/process/worker.py", line 114, in run
    self._shared_loader_obj,
  File "/usr/lib/pymodules/python2.7/ansible/executor/task_executor.py", line 91, in run
    item_results = self._run_loop(items)
  File "/usr/lib/pymodules/python2.7/ansible/executor/task_executor.py", line 241, in _run_loop
    res = self._execute(variables=task_vars)
  File "/usr/lib/pymodules/python2.7/ansible/executor/task_executor.py", line 356, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/task.py", line 238, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/base.py", line 307, in post_validate
    value = templar.template(getattr(self, name))
  File "/usr/lib/pymodules/python2.7/ansible/template/__init__.py", line 350, in template
    d[k] = self.template(variable[k], preserve_trailing_newlines=preserve_trailing_newlines, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/usr/lib/pymodules/python2.7/ansible/template/__init__.py", line 322, in template
    result = self._do_template(variable, preserve_trailing_newlines=preserve_trailing_newlines, escape_backslashes=escape_backslashes, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/usr/lib/pymodules/python2.7/ansible/template/__init__.py", line 474, in _do_template
    res = j2_concat(rf)
  File "<template>", line 9, in root
  File "/usr/lib/python2.7/dist-packages/jinja2/runtime.py", line 193, in call
    return __obj(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/ansible/template/__init__.py", line 401, in _lookup
    ran = instance.run(loop_terms, variables=self._available_variables, **kwargs)
  File "/usr/lib/pymodules/python2.7/ansible/plugins/lookup/file.py", line 47, in run
    lookupfile = self._loader.path_dwim_relative(basedir, 'files', term)
  File "/usr/lib/pymodules/python2.7/ansible/parsing/dataloader.py", line 230, in path_dwim_relative
    if source.startswith('~') or source.startswith('/'):
AttributeError: 'list' object has no attribute 'startswith'
```

**Steps To Reproduce**:
1. Create playbook with following task:

```
- name: Add RSA keys to the remote host for users
  authorized_key: user="{{ item.name }}"
                  key="{{ lookup('file', item.pubkeys) }}"
  when:
    item.state == "present"
  with_items:
    users
```

group vars.yml:

```
users:
  - { name: 'diarworld', state: 'present', comment: '"Dmitry Ibragimov"', pass: 'EncodedString', pubkeys: ['diarworld_rsa.pub', 'diarworld_prod_rsa.pub'] }
  - { name: 'test123', state: 'present', comment: '"Test User"', pass: 'EncodedString', pubkeys: ['test_rsa.pub'] }
```

Put sample key files to playbook directory. Run playbook.

**Expected Results**:

As worked with 1.7.2 version.

```
TASK: [add_developers | Add RSA keys to the remote host for users] ************ 
ok: [test.machine.com] => (item={'comment': '"Dmitry Ibragimov"', 'state': 'present', 'pubkeys': ['diarworld_rsa.pub'], 'name': 'diarworld', 'pass': 'EncodedString'})
ok: [test.machine.com] => (item={'comment': '"Dmitry Ibragimov"', 'state': 'present', 'pubkeys': ['diarworld_prod_rsa.pub'], 'name': 'diarworld', 'pass': 'EncodedString'})

```

**Actual Results**:

Error :( If this bug unable to fix, please help me modify my playbook to avoid this error.

**Comment by einarc** [comment]
+1 on 2.0.2 as well.

**Comment by atoz7** [comment]
hello,

i encountered the same problem on debian/stable with a recent ansible version 2.1.1.0

regards,
a

**Comment by krzysztof-magosa** [comment]
Try:
```
- name: Add RSA keys to the remote host for users
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', item.pubkeys) }}"
  when: item.state == "present"
  with_items: "{{ users }}"
```

**Comment by diarworld** [comment]
@krzysztof-magosa Tried this solution with git version: ansible-playbook 2.1.2.0 (detached HEAD b2fe1b39df) last updated 2016/08/29 17:10:12 (GMT +300)
Error too :(
Trace:
```An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/etc/ansible/lib/ansible/executor/task_executor.py", line 96, in run
    item_results = self._run_loop(items)
  File "/etc/ansible/lib/ansible/executor/task_executor.py", line 252, in _run_loop
    res = self._execute(variables=task_vars)
  File "/etc/ansible/lib/ansible/executor/task_executor.py", line 401, in _execute
    self._task.post_validate(templar=templar)
  File "/etc/ansible/lib/ansible/playbook/task.py", line 246, in post_validate
    super(Task, self).post_validate(templar)
  File "/etc/ansible/lib/ansible/playbook/base.py", line 317, in post_validate
    value = templar.template(getattr(self, name))
  File "/etc/ansible/lib/ansible/template/__init__.py", line 358, in template
    d[k] = self.template(variable[k], preserve_trailing_newlines=preserve_trailing_newlines, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/etc/ansible/lib/ansible/template/__init__.py", line 330, in template
    result = self._do_template(variable, preserve_trailing_newlines=preserve_trailing_newlines, escape_backslashes=escape_backslashes, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/etc/ansible/lib/ansible/template/__init__.py", line 494, in _do_template
    res = j2_concat(rf)
  File "<template>", line 9, in root
  File "/usr/local/lib/python2.7/dist-packages/jinja2/runtime.py", line 196, in call
    return __obj(*args, **kwargs)
  File "/etc/ansible/lib/ansible/template/__init__.py", line 415, in _lookup
    ran = instance.run(loop_terms, variables=self._available_variables, **kwargs)
  File "/etc/ansible/lib/ansible/plugins/lookup/file.py", line 47, in run
    lookupfile = self._loader.path_dwim_relative(basedir, 'files', term)
  File "/etc/ansible/lib/ansible/parsing/dataloader.py", line 236, in path_dwim_relative
    if source.startswith('~') or source.startswith('/'):
AttributeError: 'list' object has no attribute 'startswith'

fatal: [test-host]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

**Comment by krzysztof-magosa** [comment]
Could you show me exact copy of your code?

**Comment by pashpashka** [comment]
@krzysztof-magosa 

```
 name: Set authorized key for users
  authorized_key:
    user="{{ item.name }}"
    state="{{ item.state }}"
    key="{{ lookup('file', item.authorized) }}"
  when: item.state == "present"
  with_items: "{{ users }}"
  tags:
    - users
```

vars:

```
users:
  - name: testuser
    comment: Test
    state: present
    shell: /bin/bash
    groups: sudo
    authorized:
      - keys/testuser.pub
```

**Comment by asimayub** [comment]
Any update on this issue, I am getting the same error for Ansible 2.2

**Comment by krzysztof-magosa** [comment]
You've specified `authorized` as a list while you use it later in lookup `file` which expects ONE filename. You would need to use `with_subelements` to cover user with all belonging keys.

**Comment by pashpashka** [comment]
Hello. I've fixed this issue with this configuration:

```
- name: Set authorized key for users
  authorized_key:
    user="{{ item.name }}"
    state="{{ item.state }}"
    key="{{ item.authorized }}"
  with_items: "{{ users }}"
  when: item.state == "present"
  tags:
    - users
```

As you can see I've deleted lookup section in "key" assignment. Vars looks like in my previous reply.

**Comment by ansibot** [comment]
@diarworld Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibotdev** [comment]
@diarworld You have not responded to information requests in this issue so we will assume it no longer affects you. If you are still interested in this, please create a new issue with the requested information.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)
