### ISSUE TITLE
fatal: [node1]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute u'Core'"}

### ISSUE THREAD

**Issue by gaurav-dalvi** [ansible/ansible#18475]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
NA

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /home/admin/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
centos 7.2

##### SUMMARY
Earlier till version 2.1.2.0 never faced this problem. Now Once I upgrade to 2.2.0 I am facing this problem.

##### STEPS TO REPRODUCE

```
- name: add docker's public key for CS-engine (debian)
  apt_key:
    url: "https://sks-keyservers.net/pks/lookup?op=get&search=0xee6d536cf7dc86e2d7d56f59a178ac6c6238f52e"
    state: present
    validate_certs: "{{ validate_certs }}"

- name: add docker CS-engine repos (debian)
  apt_repository:
    repo: "deb https://packages.docker.com/{{ item }}/apt/repo ubuntu-{{ ansible_distribution_release }} main"
    state: present
  with_items: "{{ docker_cs_engine_supported_versions_ubuntu[ansible_distribution_release] }}"
```

Though I am running this playbook on Centos 7 still this is getting executed.
First task above gets skipped successfully but for second task it gives following error.

```
TASK [docker : add docker's public key for CS-engine (debian)] *****************
skipping: [node1]
skipping: [node2]

TASK [docker : add docker CS-engine repos (debian)] ****************************
fatal: [node1]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute u'Core'"}
fatal: [node2]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute u'Core'"}
	to retry, use: --limit @/home/admin/ansible/site.retry

PLAY RECAP *********************************************************************
node1                      : ok=7    changed=1    unreachable=0    failed=1
node2                      : ok=7    changed=1    unreachable=0    failed=1
```

**Comment by alikins** [comment]
Could you include the output when running with the '-vvv' verbose arguments?

What does the 'docker_cs_engine_supported_versions_ubuntu' dict look like? Where is the 'Core' coming from?

**Comment by gaurav-dalvi** [comment]
the playbook which I have mentioned is open source. Here is the link : https://github.com/contiv/ansible/blob/master/roles/docker/tasks/ubuntu_install_tasks.yml

There is nothing like Core in the playbook. Fact is this was working till 2.1.2.0 and when I install ansible 2.2.0 I get this error.

**Comment by cbrinley** [comment]
I am seeing this same issue on Ansible 2.2

we have a dict:



```
service_settings:
  api_gateway_routes:
    - data
```

In some runs for some services this key `api_gateway_routes` is optional and i attempt to test for this which worked on ansible 2.0.0.2

```
- name: install gateway routes if defined
  include: workflows/api-gateway/routes/add.yml
  when: "{{service_settings.api_gateway_routes is defined}}"
```

The `is defined` test seems is exposing a new behavior in this version of ansible vs previous
When the dict does not have this key the below error is raised:

`
FAILED! => {"failed": true, "msg": "'dict object' has no attribute 'api_gateway_routes'"}
`

This test previously worked. If the key was not defined that task was simply skipped which is the desired outcome.

**Comment by gaurav-dalvi** [comment]
You can find temp fix to get away with this problem here. Dont know when official fix from ansible will come.

https://github.com/contiv/ansible/pull/275/files#diff-f372832910642da41ad5d12b67c408efR14

**Comment by Akasurde** [comment]
@gaurav-dalvi Could you please re-try on latest Ansible and let us know if it works for you ?

needs_info

**Comment by ansibot** [comment]
@gaurav-dalvi This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@gaurav-dalvi This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@gaurav-dalvi You have not responded to information requests in this issue so we will assume it no longer affects you. If you are still interested in this, please create a new issue with the requested information.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)
