### ISSUE TITLE
The apt module won't work with python-apt < 0.8.9 (such as on Ubuntu 10.04). Workaround/fix included.

### ISSUE THREAD

**Issue by azertyfun** [ansible/ansible#47277]
##### SUMMARY

When attempting to deploy a *.deb file on an old debian-based system, the latest version of ansible will fail with the following message (on the latest version):

```
FAILED! => {"changed": false, "msg": "Unable to install package: 'module' object has no attribute 'get_architectures'"}
```

This has already been reported in #31471.

However, fixing that will only throw another error (that affects older versions before the architecture check was added):

```
FAILED! => {"changed": false, "msg": "Unable to install package: argument of type 'NoneType' is not iterable"}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
apt

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/nathan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.0 (default, Sep 15 2018, 19:13:07) [GCC 8.2.1 20180831]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

* Target OS versions: Ubuntu 10.04

##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  tasks:
    - name: "Copy test package"
      copy:
        src: "your-package.deb"
        dest: "/tmp/your-package.deb"

    - name: "Install test package"
      apt:
        deb: "/tmp/your-package.deb"
        state: present
```

##### EXPECTED RESULTS

The *.deb file gets installed on the target machine.

##### ACTUAL RESULTS

The install fails as described above.

```paste below
[REDACTED]> (0, b'', b'OpenSSH_7.8p1, OpenSSL 1.1.1  11 Sep 2018\r\ndebug1: Reading configuration data /home/nathan/.ssh/config\r\ndebug1: /home/nathan/.ssh/config line 1: Applying options for *.[REDACTED].com\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 5 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 1078\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_apt_payload_v0ns8x/__main__.py", line 625, in install_deb
    if len(apt_pkg.get_architectures()) > 1:

fatal: [<REDACTED>]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_unauthenticated": false,
            "autoclean": false,
            "autoremove": false,
            "cache_valid_time": 0,
            "deb": "/tmp/<your package>.deb",
            "default_release": null,
            "dpkg_options": "force-confdef,force-confold",
            "force": false,
            "force_apt_get": false,
            "install_recommends": null,
            "only_upgrade": false,
            "package": null,
            "purge": false,
            "state": "present",
            "update_cache": null,
            "upgrade": null
        }
    },
    "msg": "Unable to install package: 'module' object has no attribute 'get_architectures'"
}
```

#### Workaround

The first error can be worked around by using `hasattr()`:
```Python
            if hasattr(apt_pkg, 'get_architectures') and len(apt_pkg.get_architectures()) > 1:
                pkg_arch = get_field_of_deb(m, deb_file, "Architecture")
                pkg_key = "%s:%s" % (pkg_name, pkg_arch)
            else:
                pkg_key = pkg_name
```

The second error can be worked around by providing the `cache` argument (which is [never set if `None` in older versions of python-apt](https://github.com/mvo5/python-apt/commit/dd86db9ddb22b43867b5b4dc211f4440dec7aa6a)):

```
            pkg = apt.debfile.DebPackage(deb_file, cache=apt.Cache())
```

---

If the bug affects you, you can copy the [apt.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/apt.py) file in a `module/` folder next to your playbook, apply these workarounds to it, rename the module to something else and use it using `-M ./modules`.

**Comment by ansibot** [comment]
Hi @azertyfun, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/packaging/os/apt.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/apt.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @mgwilliams
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/apt.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/apt.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)
