### PR TITLE
Updates to Ansible command options

### PR DESCRIPTION
**Pull request by jlund**
- Moved the --list-hosts option that is common to both `ansible` and
  `ansible-playbook` into utils/**init**.py (corrects a FIXME)
- Wrote new help text for the --list-hosts option that makes sense
  for both of the commands that it applies to
- Changed the usage argument in `ansible-playbook` so that it is
  setup in the base_parser method the same way that it is in
  the `ansible` executable
- Updated the help text for several options to correct typos,
  clarify meaning, improve readability, or fix grammatical errors.
  In the case of `ansible-pull`, I changed the help text so that
  it adheres to the same standards as the other executables.

This pull request is similar to #3346, but omits the alphabetization modifications.

### CODE REVIEW

**Comment by mpdehaan** [comment]
merged in, thanks for restructuring this!

**Comment by danslimmon** [comment]
This broke argument handling (on OS X 10.8.3 at least). I get this error on 25aaee4:

```
$ python bin/ansible --inventory plugins/inventory/linode.py --user danslimmon --forks 10 --sudo --ask-sudo-pass all -a "ls /tmp"
Traceback (most recent call last):
  File "bin/ansible", line 154, in <module>
    (runner, results) = cli.run(options, args)
  File "bin/ansible", line 87, in run
    if options.listhosts:
AttributeError: Values instance has no attribute 'listhosts'
```

Git bisect determined that dc984d9 (included in this pull request) is where that error started occurring. I'll submit a pull request to fix the bug if no one beats me to it.

EDIT: On second thought, I'll let one of you guys figure out how you want to address this (and if you can reproduce it). I'm not sure what the best solution is.

**Comment by jlund** [comment]
I am unable to reproduce using that exact command on several Linux variants. I'll get my hands on an OS X machine and take a look.

**Comment by danslimmon** [comment]
My Python version is 2.7.2, incidentally. Odd that you can't reproduce it. Maybe I should dig in and try to understand the issue better.

**Comment by jlund** [comment]
OK, I just set things up on an OS X 10.8.3 machine that is using the system Python 2.7.2 interpreter, and this command worked perfectly on the throwaway Digital Ocean server that I started.

```
$ python bin/ansible --inventory ~/inventory --user root --forks 1 --sudo --ask-sudo-pass all -a "ls /tmp"
sudo password: 
192.241.195.164 | success | rc=0 >>
```

What is happening inside your plugins/inventory/linode.py file? As you can see, I was just using a static file for the test inventory. I'm wondering if that's the difference?

**Comment by mpdehaan** [comment]
When you say broke, can you paste _HOW_ it broke?

Thanks!

**Comment by danslimmon** [comment]
jlund: Very strange. I will look into the problem and try to understand what's going on. But before dc984d9 the linode plugin works fine for me, so I don't think it's _entirely_ a plugin bug

mpdehaan: I pasted a stacktrace in https://github.com/ansible/ansible/pull/3356#issuecomment-20306957 -- do you want more info than that? Anyway, I'm going to look into the problem myself since jlund can't reproduce it, and see what I find.

**Comment by danslimmon** [comment]
It breaks in the same way even with a trivial /etc/ansible/hosts in place and a trivial command:

```
$ cat /etc/ansible/hosts
[boo]
        whatever
$ python bin/ansible all -a "/bin/true"
Traceback (most recent call last):
  File "bin/ansible", line 156, in <module>
    (runner, results) = cli.run(options, args)
  File "bin/ansible", line 89, in run
    if options.listhosts:
AttributeError: Values instance has no attribute 'listhosts'
```

Still investigating...

EDIT: this was on 25aaee

**Comment by danslimmon** [comment]
Oh no -- I forgot to export PYTHONPATH=./lib, so "import ansible" was pulling in the gem instead of my working copy.

http://i.imgur.com/khPvZMl.gif

Sorry. Carry on.

**Comment by jlund** [comment]
Phew! That's good news :)

**Comment by mpdehaan** [comment]
Glad to hear it!
