### ISSUE TITLE
[vmware_guest] After deploy VM network is unknown

### ISSUE THREAD

**Issue by cavamagie** [ansible/ansible#36835]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

vmware_guest
when deployng a machine from template

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### CONFIGURATION
ansible-config dump --only-changed --no change

##### OS / ENVIRONMENT
debian 8.8

##### SUMMARY
i use vmware_guest
when i try to deploy a machine from template and use a not vswitch i receive the error in vmware:
"A specified parameter was not correct: spec.deviceChenge.device.port.switch.Uuid
"msg": "A specified parameter was not correct: spec.deviceChange.device.port.switchUuid"}

##### STEPS TO REPRODUCE
simply deploy a machien from template

```yaml
- name: create a VM from a template
  block:
  - vmware_guest:
      hostname: "{{vmware_hostname}}"
      username: "{{vmware_username}}"
      password: "{{vmware_password}}"
      datacenter: "{{vmware_datacenter}}"
      #cluster: "{{vmware_cluster}}"
      esxi_hostname: "{{vmware_esxi_hostname}}"
      validate_certs: no
      name: "{{vmware_machine_name}}"
      state: poweredon
      template: "{{vmware_machine_template}}"
      disk: "{{vmware_machine_size.disks}}"
      hardware:
        memory_gb: "{{vmware_machine_size.ram}}"
        num_cpus: "{{vmware_machine_size.cpu}}"
        scsi: paravirtual
      networks:
      - name: "{{vmware_machine_network}}"
        device_type: vmxnet3
        ip: "{{vmware_machine_ip}}"
        netmask: "{{vmware_machine_net.netmask}}"
        gateway: "{{vmware_machine_net.gateway}}"
      wait_for_ip_address: yes
    delegate_to: localhost
    register: deploy

```

##### EXPECTED RESULTS
deploy a machinei with vds switch

##### ACTUAL RESULTS
work on ly with VM Network
```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)
* [lib/ansible/modules/files/template.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/template.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @akasurde @dagwieers @dav1x @jctanner @nerzhul @pdellaert
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@cavamagie Thanks for reporting. Could you please retry using Ansible 2.5.0rc1 ?

needs_info

**Comment by cavamagie** [comment]
no fail
"msg": "Failed to create a virtual machine : A specified parameter was not correct: spec.deviceChange.device.port.switchUuid"


using 
ansible 2.6.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]


installed with
 pip install git+https://github.com/ansible/ansible.git@devel

**Comment by Akasurde** [comment]
@cavamagie Could you please run following script with appropriate values ? 

```python
from pyVim.connect import SmartConnect, Disconnect
import ssl
import atexit
from pyVmomi import vim

def connect(hostname, username, password):
    context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
    context.verify_mode = ssl.CERT_NONE

    si = SmartConnect(host=hostname, user=username, pwd=password, port=443, sslContext=context)
    atexit.register(Disconnect, si)
    content = si.RetrieveContent()
    return content

def get_obj(content, vimtype, name=None):
    """
    Return an object by name, if name is None the
    first found object is returned
    """
    obj = None
    if name is None:
        obj = []
    container = content.viewManager.CreateContainerView(
        content.rootFolder, vimtype, True)
    for c in container.view:
        if name:
            if c.name == name:
                obj = c
                break
        else:
            obj.append(c)

    container.Destroy()
    return obj

hostname = '0.0.0.0'
username = 'user'
password = 'pass'
dvportgroup = ''

content = connect(hostname, username, password)

dvpg = get_obj(content, [vim.DistributedVirtualPortgroup], dvportgroup)
if dvpg is None:
    print("%s seems to be non-existing Distributed Virtual Portgroup" % dvportgroup)
else:
    import pdb;pdb.set_trace()
    print("Name of Distributed Virtual Switch: %s" % dvpg.config.distributedVirtualSwitch)
    print("Type of Distributed Virtual Switch: %s" % type(dvpg.config.distributedVirtualSwitch))
    print("UUID of Distributed Virtual Switch: %s" % dvpg.config.distributedVirtualSwitch.uuid)
```

~I suspect that there are two types of DistributedVirtualSwitch -~
~1. `vim.dvs.VmwareDistributedVirtualSwitch`~
~2. `vim.DistributedVirtualSwitch`~

~One returns uuid as '50 25 1d c2 4c 01 04 b1-fb b4 7d 61 05 6d 95 3d' and two return uuid as '185bdc47-0fe8-4130-9014-00a91e8d519b' which is causing this error.~

**Comment by cavamagie** [comment]
i have to pass a  DistributedVirtualSwitch? in the scritp?

   print(dvpg.config.distributedVirtualSwitch)
AttributeError: 'NoneType' object has no attribute 'config'

**Comment by Akasurde** [comment]
@cavamagie No, You need to pass same DVPortgroup that you are passing in Ansible Playbook.

**Comment by cavamagie** [comment]
if i run with

hostname = 'vcenterxxxx'
username = 'xxxxxxx'
password = 'xxxxxxxx'
dvportgroup = '3122_Farm_Intel-2'

i receive


Traceback (most recent call last):
  File "chec-git.py", line 44, in <module>
    print(dvpg.config.distributedVirtualSwitch)
AttributeError: 'NoneType' object has no attribute 'config'

**Comment by Akasurde** [comment]
@cavamagie Try updated code. Can you confirm if the distributed virtual portgroup exists and if yes, then does it contain the said ESXi host ?

I am able to replicate your issue if I specify a DVPG which does not have ESXi server as host member.

Could you please confirm procedure of creation of DVPG - manual or automated using Ansible ?

**Comment by cavamagie** [comment]
yes exist and contain host provided by the script
return:
3122_Farm_Intel-2 seems to be non-existing Distributed Virtual Portgroup

![image](https://user-images.githubusercontent.com/9657325/36832002-26cc8e34-1d2a-11e8-9e9e-6dc755186184.png)


creation is manual of dvpg

**Comment by Akasurde** [comment]
@cavamagie Are you sure the name of Distributed virtual portgroup is correct ? I can see "rnal-2" at end of DVPG name in given screenshot where as you are specifying `3122_Farm_Intel-2` as DVPG name, which seems to be different to me. 

needs_info

**Comment by cavamagie** [comment]
yes is correct i maskerade the name but are correct
tryed in another vmware cluster and receive the same responce

 seems to be non-existing Distributed Virtual Portgroup

**Comment by Akasurde** [comment]
OK. I am not sure what is happening here.

**Comment by rbicker** [comment]
I am having the same issue and while I was reading this thread, I noticed that @cavamagie seems to have dashes and underlines in the portgroup's name, which is also the case in for me. A shot in the dark, but might this be the reason why the existing portgroup cannot be found?

**Comment by rbicker** [comment]
Hi, I was having the same issue and I found that it is working fine if I provide the "datacenter" parameter:

Your script was working for me, it produced:
```
Name of Distributed Virtual Switch: 'vim.dvs.VmwareDistributedVirtualSwitch:dvs-271'
Type of Distributed Virtual Switch: <class 'pyVmomi.VmomiSupport.vim.dvs.VmwareDistributedVirtualSwitch'>
UUID of Distributed Virtual Switch: 63 07 31 50 7c ae 7e 8c-6a 87 67 6b 46 73 d8 21
```

When invoking the task without a datacenter param:
```json
FAILED! => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "annotation": null, 
            "cdrom": {}, 
            "cluster": null, 
            "customization": {}, 
            "customvalues": [], 
            "datacenter": "ha-datacenter", 
            "disk": [], 
            "esxi_hostname": null, 
            "folder": null, 
            "force": false, 
            "guest_id": null, 
            "hardware": {}, 
            "hostname": "vsarcservvc01.arcserv.local", 
            "is_template": false, 
            "linked_clone": false, 
            "name": null, 
            "name_match": "first", 
            "networks": [
                {
                    "name": "pgtestansiblebug",
                }
            ], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "resource_pool": null, 
            "snapshot_src": null, 
            "state": "present", 
            "state_change_timeout": 0, 
            "template": null, 
            "username": "sa-ansible@arcserv.local", 
            "uuid": "42317886-460a-cdc1-ce1f-aba159923135", 
            "validate_certs": false, 
            "vapp_properties": [], 
            "wait_for_ip_address": false
        }
    }, 
    "msg": "Failed to connect virtual device 'ethernet0'. "
}

```

When invoking the task with a datacenter param:
```json
{
    "changed": true, 
    "instance": {
      "...": "..."
    }, 
    "invocation": {
        "module_args": {
            "annotation": null, 
            "cdrom": {}, 
            "cluster": null, 
            "customization": {}, 
            "customvalues": [], 
            "datacenter": "vdcarc001", 
            "disk": [], 
            "esxi_hostname": null, 
            "folder": null, 
            "force": false, 
            "guest_id": null, 
            "hardware": {}, 
            "hostname": "vsarcservvc01.arcserv.local", 
            "is_template": false, 
            "linked_clone": false, 
            "name": null, 
            "name_match": "first", 
            "networks": [
                {
                    "name": "pgtestansiblebug"
                }
            ], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "resource_pool": null, 
            "snapshot_src": null, 
            "state": "present", 
            "state_change_timeout": 0, 
            "template": null, 
            "username": "sa-ansible@arcserv.local", 
            "uuid": "42317886-460a-cdc1-ce1f-aba159923135", 
            "validate_certs": false, 
            "vapp_properties": [], 
            "wait_for_ip_address": false
        }
    }
}
```

Not sure if this is a bug or not? I find it weird that it finds the virtual machine if I omit the datacenter param but it does not find the dvswitch, I think this is inconsistent. Also it used to work without the param when using older versions of ansible (2.2 I think).

Might be the same issue: #24506

**Comment by Akasurde** [comment]
@rbicker Thanks for providing this information. @cavamagie is providing datacenter parameter and still able to re-produce the issue. This makes it more weird.

BTW, what is your Ansible version ?

**Comment by rbicker** [comment]
@Akasurde yes, also your script is not working for @cavamagie so propably our two issues are not connected, only by the outcome...

ansible --version
ansible 2.6.0

but I also had the issue with 2.4

**Comment by cavamagie** [comment]
i already pass the datacenter value

```
- name: create a VM from a template
  block:
  - vmware_guest:
      hostname: "{{vmware_hostname}}"
      username: "{{vmware_username}}"
      password: "{{vmware_password}}"
      datacenter: "{{vmware_datacenter}}"
      #cluster: "{{vmware_cluster}}"
      esxi_hostname: "{{vmware_esxi_hostname}}"
      validate_certs: no
      name: "{{vmware_machine_name}}"
      state: poweredon
      template: "{{vmware_machine_template}}"
      disk: "{{vmware_machine_size.disks}}"
      hardware:
        memory_gb: "{{vmware_machine_size.ram}}"
        num_cpus: "{{vmware_machine_size.cpu}}"
        scsi: paravirtual
      networks:
      - name: "{{vmware_machine_network}}"
        device_type: vmxnet3
        ip: "{{vmware_machine_ip}}"
        netmask: "{{vmware_machine_net.netmask}}"
        gateway: "{{vmware_machine_net.gateway}}"
      wait_for_ip_address: yes
    delegate_to: localhost
    register: deploy
```

**Comment by Akasurde** [comment]
!component -lib/ansible/modules/files/template.py

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by cavamagie** [comment]
any news?

**Comment by frntn** [comment]
I had the same issue. Now solved.

The following article https://kb.vmware.com/s/article/2073803 says :
> Note: To allow customization of Linux virtual machines with open-vm-tools version lower than 9.10, the deployPkg plug-in needs to be installed. For more information, see Installing the deployPkg plug-in in a Linux virtual machine with Open VM Tools version lower than 9.10 (2075048).

Checking my VMWare Tools setup I noticed I was actually in that configuration : 
```$ vmware-toolbox-cmd -v
9.4.0.25793 (build-1280544)
```

So I have followed the instructions https://kb.vmware.com/s/article/2075048 which basically sums up in this snippets while building my template using packer : 
```
# (Run as root)
OVM_TOOLS_VERSION=$(vmware-toolbox-cmd -v | cut -f1,2 -d'.')
VERSION_CODENAME=$(lsb_release -c | awk '{print $2}')
if echo "$OVM_TOOLS_VERSION < 9.10" | bc -lq >/dev/null; then
    echo "==> Installing deployPkg plugin"
    wget -qO - https://packages.vmware.com/tools/keys/VMWARE-PACKAGING-GPG-RSA-KEY.pub | sudo apt-key add -
    echo "deb https://packages.vmware.com/packages/ubuntu $VERSION_CODENAME main" > "/etc/apt/sources.list.d/vmware-tools.list"
    apt-get update
    apt-get install -y open-vm-tools-deploypkg
fi
```

Eventually my VM now powers up with `connected` interface ✔️

**Comment by ansibot** [comment]
cc @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by cavamagie** [comment]
but i have the problem with 10240 (10.0.0)

**Comment by cavamagie** [comment]
now i receive
A specified parameter was not correct: spec.deviceChange.device.port.switchUuid
Host pippo.host is not a member of VDS 02_dvs_01

**Comment by ansibot** [comment]
cc @ckotte
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by marcobellaccini** [comment]
I think this can now be solved by using the *dvswitch_name* parameter introduced by https://github.com/ansible/ansible/pull/41899

**Comment by jctanner** [comment]
@cavamagie please confirm @marcobellaccini 's comment.

needs_info

**Comment by ansibot** [comment]
@cavamagie This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Tomorrow9 @lparkes
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@cavamagie You have not responded to information requests in this issue so we will assume it no longer affects you. If you are still interested in this, please create a new issue with the requested information.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)
