### ISSUE TITLE
Regression in Ansible 2.2 using raw / endraw jinja tags and GO templates.

### ISSUE THREAD

**Issue by skyscooby** [ansible/ansible#20568]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

shell module with {% raw %} tags

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A (CentOS 7.2 shouldn't be platform specific)

##### SUMMARY

This is quite meta .. but I will try and explain.

We use the ansible shell command to run some commands against docker hosts which uses dockers --format feature that feature relies on GO template engine. Naturally we see conflicting behaviour here due to both jinja2 and go using '{{' as delimeters. AFAIK neither of these tools currently support switching delimeters but I may be wrong as that would be one way we could work around this..

We pass a {% raw %}{% endraw %} wrapped go template to a shell module calling docker like:
```
  - name: Count running images to check if down scaling is necessary
    shell:
      "docker ps -a --no-trunc --filter name=^/{{artifact.namespace}}-{{ artifact.name }} --format='{% raw %}{{.ID}},{{.Image}}{% endraw %}' | wc -l"
    register: docker_container_count

  - name: Debug the count
    debug:
      msg: "{{ docker_container_count }}" 
```
The command executes successfully in both Ansible 2.1.1.0 and Ansible 2.2.1.0 
**however**
The internal representation 'cmd' key representing the original command was stored using the jinja tags as '{#'  and now it is being stored verbatim like '{{'. This is causing any further usage of this registered variable to fail as jinja is trying to parse the 'cmd' string.

debug output before upgrade (v2.1.1.0):
```
16:33:28 TASK [microservices : Debug the count] *************************
16:33:28 ok: [hostname.company.org] => {
16:33:28     "msg": {
16:33:28         "changed": true, 
16:33:28         "cmd": "docker ps -a --no-trunc --filter name=^/edge-server--account-service --format='{#.ID#},{#.Image#}' | wc -l", 
16:33:28         "delta": "0:00:00.025972", 
16:33:28         "end": "2017-01-23 16:33:27.970780", 
16:33:28         "rc": 0, 
16:33:28         "start": "2017-01-23 16:33:27.944808", 
16:33:28         "stderr": "", 
16:33:28         "stdout": "1", 
16:33:28         "stdout_lines": [
16:33:28             "1"
16:33:28         ], 
16:33:28         "warnings": []
16:33:28     }
16:33:28 }
16:33:28 
```
debug output after upgrade (v2.2.1.0):
```
16:07:24 TASK [microservices : Debug the count] ***********************************
16:07:24 fatal: [hostname.company.org]: FAILED! => 
{"failed": true, 
   "msg": "{
     u'cmd': u\"docker ps -a --no-trunc --filter name=^/edge-server--account-service --format='{{.ID}},{{.Image}}' | wc -l\", 
     u'end': u'2017-01-23 16:07:24.798553', 
     u'stdout': u'1', 
     u'changed': True, 
     u'start': u'2017-01-23 16:07:24.763174', 
     u'delta': u'0:00:00.035379', 
     u'stderr': u'', 
     u'rc': 0, 
     'stdout_lines': [u'1'], 
     u'warnings': []}: 
  template error while templating string: unexpected '.'. String: docker ps -a --no-trunc --filter name=^/edge-server--account-service --format='{{.ID}},{{.Image}}' | wc -l"
}
16:07:24 	to retry, use: --limit @/home/jenkins/workspace/DeploymentFolder/DeployEdgeServer/rolling_deployment.retry
16:07:24 
```

**Comment by ravishivt** [comment]
This doesn't just affect {%raw%} {%endraw%}.  It affects all of the following variants of escaping:

```
- name: Get the Heketi Server Endpoint
  # shell: kubectl get svc/heketi --template "http://{{ '{{' }}.spec.clusterIP{{ '}}' }}:{{ '{{' }}(index .spec.ports 0).port{{ '}}' }}"
  # shell: kubectl get svc/heketi --template {%raw%} 'http://{{.spec.clusterIP}}:{{(index .spec.ports 0).port}}' {%endraw%}
  # shell: kubectl get svc/heketi --template {{ '"http://{{.spec.clusterIP}}:{{(index .spec.ports 0).port}}"' }}
  register: heketi_endpoint
```

Using any of these works on 2.1.4 but not on 2.2.x.

**Comment by maximbaele** [comment]
Noticing the same issue, also on ansible 2.2.1.0
It does seem to work when deploying a template, but not when used in a task directly.

I have a template (bash script) containing an escaped string:
`rm -f {{ '{{' }} item.repo {{ '}}' }}`

This template deploys successfully, escaping works and nothing fails.
This is the task set I use. The second task restarts some services, if a revised or new template has been deployed. 

`- name: create vcs templates
  template: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items: '{{ vcs_templates }}'
  register: vcs_config
`
`- name: restart vcs services if needed
  service: "name={{ item.name }} state=restarted"
  with_items: '{{ vcs_services }}'
  when: vcs_config.changed
`

The second step fails;
`
fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "The conditional check 'vcs_config.changed' failed. The error was: error while evaluating conditional (vcs_config.changed)
(...)
'dict object' has no attribute 'repo'
(...)
`

**Comment by ravishivt** [comment]
@Maximus86 Same, the task that uses the template succeeds but the subsequent task fails with the same error message you reported.

**Comment by booch** [comment]
Having the same problem with Ansible 2.2.1 and Jinja2 2.9.5.
NOT having the problem if we roll back to Ansible 2.2.0.

**Comment by jimi-c** [comment]
Bisected to bcceada5d9b78ad77069c78226f8e9b336ff8949, trying to figure out why...

**Comment by jimi-c** [comment]
Closing This Ticket
===================

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by alexanderadam** [comment]
I'm not quite sure whether it is the same issue or not but I'm trying to copy a go template to a host and I'm getting the `template error while templating string` error as well.

The Ansible version I'm using is `2.5.1`.

This is the task

```yml
- name: 'copy head.tmpl'
  template:
    src: ../templates/head.tmpl
    dest: "/some/path/data/gitea/templates/head.tmpl"
```

and [this is the file](https://raw.githubusercontent.com/go-gitea/gitea/master/templates/base/head.tmpl) I'm trying to copy.
