### ISSUE TITLE
MODULE FAILURE module vmware_guest  2.4.0 

### ISSUE THREAD

**Issue by mainjoehere** [ansible/ansible#29043]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

module vmware_guest 

##### ANSIBLE VERSION

```
ansible-playbook 2.4.0 (devel d8649adf10) last updated 2017/09/05 14:40:47 (GMT +200)
```

##### OS / ENVIRONMENT

OS SLES VERSION="12-SP2"

##### SUMMARY

module not working 

##### STEPS TO REPRODUCE

```yaml
#- name: create vm with ansible
- hosts: localhost
  connection: local
  tasks:

  - name: create the vm
    vmware_guest:
      hostname: {{hostname}}
      username: {{username}}
      password: {{password}}
      validate_certs: no

      name: lxyomat
      datacenter: N_SW100_01
      cluster: CL-N-SW100-02(Linux)
      folder: /Linux/Test
      guest_id: centos64guest

      state: present
      disk:
        - size_gb: 30
          type: thin
          datastore: LUN_138_CL-N-SW100-02_G
      hardware:
        memory_mb: 512
        num_cpus: 1

```

##### EXPECTED RESULTS

vm created 
This is working with ansible-2.3.2.0 
##### ACTUAL RESULTS

```
TASK [create the vm] ******************************************************************************************************************************
task path: /home/e003120/t1.yml:9
Using module file //home/e003120/ansible/ansible/lib/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: e003120
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/e003120/.ansible/tmp/ansible-tmp-1504707292.19-259378902513195 `" && echo ansible-tmp-1504707292.19-259378902513195="` echo /home/e003120/.ansible/tmp/ansible-tmp-1504707292.19-259378902513195 `" ) && sleep 0'
<localhost> PUT /tmp/tmpDCLzu5 TO /home/e003120/.ansible/tmp/ansible-tmp-1504707292.19-259378902513195/vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/e003120/.ansible/tmp/ansible-tmp-1504707292.19-259378902513195/ /home/e003120/.ansible/tmp/ansible-tmp-1504707292.19-259378902513195/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/e003120/.ansible/tmp/ansible-tmp-1504707292.19-259378902513195/vmware_guest.py; rm -rf "/home/e003120/.ansible/tmp/ansible-tmp-1504707292.19-259378902513195/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_FAqrhr/ansible_module_vmware_guest.py", line 1503, in <module>
    main()
  File "/tmp/ansible_FAqrhr/ansible_module_vmware_guest.py", line 1494, in main
    result = pyv.deploy_vm()
  File "/tmp/ansible_FAqrhr/ansible_module_vmware_guest.py", line 1189, in deploy_vm
    dcpath = compile_folder_path_for_object(datacenter)
  File "/tmp/ansible_FAqrhr/ansible_modlib.zip/ansible/module_utils/vmware.py", line 237, in compile_folder_path_for_object
AttributeError: 'NoneType' object has no attribute 'name'

fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_FAqrhr/ansible_module_vmware_guest.py\", line 1503, in <module>\n    main()\n  File \"/tmp/ansible_FAqrhr/ansible_module_vmware_guest.py\", line 1494, in main\n    result = pyv.deploy_vm()\n  File \"/tmp/ansible_FAqrhr/ansible_module_vmware_guest.py\", line 1189, in deploy_vm\n    dcpath = compile_folder_path_for_object(datacenter)\n  File \"/tmp/ansible_FAqrhr/ansible_modlib.zip/ansible/module_utils/vmware.py\", line 237, in compile_folder_path_for_object\nAttributeError: 'NoneType' object has no attribute 'name'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}



```

**Comment by mainjoehere** [comment]
This is working with ansible-2.3.2.0

**Comment by ansibot** [comment]
cc @akasurde @dagwieers @dav1x @jctanner @nerzhul
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jctanner** [comment]
@mainjoehere The traceback implies the datacenter was not found (we could definitely make that error more clear).

Could you run this script so that we can see what datacenter names are available?
https://github.com/jctanner/ansible-tools/blob/master/vmware/vmware_walk.py

needs_info

**Comment by mainjoehere** [comment]
@jctanner Here is the output
 ```
/[ServiceInstanceContent]Content/['vim.Folder:group-d1']Datencenter/['vim.Datacenter:datacenter-232']M_LE_01/['vim.Folder:group-v233']vm/['vim.Folder:group-v265']VMWare
/[ServiceInstanceContent]Content/['vim.Folder:group-d1']Datencenter/['vim.Datacenter:datacenter-303']N_SW100_01/['vim.Folder:group-h305']host/['vim.ClusterComputeResource:domain-c328']CL-N-SW100-07(Citrix II)/['vim.HostSystem:host-2256']vmesx954p.vkbads.de/['vim.VirtualMachine:vm-2431']V-VM-W8-INV-06
/[ServiceInstanceContent]Content/['vim.Folder:group-d1']Datencenter/['vim.Datacenter:datacenter-303']N_SW100_01/['vim.Folder:group-h305']host/['vim.ClusterComputeResource:domain-c328']CL-N-SW100-07(Citrix II)/['vim.HostSystem:host-2282']vmesx940p.vkbads.de/['vim.VirtualMachine:vm-2369']V-VM-W8-INV-12
/[ServiceInstanceContent]Content/['vim.Folder:group-d1']Datencenter/['vim.Datacenter:datacenter-303']N_SW100_01/['vim.Folder:group-h305']host/['vim.ClusterComputeResource:domain-c328']CL-N-SW100-07(Citrix II)/['vim.HostSystem:host-2290']vmesx941p.vkbads.de/['vim.VirtualMachine:vm-2331']V-VM-W8-INV-14
/[ServiceInstanceContent]Content/['vim.Folder:group-d1']Datencenter/['vim.Datacenter:datacenter-303']N_SW100_01/['vim.Folder:group-h305']host/['vim.ClusterComputeResource:domain-c328']CL-N-SW100-07(Citrix II)/['vim.HostSystem:host-2307']vmesx943p.vkbads.de/['vim.VirtualMachine:vm-2285']V-VM-W8-INV-18
/[ServiceInstanceContent]Content/['vim.Folder:group-d1']Datencenter/['vim.Datacenter:datacenter-303']N_SW100_01/['vim.Folder:group-h305']host/['vim.ClusterComputeResource:domain-c328']CL-N-SW100-07(Citrix II)/['vim.HostSystem:host-2314']vmesx942p.vkbads.de/['vim.VirtualMachine:vm-2442']V-VM-W8-INV-16
/[ServiceInstanceContent]Content/['vim.Folder:group-d1']Datencenter/['vim.Datacenter:datacenter-303']N_SW100_01/['vim.Folder:group-h305']host/['vim.ClusterComputeResource:domain-c328']CL-N-SW100-07(Citrix II)/['vim.HostSystem:host-2323']vmesx939p.vkbads.de/['vim.VirtualMachine:vm-2388']V-VM-W8-INV-10
/[ServiceInstanceContent]Content/['vim.Folder:group-d1']Datencenter/['vim.Datacenter:datacenter-303']N_SW100_01/['vim.Folder:group-h305']host/['vim.ClusterComputeResource:domain-c328']CL-N-SW100-07(Citrix II)/['vim.HostSystem:host-2334']vmesx946p.vkbads.de/['vim.VirtualMachine:vm-8469']V-VM-W8-INV-34
/[ServiceInstanceContent]Content/['vim.Folder:group-d1']Datencenter/['vim.Datacenter:datacenter-303']N_SW100_01/['vim.Folder:group-h305']host/['vim.ClusterComputeResource:domain-c328']CL-N-SW100-07(Citrix II)/['vim.HostSystem:host-2334']vmesx946p.vkbads.de/['vim.VirtualMachine:vm-2356']V-VM-W8-INV-24
/[ServiceInstanceContent]Content/['vim.Folder:group-d1']Datencenter/['vim.Datacenter:datacenter-303']N_SW100_01/['vim.Folder:group-h305']host/['vim.ClusterComputeResource:domain-c328']CL-N-SW100-07(Citrix II)/['vim.HostSystem:host-2348']vmesx945p.vkbads.de/['vim.VirtualMachine:vm-2274']V-VM-W8-INV-22

```

**Comment by jctanner** [comment]
@mainjoehere are you able to test this patch?

```diff
diff --git a/lib/ansible/module_utils/vmware.py b/lib/ansible/module_utils/vmware.py
index f76ab91eca..4100588bac 100644
--- a/lib/ansible/module_utils/vmware.py
+++ b/lib/ansible/module_utils/vmware.py
@@ -237,7 +237,8 @@ def compile_folder_path_for_object(vobj):
         if thisobj.name == 'Datacenters':
             break
         if isinstance(thisobj, vim.Folder):
-            paths.append(thisobj.name)
+            if hasattr(thisobj, 'name'):
+                paths.append(thisobj.name)
     paths.reverse()
     return '/' + '/'.join(paths)
```

needs_info

**Comment by mainjoehere** [comment]
```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_c7H0x9/ansible_module_vmware_guest.py", line 1503, in <module>
    main()
  File "/tmp/ansible_c7H0x9/ansible_module_vmware_guest.py", line 1494, in main
    result = pyv.deploy_vm()
  File "/tmp/ansible_c7H0x9/ansible_module_vmware_guest.py", line 1189, in deploy_vm
    dcpath = compile_folder_path_for_object(datacenter)
  File "/tmp/ansible_c7H0x9/ansible_modlib.zip/ansible/module_utils/vmware.py", line 237, in compile_folder_path_for_object
AttributeError: 'NoneType' object has no attribute 'name'

fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_c7H0x9/ansible_module_vmware_guest.py\", line 1503, in <module>\n    main()\n  File \"/tmp/ansible_c7H0x9/ansible_module_vmware_guest.py\", line 1494, in main\n    result = pyv.deploy_vm()\n  File \"/tmp/ansible_c7H0x9/ansible_module_vmware_guest.py\", line 1189, in deploy_vm\n    dcpath = compile_folder_path_for_object(datacenter)\n  File \"/tmp/ansible_c7H0x9/ansible_modlib.zip/ansible/module_utils/vmware.py\", line 237, in compile_folder_path_for_object\nAttributeError: 'NoneType' object has no attribute 'name'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}

```

**Comment by jctanner** [comment]
Ah, okay ... let's try this instead:

```diff
diff --git a/lib/ansible/module_utils/vmware.py b/lib/ansible/module_utils/vmware.py
index f76ab91eca..0750919845 100644
--- a/lib/ansible/module_utils/vmware.py
+++ b/lib/ansible/module_utils/vmware.py
@@ -234,6 +234,8 @@ def compile_folder_path_for_object(vobj):
     thisobj = vobj
     while hasattr(thisobj, 'parent'):
         thisobj = thisobj.parent
+        if not hasattr(thisobj, 'name'):
+            break
         if thisobj.name == 'Datacenters':
             break
         if isinstance(thisobj, vim.Folder):
```

needs_info

**Comment by mainjoehere** [comment]
Better, but now the folder is not found.
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cluster": "CL-N-SW100-02(Linux)",
            "customization": {},
            "customvalues": [],
            "datacenter": "N_SW100_01",
            "disk": [
                {
                    "datastore": "LUN_138_CL-N-SW100-02_G",
                    "size_gb": 30,
                    "type": "thin"
                }
            ],
            "esxi_hostname": null,
            "folder": "/Linux/Test",
            "force": false,
            "guest_id": "centos64guest",
            "hardware": {
                "memory_mb": 512,
                "num_cpus": 1
            },
            "hostname": "msvcs81p",
            "is_template": false,
            "linked_clone": false,
            "name": "lxyomat",
            "name_match": "first",
            "networks": [
                {
                    "device_type": "vmxnet3",
                    "vlan": "VLAN0003_VKB_Server_allgemein-CL-02-Linux"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "snapshot_src": null,
            "state": "present",
            "template": null,
            "username": "e003120",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": false
        }
    },
    "msg": "No folder matched the path: /Linux/Test"
}

```

**Comment by jctanner** [comment]
@mainjoehere can you try it with these variations on the folder path?

```
folder: Linux/Test
folder: Test
```

I'm also not seeing "Linux" or "Test" in the output from vmware_walk.py. Does the folder path actually exist?

needs_info

**Comment by mainjoehere** [comment]
tried: 
Linux/Test
Test
vm/Linux/Test
Datencenter/N_SW100_01/vm/Linux/Test
N_SW100_01/vm/Linux/Test

all not working.

your nice walk output would give me something like:
/[ServiceInstanceContent]Content/['vim.Folder:group-d1']Datencenter/['vim.Datacenter:datacenter-303']N_SW100_01/['vim.Folder:group-v304']vm/['vim.Folder:group-v5538']DMZ/['vim.Folder:group-v5539']Linux/['vim.Folder:group-v5546']Test/['vim.VirtualMachine:vm-6411']lxprx402t

**Comment by Akasurde** [comment]
I think you are missing DMZ folder here, try 

```
Datencenter/N_SW100_01/vm/DMZ/Linux/Test
```

**Comment by mainjoehere** [comment]
Ah sorry I pasted the wrong line, it's like this:
/[ServiceInstanceContent]Content/['vim.Folder:group-d1']Datencenter/['vim.Datacenter:datacenter-303']N_SW100_01/['vim.Folder:group-v304']vm/['vim.Folder:group-v376']Linux/['vim.Folder:group-v382']Test/['vim.VirtualMachine:vm-5199']apmas502t

![grafik](https://user-images.githubusercontent.com/31688191/30121417-e37f813c-932b-11e7-9fd5-919a2a4960eb.png)

**Comment by jctanner** [comment]
What error do you get with this patch applied and using the following folder paths:
```
N_SW100_01/vm/DMZ/Linux/Test
/vm/DMZ/Linux/Test
vm/DMZ/Linux/Test
DMZ/Linux/Test
/Linux/Test
Linux/Test
/Test
Test
```

```diff
diff --git a/lib/ansible/modules/cloud/vmware/vmware_guest.py b/lib/ansible/modules/cloud/vmware/vmware_guest.py
index 35a4aea40f..d457a8fdcc 100644
--- a/lib/ansible/modules/cloud/vmware/vmware_guest.py
+++ b/lib/ansible/modules/cloud/vmware/vmware_guest.py
@@ -1202,7 +1202,8 @@ class PyVmomiHelper(object):

         # abort if no strategy was successful
         if f_obj is None:
-            self.module.fail_json(msg='No folder matched the path: %(folder)s' % self.params)
+            self.params['fullpath'] = fullpath
+            self.module.fail_json(msg='No folder matched the path: %(folder)s searched: %(fullpath)s' % self.params)
         destfolder = f_obj

         if self.params['template']:
```

needs_info

**Comment by dav1x** [comment]
@mainjoehere it may be helpful to take a look at govc. You can use it to determine the full path of any object in vSphere. 

```
govc ls
/Boston/vm
/Boston/network
/Boston/host
/Boston/datastore

govc ls /Boston/vm
/Boston/vm/rhel-atomic-vsphere-7.3.5-4.x86_64.vsphere
/Boston/vm/atomic-vsphere
/Boston/vm/cfme-vsphere-5.8.0.16-1.x86_64.vsphere
/Boston/vm/test-docker
/Boston/vm/rhel-atomic-vsphere-7.4.0-11.x86_64.vsphere
/Boston/vm/test-pemcg
/Boston/vm/ocp36
/Boston/vm/acme-org
/Boston/vm/verizon-poc
/Boston/vm/foo
/Boston/vm/Discovered virtual machine
/Boston/vm/TEST
/Boston/vm/Infrastructure
/Boston/vm/multi-datacenter-OCP
/Boston/vm/templates
/Boston/vm/openvmtools
/Boston/vm/ocp
```

In this case my datacenter is Boston and my top level VM filder is ocp36. But this is the second issue in which there was a nested folder failure. I'll test this on my environment and see what happens.

**Comment by mainjoehere** [comment]
Tried with:
folder: Linux/Test
There is a slash missing : /DatencenterN_SW100_01 between  /Datencenter and N_SW100_01

```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cluster": "CL-N-SW100-02(Linux)",
            "customization": {},
            "customvalues": [],
            "datacenter": "N_SW100_01",
            "disk": [
                {
                    "datastore": "LUN_138_CL-N-SW100-02_G",
                    "size_gb": 30,
                    "type": "thin"
                }
            ],
            "esxi_hostname": null,
            "folder": "/Linux/Test",
            "force": false,
            "fullpath": "/DatencenterN_SW100_01/vm/Linux/Test",
            "guest_id": "centos64guest",
            "hardware": {
                "memory_mb": 512,
                "num_cpus": 1
            },
            "hostname": "msvcs81p",
            "is_template": false,
            "linked_clone": false,
            "name": "lxyomat",
            "name_match": "first",
            "networks": [],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "snapshot_src": null,
            "state": "present",
            "template": null,
            "username": "e003120",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": false
        }
    },
    "msg": "No folder matched the path: /Linux/Test searched: /DatencenterN_SW100_01/vm/Linux/Test"
}

```

**Comment by jctanner** [comment]
@mainjoehere Let's try this one ...

```diff
diff --git a/lib/ansible/modules/cloud/vmware/vmware_guest.py b/lib/ansible/modules/cloud/vmware/vmware_guest.py
index 35a4aea40f..e61d7515f6 100644
--- a/lib/ansible/modules/cloud/vmware/vmware_guest.py
+++ b/lib/ansible/modules/cloud/vmware/vmware_guest.py
@@ -1192,17 +1192,18 @@ class PyVmomiHelper(object):
         if (self.params['folder'].startswith(dcpath + self.params['datacenter'] + '/vm')):
             fullpath = self.params['folder']
         elif (self.params['folder'].startswith('/vm/') or self.params['folder'] == '/vm'):
-            fullpath = "%s%s%s" % (dcpath, self.params['datacenter'], self.params['folder'])
+            fullpath = "%s/%s%s" % (dcpath, self.params['datacenter'], self.params['folder'])
         elif (self.params['folder'].startswith('/')):
-            fullpath = "%s%s/vm%s" % (dcpath, self.params['datacenter'], self.params['folder'])
+            fullpath = "%s/%s/vm%s" % (dcpath, self.params['datacenter'], self.params['folder'])
         else:
-            fullpath = "%s%s/vm/%s" % (dcpath, self.params['datacenter'], self.params['folder'])
+            fullpath = "%s/%s/vm/%s" % (dcpath, self.params['datacenter'], self.params['folder'])

         f_obj = self.content.searchIndex.FindByInventoryPath(fullpath)

         # abort if no strategy was successful
         if f_obj is None:
-            self.module.fail_json(msg='No folder matched the path: %(folder)s' % self.params)
+            self.params['fullpath'] = fullpath
+            self.module.fail_json(msg='No folder matched the path: %(folder)s searched: %(fullpath)s' % self.params)
         destfolder = f_obj

         if self.params['template']:
```

needs_info

**Comment by mainjoehere** [comment]
TASK [create the vm] ***************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "No folder matched the path: /Linux/Test searched: /Datencenter/N_SW100_01/vm/Linux/Test"}

**Comment by jctanner** [comment]
Well that's more correct, even though it didn't find the path. I'll have to spend some time trying to reproduce this locally.

**Comment by jctanner** [comment]
@mainjoehere I've updated the script with a new feature for validating inventory paths.

```
[jctanner@jctanner-jumphost ~]$ ansible-tools/vmware/vmware_walk.py --hostname=XXXX --username=XXXX --password=XXXX --filter='Jimmy Test'  --fuzzytest

... lots of output ...

# valid inputs for findByInventoryPath
['/MNS/vm/RHLabs/Jimmy Test', 'MNS/vm/RHLabs/Jimmy Test']
```

Can you run the latest version with --fuzzytest and --filter="Test" and give us the output?

needs_info

**Comment by mainjoehere** [comment]
Here is the output
[out.txt](https://github.com/ansible/ansible/files/1306334/out.txt)

**Comment by jctanner** [comment]
According to the fuzzer tests, these are the valid inputs to findbyinventorypath ...

```
$ fgrep -A 1000 '# valid ' out.txt  | fgrep 'N_SW100_01' | fgrep -v DMZ | fgrep 'Linux/Test' | sort
 '/N_SW100_01/vm/Linux/Test',
 'N_SW100_01/vm/Linux/Test',
```

That implies the bug here is that "Datencenter" should not be put in the search path we use to find the folder. I'll try to write up a patch.

**Comment by rpasche** [comment]
Have exact same error. But I did come a bit further when I try to create the VM. Seems that we both have a 'german' windows vCenter server. I do not know, why the root datacenter folder is named `Datencenter`. But...after changing this

```
--- vmware.py.orig
+++ vmware.py
@@ -234,7 +234,7 @@
     thisobj = vobj
     while hasattr(thisobj, 'parent'):
         thisobj = thisobj.parent
-        if thisobj.name == 'Datacenters':
+        if thisobj.name == 'Datacenters' or thisobj.name == 'Datencenter':
             break
         if isinstance(thisobj, vim.Folder):
             paths.append(thisobj.name)
```
I get this error

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_FXUloM/ansible_module_vmware_guest.py", line 1503, in <module>
    main()
  File "/tmp/ansible_FXUloM/ansible_module_vmware_guest.py", line 1494, in main
    result = pyv.deploy_vm()
  File "/tmp/ansible_FXUloM/ansible_module_vmware_guest.py", line 1292, in deploy_vm
    task = destfolder.CreateVM_Task(config=self.configspec, pool=resource_pool)
UnboundLocalError: local variable 'resource_pool' referenced before assignment

fatal: [vciks -> localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_FXUloM/ansible_module_vmware_guest.py\", line 1503, in <module>\n    main()\n  File \"/tmp/ansible_FXUloM/ansible_module_vmware_guest.py\", line 1494, in main\n    result = pyv.deploy_vm()\n  File \"/tmp/ansible_FXUloM/ansible_module_vmware_guest.py\", line 1292, in deploy_vm\n    task = destfolder.CreateVM_Task(config=self.configspec, pool=resource_pool)\nUnboundLocalError: local variable 'resource_pool' referenced before assignment\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
````

**Comment by rpasche** [comment]
Ah....at least, specifying

````
resource_pool: Resources
````
after reading https://communities.vmware.com/thread/473617 fixes the problem. It would be better to use this default `Resources` resource pool if there are no resource pools defined within the object this VM is to be created

**Comment by jctanner** [comment]
@mainjoehere can you retest with the latest devel code? I have made a couple of changes over the past week that should have at least improved this situation.

needs_info

**Comment by mainjoehere** [comment]
```
TASK [create the vm] ******************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "clone_method": "CreateVM_Task", "clonespec": {}, "configspec": {"alternateGuestName": null, "annotation": null, "bootOptions": null, "changeTrackingEnabled": null, "changeVersion": null, "consolePreferences": null, "cpuAffinity": null, "cpuAllocation": null, "cpuFeatureMask": [], "cpuHotAddEnabled": 1, "cpuHotRemoveEnabled": null, "crypto": null, "deviceChange": [{"backing": null, "device": "<class 'pyVmomi.VmomiSupport.vim.vm.device.ParaVirtualSCSIController'>", "dynamicProperty": [], "dynamicType": null, "fileOperation": null, "operation": "add", "profile": []}, {"backing": null, "device": {"backing": "<class 'pyVmomi.VmomiSupport.vim.vm.device.VirtualDisk.FlatVer2BackingInfo'>", "capacityInBytes": null, "capacityInKB": 31457280, "connectable": null, "controllerKey": 0, "deviceInfo": null, "diskObjectId": null, "dynamicProperty": [], "dynamicType": null, "iofilter": [], "key": 0, "shares": null, "slotInfo": null, "storageIOAllocation": null, "unitNumber": 0, "vDiskId": null, "vFlashCacheConfigInfo": null}, "dynamicProperty": [], "dynamicType": null, "fileOperation": "create", "operation": "add", "profile": []}], "dynamicProperty": [], "dynamicType": null, "extraConfig": [], "files": "<class 'pyVmomi.VmomiSupport.vim.vm.FileInfo'>", "firmware": null, "flags": null, "ftInfo": null, "guestAutoLockEnabled": null, "guestId": "centos64guest", "instanceUuid": null, "latencySensitivity": null, "locationId": null, "managedBy": null, "maxMksConnections": null, "memoryAffinity": null, "memoryAllocation": null, "memoryHotAddEnabled": 1, "memoryMB": 512, "memoryReservationLockedToMax": null, "messageBusTunnelEnabled": null, "migrateEncryption": null, "name": "lxyomat", "nestedHVEnabled": null, "networkShaper": null, "npivDesiredNodeWwns": null, "npivDesiredPortWwns": null, "npivNodeWorldWideName": [], "npivOnNonRdmDisks": null, "npivPortWorldWideName": [], "npivTemporaryDisabled": null, "npivWorldWideNameOp": null, "npivWorldWideNameType": null, "numCPUs": 1, "numCoresPerSocket": null, "powerOpInfo": null, "repConfig": null, "scheduledHardwareUpgradeInfo": null, "swapPlacement": null, "tools": null, "uuid": null, "vAppConfig": null, "vAppConfigRemoved": null, "vAssertsEnabled": null, "vPMCEnabled": null, "version": null, "virtualICH7MPresent": null, "virtualSMCPresent": null, "vmProfile": []}, "failed": true, "msg": "Eine Komponente der virtuellen Maschine ist auf dem Host nicht zugänglich."}
---
```
```
Ansible Version:
ansible 2.5.0 (devel ba99e44b42) last updated 2017/10/02 05:00:21 (GMT +200)
  config file = /opt/ansible/ansible-data/ansible.cfg
  configured module search path = [u'/home/e003120/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/ansible/lib/ansible
  executable location = /opt/ansible/ansible/bin/ansible
  python version = 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
```
---
With govc I am able to create the vm without any problems and even the vlan is correct:
govc vm.create -dc="N_SW100_01" -ds="LUN_138_CL-N-SW100-02_G"  -pool="CL-N-SW100-02(Linux)/Resources/Test_Systeme" -net="VLAN0805_Bestand_Nprod_AppAdm-CL-02-Linux" -disk=10GB -folder="/N_SW100_01/vm/Linux/Test" test9910

`

**Comment by rpasche** [comment]
Hm...but it says...."one component on the host is missing". Do you know, which? What does the logs on vCenter say?

**Comment by Akasurde** [comment]
@mainjoehere I think this is a different issue than this. Could you please open a new issue with your playbook and issue details ?

**Comment by mainjoehere** [comment]
I need to close my duty this month. As it is possible to create a vm with govc and with the old vsphere module we will not use the vmware_guest module. It seems to be far away for beeing usable in production.

**Comment by tenhishadow** [comment]
Hi All,
I have the same issue with this module.
As for vmware_guest it's working, but for deploying VM from template you need do in in 2 steps - deploy and reconfigure.

I have this in logs without specifying pool:

```
   "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_miO42f/ansible_module_vmware_guest.py\", line 1503, in <module>\n    main()\n  File \"/tmp/ansible_miO42f/ansible_module_vmware_guest.py\", line 1494, in main\n    result = pyv.deploy_vm()\n  File \"/tmp/ansible_miO42f/ansible_module_vmware_guest.py\", line 1292, in deploy_vm\n    task = destfolder.CreateVM_Task(config=self.configspec, pool=resource_pool)\nUnboundLocalError: local variable 'resource_pool' referenced before assignment\n",
```

With using ' resource_pool: Resources '

```
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1512391656.82-278073237295123 `" && echo ansible-tmp-1512391656.82-278073237295123="` echo /root/.ansible/tmp/ansible-tmp-1512391656.82-278073237295123 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmphm_BRF TO /root/.ansible/tmp/ansible-tmp-1512391656.82-278073237295123/vmware_guest.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1512391656.82-278073237295123/ /root/.ansible/tmp/ansible-tmp-1512391656.82-278073237295123/vmware_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1512391656.82-278073237295123/vmware_guest.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1512391656.82-278073237295123/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_FGrOVl/ansible_module_vmware_guest.py", line 1503, in <module>
    main()
  File "/tmp/ansible_FGrOVl/ansible_module_vmware_guest.py", line 1497, in main
    module.fail_json(**result)
  File "/tmp/ansible_FGrOVl/ansible_modlib.zip/ansible/module_utils/basic.py", line 2277, in fail_json
  File "/tmp/ansible_FGrOVl/ansible_modlib.zip/ansible/module_utils/basic.py", line 2255, in _return_formatted
  File "/tmp/ansible_FGrOVl/ansible_modlib.zip/ansible/module_utils/basic.py", line 509, in remove_values
  File "/tmp/ansible_FGrOVl/ansible_modlib.zip/ansible/module_utils/basic.py", line 448, in _remove_values_conditions
TypeError: 'vim.vm.device.VirtualDeviceSpec.FileOperation' object is not callable

fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_FGrOVl/ansible_module_vmware_guest.py\", line 1503, in <module>\n    main()\n  File \"/tmp/ansible_FGrOVl/ansible_module_vmware_guest.py\", line 1497, in main\n    module.fail_json(**result)\n  File \"/tmp/ansible_FGrOVl/ansible_modlib.zip/ansible/module_utils/basic.py\", line 2277, in fail_json\n  File \"/tmp/ansible_FGrOVl/ansible_modlib.zip/ansible/module_utils/basic.py\", line 2255, in _return_formatted\n  File \"/tmp/ansible_FGrOVl/ansible_modlib.zip/ansible/module_utils/basic.py\", line 509, in remove_values\n  File \"/tmp/ansible_FGrOVl/ansible_modlib.zip/ansible/module_utils/basic.py\", line 448, in _remove_values_conditions\nTypeError: 'vim.vm.device.VirtualDeviceSpec.FileOperation' object is not callable\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
```

Ansible Configuration

```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```
