### ISSUE TITLE
docker_login module tracebacks in ansible 2.9.24 (working in 2.9.23)

### ISSUE THREAD

**Issue by zach-prometheus** [ansible/ansible#75378]
### Summary

After upgrading to ansible 2.9.24 invoking the docker_login module gives the following error:

Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on marcus-dex-00's Python /usr/bin/python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: cannot import name certs

Downgrading to 2.9.23, the module works correctly.

### Issue Type

Bug Report

### Component Name

docker_login

### Ansible Version

```console
$ ansible --version
ansible 2.9.24
  config file = /Users/1234567/local_repo/ansible.cfg
  configured module search path = ['/Users/1234567/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/1234567/ansible/2.9/lib/python3.9/site-packages/ansible
  executable location = /Users/1234567/ansible/2.9/bin/ansible
  python version = 3.9.6 (default, Jun 29 2021, 05:25:02) [Clang 12.0.5 (clang-1205.0.22.9)]
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_PIPELINING(/Users/1234567/local_repo/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/Users/1234567/local_repo/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=5m -o ForwardAgent=yes
DEFAULT_BECOME(/Users/1234567/local_repo/ansible.cfg) = True
DEFAULT_FORKS(/Users/1234567/local_repo/ansible.cfg) = 5
DEFAULT_LOOKUP_PLUGIN_PATH(/Users/1234567/local_repo/ansible.cfg) = ['/Users/1234567/local_repo/lookup_plugins']
DEFAULT_MANAGED_STR(/Users/1234567/local_repo/ansible.cfg) = This file is managed by Ansible. Do not make changes here - they will be overwritten!
DEFAULT_ROLES_PATH(/Users/1234567/local_repo/ansible.cfg) = ['/Users/1234567/local_repo/roles']
DEFAULT_STDOUT_CALLBACK(/Users/1234567/local_repo/ansible.cfg) = debug
RETRY_FILES_ENABLED(/Users/1234567/local_repo/ansible.cfg) = False
```

### OS / Environment

Target environment: Ubuntu 18.04

Local environment: MacOS Big Sur (11.4)

### Steps to Reproduce

```yaml (paste below)
- hosts: example
  tasks:
  - name: install docker packages
    apt:
      name:
      - docker.io
      - python-docker
  - name: login to the docker registry
    docker_login:
      url: "registry.example.com"
      username: "foobar"
      password: "correcthorsebatterystaple"
```

### Expected Results

The module logs in to the docker registry.

### Actual Results

```console
Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on marcus-dex-00's Python /usr/bin/python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: cannot import name certs
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* `lib/ansible/modules/cloud/docker/docker_login.py`

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Thank you very much for your interest in Ansible. Ansible has migrated much of the content into separate repositories to allow for more rapid, independent development. We are closing this issue/PR because this content has been moved to one or more collection repositories.

* lib/ansible/modules/cloud/docker/docker_login.py -> https://github.com/ansible-collections/community.docker (https://galaxy.ansible.com/community/docker)

For further information, please see:
https://github.com/ansible/ansibullbot/blob/devel/docs/collection_migration.md
