### ISSUE TITLE
hostname module failing on CentOS 7 (released)

### ISSUE THREAD

**Issue by phips** [ansible/ansible#8102]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.7 (devel fbdb10d8a5) last updated 2014/07/11 17:14:11 (GMT +100)
```
##### Environment:

Control host: OSX 10.9.4
Target host: CentOS 7 VM

```
$ ansible -ki hosts -m setup centos7 -a 'filter=ansible_distribution_\*'
centos7 | success >> {
    "ansible_facts": {
        "ansible_distribution_major_version": "7", 
        "ansible_distribution_release": "Core", 
        "ansible_distribution_version": "7.0.1406"
    }, 
    "changed": false
}
```
##### Summary:

Hostname module fails with a traceback (see below).
##### Steps To Reproduce:

See _Actual Results_.
##### Expected Results:

```
TASK: [hosts | Ensure hostname set] ******************************************* 
changed: [default]
```
##### Actual Results:

```
TASK: [hosts | Ensure hostname set] ******************************************* 
failed: [centos7] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "<stdin>", line 1597, in <module>
  File "<stdin>", line 1600, in RedHatServerHostname
ValueError: invalid literal for float(): 7.0.1406


FATAL: all hosts have already failed -- aborting
```

**Comment by phips** [comment]
OK, it would appear the version number of 7.0 is 7.0.1406, which is returned from platform.linux_distribution()[1]

'float' doesn't handle that so well. Could it be fixed by stripping off the last part of the version number, giving 7.0? Would that have lots of bad side effects?

**Comment by jimi-c** [comment]
I think that'd be fine, since we're primarily concerned with just the major/minor number - the revision or whatever the rest of that would be considered does not need to be preserved.

**Comment by vincentvdk** [comment]
Not sure if it's a good idea to completely drop it. Maybe you want to target machines at a certain patch level. Until now we had point release (6.4, 6.5, ..), but now you can be more fine grained if needed.

**Comment by phips** [comment]
Looking through the code though @vincentvdk this routine (in basic.py) isn't used in any other module, currently. Which implies nobody cares about a sub release number. Plus, if we do take it account, then the code needs changing considerably as float() isn't going to work.

I started to look at patching it yesterday. Got the 7.0 captured just fine, but for some reason it still wasn't working (different error). Am working through it.

**Comment by phips** [comment]
Incidentally, this works just fine for the first bit of the problem...

```
-    return distribution_version
+    return re.match('\d+(?:\.\d+|)', distribution_version).group()
```

The second grouping in the regex ensures versions like '20' (i.e. Fedora) also work as well as N.N versioned OSs.

I'm not submitting it, yet, though as the bigger problem (with CentOS7) still exists.

**Comment by rmarchei** [comment]
What if we modify the CentOSHostname class in library/system/hostname to:

```
class CentOSHostname(Hostname):
    platform = 'Linux'
    distribution = 'Centos'
    if float(".".join(get_distribution_version().rsplit(".")[:2])) >= 7:
        strategy_class = FedoraStrategy
    else:
        strategy_class = RedHatStrategy
```

It should work with any distribution version type (6, 6.5, 7.0.1406, etc)
We may have to do the same with the ScientificLinuxHostname class

**Comment by jimi-c** [comment]
You could also use LooseVersion there, which would make things quite a bit easier.

**Comment by rmarchei** [comment]
I didn't know about LooseVersion! Thanks!

Anyway, I've tested with it and everything seems to work (I'm sending a pull request)

**Comment by phips** [comment]
I'm still getting an error though @rmarchei ...

```
TASK: [hosts | Ensure hostname set] ******************************************* 
failed: [centos7] => {"failed": true}
msg: hostname module cannot be used on platform Linux (Centos linux)

FATAL: all hosts have already failed -- aborting
```

This is using your fork, BTW.

```
$ ansible --version
ansible 1.7 (8102 8f1e6df3d7) last updated 2014/07/14 23:15:18 (GMT +100)
```

Incidentally, if you don't have a CentOS7 host to test on, I do have the trace output from saving the module. it's 75k lines long, mind :-)

**Comment by rmarchei** [comment]
No it's ok thanks :P 
I found the problem, can you try again now?

**Comment by phips** [comment]
Bingo!

```
$ ansible-playbook box_create.yml -l centos7 -k
SSH password: 

PLAY [vmware] ***************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [centos7]

TASK: [hosts | Ensure hostname set] ******************************************* 
changed: [centos7]
```

Thanks @rmarchei

**Comment by jimi-c** [comment]
The above PR was merged, so this issue should be resolved. Thanks!

**Comment by mpeters** [comment]
This same problem exists for AWS linux variant which is part of the RedHat family. It works in 1.6.2 but not in dev:

ansible 1.7 (devel f063aafeeb) last updated 2014/07/15 14:17:28 (GMT +000)

Not sure if we need a separate ticket for that, or if it's part of the same problem.

**Comment by rmarchei** [comment]
mmm nothing should be changed for Amazon linux from 1.6.2 to 1.7 dev. 
Can you please post the error and the amazon linux version?

**Comment by mpeters** [comment]
The error was the exact same as the initial ticket. Now with this patch in dev the error is slightly different:

```
failed: [10.0.0.225] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "<stdin>", line 1599, in <module>
  File "<stdin>", line 1602, in RedHatServerHostname
  File "/usr/lib64/python2.6/distutils/version.py", line 296, in __cmp__
    return cmp(self.version, other.version)
AttributeError: LooseVersion instance has no attribute 'version'
```

Some relevant facts from setup module:

```
        "ansible_distribution": "Amazon", 
        "ansible_distribution_major_version": "NA", 
        "ansible_distribution_release": "NA", 
        "ansible_distribution_version": "2014.03",
        "ansible_kernel": "3.10.42-52.145.amzn1.x86_64",
        "ansible_os_family": "RedHat",
        "ansible_python_version": "2.6.9",
        "ansible_system": "Linux", 
        "ansible_system_vendor": "NA",
        "ansible_userspace_architecture": "x86_64", 
        "ansible_userspace_bits": "64",
```

Let me know if you need anything else.

**Comment by phips** [comment]
Python 2.6 - LooseVersion not in 2.6?

**Comment by rmarchei** [comment]
I've already checked it and 2.6 has LooseVersion. 
Let me do some tests

**Comment by rmarchei** [comment]
The problem is in get_distribution_version() that doesn't work for Amazon Linux, it returns a blank string and LooseVersion doesn't like that. I'm trying to fix it.

**Comment by rmarchei** [comment]
I may have fixed the problem, but now I don't know if I can reopen the merged pull request or i must open a new one :P

**Comment by rmarchei** [comment]
Can you test it with this patch please?

**Comment by mpeters** [comment]
Yes, that patch works for me.

**Comment by jimi-c** [comment]
Thanks for the feedback, I've merged that PR in as well, so I'm going to go ahead and close this. Please let us know if you continue to see any problems related to this issue. Thanks!

**Comment by jdelaporte** [comment]
I am seeing this problem today on an AWS instance running CentOS 7:
"ansible_distribution": "CentOS", 
        "ansible_distribution_major_version": "7", 
        "ansible_distribution_release": "Core", 
        "ansible_distribution_version": "7.0.1406", 

My ansible version is 1.9.3:

$ ansible --version
ansible 1.9.3
  configured module search path = /usr/share/ansible

TASK: [gregswift.ipaserver | Hard set the hostname] **************************\* 
failed: [ipaddress] => {"failed": true}
msg: hostname module cannot be used on platform Linux (Centos linux)

FATAL: all hosts have already failed -- aborting
