### ISSUE TITLE
Region eu-north-1 does not seem to be available for aws module boto.ec2

### ISSUE THREAD

**Issue by igoratencompass** [ansible/ansible#56104]
##### SUMMARY

I can't access `eu-north-1` region in ansible and boto 2.49.0.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

boto.ec2 module

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.5.5
  config file = /home/igorc/configuration-management/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```
Same issue with 2.4.4

##### OS / ENVIRONMENT

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```
```
$ pip list | grep boto
boto                         2.49.0                       
botocore                     1.12.142
```
```
$ python --version
Python 2.7.12
```

##### STEPS TO REPRODUCE
Try creating instance in `eu-north-1` region.

##### EXPECTED RESULTS

Expect it to work.

##### ACTUAL RESULTS

```
"Region eu-north-1 does not seem to be available for aws module boto.ec2. If the region definitely exists, you may need to upgrade boto or extend with endpoints_path"
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by igoratencompass** [comment]
An issue with same boto version 2.49.0 has been reported here https://github.com/ansible/ansible/issues/21566

**Comment by s-hertel** [comment]
Boto is not longer actively maintained so the most that can be done is port boto modules to use boto3 instead. Here's the current state of things: https://github.com/ansible/community/blob/master/group-aws/boto3.md

What are the module(s) you're having trouble with?

needs_info

**Comment by igoratencompass** [comment]
Hi @s-hertel my problem begins with trying to obtain dynamic repository for the region:

```
 [WARNING]:  * Failed to parse inventory/repo/ec2.py with script plugin: Inventory script (inventory/repo/ec2.py) had an execution error: region name: eu-north-1 likely not supported, or AWS is down.  connection to region failed.
```
I have boto3 installed but not sure which modules use it and which don't:
```
boto (2.49.0)
boto3 (1.9.142)
botocore (1.12.142)
```

**Comment by zephyia** [comment]
We are having exact same issue - are you suggesting someone is already working on modifying the ec2.py script to use boto3?

**Comment by igoratencompass** [comment]
Upgrading to:

```
$ pip list --format=columns | grep -E "boto|aws"
awscli          1.16.153              
boto            2.49.0                
boto3           1.9.143               
botocore        1.12.143              
```
didn't help either.

**Comment by s-hertel** [comment]
@igoratencompass @zephyia The contrib script doesn't use boto3, only boto, and is not taking new features at this time. There is however, a supported inventory plugin that you could use instead which uses boto3.

Rather than targeting a script with `-i ec2.py` you'll create a yaml inventory configuration file with the options for the inventory plugin and run `-i config_aws_ec2.yml`. Your config file must end in aws_ec2.yml or aws_ec2.yaml for the aws_ec2 inventory plugin to use it. Here's an example of the possible contents of the config:
```
plugin: aws_ec2
boto_profile: testdev
regions:
  - eu-north-1
```
Here's some more detailed documentation about how to get started with inventory plugins: https://docs.ansible.com/ansible/latest/plugins/inventory.html#using-inventory-plugins, and documentation about the options for aws_ec2: https://docs.ansible.com/ansible/latest/plugins/inventory/aws_ec2.html.

Feel free to reach out on IRC freenode if you have questions (my handle is shertel).

**Comment by igoratencompass** [comment]
Thanks a lot @s-hertel but I'm facing an issue installing the plugin:
```
$ sudo -H pip install ansible-inventory
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting ansible-inventory
  Using cached https://files.pythonhosted.org/packages/7f/fd/9d3801d1ddf9e86588f499cedd15593329d7aac6e6ac6e0798a910686e27/ansible-inventory-0.5.19.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-SBJC3k/ansible-inventory/setup.py", line 11, in <module>
        from ansible_inventory.globals import VERSION as AI_VERSION, AUTHOR_NAME as AI_AUTHOR, AUTHOR_MAIL as AI_AUTHOR_EMAIL, URL as AI_URL
      File "/tmp/pip-install-SBJC3k/ansible-inventory/ansible_inventory/__init__.py", line 6, in <module>
        from re import fullmatch
    ImportError: cannot import name fullmatch
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-SBJC3k/ansible-inventory/
```

**Comment by igoratencompass** [comment]
I worked around that by manually installing the plugins from https://github.com/ansible/ansible/tree/devel/lib/ansible/plugins/inventory under `/usr/share/ansible/plugins/inventory/` but now I'm hitting another error:

```
ERROR! Unexpected Exception, this is probably a bug: cannot import name Constructable
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-inventory", line 106, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/inventory.py", line 113, in run
    self.loader, self.inventory, self.vm = self._play_prereqs(self.options)
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/__init__.py", line 790, in _play_prereqs
    inventory = InventoryManager(loader=loader, sources=options.inventory)
  File "/usr/local/lib/python2.7/dist-packages/ansible/inventory/manager.py", line 145, in __init__
    self.parse_sources()
  File "/usr/local/lib/python2.7/dist-packages/ansible/inventory/manager.py", line 197, in parse_sources
    self._setup_inventory_plugins()
  File "/usr/local/lib/python2.7/dist-packages/ansible/inventory/manager.py", line 185, in _setup_inventory_plugins
    plugin = inventory_loader.get(name)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/loader.py", line 363, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/loader.py", line 339, in _load_module_source
    module = imp.load_source(full_name, path, module_file)
  File "/usr/share/ansible/plugins/inventory/aws_ec2.py", line 148, in <module>
    from ansible.plugins.inventory import BaseInventoryPlugin, Constructable, Cacheable
ImportError: cannot import name Constructable
```

**Comment by zephyia** [comment]
Thanks @s-hertel didn't realise that existed, will change to that tomorrow and see how I go. Appreciate you taking the time to point it out.

**Comment by s-hertel** [comment]
@igoratencompass What version of Ansible are you using? Your description says `2.5.5` and the plugins should already be available with this version: https://github.com/ansible/ansible/tree/v2.5.5/lib/ansible/plugins/inventory. You shouldn't need to install things piece-by-piece.

**Comment by igoratencompass** [comment]
@s-hertel that was from 2.4.4 instance sorry for mixing it up. I guess I'm screwed on this version and left without any solution but upgrading ansible which is not possible atm. Regarding the plugins install, on that box I have ansible installed via pip which, from what I can see, does not install the plugins automatically like in case of package installer.

On 2.5.5 I get the following warning:

```
[WARNING]:  * Failed to parse config_aws_ec2.yml with aws_ec2 plugin: Not a ec2 inventory plugin configuration file
```
with the config file like:
```
plugin: aws_ec2
boto_profile: default
regions:
  - eu-north-1
filters:
  tag:Environment: my-env
```
This is per the examples so not sure what is going on here. Thanks for your support till now.

**Comment by s-hertel** [comment]
@igoratencompass Ah, I see what's happening. If you rename config_aws_ec2.yml to config.aws_ec2.yml that should work on 2.5. The method to verify expected files was loosened in 2.7 as well as providing a better debug message to indicate why a file is rejected. It would be nice to backport those improvements to 2.5 but that version is security-fixes-only at this point.

**Comment by igoratencompass** [comment]
Thanks @s-hertel that worked for 2.5.5

**Comment by igoratencompass** [comment]
Closing this since there is nothing else to be done. It is sad that there is no solution provided for 2.4 and older versions but that is so typical for the Ansible project -- break backwards compatibility and abandon maintaining the old stable versions with no consideration to the users that have spent years building their repository around a specific version.
