### ISSUE TITLE
The `s3` module alias does not work in Ansible 2.6.1.

### ISSUE THREAD

**Issue by veetow** [ansible/ansible#43217]
##### SUMMARY

The `s3` module alias does not work in Ansible 2.6.1.
https://docs.ansible.com/ansible/2.6/modules/aws_s3_module.html?highlight=Aliases:

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

aws_s3

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = None
  configured module search path = [u'/Users/vito.laurenza/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### OS / ENVIRONMENT

macOS 10.13.5

##### STEPS TO REPRODUCE

```yaml
- name: Download Bucket Item
  s3:
    bucket: "{{ s3_software_bucket }}"
    object: "{{ s3_object }}"
    dest: "{{ s3_object_dest }}"
    mode: get
```

##### EXPECTED RESULTS

It should work.

##### ACTUAL RESULTS

AttributeError on AnsibleAWSModule

```
fatal: [default]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_UhFRRo/ansible_module_s3.py\", line 908, in <module>\n    main()\n  File \"/tmp/ansible_UhFRRo/ansible_module_s3.py\", line 659, in main\n    module.deprecate(\"The 's3' module is being renamed 'aws_s3'\", version=2.7)\nAttributeError: 'AnsibleAWSModule' object has no attribute 'deprecate'\nShared connection to 127.0.0.1 closed.\r\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/aws_s3.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/aws_s3.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @lwade @s-hertel
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Hi veetow,

Thank you for the issue, just so you are aware we have a dedicated Working Group for aws.
You can find other people interested in this in #ansible-aws on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by andreaso** [comment]
Fixed in https://github.com/ansible/ansible/pull/42679
2.6.x backported in https://github.com/ansible/ansible/pull/42685

**Comment by ryansb** [comment]
Already fixed, as @andreaso points out.
