### ISSUE TITLE
1.8.1 regression - lookup() nolonger working as expected?

### ISSUE THREAD

**Issue by PriceChild** [ansible/ansible#9850]
##### Issue Type:

Bug Report
##### Ansible Version:

$ ansible --version
ansible 1.8.1
##### Environment:

Centos 7
##### Summary:

Some sort of regression means a lookup of a file wnolonger works in 1.8.1
##### Steps To Reproduce:

``` yaml
--
- hosts: 127.0.0.1
  connection: local
  vars:
    postgres_rsa: "{{ lookup('file', 'postgres_rsa.pub') }}"
  tasks:
  - debug:
      var: postgres_rsa
  - debug:
      msg: "{{ lookup('file', 'postgres_rsa.pub') }}"
```
##### Expected Results:

```
PLAY [127.0.0.1] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [debug ] **************************************************************** 
ok: [127.0.0.1] => {
    "postgres_rsa": "aofasfsd"
}

TASK: [debug ] **************************************************************** 
ok: [127.0.0.1] => {
    "msg": "aofasfsd"
}

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=3    changed=0    unreachable=0    failed=0
```
##### Actual Results:

In 1.8.1 the file isn't looked up:

```
PLAY [127.0.0.1] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [debug ] **************************************************************** 
ok: [127.0.0.1] => {
    "postgres_rsa": "{{ lookup('file', 'postgres_rsa.pub') }}"
}

TASK: [debug ] **************************************************************** 
fatal: [127.0.0.1] => undefined variable in items: 'unicode object' has no attribute 'pub'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/jpc/site.retry

127.0.0.1                  : ok=2    changed=0    unreachable=1    failed=0
```

**Comment by redbaron** [comment]
try 1.8.2, I recon relative lookup paths were fixed there

**Comment by PriceChild** [comment]
So it is, awesome!

Removed epel's ansible and pip installed 1.8.2 and the above works fine again.

**Comment by redbaron** [comment]
close the issue then :)
