### ISSUE TITLE
selectattr stopped working in the latest ansible version 

### ISSUE THREAD

**Issue by mohtashims** [ansible/ansible#77288]
### Summary

`selectattr` stopped working in the latest ansible version when it used to work on version 2.12. 

### Issue Type

Bug Report

### Component Name

ansible, selectattr

### Ansible Version

```console
$ ansible --version

ansible --version ansible 2.9.6   config file = /etc/ansible/ansible.cfg   configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']   ansible python module location = /usr/lib/python3/dist-packages/ansible   executable location = /usr/bin/ansible   python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

RHEL 8

### Steps to Reproduce

Below is a test case:

Sample file.json

```
[
  {
    "?xml": {
      "attributes": {
        "encoding": "UTF-8",
        "version": "1.0"
      }
    }
  },
  {
    "domain": [
      {
        "name": "mydom"
      },
      {
        "domain-version": "12.2.1.3.0"
      },
      {
        "server": [
          {
            "name": "AdminServer"
          },
          {
            "ssl": {
              "name": "AdminServer"
            }
          },
          {
            "listen-port": "12400"
          },
          {
            "listen-address": "mydom.host1.bank.com"
          }
        ]
      },
      {
        "server": [
          {
            "name": "myserv1"
          },
          {
            "ssl": [
              {
                "name": "myserv1"
              },
              {
                "login-timeout-millis": "25000"
              }
            ]
          },
          {
            "log": [
              {
                "name": "myserv1"
              },
              {
                "file-name": "/web/bea_logs/domains/mydom/myserv1/myserv1.log"
              }
            ]
          }
        ]
      },
      {
        "server": [
          {
            "name": "myserv2"
          },
          {
            "ssl": {
              "name": "myserv2"
            }
          },
         {
           "reverse-dns-allowed": "false"
         },
          {
            "log": [
              {
                "name": "myserv2"
              },
              {
                "file-name": "/web/bea_logs/domains/mydom/myserv2/myserv2.log"
              }
            ]
          }
        ]
      }
    ]
  }
]
```
I get the below output with ansible version 2.12

```
- hosts: localhost
  gather_facts: no
  vars:
    json: "{{ lookup('file', './file.json') | from_json }}"
  tasks:
    - name: display
      debug:
        msg: "{{ server.0.name }} -> {{ filename.0.log[1]['file-name'] }}"
      loop: "{{ json[1].domain }}"
      vars:
        server: "{{ item.server | selectattr('name', 'defined') }}"
        filename:  "{{ item.server | selectattr('log', 'defined') }}"
      when: item.server is defined and (item.server | selectattr('log', 'defined')) != []

Desired output:

> myserv1_log: "/web/bea_logs/domains/mydom/myserv1/myserv1.log"
> myserv2_log: "/web/bea_logs/domains/mydom/myserv2/myserv2.log"

Output:

skipping: [localhost] => (item={'name': 'mydom'}) 
skipping: [localhost] => (item={'domain-version': '12.2.1.3.0'}) 
skipping: [localhost] => (item={'server': [{'name': 'AdminServer'}, {'ssl': {'name': 'AdminServer'}}, {'listen-port': '12400'}, {'listen-address': 'mydom.host1.bank.com'}]}) 
ok: [localhost] => (item={'server': [{'name': 'myserv1'}, {'ssl': [{'name': 'myserv1'}, {'login-timeout-millis': '25000'}]}, {'log': [{'name': 'myserv1'}, {'file-name': '/web/bea_logs/domains/mydom/myserv1/myserv1.log'}]}]}) => {
    "msg": "myserv1 -> /web/bea_logs/domains/mydom/myserv1/myserv1.log"
}
ok: [localhost] => (item={'server': [{'name': 'myserv2'}, {'ssl': {'name': 'myserv2'}}, {'reverse-dns-allowed': 'false'}, {'log': [{'name': 'myserv2'}, {'file-name': '/web/bea_logs/domains/mydom/myserv2/myserv2.log'}]}]}) => {
    "msg": "myserv2 -> /web/bea_logs/domains/mydom/myserv2/myserv2.log"
}
      when: item.server is defined and item.server.2.log is defined
```

But with the latest ansible version 2.9.6 instead of the output I get below error:

> "The task includes an option with an undefined variable. The error was: 'str object' has no attribute 'name'\n\nThe error appears to be in '/root/test.yml': line 29, column 8

Can you please share a workaround as soon as possible & and a bug fix as feasible?

### Expected Results

Expected output:

> myserv1_log: "/web/bea_logs/domains/mydom/myserv1/myserv1.log"
> myserv2_log: "/web/bea_logs/domains/mydom/myserv2/myserv2.log

### Actual Results

```console
"The task includes an option with an undefined variable. The error was: 'str object' has no attribute 'name'\n\nThe error appears to be in '/root/test.yml': line 29, column 8
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
2.12 is the latest version. If it does not work in 2.9.6 that means it was fixed in some version between 2.9.6 and 2.12.

**Comment by flowerysong** [comment]
Because you've gone backward from 2.12 to 2.9, the automatic generator unrolling that was added in 2.10 is not present. You need to manually ensure the generators returned by `selectattr()` are converted to lists if you want this code to work on 2.9.

```
    - name: display
      debug:
        msg: "{{ server.0.name }} -> {{ filename.0.log[1]['file-name'] }}"
      loop: "{{ json[1].domain }}"
      vars:
        server: "{{ item.server | selectattr('name', 'defined') | list }}"
        filename:  "{{ item.server | selectattr('log', 'defined') | list }}"
      when:
        - item.server is defined
        - item.server | selectattr('log', 'defined') | list
```

**Comment by mkrizek** [comment]
Closing as per above.

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.libera.chat
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
