### ISSUE TITLE
2.19.0 breaks  cisco.ios.ios_command

### ISSUE THREAD

**Issue by SaruWiz** [ansible/ansible#85563]
### Summary

Playbooks for cisco does not work on < 2.19.0 
if 2.19.0 is installed the following error occurs

```
 TASK [Gather current default gateway] *************************************************************************************************
[ERROR]: Task failed: ActionBase._parse_returned_data() missing 1 required positional argument: 'profile'
Origin: myscript.yml:48:7

46
47   tasks:
48     - name: Gather current default gateway
         ^ column 7

fatal: [switch]: FAILED! => {"changed": false, "msg": "Task failed: ActionBase._parse_returned_data() missing 1 required positional argument: 'profile'"}

PLAY RECAP ****************************************************************************************************************************
scwitch             : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```

Playbook action:

```
  tasks:
    - name: Gather current default gateway
      cisco.ios.ios_command:
        commands: "show ip route"
      register: sh_ip_route_output
```

### Issue Type

Bug Report

### Component Name

pip

### Ansible Version

```console
$ ansible --version

2.19.0
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Debian 12 

### Steps to Reproduce

```yaml (paste below)
  tasks:
    - name: Gather current default gateway
      cisco.ios.ios_command:
        commands: "show ip route"
      register: sh_ip_route_output
```

### Expected Results

TASK [Display current default gateway] ************************************************************************************************
ok: [von-ci-of1-w01] => {
    "msg": "Current default gateway: 192.168.0.1"

### Actual Results

```console
TASK [Gather current default gateway] *************************************************************************************************
[ERROR]: Task failed: ActionBase._parse_returned_data() missing 1 required positional argument: 'profile'
Origin: myscript.yml:48:7

46
47   tasks:
48     - name: Gather current default gateway
         ^ column 7

fatal: [switch]: FAILED! => {"changed": false, "msg": "Task failed: ActionBase._parse_returned_data() missing 1 required positional argument: 'profile'"}

PLAY RECAP ****************************************************************************************************************************
scwitch             : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

* [`lib/ansible/modules/pip.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/pip.py)

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by mattclay** [comment]
This is a bug in the ansible.netcommon collection: https://github.com/ansible-collections/ansible.netcommon/issues/698
