### ISSUE TITLE
include_vars fails with AttributeError when working with dir

### ISSUE THREAD

**Issue by horseinthesky** [ansible/ansible#43272]
##### SUMMARY

**include_vars** fails with with **AttributeError** when working with dir

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

include_vars

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /home/horseinthesky/netprog/Ansible/05_deploy_JunOS_vRR/ansible.cfg
  configured module search path = ['/home/horseinthesky/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.5 (default, Apr  1 2018, 05:46:30) [GCC 7.3.0]
```

##### CONFIGURATION

```
[defaults]
inventory = ./hosts.yml
host_key_checking=False
retry_files_enabled = False
gathering = explicit
remote_user = root
ask_pass = True
```

##### OS / ENVIRONMENT

Linux Kappa 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

tree of role files
```
roles/vrr/
├── files
├── tasks
│   └── main.yml
├── templates
│   ├── bgp.j2
│   ├── community.j2
│   ├── firewall.j2
│   ├── interfaces.j2
│   ├── login.j2
│   ├── mpls.j2
│   ├── policy-options.j2
│   ├── policy-statement.j2
│   ├── prefix-list.j2
│   ├── protocols.j2
│   ├── routing-instances.j2
│   ├── routing-options.j2
│   ├── services.j2
│   ├── syslog.j2
│   ├── system.j2
│   └── vRR.j2
└── vars
    ├── communities.yml
    ├── firewall.yml
    ├── interfaces.yml
    ├── policy-options.yml
    ├── prefix-lists.yml
    ├── protocols.yml
    ├── routing-instances.yml
    ├── routing-options.yml
    └── users.yml
```

Play
```
- name: Include vars
  include_vars:
    dir: vars
```

##### EXPECTED RESULTS

vars to be included to the play

##### ACTUAL RESULTS

```

TASK [vrr : Include vars] *******************************************************************************************************
task path: /home/horseinthesky/netprog/Ansible/05_deploy_JunOS_vRR/roles/vrr/tasks/main.yml:1
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/bin/ansible-connection", line 87, in start
    self.connection._connect()
  File "/usr/local/lib/python3.6/dist-packages/ansible/plugins/connection/netconf.py", line 283, in _connect
    self._netconf = netconf_loader.get(network_os, self)
  File "/usr/local/lib/python3.6/dist-packages/ansible/plugins/loader.py", line 373, in get
    path = self.find_plugin(name)
  File "/usr/local/lib/python3.6/dist-packages/ansible/plugins/loader.py", line 330, in find_plugin
    plugin = self._find_plugin(name, mod_type=mod_type, ignore_deprecated=ignore_deprecated, check_aliases=check_aliases)
  File "/usr/local/lib/python3.6/dist-packages/ansible/plugins/loader.py", line 312, in _find_plugin
    if not name.startswith('_'):
AttributeError: 'NoneType' object has no attribute 'startswith'

fatal: [192.168.0.111]: FAILED! => {
    "msg": "'NoneType' object has no attribute 'startswith'"
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/utilities/logic/include_vars.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/include_vars.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @linuxdynasty
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by horseinthesky** [comment]
FInd out `incdule_vars` fail on Ansible 2.6.0 and 2.6.1 both Python2 and 3 but works on Ansible 2.5.0.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/include_vars.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/include_vars.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@horseinthesky Can you please retry with the latest Ansible versions, as I am not able to reproduce this?

needs_info

**Comment by horseinthesky** [comment]
Well, 3 years have passed. I try not to use Ansible anymore.
