### ISSUE TITLE
 AttributeError: 'StrategyModule' object has no attribute '_cond_not_supported_warn'

### ISSUE THREAD

**Issue by radez** [ansible/ansible#46275]
##### SUMMARY
https://github.com/ansible/ansible/pull/41655/files
This pull introduced a method named _cond_not_supported_warn
This method is in devel and stable 2.7. The patch from pull req is in 2.6 and 2.5.
Looks like 5f7ffd39dc8 needs to be back ported to 2.6 and 2.5

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
StrategyModule

##### ANSIBLE VERSION
```
# ansible --version
ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### OS / ENVIRONMENT
CentOS Linux release 7.5.1804 (Core) 

##### STEPS TO REPRODUCE
Stood up a Juniper vqfx switch
executed this playbook
```yaml
---
- name: "junos: check netconf service"
  block:
    - name: "junos: enable netconf if not already enabled"
      junos_netconf:
        state: present

    - name: "junos: close network_cli connection as its no longer needed"
      meta: reset_connection

  connection: network_cli
  when: ml2_settings_junos_enable_netconf

```

##### EXPECTED RESULTS
a warning to be thrown and the task to complete

##### ACTUAL RESULTS
stack trace thrown
```
 TASK [openstack-ml2 : junos: enable netconf if not already enabled]
************
 task path:
/root/networking-ansible/etc/ansible/roles/openstack-ml2/providers/junos/netconf.yaml:4
 <192.168.121.47> attempting to start connection
 <192.168.121.47> using connection plugin network_cli
 <192.168.121.47> local domain socket does not exist, starting it
 <192.168.121.47> control socket path is /root/.ansible/pc/97ab3e37c7
 <192.168.121.47> <192.168.121.47> ESTABLISH CONNECTION FOR USER:
ansible on PORT 22 TO 192.168.121.47
 <192.168.121.47> <192.168.121.47> ssh connection done, setting terminal
 <192.168.121.47> <192.168.121.47> loaded terminal plugin for network_os
junos
 <192.168.121.47> <192.168.121.47> loaded cliconf plugin for network_os
junos
 <192.168.121.47> <192.168.121.47> firing event: on_open_shell()
 <192.168.121.47> <192.168.121.47> ssh connection has completed successfully
 <192.168.121.47> connection to remote device started successfully
 <192.168.121.47> local domain socket listeners started successfully
 <192.168.121.47>
 <192.168.121.47> local domain socket path is /root/.ansible/pc/97ab3e37c7
 <192.168.121.47> ESTABLISH LOCAL CONNECTION FOR USER: root
 <192.168.121.47> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo
/root/.ansible/tmp/ansible-local-831465SsNcF/ansible-tmp-1537454837.36-125811669781692
`" && echo ansible-tmp-1537454837.36-125811669781692="` ec
ho
/root/.ansible/tmp/ansible-local-831465SsNcF/ansible-tmp-1537454837.36-125811669781692
`" ) && sleep 0'
 Using module_utils file
/usr/lib/python2.7/site-packages/ansible/module_utils/network/__init__.py
 Using module_utils file
/usr/lib/python2.7/site-packages/ansible/module_utils/six/__init__.py
 Using module_utils file
/usr/lib/python2.7/site-packages/ansible/module_utils/basic.py
 Using module_utils file
/usr/lib/python2.7/site-packages/ansible/module_utils/network/junos/__init__.py
 Using module_utils file
/usr/lib/python2.7/site-packages/ansible/module_utils/network/common/utils.py
 Using module_utils file
/usr/lib/python2.7/site-packages/ansible/module_utils/network/common/__init__.py
 Using module_utils file
/usr/lib/python2.7/site-packages/ansible/module_utils/network/junos/junos.py
 Using module_utils file
/usr/lib/python2.7/site-packages/ansible/module_utils/_text.py
 Using module_utils file
/usr/lib/python2.7/site-packages/ansible/module_utils/parsing/convert_bool.py
 Using module_utils file
/usr/lib/python2.7/site-packages/ansible/module_utils/parsing/__init__.py
 Using module_utils file
/usr/lib/python2.7/site-packages/ansible/module_utils/pycompat24.py
 Using module_utils file
/usr/lib/python2.7/site-packages/ansible/module_utils/network/common/netconf.py
 Using module_utils file
/usr/lib/python2.7/site-packages/ansible/module_utils/connection.py
 Using module file
/usr/lib/python2.7/site-packages/ansible/modules/network/junos/junos_netconf.py
 <192.168.121.47> PUT
/root/.ansible/tmp/ansible-local-831465SsNcF/tmplSq4Kd TO
/root/.ansible/tmp/ansible-local-831465SsNcF/ansible-tmp-1537454837.36-125811669781692/junos_netconf.py
 <192.168.121.47> EXEC /bin/sh -c 'chmod u+x
/root/.ansible/tmp/ansible-local-831465SsNcF/ansible-tmp-1537454837.36-125811669781692/
/root/.ansible/tmp/ansible-local-831465SsNcF/ansible-tmp-1537454837.36-1258116
69781692/junos_netconf.py && sleep 0'
 <192.168.121.47> EXEC /bin/sh -c '/usr/bin/python
/root/.ansible/tmp/ansible-local-831465SsNcF/ansible-tmp-1537454837.36-125811669781692/junos_netconf.py
&& sleep 0'
 <192.168.121.47> EXEC /bin/sh -c 'rm -f -r
/root/.ansible/tmp/ansible-local-831465SsNcF/ansible-tmp-1537454837.36-125811669781692/
> /dev/null 2>&1 && sleep 0'
 ok: [Juniper-vQFX] => {
     "changed": false,
     "commands": [],
     "invocation": {
         "module_args": {
             "host": null,
             "netconf_port": 830,
             "password": null,
             "port": null,
             "provider": null,
             "ssh_keyfile": null,
             "state": "present",
             "timeout": null,
             "transport": null,
             "username": null
         }
     }
 }
 ERROR! Unexpected Exception, this is probably a bug: 'StrategyModule'
object has no attribute '_cond_not_supported_warn'
 the full traceback was:
 
 Traceback (most recent call last):
   File "/usr/bin/ansible-playbook", line 118, in <module>
     exit_code = cli.run()
   File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line
122, in run
     results = pbex.run()
   File
"/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py",
line 156, in run
     result = self._tqm.run(play=play)
   File
"/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py",
line 292, in run
     play_return = strategy.run(iterator, play_context)
   File
"/usr/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py",
line 265, in run
     results.extend(self._execute_meta(task, play_context, iterator, host))
   File
"/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py",
line 1018, in _execute_meta
     self._cond_not_supported_warn(meta_action)
 AttributeError: 'StrategyModule' object has no attribute
'_cond_not_supported_warn'

```

**Comment by radez** [comment]
```
dradez@tirreno:~/git/ansible git:(stable-2.7)➤ git grep _cond_not_supported_warn
lib/ansible/plugins/strategy/__init__.py:    def _cond_not_supported_warn(self, task_name):
lib/ansible/plugins/strategy/__init__.py:                self._cond_not_supported_warn(meta_action)
lib/ansible/plugins/strategy/__init__.py:                self._cond_not_supported_warn(meta_action)
lib/ansible/plugins/strategy/__init__.py:                self._cond_not_supported_warn(meta_action)
lib/ansible/plugins/strategy/__init__.py:                self._cond_not_supported_warn(meta_action)
dradez@tirreno:~/git/ansible git:(stable-2.7)➤ git checkout stable-2.6                           
Switched to branch 'stable-2.6'
Your branch is up to date with 'origin/stable-2.6'.
dradez@tirreno:~/git/ansible git:(stable-2.6)➤ git grep _cond_not_supported_warn
lib/ansible/plugins/strategy/__init__.py:                self._cond_not_supported_warn(meta_action)
dradez@tirreno:~/git/ansible git:(stable-2.6)➤ git checkout stable-2.5          
Branch 'stable-2.5' set up to track remote branch 'stable-2.5' from 'origin'.
Switched to a new branch 'stable-2.5'
dradez@tirreno:~/git/ansible git:(stable-2.5)➤ git grep _cond_not_supported_warn
lib/ansible/plugins/strategy/__init__.py:                self._cond_not_supported_warn(meta_action)
dradez@tirreno:~/git/ansible git:(stable-2.5)➤ git checkout stable-2.4          
Switched to branch 'stable-2.4'
Your branch is up to date with 'origin/stable-2.4'.
dradez@tirreno:~/git/ansible git:(stable-2.4)➤ git grep _cond_not_supported_warn
Exit Code: 1 ▶ 
```

**Comment by mkrizek** [comment]
So the `_cond_not_supported_warn` method was introduced in https://github.com/ansible/ansible/pull/41126 and is present since `v2.7.0.a1`. However the method is used in https://github.com/ansible/ansible/pull/40866 (merged later despite the number might indicate otherwise) which was backported to `2.5` and `2.6`.

@nitzmahone @mattclay Do you prefer to backport just the `_cond_not_supported_warn` method or the whole https://github.com/ansible/ansible/pull/41126?

**Comment by mattclay** [comment]
@mkrizek I'm OK backporting just the function or the full PR. @nitzmahone ?

**Comment by zombieprocess** [comment]
I am also experiencing this issue. Thanks for reporting this and creating the backport PRs @radez @mkriedel 👍  

I'm just trying to use `meta: reset_connection` to refresh the connection for changes made to user group memberships so the ansible user can write to certain web directories. 😂 

```shell
$ ansible --version
ansible 2.5.10
  config file = ~/ansible-project/ansible.cfg
  configured module search path = [u'~/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]

$ uname -a
Darwin [hostname] 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```

```py
ERROR! Unexpected Exception, this is probably a bug: 'StrategyModule' object has no attribute '_cond_not_supported_warn'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 118, in <module>
    exit_code = cli.run()
  File "/Library/Python/2.7/site-packages/ansible/cli/playbook.py", line 122, in run
    results = pbex.run()
  File "/Library/Python/2.7/site-packages/ansible/executor/playbook_executor.py", line 156, in run
    result = self._tqm.run(play=play)
  File "/Library/Python/2.7/site-packages/ansible/executor/task_queue_manager.py", line 289, in run
    play_return = strategy.run(iterator, play_context)
  File "/Library/Python/2.7/site-packages/ansible/plugins/strategy/linear.py", line 265, in run
    results.extend(self._execute_meta(task, play_context, iterator, host))
  File "/Library/Python/2.7/site-packages/ansible/plugins/strategy/__init__.py", line 1018, in _execute_meta
    self._cond_not_supported_warn(meta_action)
AttributeError: 'StrategyModule' object has no attribute '_cond_not_supported_warn'
```

**Comment by mkrizek** [comment]
Backported in #48175 for `2.6` release (`2.5` is now at critical bugfixes only). Closing.
