### ISSUE TITLE
Directly runnig module doesn't work with fetch_url() function within module

### ISSUE THREAD

**Issue by okgolove** [ansible/ansible#53872]
##### SUMMARY

I'm trying to run my module locally using next instructions https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general.html#exercising-module-code-locally

And I get an error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Any module containing fetch_url() function from ansible.module_utils.urls
In my case it is my module I'm developing https://github.com/okgolove/ansible/blob/sentry_fixes/lib/ansible/modules/web_infrastructure/sentry_project.py

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0
  config file = None
  configured module search path = [u'/Users/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/user/git/ansible/lib/ansible
  executable location = /Users/user/git/ansible/bin/ansible
  python version = 2.7.15 (default, Oct  2 2018, 11:47:18) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)]
```

##### CONFIGURATION

args.json
```paste below
{
    "ANSIBLE_MODULE_ARGS": {
        "api_token": "abcxdz",
        "organization": "develop",
        "project_name": "backendtest",
        "project_slug": "backendtest",
        "state": "present",
        "team": "develop",
        "url": "https://sentry.io"
    }
}
```

##### OS / ENVIRONMENT

MacOS 10.14.3, Python 2.7.15

##### STEPS TO REPRODUCE

```pipenv shell && source hacking/env-setup && python lib/ansible/modules/web_infrastructure/sentry_project.py args.json```

##### EXPECTED RESULTS

Module runs properly.

##### ACTUAL RESULTS

And I get an error:

```Traceback (most recent call last):
  File "lib/ansible/modules/web_infrastructure/sentry_project.py", line 159, in <module>
    main()
  File "lib/ansible/modules/web_infrastructure/sentry_project.py", line 118, in main
    if is_project_exists(project_name, organization, team, api_token):
  File "lib/ansible/modules/web_infrastructure/sentry_project.py", line 110, in is_project_exists
    method="GET")
  File "/Users/user/git/ansible/lib/ansible/module_utils/urls.py", line 1327, in fetch_url
    tempfile.tempdir = module.tmpdir
  File "/Users/user/git/ansible/lib/ansible/module_utils/basic.py", line 851, in tmpdir
    basedir = os.path.expanduser(os.path.expandvars(self._remote_tmp))
AttributeError: 'AnsibleModule' object has no attribute '_remote_tmp'
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
This has not worked since Ansible 2.5.0. I bisected to this commit https://github.com/ansible/ansible/commit/ca8e4c806a70eab259fb5d3036e3295b0e7880a4.

This may actually be a bug in the `tmpdir()` property since that should be returning a valid value.

**Comment by okgolove** [comment]
@samdoran my tests for my module with fetch_url() also are not able to pass because of the same error:

https://app.shippable.com/github/ansible/ansible/runs/116365/6/console
<img width="957" alt="123" src="https://user-images.githubusercontent.com/36846182/55101818-a9df1d00-50cd-11e9-8ab7-a1c59568cfc6.png">

**Comment by lithammer** [comment]
To work around the issue you can pass `_ansible_tmpdir` in your `args.json`:

```json
{
  "ANSIBLE_MODULE_ARGS": {
    "foo": "bar",
    "_ansible_tmpdir": "/tmp"
  }
}
```
