### ISSUE TITLE
docker_container fails while pulling new image

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29512]
From @maciej on 2016-11-07T17:28:08Z

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

docker_container

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = [redacted]/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

```
[defaults]
host_key_checking=False
```

##### OS / ENVIRONMENT

Running ansible from: macOS Sierra
Provisioning: CentOS 7.2, Docker installed from https://yum.dockerproject.org/repo/main/centos/7

##### SUMMARY

`docker_container` module fails with: 
```
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "Error pulling image httpd:latest - pull() got an unexpected keyword argument 'decode'"}
```
while pulling an image

##### STEPS TO REPRODUCE

Execute ansible-playbook with the following play:

```
- name: "Start container"
  docker_container:
    name: whatever
    image: "httpd"
    pull: true
```

Copied from original issue: ansible/ansible-modules-core#5515

**Comment by ansibot** [comment]
From @ansibot on 2016-11-07T17:28:08Z



@ansible ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
From @maciej on 2016-11-07T17:28:08Z

It does seem the issue is related to docker-py version 1.7.0. After updating to the latest 1.10.6 the problem gone away.
However the documentation https://docs.ansible.com/ansible/docker_container_module.html still states that 1.7.0 should be sufficient: `docker-py >= 1.7.0`

**Comment by ansibot** [comment]
From @vce-xx on 2016-11-07T17:28:08Z

Upgraded to 1.10.6 and problem still there:
`$ ansible --version`
**ansible 2.2.0.0**
`$ pip list docker-py | grep docker-py`
**docker-py (1.10.6)**
docker-pycreds (0.2.1)
`$ ansible-playbook docker_container.play`
fatal: [jenkinsslave3]: FAILED! => {"changed": false, "failed": true, "msg": "Error pulling image xxx:443/xxx/xxx:ttt - **pull() got an unexpected keyword argument 'decode'**"}

**Comment by ansibot** [comment]
From @pondix on 2016-11-07T17:28:08Z

Same problem here with the following OS & packages:

```
$ cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 

$ pip list docker-py | grep docker-py
docker-py (1.10.6)
docker-pycreds (0.2.1)

$ ansible --version
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

Task:

```
- name: Create PMM Data Container
  docker_container:
    name: pmm-data
    image: percona/pmm-server:latest
    state: present
    pull: no
    volumes:
    - /opt/prometheus/data
    - /opt/consul-data
    - /var/lib/mysql
    - /var/lib/grafana
    command: /bin/true
```

Output:

```
TASK [pmm : Create PMM Data Container] *****************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error pulling image percona/pmm-server:latest - pull() got an unexpected keyword argument 'decode'"}
```

**Comment by ansibot** [comment]
From @maciej on 2016-11-07T17:28:08Z

@vce-xx @pondix just to be sure, are you checking `docker-py` version that's installed on the host (not the machine from where Ansible runs)? 1.10.6 works well for me.

**Comment by ansibot** [comment]
From @pondix on 2016-11-07T17:28:08Z

Yes - I'm actually running the playbook locally on the same machine

**Comment by ansibot** [comment]
From @vce-xx on 2016-11-07T17:28:08Z

That makes perfect sense.
Thanks 👍

**Comment by ansibot** [comment]
From @gaahrdner on 2016-11-07T17:28:08Z

Hitting this as well with `ansible 2.2.0` and `python-docker-py-1.7.2-1.el7.noarch`:

```
  - name: Pull nginx Docker image to host installer
    docker_image:
      name: nginx
```

**Comment by ansibot** [comment]
From @henriklynggaard on 2016-11-07T17:28:08Z

Seeing this too, ansible 2.2.0 and python-docker-py-1.7.2-1.el7.noarch.

Trying to use 2.1.2.0 from another ansible controller  afterwards results in a 404 image not found despite manual pulling is possible

sh-4.2# docker --version
Docker version 1.10.3, build 5206701

**Comment by ansibot** [comment]
From @vital-st1x on 2016-11-07T17:28:08Z

Could confirm the bug
CentOS Linux release 7.2.1511 (Core)
python-docker-py-1.7.2-1.el7.noarch
docker-engine-selinux-1.11.2-1.el7.centos.noarch
docker-engine-1.10.2-1.el7.centos.x86_64

**Comment by ansibot** [comment]
From @jctanner on 2016-11-07T17:28:08Z

@maciej @vital-st1x @henriklynggaard @pondix 

I reproduced the error on centos7 with the docker and python-docker-py packages from epel. Can you please confirm if removing the docker-py rpm and installing the latest from pip resolves the issue?

```
rpm -e --nodeps python-docker-py
yum install python-pip
pip install docker-py
```

needs_info

**Comment by ansibot** [comment]
From @maciej on 2016-11-07T17:28:08Z

@jctanner installing docker-py (from pip) in version 1.10.6 resolves the issue for me.

**Comment by ansibot** [comment]
From @damien-carcel on 2016-11-07T17:28:08Z

Hello.

I can confirm this issue on Archlinux too. Everything up to date: ansible 2.2.0, python 2.7.12 and docker-py 1.10.6.

I tried to remove docker-py, then install it with pip, but that changes nothing…

For the moment, I reverted to ansible 2.1 to get things working again.

**Comment by ansibot** [comment]
From @packeteer on 2016-11-07T17:28:08Z

fwiw, I'm hitting the same issue
OSX El Cap with python 2.7.12 and pip installed ansible 2.2.0, running against vagrant centos 7 box (Docker 1.10.3, docker-py 1.7.2)

pip installing docker-py (1.10.6) on the target solves the issue

**Comment by ansibot** [comment]
From @bcorijn on 2016-11-07T17:28:08Z

Same issue here.
Running from OSX Sierra against a Ubuntu 14.04 box with Docker 1.9.1. Updating docker-py 1.10.6 on the remote machine through pip did not help, tried with Ansible 2.1.3, 2.2.0, 2.3.0, none of them worked.

**Comment by ansibot** [comment]
From @cben on 2016-11-07T17:28:08Z

On Fedora 24, had bug with `python-docker-py` 1.8.1-1.fc24, solved by getting 1.10.4-1.fc26 from rawhide:
```
sudo dnf install --enablerepo rawhide --best python-docker-py
```

**Comment by ansibot** [comment]
From @gbolo on 2016-11-07T17:28:08Z

having the same issue on both Centos 7.2 and RHEL 7.3
```
pull() got an unexpected keyword argument 'decode'
```

using:
```
docker --version
Docker version 1.12.3, build 6b644ec

ansible --version
ansible 2.2.0.0

rpm -qa | grep -i python-docker-py
python-docker-py-1.7.2-1.el7.noarch
```

I can also confirm that everything works fine on ansible 2.1

**Comment by ansibot** [comment]
From @xiemeilong on 2016-11-07T17:28:08Z

same issue 

```
ubuntu 16.04

Docker version 1.12.3, build 6b644ec

ansible 2.2.0.0

docker-py (1.10.6)
```

**Comment by ansibot** [comment]
From @vce-xx on 2016-11-07T17:28:08Z

A first thing to verify : the python-docker-py version must be checked on the remote (not local) machine because that 's where it will used.

**Comment by ansibot** [comment]
From @likid0 on 2016-11-07T17:28:08Z

Hi Same here with centos 7.1 and python-docker-py, all works ok after installing docker-py (1.10.6) from pip.

Regards.

**Comment by ansibot** [comment]
From @eoinverling on 2016-11-07T17:28:08Z

Confirm my fix ... 

Host (where I run "ansible-playbook" from): OSX Sierra, ansible 2.2.0.0, docker-py 1.10.6
Target (where ansible-playbook targets!): Centos7, python-docker-py.noarch 1.7.2-1.el7

This setup would produce the error with the ansible module "docker_container"

Upgrade the TARGET docker-py (add these 2 x steps to my ansible playbook: easy_install pip; pip install docker-py) to the latest 1.10.6 ... all ok now

thanks

**Comment by ansibot** [comment]
From @Hubbitus on 2016-11-07T17:28:08Z

Does someone reported it into CentOS for example?

**Comment by ansibot** [comment]
From @mschirrmeister on 2016-11-07T17:28:08Z

@Hubbitus Have you tried the latest version available on CentOS *extras*. They released mid December `python-docker-py-1.9.0-1.el7` and that seems to have fixed the problem. The Ansible `docker_container` module can pull images, if that 1.9.0 version is installed. So I think this issue is or can be closed?

**Comment by ansibot** [comment]
From @Hubbitus on 2016-11-07T17:28:08Z

Hm, indeed it seams work on `python-docker-py-1.9.0-1.el7.noarch`. Thank you.

**Comment by ansibot** [comment]
From @ryanwalls on 2016-11-07T17:28:08Z

Updating to 1.10.6 worked for me.

**Comment by ansibot** [comment]
From @ntwrkguru on 2016-11-07T17:28:08Z

Still broken for me with docker-py 1.10.6.

Target machine: Ubuntu 14.04.5
```bash
$ python --version
Python 2.7.6

$ pip list
apt-xapian-index (0.45)
backports.ssl-match-hostname (3.5.0.1)
chardet (2.0.1)
configobj (4.7.2)
docker-py (1.10.6)
docker-pycreds (0.2.1)
ipaddress (1.0.18)
Landscape-Client (14.12)
PAM (0.4.2)
pip (9.0.1)
pyOpenSSL (0.13)
pyserial (2.6)
python-apt (0.9.3.5ubuntu2)
python-debian (0.1.21-nmu2ubuntu2)
requests (2.13.0)
setuptools (3.3)
six (1.10.0)
ssh-import-id (3.21)
Twisted-Core (13.2.0)
urllib3 (1.7.1)
websocket-client (0.40.0)
wheel (0.29.0)
zope.interface (4.0.5)
```

Source machine: macOS Sierra 10.12.3
```bash
$ ansible --version
ansible 2.2.1.0
```

Outcome:
```bash
fatal: [portus-lab]: FAILED! => {"changed": false, "failed": true, "msg": "Error pulling image opensuse/portus:latest - pull() got an unexpected keyword argument 'decode'"}
```

Play:

```yaml
- name: start portus
    docker_container:
      name: portus
      pull: true
      image: opensuse/portus
      state: started
      restart_policy: unless-stopped
      volumes:
      - /var/opt/portus/certs/portus-ca.crt:/certificates/portus-ca.crt
      - /var/opt/portus/secrets/portus.key:/secrets/portus.key
      env:
        # Security related settings
        PORTUS_SECRET_KEY_BASE: xxx
        PORTUS_PORTUS_PASSWORD: xxx
        # Database releated settings:
        MARIADB_SERVICE_HOST: localhost
        MARIADB_USER: portus
        MARIADB_PASSWORD: portus
        MARIADB_DATABASE: portus
        # Deployment related settings:
        PORTUS_MACHINE_FQDN_VALUE: example.com
      published_ports:
      - "80:80"
      - "443:443"
```

**Comment by ansibot** [comment]
From @darkk on 2016-11-07T17:28:08Z

Seems to be duplicate of ansible/ansible#20776

**Comment by ansibot** [comment]
From @antonbormotov on 2016-11-07T17:28:08Z

Issue is resolved in `docker-py` package version `1.10.6`.

**Comment by ansibot** [comment]
cc @ThomasSteinbach @cove @dusdanig @kassiansun @softzilla @zfil
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chouseknecht @joshuaconner
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
resolved_by_pr #37513

**Comment by skylerbunny** [comment]
This was never resolved because #37513 was never actually merged. The bottom line is that docker_container and docker_image (and by the looks of it, other modules) still need to have a minimum of docker-py 1.8.0 stated, and this wasn't done even in #42457.

Since #42457 made so many changes and #37513 is closed, it's probably the best course to create a new PR making the 1.8.0 minimum bump, but in any event, this still needs to be done.

**Comment by ansibot** [comment]
cc @felixfontein
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ntwrkguru** [comment]
@skylerbunny Perhaps that's not the full fix. If you notice above, I ran into the same issue even with docker-py 1.10.6.

**Comment by felixfontein** [comment]
@ntwrkguru Are you sure you got the message with `docker-py` 1.10.6 installed on the target machine? I can reproduce it with 1.7.0, but neither with 1.8.0 nor with 1.10.6.

**Comment by ntwrkguru** [comment]
@felixfontein, yes, see above. I can see if I can reproduce it, but that project is long since over, so I'll be digging through old stuff. :-)
