### PR TITLE
Workaround bug in jinja2-3.0.0 and 3.0.1

### PR DESCRIPTION
**Pull request by abadger**
Jinja2-3.0.0 and 3.0.1 has a bug where undefined values cannot be
checked to see if they contain a value: https://github.com/pallets/jinja/issues/1448#issuecomment-846029509

We workaround this in two ways, either of which would be sufficient:
* Normalize the data so that choices is an empty iterable when it isn't
  specified in the documentation.  This is what antsibull-docs (and thus
  documentation builds on 2.10+) do.
* Change the logic in the template to check whether choices exists
  before checking containment.  This better expresses the logic at that
  point in the template (if there is a default value but there is not a
  list of choices, then display the default in its own string) so it's
  a good change to make as well.

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
Documentation build for ansible-2.9 (newer versions are built via code in antsibull-docs)

##### ADDITIONAL INFORMATION
/CC @acozine @samccann @relrod

### CODE REVIEW

**Comment by acozine** [comment]
This bug causes about half of the 2.9 module docs to fail with the error `[WARNING]: Could not parse <module_name> due to 'ansible.parsing.yaml.objects.AnsibleMapping object' has no attribute 'choices'` when run with Jinja2 version 3.x. The overall docs build "succeeds" but no docs get generated for the modules that trip the error (resulting in a silent outage for the 2.9 documentation). 

We are currently pinning the version of Jinja2 to <3.0.0 in our Jenkins build, so docs.ansible.com/ansible/2.9 is back up and running, but this issue will hit anyone who tries to build the 2.9 documentation locally as well.
