### PR TITLE
import_tasks processing closer to include_tasks

### LINKED ISSUE #69882: import_tasks within import_role not working
##### SUMMARY
import/include_tasks from within an import/include_role not working.

Looks like: https://github.com/ansible/ansible/issues/27345

Trying to import/include_role:
https://github.com/oVirt/ovirt-ansible-hosted-engine-setup

fails because the two import_tasks at the beginning
https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/master/tasks/pre_checks/002_validate_hostname_tasks.yml

Due to the import on
https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/master/tasks/full_execution.yml

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
import_role
include_role

##### ANSIBLE VERSION

```
ansible 2.9.9
  config file = /root/huertasv10/ansible/ansible.cfg
  configured module search path = [u'/root/huertasv10/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```
and
```
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/root/huertasv10/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/root/huertasv10/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=30m
ANSIBLE_SSH_CONTROL_PATH(/root/huertasv10/ansible/ansible.cfg) = %(directory)s/%%h-%%r
ANSIBLE_SSH_CONTROL_PATH_DIR(/root/huertasv10/ansible/ansible.cfg) = /root/cp
DEFAULT_MODULE_PATH(/root/huertasv10/ansible/ansible.cfg) = [u'/root/huertasv10/ansible/plugins/modules']
DEFAULT_MODULE_UTILS_PATH(/root/huertasv10/ansible/ansible.cfg) = [u'/root/huertasv10/ansible/plugins/module_utils']
DEFAULT_ROLES_PATH(/root/huertasv10/ansible/ansible.cfg) = [u'/root/huertasv10/ansible/roles', u'/root/huertasv10/ansible/roles_
HOST_KEY_CHECKING(/root/huertasv10/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT

CentOS Linux release 7.6.1810 (Core)
ovirt-node-ng-installer-4.3.4-2019061016.el7

##### STEPS TO REPRODUCE

```
- name: Deploy ovirt hosted engine over a physical host
  include_role:
    name: ovirt.hosted_engine_setup

```
or
```
- name: Deploy ovirt hosted engine over a physical host
  import_role:
    name: ovirt.hosted_engine_setup

```

##### EXPECTED RESULTS

import/include_role should work as regular role invocation

##### ACTUAL RESULTS

```paste below
TASK [ovirt.hosted_engine_setup : System configuration validations] ************************************************************
task path: /root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/tasks/full_execution.yml:7
META: noop
META: noop
META: noop
META: noop
looking for "pre_checks" at "/root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/files/pre_checks"
looking for "pre_checks" at "/root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/pre_checks"
looking for "pre_checks" at "/root/huertasv10/ansible/roles/ovirt.he.iscsi.deploy/files/pre_checks"
looking for "pre_checks" at "/root/huertasv10/ansible/roles/ovirt.he.iscsi.deploy/pre_checks"
looking for "pre_checks" at "/root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/tasks/files/pre_checks"
looking for "pre_checks" at "/root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/tasks/pre_checks"
included: /root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/tasks/pre_checks/validate_network_test.yml for fenix1
included: /root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/tasks/pre_checks/validate_memory_size.yml for fenix1
included: /root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/tasks/pre_checks/define_variables.yml for fenix1
included: /root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/tasks/pre_checks/validate_data_center_name.yml for fenix1
included: /root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/tasks/pre_checks/validate_gateway.yml for fenix1
included: /root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/tasks/pre_checks/001_validate_network_interfaces.yml for fenix1
included: /root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/tasks/pre_checks/validate_mac_address.yml for fenix1
included: /root/huertasv10/ansible/roles_lib/ovirt.hosted_engine_setup/tasks/pre_checks/validate_services_status.yml for fenix1
ERROR! Unexpected Exception, this is probably a bug: 'NoneType' object has no attribute 'rfind'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 110, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 123, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 169, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 249, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 355, in run
    new_blocks = self._load_included_file(included_file, iterator=iterator)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 807, in _load_included_file
    variable_manager=self._variable_manager,
  File "/usr/lib/python2.7/site-packages/ansible/playbook/helpers.py", line 77, in load_list_of_blocks
    loader=loader,
  File "/usr/lib/python2.7/site-packages/ansible/playbook/block.py", line 95, in load
    return b.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/base.py", line 240, in load_data
    self._attributes[target_name] = method(name, ds[name])
  File "/usr/lib/python2.7/site-packages/ansible/playbook/block.py", line 131, in _load_block
    use_handlers=self._use_handlers,
  File "/usr/lib/python2.7/site-packages/ansible/playbook/helpers.py", line 193, in load_list_of_tasks
    parent_include_dir = os.path.dirname(templar.template(parent_include.args.get('_raw_params')))
  File "/usr/lib64/python2.7/posixpath.py", line 129, in dirname
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

### LINKED ISSUE #85855: become not applied with nested import_tasks since 2.19.1
### Summary

I have nested import_tasks in my role (https://gitlab.com/yan12125/ansible-chyen/-/tree/master/roles/firewalld), and become is no longer applied since ansible 2.19.1. The issue also happens to the reduced test case in the repo mentioned below.

git bisect points to commit 6404fdce457f3f437009cb7ccedc949ecf05afd3 (https://github.com/ansible/ansible/pull/85599). If I remove import_tasks with empty.yml in the test case, everything works fine. Maybe the change above breaks handling of become with nested import_tasks?

### Issue Type

Bug Report

### Component Name

import_tasks

### Ansible Version

```console
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of code and can become unstable at any point.
ansible [core 2.20.0.dev0] (devel e30da51731) last updated 2025/09/12 23:22:28 (GMT +800)
  config file = None
  configured module search path = ['/home/yen/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/yen/tmp/ansible/lib/ansible
  ansible collection location = /home/yen/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/yen/.local/bin/ansible
  python version = 3.13.7 (main, Aug 15 2025, 12:34:02) [GCC 15.2.1 20250813] (/usr/bin/python)
  jinja version = 3.1.6
  pyyaml version = 6.0.2 (with libyaml v0.2.5)
```

### Configuration

```console
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of code and can become unstable at any point.
CONFIG_FILE() = None
EDITOR(env: EDITOR) = nvim

GALAXY_SERVERS:


CONNECTION:
==========

ssh:
___
control_path_dir(env: ANSIBLE_SSH_CONTROL_PATH_DIR) = /run/user/1000/ansible/cp
```

### OS / Environment

Arch Linux up-to-date

### Steps to Reproduce

```
$ git clone https://gitlab.com/yan12125/ansible-bug-case
$ cd ansible-bug-case
$ ansible-playbook foo.yml --ask-become-pass
```

### Expected Results

All tasks succeeded

### Actual Results

```console
[ERROR]: Task failed: Module failed: File is not readable: /etc/shadow: [Errno 13] 拒絕不符權限的操作: '/etc/shadow'
Origin: /home/yen/tmp/foo/roles/foo/tasks/inner.yml:4:3

2     file: empty.yml
3
4 - slurp:
    ^ column 3

fatal: [localhost]: FAILED! => {"changed": false, "msg": "File is not readable: /etc/shadow"}
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

### LINKED ISSUE #85856: become_user broken with import_tasks since 2.19
### Summary

After upgrading from `ansible==11.9.0`/`ansible-core==2.18.8` to `12.0.0`/`2.19.2` respectively, this breaks before the playbook starts executing:

```
- import_tasks: some_tasks.yml
  become_user: "{{ user_dictionary.name }}"
```

This is in the `tasks/main.yml` file of a role at the top level, and `some_tasks.yml` is a file in the same directory.

The error is:

`[ERROR]: Error processing keyword 'become_user': 'user_dictionary' is undefined`

Multiple other tasks in the same playbook feature `user_dictionary` (or its `name` key), and they do not cause this error. The variable itself is defined in `group_vars/all`.

The playbooks or variables have not changed, this happens as a direct consequence of the Ansible upgrade. No errors or warnings about this were printed with the old versions. I read through the Ansible 2.19 porting guide, but could not find an item there that I could see explain this.

### Issue Type

Bug Report

### Component Name

The task import machinery? idk

### Ansible Version

```console
$ ansible --version
ansible [core 2.19.2]
  config file = /Users/itsame/SomeProject/ansible/ansible.cfg
  configured module search path = ['/Users/itsame/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/itsame/.local/share/mise/installs/python/3.13.6/lib/python3.13/site-packages/ansible
  ansible collection location = /Users/itsame/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/itsame/.local/share/mise/installs/python/3.13.6/bin/ansible
  python version = 3.13.6 (main, Aug 14 2025, 16:05:41) [Clang 20.1.4 ] (/Users/itsame/.local/share/mise/installs/python/3.13.6/bin/python3.13)
  jinja version = 3.1.6
  pyyaml version = 6.0.2 (with libyaml v0.2.5)
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /Users/itsame/SomeProject/ansible/ansible.cfg
DEFAULT_BECOME(/Users/itsame/SomeProject/ansible/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/Users/itsame/SomeProject/ansible/ansible.cfg) = True
DEFAULT_BECOME_FLAGS(/Users/itsame/SomeProject/ansible/ansible.cfg) = -i
DEFAULT_FILTER_PLUGIN_PATH(/Users/itsame/SomeProject/ansible/ansible.cfg) = ['/Users/itsame/SomeProject/ansible/shared/plugins/filter_plugins']
DEFAULT_REMOTE_USER(/Users/itsame/SomeProject/ansible/ansible.cfg) = someuser
DEFAULT_ROLES_PATH(/Users/itsame/SomeProject/ansible/ansible.cfg) = ['/Users/itsame/SomeProject/ansible/shared/roles']
DEFAULT_VARS_PLUGIN_PATH(/Users/itsame/SomeProject/ansible/ansible.cfg) = ['/Users/itsame/SomeProject/ansible/shared/plugins/vars_plugins']
DEFAULT_VAULT_PASSWORD_FILE(/Users/itsame/SomeProject/ansible/ansible.cfg) = /Users/itsame/SomeProject/ansible/get_vault_pass.py
EDITOR(env: EDITOR) = /usr/bin/vim
INTERPRETER_PYTHON(/Users/itsame/SomeProject/ansible/ansible.cfg) = auto
RETRY_FILES_ENABLED(/Users/itsame/SomeProject/ansible/ansible.cfg) = False

GALAXY_SERVERS:


BECOME:
======

runas:
_____
become_flags(/Users/itsame/SomeProject/ansible/ansible.cfg) = -i

su:
__
become_flags(/Users/itsame/SomeProject/ansible/ansible.cfg) = -i

sudo:
____
become_flags(/Users/itsame/SomeProject/ansible/ansible.cfg) = -i

CONNECTION:
==========

paramiko_ssh:
____________
remote_user(/Users/itsame/SomeProject/ansible/ansible.cfg) = someuser

ssh:
___
remote_user(/Users/itsame/SomeProject/ansible/ansible.cfg) = someuser
ssh_args(/Users/itsame/SomeProject/ansible/ansible.cfg) = -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=30m -o ControlPath=~/.ansible/cp/ansible-ssh-%h-%p-%r

SHELL:
=====

sh:
__
world_readable_temp(/Users/itsame/SomeProject/ansible/ansible.cfg) = True
```

### OS / Environment

macOS 15.6.1, MacBook Pro 2019 (Intel)

### Steps to Reproduce

Covered in the issue text.

### Expected Results

No error message, playbook runs.

### Actual Results

Error message as described, playbook execution does not begin.

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by mkrizek**
##### SUMMARY
Fixes https://github.com/ansible/ansible/issues/69882
Closes https://github.com/ansible/ansible/pull/83853
Fixes https://github.com/ansible/ansible/issues/85855
Fixes https://github.com/ansible/ansible/issues/85856

##### ISSUE TYPE

- Bugfix Pull Request

### CODE REVIEW

**Comment by mkrizek** [comment]
An alternative fix would be to just template `_raw_params` instead of `post_validate`'ing the whole include:
https://github.com/ansible/ansible/blob/27a56a34df7c7d879c2c0473aef5c58490024319/lib/ansible/playbook/helpers.py#L173

which is what we do for includes:
https://github.com/ansible/ansible/blob/27a56a34df7c7d879c2c0473aef5c58490024319/lib/ansible/playbook/included_file.py#L149

**Comment by s-hertel** [comment]
> An alternative fix would be to just template _raw_params instead of post_validate'ing the whole include:

I am in favor of this. That's how it was working prior to 2.19 https://github.com/ansible/ansible/blob/stable-2.18/lib/ansible/playbook/helpers.py#L172.

**Comment by mkrizek** [comment]
This basically does:
* copy the logic for `IncludeRole` for setting `parent_include_dir` from the `include_tasks` https://github.com/ansible/ansible/blob/5125ec797c129eaa64e168ed9ed6177a1d2de1a3/lib/ansible/playbook/included_file.py#L143
* bring back templating `parent_include.args.get('_raw_params')` instead of `post_validate`ing which causes issues - https://github.com/ansible/ansible/blob/stable-2.18/lib/ansible/playbook/helpers.py#L172
* avoid re-templating `task.args['_raw_params']` per each element in the parent chain

TODO/FIXME for $future: ideally merge the almost identical code for handling this for `import_tasks` and `include_tasks`

File: lib/ansible/playbook/helpers.py [hunk 1]
```diff
@@ -165,17 +165,40 @@ def load_list_of_tasks(ds, play, block=None, role=None, task_include=None, use_h
...
                             continue
-                        parent_include.post_validate(templar=templar)
-                        parent_include_dir = os.path.dirname(parent_include.args.get('_raw_params'))
+                        if isinstance(parent_include, IncludeRole):
+                            parent_include_dir = parent_include._role_path
+                        else:
+                            try:
+                                parent_include_dir = os.path.dirname(templar.template(parent_include.args.get('_raw_params')))
+                            except AnsibleUndefinedVariable as ex:
+                                if not parent_include.statically_loaded:
```
Comment (s-hertel) [inline lib/ansible/playbook/helpers.py]: Does _raw_params need templating here if it wasn't statically loaded? I'm wondering if the error handling for non-static parent includes is reachable.

File: lib/ansible/playbook/helpers.py [hunk 2]
```diff
@@ -165,17 +165,40 @@ def load_list_of_tasks(ds, play, block=None, role=None, task_include=None, use_h
...
+                                    raise AnsibleParserError(
+                                        message="Error when evaluating variable in dynamic parent "
+                                                f"include path {parent_include.args.get('_raw_params')!r}.",
+                                        help_text="When using static imports, the parent dynamic include "
+                                                  "cannot utilize host facts or variables from inventory.",
```
Comment (s-hertel) [inline lib/ansible/playbook/helpers.py]: I think the parent dynamic include can utilize host vars.

**Review by s-hertel — APPROVED** [review]
This looks good to me. I don't think the exception handling for dynamic parent includes is necessary, though I might be misunderstanding how that works.

File: lib/ansible/playbook/helpers.py (hunk 1 above)
Comment (mkrizek) [reply lib/ansible/playbook/helpers.py]: Good catch. I failed to check this when copying the code from 2.18.

**Review by s-hertel — APPROVED** [review]
