### ISSUE TITLE
ec2_ami: AttributeError: 'BlockDeviceType' object has no attribute 'encrypted'

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29583]
From @bryanlarsen on 2016-10-13T17:00:35Z

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

ec2_ami
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

doesn't work from: Ubuntu 14.04, with python2.7-boto 2.20.1-2ubuntu2
works from: Ubuntu 16.04, with 2.38.0-1ubuntu1
to: Ubuntu 16.04 on AWS
##### SUMMARY

ec2_ami doesn't work on Ubuntu 14.04, works fine on 16.04

I suspect python-boto might be the problem.  14.04 uses 2.20.1-2ubuntu2, 16.04 uses 2.38.0-1ubuntu1

##### STEPS TO REPRODUCE

```
    - ec2_ami:
        instance_id: "{{ awsInstanceId }}"
        region: "{{ awsRegion }}"
        ec2_access_key: "{{ hostvars[apiHost]['ec2_access_key'] }}"
        ec2_secret_key: "{{ hostvars[apiHost]['ec2_secret_key'] }}"
        wait: true
        name: "{{gitsha}}-{{templateName}}"
        wait_timeout: 3600
      register: ami
```

##### ACTUAL RESULTS

```
fatal: [production-worker-template.clara.io]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_Uk8_mk/ansible_module_ec2_ami.py\", line 560, in <module>\n    main()\n  File \"/tmp/ansible_Uk8_mk/ansible_module_ec2_ami.py\", line 552, in main\n    create_image(module, ec2)\n  File \"/tmp/ansible_Uk8_mk/ansible_module_ec2_ami.py\", line 419, in create_image\n    module.exit_json(msg=\"AMI creation operation complete\", changed=True, **get_ami_info(img))\n  File \"/tmp/ansible_Uk8_mk/ansible_module_ec2_ami.py\", line 331, in get_ami_info\n    block_device_mapping=get_block_device_mapping(image),\n  File \"/tmp/ansible_Uk8_mk/ansible_module_ec2_ami.py\", line 318, in get_block_device_mapping\n    'encrypted': bdm[device_name].encrypted,\nAttributeError: 'BlockDeviceType' object has no attribute 'encrypted'\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

Copied from original issue: ansible/ansible-modules-core#5256

**Comment by ansibot** [comment]
From @ansibot on 2016-10-13T17:00:35Z



@jjshoe ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Constantin07 @gunzy83 @scicoin-project @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by willthames** [comment]
I'm surprised a boto that old can be used for anything. We barely still support boto, we definitely don't support boto that old!

I recommend that you upgrade boto on your ubuntu 14.04 boxes using whatever mechanism is available. 

There's a lot of work in progress to move ec2_ami to boto3 (#28506), so if your ubuntu 14.04 boxes can run boto3, then they might benefit from that change as a 'fix' to your problem.
