### ISSUE TITLE
Jinja2 - Standard dict methods not working - 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'pop'

### ISSUE THREAD

**Issue by araghuraman123** [ansible/ansible#68650]
##### SUMMARY
When attempting to use standard dict methods against hostvars within Jinja2 templating expressions, error is thrown indicating no such attribute exists. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Jinja2 templating

##### ANSIBLE VERSION
ansible --version
ansible 2.9.3
python version = 3.8.1 (v3.8.1:1b293b6006, Dec 18 2019, 14:08:53) [Clang 6.0 (clang-600.0.57)]

pip show jinja2
Name: Jinja2
Version: 2.11.1

##### CONFIGURATION
ansible-config dump --only-changed
DEFAULT_FORKS(/Users/araghuraman/AnsiblePOC/playbooks/ansible.cfg) = 5
DEFAULT_GATHER_TIMEOUT(/Users/araghuraman/AnsiblePOC/playbooks/ansible.cfg) = 10
DEFAULT_TRANSPORT(/Users/araghuraman/AnsiblePOC/playbooks/ansible.cfg) = paramiko
HOST_KEY_CHECKING(/Users/araghuraman/AnsiblePOC/playbooks/ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/araghuraman/AnsiblePOC/playbooks/ansible.cfg) = False

##### OS / ENVIRONMENT
Control Node - macOS 10.14.3 (18D42)
Remote Nodes - Oracle Linux 7

##### STEPS TO REPRODUCE
Sample playbook -
---
- hosts: all
  gather_facts: true
  tasks:
    - name: sample task
      shell: echo "`hostname`";

- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: remove something from dict
      shell: echo "Trying to pop - {% set _var = hostvars['host1.xyz.com'].pop('groups') %}"

##### EXPECTED RESULTS
No error should be thrown for the attempted pop operation. The hostvars dict does contain a groups element within.

##### ACTUAL RESULTS
Error is thrown indicating the pop operation is not valid.

fatal: [127.0.0.1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'pop'\n\nThe error appears to be in '/path/facts.yml': line 11, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: remove something from dict\n      ^ here\n"}

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/files/template.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/template.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
The `HostVarsVars` object does not support deletion, which a `.pop` would perform.  This is working as expected.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by araghuraman123** [comment]
This was working fine in ansible 2.5.2. If we do need to effectively remove certain elements from within hostvars dict, what would the workaround be in ansible 2.9.3?

**Comment by sivel** [comment]
It is not possible.  See https://github.com/ansible/ansible/pull/60081
