### ISSUE TITLE
vv() got an unexpected keyword argument 'color'

### ISSUE THREAD

**Issue by mirskifa** [ansible/ansible#17920]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

ansible-playbook using statically included files
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Running ansible from the stable-2.1 branch fails after commit 6db31bb4c6f8b6338a38ae602d3b4f5ca8cbce5b was merged
##### STEPS TO REPRODUCE

1. Create playbook that uses include
2. clone ansible and use current stable-2.1 branch (currently at commit `6db31bb4c6f8b6338a38ae602d3b4f5ca8cbce5b`)
3. run playbook

##### EXPECTED RESULTS

Playbook runs
##### ACTUAL RESULTS

Ansible exits at start of playbook with

```
ERROR! Unexpected Exception: vv() got an unexpected keyword argument 'color'
```

**Comment by juliakreger** [comment]
Thank you @cinerama70!  Hopefully this, or a revert will merge soon to stable-2.1 so my CI jobs work again without me having to pin to a specific version.

**Comment by cinerama70** [comment]
https://github.com/ansible/ansible/commit/972379c9072e1debeefce7a7bf99ffbe1e9217c4 should have fixed this.

**Comment by Akasurde** [comment]
@cinerama70 Could you please confirm if this works for you ? 

needs_info

**Comment by bcoca** [comment]
closed via 972379c
