### ISSUE TITLE
vmware_guest_snapshot doesn't revert to snapshot with python 2.7.x and pyvmomi 5.5.0-2014.1.1

### ISSUE THREAD

**Issue by KroArtem** [ansible/ansible#24213]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest_snapshot

##### ANSIBLE VERSION

```
2.3.0.0
```

##### CONFIGURATION
Python 2.7.12
pyvmomi 5.5.0-2014.1.1

##### OS / ENVIRONMENT
Ubuntu 16.04 as a host
vmWare ESXi 5.5.0 as a destination machine.

##### SUMMARY
With pyvmomi 5.5.0-2014.1.1 installed reverting to a snapshot doesn't work. If I upgrade to pyvmomi 6.5 then everything works correctly.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  tasks:
    - vmware_guest_snapshot:
        validate_certs: False
        hostname: 192.168.0.64
        username: root
        password: mypassword
        name: myname
        state: revert
        snapshot_name: '{{ snapshot }}'
```

##### EXPECTED RESULTS
VM is reverted to required snapshot.

##### ACTUAL RESULTS
An error occures.

```
Revert to a snapshot (Command Line) (1s)
Starting: /home/test/buildAgent/temp/agentTmp/custom_script2614534317611333103
in directory: /home/test/buildAgent/work/8d0eb4ab9cd2f736/qa_fileserver
Using /etc/ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: restore_snapshot.yml *************************************************
1 plays in restore_snapshot.yml

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: test
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/test/.ansible/tmp/ansible-tmp-1493726233.54-243210034392552 `" && echo ansible-tmp-1493726233.54-243210034392552="` echo /home/test/.ansible/tmp/ansible-tmp-1493726233.54-243210034392552 `" ) && sleep 0'
<127.0.0.1> PUT /home/test/buildAgent/temp/buildTmp/tmpChY6OW TO /home/test/.ansible/tmp/ansible-tmp-1493726233.54-243210034392552/setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/test/.ansible/tmp/ansible-tmp-1493726233.54-243210034392552/ /home/test/.ansible/tmp/ansible-tmp-1493726233.54-243210034392552/setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/test/.ansible/tmp/ansible-tmp-1493726233.54-243210034392552/setup.py; rm -rf "/home/test/.ansible/tmp/ansible-tmp-1493726233.54-243210034392552/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [vmware_guest_snapshot] ***************************************************
task path: /home/test/buildAgent/work/8d0eb4ab9cd2f736/qa_fileserver/restore_snapshot.yml:4
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/cloud/vmware/vmware_guest_snapshot.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: test
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/test/.ansible/tmp/ansible-tmp-1493726233.86-247463733206249 `" && echo ansible-tmp-1493726233.86-247463733206249="` echo /home/test/.ansible/tmp/ansible-tmp-1493726233.86-247463733206249 `" ) && sleep 0'
<127.0.0.1> PUT /home/test/buildAgent/temp/buildTmp/tmpYwyQBd TO /home/test/.ansible/tmp/ansible-tmp-1493726233.86-247463733206249/vmware_guest_snapshot.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/test/.ansible/tmp/ansible-tmp-1493726233.86-247463733206249/ /home/test/.ansible/tmp/ansible-tmp-1493726233.86-247463733206249/vmware_guest_snapshot.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/test/.ansible/tmp/ansible-tmp-1493726233.86-247463733206249/vmware_guest_snapshot.py; rm -rf "/home/test/.ansible/tmp/ansible-tmp-1493726233.86-247463733206249/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/test/buildAgent/temp/buildTmp/ansible_QKhNxd/ansible_module_vmware_guest_snapshot.py", line 313, in <module>
    main()
  File "/home/test/buildAgent/temp/buildTmp/ansible_QKhNxd/ansible_module_vmware_guest_snapshot.py", line 290, in main
    pyv = PyVmomiHelper(module)
  File "/home/test/buildAgent/temp/buildTmp/ansible_QKhNxd/ansible_module_vmware_guest_snapshot.py", line 155, in __init__
    self.content = connect_to_api(self.module)
  File "/home/test/buildAgent/temp/buildTmp/ansible_QKhNxd/ansible_modlib.zip/ansible/module_utils/vmware.py", line 333, in connect_to_api
TypeError: SmartConnect() got an unexpected keyword argument 'sslContext'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/test/buildAgent/temp/buildTmp/ansible_QKhNxd/ansible_module_vmware_guest_snapshot.py\", line 313, in <module>\n    main()\n  File \"/home/test/buildAgent/temp/buildTmp/ansible_QKhNxd/ansible_module_vmware_guest_snapshot.py\", line 290, in main\n    pyv = PyVmomiHelper(module)\n  File \"/home/test/buildAgent/temp/buildTmp/ansible_QKhNxd/ansible_module_vmware_guest_snapshot.py\", line 155, in __init__\n    self.content = connect_to_api(self.module)\n  File \"/home/test/buildAgent/temp/buildTmp/ansible_QKhNxd/ansible_modlib.zip/ansible/module_utils/vmware.py\", line 333, in connect_to_api\nTypeError: SmartConnect() got an unexpected keyword argument 'sslContext'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
	to retry, use: --limit @/home/test/buildAgent/work/8d0eb4ab9cd2f736/qa_fileserver/restore_snapshot.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   
```

**Comment by ansibot** [comment]
cc @nerzhul
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by nerzhul** [comment]
Okay, a hard dependy to recent PyVmomi should be added, okay @gundalow for that ?

**Comment by KroArtem** [comment]
@nerzhul , according to their `Compatibility Policy` older versions may be required to work with ESXi 5.0, if I understand it correctly.

**Comment by nerzhul** [comment]
can you test with a vmomi 6.0 ? I will publish a patch with the minimum required version to ensure it works (i have ESX 5.5 at work and vmomi 6.5)

**Comment by KroArtem** [comment]
@nerzhul , I'll try it but not sure it will happen very soon (approx. 1 week).

**Comment by KroArtem** [comment]
Still remember about this one but still don't have enough time.

**Comment by ansibot** [comment]
cc @akasurde @dagwieers @dav1x @jctanner
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@KroArtem Are you still facing this problem ? If not we can close this issue.

needs_info

**Comment by KroArtem** [comment]
@Akasurde, nope, I'm not working with Ansible or esxi anymore but I still think there was a need to use specific version of pyvmomi. AFAIR I ended up using version 6.5
