### PR TITLE
Facts with lookups v2

### LINKED ISSUE #3802: bug related to with_items (and possibly isolated to the yum module) ?
After a pull from devel, I get an error on a play task that didn't have an error previously.  I used git bisect to track down the error.

```
git bisect good start: 863b88ba44ac9bb41401d634a2374c7b4d01ff89
git bisect bad start:1c361a99680305097c9b098aeb2413fdfe697064


1a4e6e415ef9fa156aecbd7682d309858542c69b is the first bad commit
commit 1a4e6e415ef9fa156aecbd7682d309858542c69b
Author: Serge van Ginderachter <serge@vanginderachter.be>
Date:   Thu Aug 8 16:21:03 2013 +0200

    Check for ansible_facts in results for with_ tasks

    that loop over a lookup plugin. Fixes #3704 and #3735
```

Here is some reproducing info:

``` yaml
# playbook.yml
# --- SNIP ---

- name: install common Centos packages
  yum: name={{ item }}
  with_items:
    - man
    - acpid
    - curl
    - git
    - ntp
    - pv
    - vim
    - zsh
    - sudo
    - logrotate
    - fail2ban
    - htop
    - wget
    - cronie
    - libselinux-python
  tags:   
    - packages

# --- SNIP ---

# This fails when running the playbook with the following command:

# ansible-playbook playbook.yml -i production --tags "packages" -K -c paramiko

# Error Text: 

# Traceback (most recent call last):
#   File "/usr/local/bin/ansible-playbook", line 259, in <module>
#     sys.exit(main(sys.argv[1:]))
#   File "/usr/local/bin/ansible-playbook", line 205, in main
#     pb.run()
#   File "/Library/Python/2.7/site-packages/ansible/playbook/__init__.py", line 258, in run
#     if not self._run_play(play):
#   File "/Library/Python/2.7/site-packages/ansible/playbook/__init__.py", line 566, in _run_play
#     if not self._run_task(play, task, False):
#   File "/Library/Python/2.7/site-packages/ansible/playbook/__init__.py", line 368, in _run_task
#     facts = res.get('ansible_facts', {})
# AttributeError: 'unicode' object has no attribute 'get'
```

### PR DESCRIPTION
**Pull request by srgvg**
possibly fixes #3802 but don't have redhat box to test it

### CODE REVIEW

**Comment by mpdehaan** [comment]
Hmm, that's not really good to submit a pull request to replace some code that had a known problem on a particular OS, and not test.

You can install a VM of CentOS or Fedora pretty easily.

Let us know and resubmit when you have it tested.

**Comment by mpdehaan** [comment]
Also please submit this as one commit, there's no reason to have the bug introduced in bba7c7f and corrected in c485787 when we can just have one patch that implements it working.

**Comment by jimi-c** [comment]
@sergevanginderachter I already have a patch for your original working, but since I had reverted it git wouldn't let me re-apply it.  All I did was this:

<pre>
@@ -361,8 +361,16 @@ class PlayBook(object):
 
         # add facts to the global setup cache
         for host, result in contacted.iteritems():
-            facts = result.get('ansible_facts', {})
-            self.SETUP_CACHE[host].update(facts)
+            if 'results' in result:
+                # task ran with_ lookup plugin, so facts are encapsulated in
+                # multiple list items in the results key
+                for res in result['results']:
+                    if type(res) == dict:
+                        facts = res.get('ansible_facts', {})
+                        self.SETUP_CACHE[host].update(facts)
+            else:
+                facts = result.get('ansible_facts', {})
+                self.SETUP_CACHE[host].update(facts)
             # extra vars need to always trump - so update  again following the facts
             self.SETUP_CACHE[host].update(self.extra_vars)
             if task.register:
</pre>

I'll go ahead and merge this in today, as I have tested it on my systems.
