### ISSUE TITLE
TypeError: exec_command() got an unexpected keyword argument 'become_user'

### ISSUE THREAD

**Issue by joaocc** [ansible/ansible#10573]
Hi,
We started getting this error when running a playbook on LXC guest with Ansible 1.9.0.1.
Since 1.8.4 is no longer available in the PPA, this is a showstopper.

The code below worked perfectly in 1.8.4

```
- hosts: all-my-huests
  gather_facts: yes
  sudo: true
  roles:
  - { role: debug-dump-all }
```

Now it breaks with this error

```
GATHERING FACTS *************************************************************** 
fatal: [guest-001] => Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 785, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 1028, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/lib/pymodules/python2.7/ansible/runner/action_plugins/normal.py", line 57, in run
    return self.runner._execute_module(conn, tmp, module_name, module_args, inject=inject, complex_args=complex_args)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 470, in _execute_module
    tmp = self._make_tmp_path(conn)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 1284, in _make_tmp_path
    result = self._low_level_exec_command(conn, cmd, None, sudoable=False)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 1165, in _low_level_exec_command
    in_data=in_data)
TypeError: exec_command() got an unexpected keyword argument 'become_user'
```

**Comment by bcoca** [comment]
this looks like v1.9 runner is trying to execute a 1.8 connection plugin, what connection are you using?

**Comment by joaocc** [comment]
I'm using Mic92/ansible-lxc.
However it appears that this is already fixed in
https://github.com/Mic92/ansible-lxc/commit/1377368cbe6c65dc080a336c9094114002ca615b.

Will check.
Thx

**Comment by bcoca** [comment]
closing as this was not an ansible bug.

**Comment by joshunger** [comment]
Can you give me a recommended fix?  Trying to fix another plugin.  Thanks.
