### PR TITLE
wait_for_connection: Wait for system to become reachable

### LINKED ISSUE #19998: wait_for_connection: action plugin to wait until ansible connection is restored
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

wait_for_connection

##### ANSIBLE VERSION

v2.3

##### SUMMARY

When you are building new systems (think: vmware clone) it would be nice to be able to just wait until you can run something remotely. Usually what's being done right now is that we use **wait_for** on e.g. tcp/22 and as soon there is a connection we can use it.

In the Windows world it's not that simple. The port may already be listened on, but WinRM is not working yet (it may take up to 20 seconds before it starts working instead of giving HTTP 500). win_reboot understands this quite well and what win_reboot does I want to have as well (without the reboot, that is).

Even on Linux your SSH may already be up, but the SSH keys may not have been deployed yet (think of kickstart SSH during installation, not %post). So testing for the connection to be actually working is what is required.

It is important to understand that depending on the systems configuration this could mean testing the ssh connection (on a different port using different credentials) or winrm connection (using kerberos, https, or other auth metods) based on a systems characteristics as configured in ansible.

That's why I'd like to have a wait_for_connection that is just an action plugin and works for both Linux and Windows equally well. I plan to write this the coming days.

```yaml
- name: Wait for system to become reachable
  wait_for_connection:
    timeout: 600
    sleep: 5
```

### PR DESCRIPTION
**Pull request by dagwieers**
##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

wait_for_connection

##### ANSIBLE VERSION

v2.3

##### SUMMARY

This action plugin allows to check when a system is back online and usable by Ansible.

As an example, when doing a SysPrep and running Enable-WinRM.ps1, it takes between 10 to 20 seconds between the WinRM TCP port to open, and it actually being able to serve Ansible requests. This time is variable and depends on the boot process.

Current implementation should work for all connection types using the **ping** module (or **win_ping** on winrm/powershell)

This fixes #19998

### CODE REVIEW

**Comment by dagwieers** [comment]
I don't particularly like the (long) name, but it's the best I could come up with :-/

**Comment by dagwieers** [comment]
PS I would like to add the specific connection-related stuff (e.g. connect-test, ping-test) as part of the connection plugin itself. This way new connection methods can implement their own methodology.

**Comment by dagwieers** [comment]
I am also contemplating a 'wait to become unreachable' and a 'wait for becoming reachable again' modus.
Again, not sure what terminology would be best. present/absent feels a bit odd here.

**Comment by bcoca** [comment]
bikeshedding: 'connect'

**Comment by bcoca** [comment]
The more i think of this, the more it seems like an expansion of ping

**Comment by dagwieers** [comment]
bcoca: I agree, but some concerns:
- What would the interface look like ? Ping is so nice in its simplicity.
- People will probably not find this hidden in ping, most will do something sub-optimal with `wait_for` instead.
- Module ping/win_ping is a real module, where this is only action_plugin

**Comment by dagwieers** [comment]
ready_for_review

File: test/integration/targets/wait_for_connection/aliases [hunk 1]
```diff
@@ -0,0 +1,2 @@
+posix/ci/group2
+windows/ci/group2
```
Comment (mattclay) [inline test/integration/targets/wait_for_connection/aliases]: Missing newline at end of file.

File: test/integration/targets/wait_for_connection/tasks/main.yml [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+    connect_timeout: 5
+    sleep: 1
+    timeout: 10
+
+- name: Test local connection on control master
+  wait_for_connection:
+    connect_timeout: 5
+    sleep: 1
+    timeout: 10
+  connection: local
```
Comment (mattclay) [inline test/integration/targets/wait_for_connection/tasks/main.yml]: Missing newline at end of file.

**Review by mattclay — CHANGES_REQUESTED** [review]

File: test/integration/targets/wait_for_connection/aliases (hunk 1 above)
Comment (dagwieers) [reply test/integration/targets/wait_for_connection/aliases]: I don't really see why that is important. That is the default in VIM.
Ironically PEP8 is requiring me to remove the trailing newline, and you are asking me to add one :-)

File: test/integration/targets/wait_for_connection/tasks/main.yml (hunk 2 above)
Comment (dagwieers) [reply test/integration/targets/wait_for_connection/tasks/main.yml]: I don't really see why that is important. That is the default in VIM.
Ironically PEP8 is requiring me to remove the trailing newline, and you are asking me to add one :-)

File: test/integration/targets/wait_for_connection/aliases (hunk 1 above)
Comment (mattclay) [reply test/integration/targets/wait_for_connection/aliases]: PEP 8 requires a newline at the end of python files. Perhaps you're confusing it with a blank line?

As for the rational, it's about making clean diffs for future PRs. If I need to an another line at the end of the file, I need to modify the last line to add a newline. If it already has a newline, that's not necessary.

File: test/integration/targets/wait_for_connection/tasks/main.yml (hunk 2 above)
Comment (mattclay) [reply test/integration/targets/wait_for_connection/tasks/main.yml]: Same as above.

File: test/integration/targets/wait_for_connection/aliases (hunk 1 above)
Comment (dagwieers) [reply test/integration/targets/wait_for_connection/aliases]: Well, a newline at the end of my file is a blank line in my editor.

File: test/integration/targets/wait_for_connection/tasks/main.yml (hunk 2 above)
Comment (dagwieers) [reply test/integration/targets/wait_for_connection/tasks/main.yml]: Done.

**Comment by dagwieers** [comment]
Something wrong with Shippable ?

**Comment by mattclay** [comment]
CI was failing due to changes to unit tests which passed CI on the PR but failed after merge. That change has been reverted and affected PRs are being run through CI again.

**Review by mattclay — APPROVED** [review]

File: lib/ansible/modules/utilities/logic/wait_for_connection.py [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+# along with Ansible.  If not, see <http://www.gnu.org/licenses/>.
+
+ANSIBLE_METADATA = {'status': ['stableinterface'],
+                    'supported_by': 'core',
+                    'version': '1.0'}
+
+DOCUMENTATION = '''
+---
+module: wait_for_connection
+short_description: Waitis until remote system is reachable/usable
```
Comment (jhawkesworth) [inline lib/ansible/modules/utilities/logic/wait_for_connection.py]: Tiny typo here 'Waitis' -> 'Waits'

Comment (dagwieers) [reply lib/ansible/modules/utilities/logic/wait_for_connection.py]: Thanks ! Fixed.

**Comment by dagwieers** [comment]
CI failed with TIMEOUT :-/

**Comment by mattclay** [comment]
CI failure due to:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'Connection' object has no attribute '_winrm_host'
```

**Comment by dagwieers** [comment]
Close and reopen because Shippable status was UNSTABLE ?!?

**Comment by jhawkesworth** [comment]
I think this is going to be very useful!

shipit

**Comment by mattclay** [comment]
@dagwieers The unable status means that tests passed, but only after an automatic retry. This usually indicates a network error, such as failure to download a package required for a test.

**Comment by dagwieers** [comment]
ready_for_review

File: lib/ansible/modules/utilities/logic/wait_for_connection.py [hunk 4]
```diff
@@ -0,0 +1,93 @@
...
+      - name: VLAN 123
+        ip: '{{ ansible_host }}'
+        netmask: '{{ vm_netmask }}'
+        gateway: '{{ gw_ip }}'
+        domain: '{{ domain }}'
+        dns_servers: [ '{{ dns_ip }}' ]
+      customization:
+        hostname: '{{ vm_shortname }}'
+        runonce:
+        - powershell.exe -ExecutionPolicy Unrestricted -File C:\Windows\Temp\Enable-WinRM.ps1 -CertValidityDays 3650 -ForceNewSSLCert
```
Comment (jhawkesworth) [inline lib/ansible/modules/utilities/logic/wait_for_connection.py]: I know you aren't fond of the current name, but for clarity I'd consider referring to the ConfigureRemotingForAnsible.ps1 name here

Comment (dagwieers) [reply lib/ansible/modules/utilities/logic/wait_for_connection.py]: Oh right, the example was written during the name-discussions. Will rename !

**Comment by dagwieers** [comment]
ready_for_review
bot_status

**Comment by mattclay** [comment]
CI failure on wait_for_connection for FreeBSD for the chroot test. I'm not sure why this happens, since ansible ping (and other modules) work just fine for the same connection:

```
2017-02-17 00:50:06 fatal: [chroot-pipelining]: FAILED! => {
2017-02-17 00:50:06     "changed": false, 
2017-02-17 00:50:06     "elapsed": 600, 
2017-02-17 00:50:06     "failed": true, 
2017-02-17 00:50:06     "msg": "timed out waiting for ping module test success: 'ping'"
2017-02-17 00:50:06 }
```

**Comment by dagwieers** [comment]
No CI today ?

**Comment by dagwieers** [comment]
It's the second time I see that an amended commit does not start CI. In fact, there is no CI entry in the summary below. Closing and re-opening the PR does work.

**Comment by mattclay** [comment]
Shippable is deploying a fix for the lost webooks issue this weekend. That should solve the missing CI problem.

**Comment by dagwieers** [comment]
@mattclay Ah, I didn't know this symptom was related to that. Sorry for the noise. I'll refrain from sending you these bits until the dust has settled :-) Thanks again for your help and feedback !

**Comment by dagwieers** [comment]
@mattclay It seems that the issue with FreeBSD was fixed by adding `task_vars` to the `_execute_module()` call. This was really unnecessary because it's the ping-module (with no module_args anyway). But somehow FreeBSD+chroot+pipelining is affected by this. Weird.

**Comment by dagwieers** [comment]
ready_for_review

**Comment by dagwieers** [comment]
ready_for_review
shipit

**Comment by dagwieers** [comment]
ready_for_review

**Comment by mattclay** [comment]
Closing and re-opening to trigger CI.

**Comment by dagwieers** [comment]
@gundalow @nitzmahone @mattclay @jhawkesworth ready_for_review

**Comment by jhawkesworth** [comment]
shipit

File: lib/ansible/plugins/connection/winrm.py [hunk 5]
```diff
@@ -86,6 +87,15 @@ def __init__(self,  *args, **kwargs):
 
         super(Connection, self).__init__(*args, **kwargs)
 
+        self.host = self._play_context.remote_addr
```
Comment (nitzmahone) [inline lib/ansible/plugins/connection/winrm.py]: Do these values even need to exist in most of the plugins? Only reason I can see that they'd need to is if `transport_test` were defined on the base connection (and override-able by plugins that don't use a TCP port). Otherwise, `transport_test` can just use the existing `self._winrm_(host/port)`. If they do stay, I'd prefer that these values be init'd in `set_host_overrides` off the existing values instead of duplicating the logic here (at least for this plugin- IIRC nobody else uses `set_host_overrides` ATM). I've verified that it works with that change (since you're using the play's existing connection, it's already been run by the time it gets there).

File: lib/ansible/plugins/action/wait_for_connection.py [hunk 6]
```diff
@@ -0,0 +1,119 @@
...
+            # Use the ping module test to determine end-to-end connectivity
+            self.do_until_success_or_timeout(ping_module_test, timeout, connect_timeout, what_desc="ping module test success", sleep=sleep)
+
+        except TimedOutException:
+            e = get_exception()
+            result['failed'] = True
+            result['msg'] = str(e)
+
+        elapsed = datetime.now() - start
+        result['elapsed'] = elapsed.seconds
```
Comment (nitzmahone) [inline lib/ansible/plugins/action/wait_for_connection.py:117]: `elapsed_sec`/`'elapsed_seconds`? I personally dislike time values/args without units...

**Review by nitzmahone — CHANGES_REQUESTED** [review]
A couple of minor things... Unless this stock version of `transport_test` gets moved to the connection base (which isn't a bad idea IMO- no sense in duplicating what most connection plugins need), I think a number of the host/port members you added can probably go away.

File: lib/ansible/plugins/action/wait_for_connection.py (hunk 6 above)
Comment (dagwieers) [reply lib/ansible/plugins/action/wait_for_connection.py:117]: I used the same output as wait_for. That was the intent.

File: lib/ansible/plugins/connection/winrm.py (hunk 5 above)
Comment (dagwieers) [reply lib/ansible/plugins/connection/winrm.py]: To be honest I preferred some consistency in the various connection plugins. But I really don't mind.
The difference now looks more better self-contained, so I am pleased with that as well.

**Comment by dagwieers** [comment]
@gundalow @nitzmahone @mattclay @jhawkesworth Can we get this merged before v2.3 freeze ?

File: lib/ansible/plugins/action/wait_for_connection.py (hunk 6 above)
Comment (dagwieers) [reply lib/ansible/plugins/action/wait_for_connection.py:117]: The return values are now documented, and the units are specified there as well.

**Comment by jhawkesworth** [comment]
Still looks good to me.  I guess @nitzmahone will want to re-check.

In case its been invalidated by subsequent commits

shipit

**Comment by dagwieers** [comment]
Please merge before 12AM  :-)
