### ISSUE TITLE
not able to access group variable host not working in ansible 2.8.0

### ISSUE THREAD

**Issue by thatsk** [ansible/ansible#58385]
##### SUMMARY
group_vars is not working anymore

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible core

##### ANSIBLE VERSION
```
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### OS / ENVIRONMENT
centos7

##### STEPS TO REPRODUCE
```yaml
    - name: distribute the ssh key to the remote hosts
      shell: "/usr/local/bin/sshpass -p \"{{remote_machine_password}}\" ssh-copy-id -o StrictHostKeyChecking=no -i ~/.ssh/{{ssh_key_filename}}.pub  \"{{remote_machine_username}}@{{ hostvars[item].ansible_host }}\""
      register: ssh_copy_id_execution
      with_items:
        - "{{ groups['ansible_setup_passwordless_setup_group']}}"
      failed_when: ssh_copy_id_execution.rc != 0
```

##### EXPECTED RESULTS
it should get hosts from hosts file

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! =>
msg: |-
The task includes an option with an undefined variable. The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_host'
```

**Comment by thatsk** [comment]
https://github.com/ilias-sp/ansible-setup-passwordless-ssh/blob/master/ansible_setup_passwordless_ssh.yml

**Comment by bcoca** [comment]
how and where are you setting ansible_host?

needs_info

**Comment by thatsk** [comment]
resolved. looks like hosts file has some problem
