### ISSUE TITLE
bigip_pool_member error - merge_provider_params AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by doogieho7** [ansible/ansible#43916]
##### SUMMARY

After ansible version upgrade from 2.4 to 2.6, bigip_pool_member module is not working.
below ansible playbook was worked in ansible 2.4

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

bigip_pool_member.py

##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /home/spass/.ansible.cfg
  configured module search path = [u'/home/spass/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]
```

##### PYTHON VERSION
```
Python 2.7.6
```

##### LIBRARY VERSION
```
bigsuds==1.0.6
f5-sdk==3.0.19
```

##### CONFIGURATION

DEFAULT_DEBUG(env: ANSIBLE_DEBUG) = False
DEFAULT_HOST_LIST(/home/spass/.ansible.cfg) = [u'/home/spass/hosts']
DEFAULT_LOG_PATH(env: ANSIBLE_LOG_PATH) = /home/spass/ansible.log
DEFAULT_REMOTE_PORT(/home/spass/.ansible.cfg) = 4022
HOST_KEY_CHECKING(/home/spass/.ansible.cfg) = False

```
[/home/spass/.ansible.cfg]
remote_port    = 4022
host_key_checking = False
```

##### OS / ENVIRONMENT

ubuntu 14.04.5 LTS

##### STEPS TO REPRODUCE

```yaml
  - name: LBControl - disable host (forced offline )
    bigip_pool_member:
        server: 172.24.2.1
        server_port: 443
        user: stgspass
        password: "!wkrdjq00"
        validate_certs: False
        pool: pool_RGN_112.107.85.170_10080
        host: 172.24.2.41
        port: 10080
        state: "present"
        session_state: "disabled"
        monitor_state: "disabled"
    delegate_to: "jumphost-local"
```

##### EXPECTED RESULTS

I expected that force pool member(=172.24.2.41) offline

##### ACTUAL RESULTS

```
TASK [LBControl - disable host (forced offline )] *********************************************************************************
task path: /home/spass/components/spass_svc_rgn/playbooks/test_rgn.yml:49
<127.0.0.1> ESTABLISH CONNECTION FOR USER: spass on PORT 2022 TO 127.0.0.1
<127.0.0.1> CONFIGURE PROXY COMMAND FOR CONNECTION: sshpass -p dptmvotm1@ ssh -q -A -W 127.0.0.1:2022 -o StrictHostKeyChecking=no -p 2022 spass@112.107.85.156
<127.0.0.1> EXEC /bin/sh -c 'echo ~spass && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/spass/.ansible/tmp/ansible-tmp-1533887988.97-49148072061992 `" && echo ansible-tmp-1533887988.97-49148072061992="` echo /home/spass/.ansible/tmp/ansible-tmp-1533887988.97-49148072061992 `" ) && sleep 0'
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/network/f5/bigip_pool_member.py
<127.0.0.1> PUT /home/spass/.ansible/tmp/ansible-local-10254M4a0JC/tmp9h194I TO /home/spass/.ansible/tmp/ansible-tmp-1533887988.97-49148072061992/bigip_pool_member.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/spass/.ansible/tmp/ansible-tmp-1533887988.97-49148072061992/ /home/spass/.ansible/tmp/ansible-tmp-1533887988.97-49148072061992/bigip_pool_member.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/jdk1.8.0_51/bin JAVA_HOME=/usr/lib/jvm/jdk1.8.0_51 /usr/bin/python /home/spass/.ansible/tmp/ansible-tmp-1533887988.97-49148072061992/bigip_pool_member.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/spass/.ansible/tmp/ansible-tmp-1533887988.97-49148072061992/ > /dev/null 2>&1 && sleep 0'
fatal: [pre-prd-an2b-spass_svc_rgn-01 -> None]: FAILED! => {
    "changed": false, 
    "module_stderr": "", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_Ko3I41/ansible_module_bigip_pool_member.py\", line 913, in <module>\r\n    main()\r\n  File \"/tmp/ansible_Ko3I41/ansible_module_bigip_pool_member.py\", line 902, in main\r\n    client = F5Client(**module.params)\r\n  File \"/tmp/ansible_Ko3I41/ansible_modlib.zip/ansible/module_utils/network/f5/bigip.py\", line 32, in __init__\r\n  File \"/tmp/ansible_Ko3I41/ansible_modlib.zip/ansible/module_utils/network/f5/common.py\", line 396, in merge_provider_params\r\nAttributeError: 'NoneType' object has no attribute 'get'\r\n", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/f5/bigip_pool_member.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/f5/bigip_pool_member.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @caphrim007
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Hi @doogieho7,

Thank you for the issue, just so you are aware we have a dedicated Working Group for network.
You can find other people interested in this in #ansible-network on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by caphrim007** [comment]
this should be fixed in the f5devcentral.f5ansible galaxy role. If it remains an issue, please file an issue with F5 here https://github.com/F5Networks/f5-ansible
