### ISSUE TITLE
Getting Error When Using Network_cli and not providing - provider

### ISSUE THREAD

**Issue by amb1s1** [ansible/ansible#42708]
##### SUMMARY
We get an error when trying to use nxos_install_os with network_cli and not providing provider. 

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_install_os

##### ANSIBLE VERSION

```
ansible 2.5.6
  config file = /Users/gomezd/sum/ansible.cfg
  configured module search path = [u'/Users/gomezd/sum/library']
  ansible python module location = /Users/gomezd/Envs/sum/lib/python2.7/site-packages/ansible
  executable location = /Users/gomezd/Envs/sum/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 16:44:08) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

##### CONFIGURATION
task path: /Users/gomezd/sum/roles/os_upgrade/tasks/nxos-5k.yml:40
DEFAULT_HOST_LIST(/Users/gomezd/sum/ansible.cfg) = [u'/Users/gomezd/sum/inventory']
DEFAULT_MODULE_PATH(/Users/gomezd/sum/ansible.cfg) = [u'/Users/gomezd/sum/library']
HOST_KEY_CHECKING(/Users/gomezd/sum/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/Users/gomezd/sum/ansible.cfg) = 700
PERSISTENT_CONNECT_TIMEOUT(/Users/gomezd/sum/ansible.cfg) = 700
RETRY_FILES_ENABLED(/Users/gomezd/sum/ansible.cfg) = False

##### OS / ENVIRONMENT
MAC OS 10.13.5

##### STEPS TO REPRODUCE

```yaml
- name: Playbook
   connection: network_cli
   hosts: 5k
   gather_facts: no
   tasks:

   - name: '4 - INSTALL OS'
      nxos_install_os :
        system_image_file: "{{ system_image }}"
        kickstart_image_file: "{{ kickstart_image }}"
      register: upgrade
```
group_vars/5k.yml
```yaml
ansible_network_os: nxos
ansible_user: admin
ansible_ssh_pass: pass
```
##### EXPECTED RESULTS

```
<5k1> using connection plugin network_cli (was local)
Using module file /Users/gomezd/Envs/sumitomo/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_install_os.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: gomezd
<localhost> EXEC /bin/sh -c 'echo ~gomezd && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/gomezd/.ansible/tmp/ansible-tmp-1531423985.0-182056835953952 `" && echo ansible-tmp-1531423985.0-182056835953952="` echo /Users/gomezd/.ansible/tmp/ansible-tmp-1531423985.0-182056835953952 `" ) && sleep 0'
<localhost> PUT /Users/gomezd/.ansible/tmp/ansible-local-33510OoFtsp/tmpLSDC1G TO /Users/gomezd/.ansible/tmp/ansible-tmp-1531423985.0-182056835953952/nxos_install_os.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/gomezd/.ansible/tmp/ansible-tmp-1531423985.0-182056835953952/ /Users/gomezd/.ansible/tmp/ansible-tmp-1531423985.0-182056835953952/nxos_install_os.py && sleep 0'
<localhost> EXEC /bin/sh -c '/Users/gomezd/Envs/sumitomo/bin/python2.7 /Users/gomezd/.ansible/tmp/ansible-tmp-1531423985.0-182056835953952/nxos_install_os.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /Users/gomezd/.ansible/tmp/ansible-tmp-1531423985.0-182056835953952/ > /dev/null 2>&1 && sleep 0'
ok: [5k1 -> localhost] => {
    "changed": false,
    "install_state": [
        "\"Module 1 3 might not be supported in the new image,",
        "Compatibility check is done:",
        "Module  bootable          Impact  Install-type  Reason",
        "------  --------  --------------  ------------  ------",
        "Images will be upgraded according to following table:",
        "Module             Image         Running-Version             New-Version  Upg-Required",
        "------  ----------------  ----------------------  ----------------------  ------------",
        "     1            system             7.3(3)N1(1)             7.3(3)N1(1)            no",
        "     1         kickstart             7.3(3)N1(1)             7.3(3)N1(1)            no",
        "     1              bios      v3.6.0(05/09/2012)      v3.6.0(05/09/2012)            no",
        "     1         power-seq                    v3.0                    v3.0            no",
        "     1            SFP-uC                v1.1.0.0                v1.0.0.0            no",
        "     3         power-seq                    v2.0                    v2.0            no",
        "     1   microcontroller                v1.2.0.1                v1.2.0.1            no"
    ],
    "invocation": {
        "module_args": {
            "auth_pass": null,
            "authorize": null,
            "host": "5k1",
            "issu": "no",
            "kickstart_image_file": "n5000-uk9-kickstart.7.3.3.N1.1.bin",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 22,
            "provider": {
                "auth_pass": null,
                "authorize": null,
                "host": "5k1",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 22,
                "ssh_keyfile": null,
                "timeout": 700,
                "transport": "cli",
                "use_proxy": true,
                "use_ssl": null,
                "username": "admin",
                "validate_certs": null
            },
            "ssh_keyfile": null,
            "system_image_file": "n5000-uk9.7.3.3.N1.1.bin",
            "timeout": 700,
            "transport": "cli",
            "use_proxy": true,
            "use_ssl": null,
            "username": "admin",
            "validate_certs": null
        }
    }
}
```

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/3q/sd1ybtrd0p5fc9pbhnp9dscc0000gn/T/ansible_6bOz6y/ansible_module_nxos_install_os.py", line 573, in <module>
    main()
  File "/var/folders/3q/sd1ybtrd0p5fc9pbhnp9dscc0000gn/T/ansible_6bOz6y/ansible_module_nxos_install_os.py", line 547, in main
    check_ansible_timer(module)
  File "/var/folders/3q/sd1ybtrd0p5fc9pbhnp9dscc0000gn/T/ansible_6bOz6y/ansible_module_nxos_install_os.py", line 146, in check_ansible_timer
    if data.get('timeout') is None:
AttributeError: 'NoneType' object has no attribute 'get'

fatal: [5k1]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/3q/sd1ybtrd0p5fc9pbhnp9dscc0000gn/T/ansible_6bOz6y/ansible_module_nxos_install_os.py\", line 573, in <module>\n    main()\n  File \"/var/folders/3q/sd1ybtrd0p5fc9pbhnp9dscc0000gn/T/ansible_6bOz6y/ansible_module_nxos_install_os.py\", line 547, in main\n    check_ansible_timer(module)\n  File \"/var/folders/3q/sd1ybtrd0p5fc9pbhnp9dscc0000gn/T/ansible_6bOz6y/ansible_module_nxos_install_os.py\", line 146, in check_ansible_timer\n    if data.get('timeout') is None:\nAttributeError: 'NoneType' object has no attribute 'get'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/nxos/nxos_install_os.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/nxos/nxos_install_os.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @GGabriele @jedelman8 @mikewiebe @privateip @rahushen @rcarrillocruz @trishnaguha @tstoner
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by trishnaguha** [comment]
@amb1s1 I am not sure what you meant by "not providing provider"

**Comment by trishnaguha** [comment]
@amb1s1 This is fixed in Ansible 2.6 https://github.com/ansible/ansible/commit/9f026309a69497630a37affbae5ccc46fe2cbd1b. Note that if you are using network_cli you will need to use ANSIBLE_PERSISTENT_CONNECT_TIMEOUT and ANSIBLE_PERSISTENT_COMMAND_TIMEOUT. Can you please try on 2.6?

**Comment by amb1s1** [comment]
It works on 2.6. Any reason why this bug cannot be fix on this version?

**Comment by trishnaguha** [comment]
@amb1s1 It is because nxapi still uses on connection local and provider values in 2.5, it doesn't have ability to use PERSISTENT timeout values. This commit will break nxapi in 2.5. Hence we cannot cherry-pick this fix to 2.5. But from 2.6 onwards, with httpapi connection plugin that is resolved.

**Comment by amb1s1** [comment]
@trishnaguha make sense
