### ISSUE TITLE
ERROR! conflicting action statements: ping, async

### ISSUE THREAD

**Issue by 2bithacker** [ansible/ansible#31116]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
ping

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /Users/chip/Personal/ansible/ansible.cfg
  configured module search path = [u'/Users/chip/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(/Users/chip/Personal/ansible/ansible.cfg) = True
CACHE_PLUGIN(/Users/chip/Personal/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/Users/chip/Personal/ansible/ansible.cfg) = /tmp/cachedir
CACHE_PLUGIN_TIMEOUT(/Users/chip/Personal/ansible/ansible.cfg) = 86400
COMMAND_WARNINGS(/Users/chip/Personal/ansible/ansible.cfg) = False
DEFAULT_GATHERING(/Users/chip/Personal/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/Users/chip/Personal/ansible/ansible.cfg) = [u'/Users/chip/Personal/ansible/inventory']
DEFAULT_MANAGED_STR(/Users/chip/Personal/ansible/ansible.cfg) = Ansible managed, do not edit directly!
DEFAULT_VAULT_PASSWORD_FILE(/Users/chip/Personal/ansible/ansible.cfg) = /Users/chip/.vaultpass
RETRY_FILES_ENABLED(/Users/chip/Personal/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Mac OS X 10.12.6 x86_64

##### SUMMARY

Since upgrading to Ansible 2.4.0.0 I get an error when trying to use `ansible -m` with the `ping`, `setup`, and several other modules.  Running playbooks works fine though.

##### STEPS TO REPRODUCE

```
> ansible all -m ping
ERROR! conflicting action statements: ping, async
exception type: <class 'ansible.errors.AnsibleParserError'>
exception: conflicting action statements: ping, async
```

##### EXPECTED RESULTS

I expect the ping module to hit each host and return success.

##### ACTUAL RESULTS

```
> ansible all -m ping -vvvv
ansible 2.4.0.0
  config file = /Users/chip/Personal/ansible/ansible.cfg
  configured module search path = [u'/Users/chip/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
Using /Users/chip/Personal/ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /Users/chip/Personal/ansible/inventory/hosts inventory source with ini plugin
ERROR! conflicting action statements: ping, async
exception type: <class 'ansible.errors.AnsibleParserError'>
exception: conflicting action statements: ping, async
```

**Comment by bcoca** [comment]
I cannot reproduce this, this is specially weird since async is not an action, but a keyword that affects actions.

Can you try a clean install?

**Comment by 2bithacker** [comment]
Yeah, this must be something broken in my environment. I created a virtualenv and installed a fresh ansible 2.4.0.0 in there and it works fine.

**Comment by leifmadsen** [comment]
I ran into a similar issue when using the `async` command in a playbook. Not sure exactly what the problem was, but I completely removed Ansible using `dnf` from my Fedora 26 host, searched for anything related to Ansible on the host (removed `$HOME/ansible/` and an old site-package in the `/usr/lib/python2.7` directory).

Installed Ansible again, and now it works.

**Comment by onebraveman** [comment]
I meet same ERROR after i upgrade ansible to 2.4.0.0.

**Comment by leifmadsen** [comment]
As far as I can tell, there is something that results in a conflict when doing an "upgrade" to Ansible 2.4.0.0. The work around appears to fully remove Ansible (`dnf remove ansible`) and then do a full new install.

**Comment by onebraveman** [comment]
Thanks the suggestion of @leifmadsen . I found pip install two version of ansible, 2.2.0 and 2.4.0. So it works for me after uninstall two version and install Ansible 2.4.0.

**Comment by hughsaunders** [comment]
I installed python3 via homebrew and this caused various problems with ansible.  After reading the comments above I thought I may have multiple versions installed. `pip freeze` only showed 2.4, I uninstalled it, then ran uninstall again and the second time it removed 2.2! 

Next problem was that the python3 upgrade meant that `pip` defaulted to python3, so ansible was installed in python3's site packages and not available to python2:

```
15:47 $ python2 /usr/local/bin/ansible -i openstack.py "long-running*" -m ping
Traceback (most recent call last):
  File "/usr/local/bin/ansible", line 40, in <module>
    import ansible.constants as C
ImportError: No module named ansible.constants
```

Reinstalled with pip2 to solve that.

Next problem: 
```
ERROR! Unexpected Exception, this is probably a bug: 'InventoryManager' object has no attribute 'get_group_dict'
```
That was probably due to an icompatible plugin so I moved ~/.ansible out the way and now ansible is working again.
