### ISSUE TITLE
S3: 'module' object has no attribute 'connect_to_region'

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30110]
##### ISSUE TYPE

bug report

##### COMPONENT NAME

s3 module

##### ANSIBLE VERSION

1.9.1

##### OS / ENVIRONMENT

OSX 10.9.5 and Ubuntu 12.04

##### SUMMARY

Connection to the S3 is failing (we are using eu-west-1 if this matters)

##### STEPS TO REPRODUCE

Run this playbook

```
- hosts: {{Remote_host}}
  tasks:
    - name: 's3'
      s3: bucket=test_bucket object=test_object aws_access_key={{ lookup('env','AWS_ACCESS_KEY') }} aws_secret_key={{ lookup('env','AWS_SECRET_KEY') }} mode=create region=eu-west-1
```

##### EXPECTED RESULTS

The bucket gets created.

##### ACTUAL RESULTS

```
failed: [Remote_host] => {"failed": true}
msg: Failed to connect to S3: 'module' object has no attribute 'connect_to_region'

FATAL: all hosts have already failed -- aborting
```

Copied from original issue: ansible/ansible-modules-core#1544

**Comment by ansibot** [comment]
From @bennojoy on 2015-06-18T09:57:08Z

@samyray can you please try with latest devel and let us know if you have the same issue there.

**Comment by ansibot** [comment]
From @samyray on 2015-06-18T09:57:08Z

@bennojoy thanks for looking, just tried with below version:

```
ansible-playbook 2.0.0 (devel 7c65f3ddd7) last updated 2015/06/18 13:43:57 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 9acc7c402f) last updated 2015/06/18 13:44:03 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 2f967a949f) last updated 2015/06/18 13:44:09 (GMT +000)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/18 13:44:15 (GMT +000)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/18 13:44:23 (GMT +000)
  configured module search path = None
```

And got the same result:

```
fatal: [Remote_host]: FAILED! => {"msg": "Failed to connect to S3: 'module' object has no attribute 'connect_to_region'", "failed": true, "changed": false, "invocation": {"module_name": "s3", "module_args": {"aws_secret_key": "", "aws_access_key": "", "region": "eu-west-1", "object": "test_object", "bucket": "test_bucket", "mode": "create"}}}
```

btw, it works fine on ansible 1.7.2 (don't have any other versions to check unfortunately)

**Comment by ansibot** [comment]
From @bennojoy on 2015-06-18T09:57:08Z

@samyray from your output seems like it is not able to connect to s3, does you system have internet access ? also i am not able to reproduce this.

**Comment by ansibot** [comment]
From @shay-li on 2015-06-18T09:57:08Z

Reproduce 

Ansible Version:
1.9.1
OS:
Ubuntu 14.04

What`s the status of this bug?

**Comment by ansibot** [comment]
From @jsabo on 2015-06-18T09:57:08Z

I'm seeing the same issue but it's only happening to me on Ubuntu.

**Comment by ansibot** [comment]
From @erikkri on 2015-06-18T09:57:08Z

This happens because ubuntu is running boto 2.2. Check this for details: http://stackoverflow.com/questions/22718987/want-to-connect-to-dynamodb-get-attributeerror-module-object-has-no-attribut

**Comment by ansibot** [comment]
From @romanr on 2015-06-18T09:57:08Z

I was able to fix it by logging in to target host and running `sudo pip install boto --upgrade`

**Comment by ansibot** [comment]
@ansibot Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @lwade
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @s-hertel
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by s-hertel** [comment]
Closing because I'm unable to reproduce this on a recent version of Ansible, and aws_s3 has been ported to boto3 as of 2.4.
