### ISSUE TITLE
default.py callback plugin throwing exceptions

### ISSUE THREAD

**Issue by agaffney** [ansible/ansible#13712]
```
 [WARNING]: Error when using <bound method CallbackModule.v2_on_file_diff of </home/agaffney/dev/ansible/lib/ansible/plugins/callback/default.CallbackModule object at
0x760c34f0>>: 'TaskResult' object has no attribute 'get'
```

This appears to have been introduced by commit 14e19c239d610619498f06978e2841764a262e15. It does NOT look like this commit is in the `2.0.0-0.8.rc3` release (or even in the `stable-2.0` branch), which probably explains why nobody is running into it yet.

**Comment by agaffney** [comment]
It looks like the commit that broke this belongs to @jimi-c

**Comment by agaffney** [comment]
I was going to test a straight revert of the commit, but it causes merge conflicts.

**Comment by agaffney** [comment]
I've verified that commenting out the "new" code in the `v2_on_file_diff` function and leaving only the final part of the `if` statement (the "old" code) makes the error go away.

**Comment by agaffney** [comment]
The following playbook will reproduce this:

```
---
- hosts: local
  tasks:
  - user:
      name: "{{ item }}"
      state: absent
    with_items: ['foo', 'bar']
```

It doesn't necessarily need to be 'user', but that's how I found it. I was running ansible as follows:

```
$ ansible-playbook --check --diff -v /tmp/ansible_test.yml
```

**Comment by bcoca** [comment]
this should be fixed by 3d608ef9fa63b7a47e1e4527e2b719cb7dec1bb2

**Comment by jimi-c** [comment]
Agreed, I was working on the exact same fix and was about to commit it, so going to go ahead and close this now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by ghost** [comment]
Confirmed.
