### ISSUE TITLE
Bug Report: Accessing variables of other hosts does not work from j2 template

### ISSUE THREAD

**Issue by kosmodromov** [ansible/ansible#9260]
##### Issue Type:

Bug Report: Accessing variables of other hosts does not work from j2 template
##### Ansible Version:

ansible 1.7.2
##### Environment:

Running ansible from mac os mavericks, manage CentOS 7
##### Summary:

I can't get variables from other hosts from j2 template through {{hostvars[servers]['ansible_default_ipv4']['address']}} construction.

This is code from template.

```
{% if inventory_hostname in groups['haproxy_front'] %}
{% for servers in groups['front'] %}
    server  {{servers}} {{hostvars[servers]['ansible_default_ipv4']['address']}}:80 check
{% endfor %}
{% endif %}
```

Check this variables on hosts in 'front' group

```
ansible front -m setup |grep ansible_default_ipv4
        "ansible_default_ipv4": {
        "ansible_default_ipv4": {
```

Got this error when run playbook

```
fatal: [orion.host.ru] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'ansible_default_ipv4'", 'failed': True}
fatal: [orion.host.ru] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'ansible_default_ipv4'", 'failed': True}
```

Code from playbook

```
- name: Copy config
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg owner=root group=root mode=0644
```
##### Steps To Reproduce:

---
##### Expected Results:

Get ip addresses from hosts in group 'front' with construction {{hostvars[servers]['ansible_default_ipv4']['address']}}
##### Actual Results:

```
fatal: [orion.host.ru] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'ansible_default_ipv4'", 'failed': True}
fatal: [orion.host.ru] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'ansible_default_ipv4'", 'failed': True}
```

**Comment by mpdehaan** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by soulmachine** [comment]
Today I bumped into this bug too. As follows:

```
- debug: msg="{{ hostvars[inventory_hostname].ansible_default_ipv4.address }} {{ hostvars[inventory_hostname]["ansible_fqdn"] }} {{ hostvars[inventory_hostname]["ansible_hostname"] }}"
```

This line runs fine.

But if I put this line into a template, 

```
{% for host in groups['all'] %}
{{ hostvars[host]["ansible_default_ipv4"].address }} {{ hostvars[host]["ansible_fqdn"] }} {{ hostvars[host]["ansible_hostname"] }}
{% endfor %}
```

It will complain:

```
fatal: [us0701aopc172018080143] => {'msg': "One or more undefined variables: 'dict' object has no attribute 'ansible_default_ipv4'", 'failed': True}
```

My ansible version is 1.5.5, after I upgrade to 1.9, my template runs fine.

**Comment by drzraf** [comment]
Ansible 1.7.2: **bug** is here

**Comment by jaytaylor** [comment]
I am also running into this issue.

```
fatal: [a.b.c.d] => One or more undefined variables: 'dict object' has no attribute 'ansible_default_ipv4'
```

Code:

```
- name: "Build hosts file (cloud)"
  lineinfile: dest=/etc/hosts regexp=".*(?:{{ item }}|{{ hostvars[item].hostname }}).*$" line="{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].hostname }} {{ hostvars[item].hostname }}-{{ region_name }}.{{ domain_name }}" state=present
  with_items: groups["all"]
  when: (env is not defined or env != "lan") and hostvars[item].hostname is defined and hostvars[item].hostname != "" and item != inventory_hostname
  tags:
    - etc-hosts
```

Even when I have specified `gather_facts: yes` beforehand, this error still occurs.

My Ansible version is 1.9.0.

**_UPDATE**_

I narrowed the cause down to running `ansible-playbook` with `--limit host1,host2`.  When it is run this way, it appears that information about the other hosts is not available.

I don't think there is a real bug here per sé, it seems more likely to be a user expectation vs. reality impedance mismatch.

**Comment by drzraf** [comment]
I think it's a bug that ipv4/ipv6 of other hosts (and only these specific facts) aren't known.
Public ip are known from the inventory, or .ssh/config or even DNS requests, Ansible should provides this facts without having to "gather"" anything. About the other facts, well, that's another story (for which workaround alreadys exists like running a no-op task on said machines)

**Comment by jayunit100** [comment]
is this still a bug  ? I see it in 1.9?

**Comment by kosmodromov** [comment]
In my case it was my fault because before using facts you will need to take them from hosts. You may take them by running this code in beginning of your playbook.

```
- hosts: all
  tasks: []
```

**Comment by rk-git** [comment]
Why is this not a defect? How do I collect an attribute, say default IPv4 address, from each host to emit a configuration?

The "- host: all, tasks: []' method did not work as well.

Thanks,

Rk

**Comment by kosmodromov** [comment]
It works for me and I can get any available attribute from any host after that.

**Comment by ghost** [comment]
It works for me but I sophisticated a bit to be more usefull indeed

```
# Allow all host to be hitted even if nothing is executed
- hosts: all
  tasks:
     - name: Ping 
       ping:
```

**Comment by ghost** [comment]
not working with ansible ad-hoc command:

```
bin/ansible all -m debug -a var=myvar -i inventory/test3.ini
```

myvar is: 

```
myvar: "jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST={{ hostvars[groups['oracle_servers'][0]]['ansible_fqdn'] }})(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=ACME)))"
```

**Expected Result**:

```
server01.lan.test3.dev.acme.com | FAILED! => {
    "failed": true, 
    "msg": "ERROR! ERROR! ERROR! 'dict object' has no attribute 'ansible_fqdn'"
}
```

**Actual Result**:

```
server01.lan.test3.dev.acme.com | success >> {
    "myvar": "jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=dbms01.lan.test3.dev.acme.com)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=ACME)))"
}
```

**Version tested**
- 1.9.4
- v2.0.0-0.3.beta1 (devel)

**Comment by zstarer** [comment]
ad hoc works for me, doesn't work in a .j2 template at the moment.

on 1.8.4

**Comment by javiervegas** [comment]
Yes, this used to work in a .j2 template in ansible 1.7 but is broken in 1.8 and 1.9.

**Comment by aabouzaid** [comment]
This issue still affect Ansible 2.0.1.0!
@kosmodromov 's workaround worked for me, but I think we need to more standard way to do this.

**Comment by ernestas-poskus** [comment]
Had same issue with

```
$ ansible --version
ansible 2.0.2.0
```

For me only happens when fact_caching is enabled, therefore this might not be a bug.

```
fact_caching = jsonfile
fact_caching_connection = /tmp/ansible_fact_cache
```

To reproduce provision local vagrant machine then destroy it and try to provision again (of course involving some ansible facts accessing).

I have solved this with:

```
fact_caching_timeout = 600
```

**Comment by sadsfae** [comment]
I still see this behavior on 2.1.0.
The proposed workaround works for me if add the following to my playbook.

```
- hosts: all
  remote_user: root
  tasks: []
```

**Comment by ftaeger** [comment]
Same here with 2.1.2.0 on mac os x sierra

this is really breaking my /etc/hosts depoyments of large scale setups. This is just bad!

**Comment by mahesh-kore** [comment]
Any update/fix for this..??

**Comment by jarosite** [comment]
I faced with same issue, but now I think it is not right way to use ansible for managing /etc/hosts or  for service discovery in large scale setup. By the way, workaround still works for me.

**Comment by mahesh-kore** [comment]
what is the workaround you have tried.?

**Comment by eagleusb** [comment]
I had the same issue, in my understanding hostvars can't output facts of machines outside of the targets. 

That's why you need to gather the facts of all your hosts by running an empty list of tasks against all the hosts.

See https://docs.ansible.com/ansible/playbooks_variables.html#magic-variables-and-how-to-access-information-about-other-hosts

**Comment by DanSlutzky** [comment]
I solved this problem by using this 

- hosts: server
  serial: 10
 

before it was "serial: 1" but in my case I have several instances.

**Comment by ghost** [comment]
Unfortunately gathering facts does not work:

```
(env) Yves-iMac:ansible-provisioning Yves$ ansible-playbook backuppc-servers.yml  --diff --tags backuppc-clients

PLAY [host1.example.com] *************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
ok: [host1.example.com]

PLAY [backuppc-servers] *******************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
ok: [another.example.org]

TASK [backuppc : Configure BackupPC clients] **********************************************************************************************************************************************************************************************************************************
failed: [another.example.org] (item=host1.example.com) => {"failed": true, "item": "host1.example.com", "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVars object' has no attribute u'host1.example.com'"}
	to retry, use: --limit @/Users/Yves/Infrastructure/ansible-provisioning/backuppc-servers.retry

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
host1.example.com     : ok=1    changed=0    unreachable=0    failed=0   
another.example.org : ok=1    changed=0    unreachable=0    failed=1  
```


That's the template.
```
# {{ ansible_managed }}

$Conf{RsyncdUserName} = "{{ backuppc_clients[item].config.username }}";
$Conf{RsyncdPasswd} = "{{ (hostvars[item].rsyncd.users | selectattr('name', 'equalto', backuppc_clients[item].config.username) | first).password }}";
$Conf{RsyncShareName} = "{{ backuppc_clients[item].config.share | default('root') }}";
```

```
ansible -m debug -a "var=hostvars['host1.example.com']" localhost
localhost | SUCCESS => {
    "hostvars['host1.example.com']": {
        "ansible_check_mode": false, 
        "ansible_playbook_python": "/Users/Yves/Infrastructure/ansible-provisioning/env/bin/python", 
        "ansible_user": "vogl", 
        "ansible_version": {
            "full": "2.3.1.0", 
            "major": 2, 
            "minor": 3, 
            "revision": 1, 
            "string": "2.3.1.0"
        }, 
        (…)
        "inventory_dir": "/Users/Yves/Infrastructure/ansible-provisioning/inventories", 
        "inventory_file": null, 
        "inventory_hostname": "host1.example.com", 
        "inventory_hostname_short": "host1", 
        "omit": "__omit_place_holder__5a1606e776bc49129dffad56e629d9fae8206a16", 
        "playbook_dir": "."
    }
}
```

To me it looks like a bug in ansible 2.3.1.0

**Comment by MPW1412** [comment]
Still doesn't work inansible 2.3.2.0. Can someone please fix this? @mpdehaan

**Comment by danielmotaleite** [comment]
People having problems with hostvars, please check the above documentation ticket, specially the 
https://docs.ansible.com/ansible/latest/playbooks_variables.html#fact-caching , as it should solve most problems.

Notice that this documentation is when `hostvars` is requesting a `hostname` that do not belong to the current server group. If your `hostname` do exists in the current server group **and** you are **not** using `--limit=` then it should be a different problem

**Comment by MPW1412** [comment]
I didn't notice, that I was accessing hostvars from another group. Preloading those facts with 

```
- name: get hostvars information
  hosts: other_groupname
  remote_user: root
  tasks: []
```
as first lines in my yml worked! Thanks for all the tips!
