### ISSUE TITLE
Ansible 2: All plays fail with "ERROR! connect() got an unexpected keyword argument 'compress'"

### ISSUE THREAD

**Issue by yeroc** [ansible/ansible#12511]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 2.0.0 (devel 5d3d9cfe0d) last updated 2015/09/23 17:22:21 (GMT -600)
  lib/ansible/modules/core: (detached HEAD e8227dea7a) last updated 2015/09/24 10:23:05 (GMT -600)
  lib/ansible/modules/extras: (detached HEAD 6cd7399a71) last updated 2015/09/24 10:23:07 (GMT -600)
  config file = /space/ansible/ansible.cfg
  configured module search path = None
```
##### Ansible Configuration:

```
remote_tmp     = /tmp/.ansible
```
##### Environment:

Management Host: CentOS release 6.5 x64
Target Host: CentOS release 6.7 x64
##### Summary:

All our plays which currently work fine with Ansible 1.9 are failing to connect to our hosts successfully with Ansible 2.
##### Steps To Reproduce:

Given a simple play:

``` yaml

---
- hosts: webserver
  remote_user: "{{ deploy_user }}"
  sudo: no
  tasks:
  - name: debug
    debug: msg="Hello world!"
```
##### Expected Results:

This is what we get with Ansible 1.9:

```
$ ansible-playbook -i inventory connect-failure.yml 

PLAY [webserver] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [inet-dmz2-tst]

TASK: [debug] ***************************************************************** 
ok: [inet-dmz2-tst] => {
    "msg": "Hello world!"
}

PLAY RECAP ******************************************************************** 
inet-dmz2-tst              : ok=2    changed=0    unreachable=0    failed=0   
```
##### Actual Results:

But with Ansible 2:

```
$ ansible-playbook -i inventory connect-failure.yml 

PLAY ***************************************************************************

TASK [setup] *******************************************************************
fatal: [inet-dmz2-tst]: UNREACHABLE! => {"changed": false, "msg": "ERROR! connect() got an unexpected keyword argument 'compress'", "unreachable": true}

PLAY RECAP *********************************************************************
inet-dmz2-tst              : ok=0    changed=0    unreachable=1    failed=0   
```

**Comment by abadger** [comment]
Looks like this was a problem with the paramiko connection plugin.  At some point we added the compress option to the connection but older versions of paramiko (such as shipped in RHEL6) do not have that.  Removed that option for now which should fix the issue:
https://github.com/ansible/ansible/commit/0250beb68a05778315a4b7c962dbad2b8e066d87

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by yeroc** [comment]
I can confirm this fix resolves the connect issue.  Thanks for the quick fix!
