### ISSUE TITLE
Ansible docker and docker-compose issue on Redhat 7.x

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#56576]
##### SUMMARY
Ansible is not able to run docker or docker-compose command. Pip was updated to v.19
but also after downgrade to 8.1.2 I'm facing same problem.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker

##### ANSIBLE VERSION

```paste below
2.7
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Redhat 7.2, 7.3, 7.6

##### STEPS TO REPRODUCE

```yaml
- name: Log into docker registry
  docker_login:
    registry: "{{ dockerRegistry }}"
    username: "{{ dockerUser }}"
    password: "{{ vault_docker_pass }}"
    reauthorize: yes
```

##### ACTUAL RESULTS

TASK [setup-cordapp : Log into docker registry] *********************************************************************************************************************************************************************************************
fatal: [10.2.1.9]: FAILED! => {"changed": false, "msg": "Failed to import docker or docker-py - cannot import name __version__. Try `pip install docker` or `pip install docker-py` (Python 2.6)"}

```paste below
Failed to import docker or docker-py - cannot import name __version__
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/docker/_docker.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/_docker.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @DBendit @WojciechowskiPiotr @akshay196 @danihodovic @dariko @felixfontein @jwitko @kassiansun @tbouvet
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dusten** [comment]
@adamsem can you check what version of ansible you have on both the local machine and the machine under management.

I just had the same issue where my local machine was using 2.7.10 and the remote host was using 2.8.0.

Locking the remote host to 2.7.10 solved the issue for me.

**Comment by adamsem** [comment]
@dusten Yes same situation. Thanks for that I'll check this workaround on Monday and give you posted if it help for me.

**Comment by felixfontein** [comment]
This is usually caused by Ansible using another Python interpreter than the one you've used to install the `docker` Python module with. It's probably not related to your `pip` version at all.

@dusten there's no need to have Ansible installed on the remote machine at all. (Except if you use ansible-pull on the remote machine, that is.)

**Comment by adamsem** [comment]
@dusten your solution is working, @felixfontein I'm not sure why ansible is installed on remote machine , is not installed by yum but by pip.

**Comment by dusten** [comment]
@adamsem I'm happy I wasn't the only one with the issue and that it is working for you.  While I'm sure there is some configuration option can be passed, I will leave that to someone that has more knowledge on the topic.

@felixfontein my Ansible script is about getting from 0 to 1.  For example turning up an on-demand jump-box to run Ansible scripts from.  I am sure there is a configuration option I am missing but for the time being setting it to 2.7.10 is working.

**Comment by marwatk** [comment]
I can confirm that the presence of `ansible.noarch 2.8.0-2.el7` on the target system causes the issue. Downgrading to `ansible-2.7.10-1.el7` or removing it completely (`yum remove ansible`) both work.

**Comment by juanvalino** [comment]
I have the same problem.

**Comment by vin-c** [comment]
Following this https://github.com/ansible/ansible/issues/20492 (none of the actions worked for us)
With only `docker` as a dependancy (no `docker-py` installed)

(Background goal here: deploy a registry + awx on the same host)

Check that you run the same `ansible` master version (2.7.x for exemple) between the server and target host: it's ok with ansible 2.7.12 on server and 2.7.9 on target, but failing if the target is in 2.8.x (default to last available version)

**Comment by felixfontein** [comment]
Here's a similar error message with some attempts to find out what's going on: #59296

Maybe you could check whether you have the same problem as in that issue.

**Comment by balmha** [comment]
> Here's a similar error message with some attempts to find out what's going on: #59296
> 
> Maybe you could check whether you have the same problem as in that issue.

Hi Felix, thanks for shared my issue, i currently have a similar error but I running Ansible as a localhost.

**Comment by Xachman** [comment]
I totally ran into this.  I probably accidentally installed ansible on the target host.  Removing it fixed the problem.  What I found is that it was kinda intermittent.  Sometimes it would throw up the error `Failed to import docker or docker-py - cannot import name __version__` sometimes not.

**Comment by sgeschwill** [comment]
I can as well confirm. This problem happened to me as well when installing Ansible on the target machine and trying to run a playbook using docker modules (and pip). After removing Ansible from the target host, the execution was without issues from the remote controller (host).
Thank you all for your help!

**Comment by thanos1983** [comment]
In case that someone is trying to trying to run the latest version of Ansible in RedHat 7.7 etc. I got the same problem with Ansible 2.8.0 and up. The only working version from me was:

```bash
$ ansible --version
ansible 2.7.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/g02452-udm/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

Also I had to install [docker 4.0.2](https://pypi.org/project/docker/).

All these packages need to be installed on the remote node (host) that the playbook is connecting.

Hope this helps someone on resolving their problem faster.

Similar bug that was closed in the past [Failed to import docker-py for docker_container module](https://github.com/ansible/ansible/issues/20492). The bug is related to [docker-compse](https://pypi.org/project/docker-compose/) but it is exactly the same problem.

**Comment by blightbow** [comment]
For those who experience this problem on RHEL **without** Python3 installed on the target system,  it appears to be caused by the presence of the ansible libraries in site_packages the RHEL system. Here are some steps to reproduce.

Terms:
ADMINHOST = Server you executing the playbook on.
TARGET = Remote server running docker that is being managed by Ansible on ADMINHOST.

    # execute on TARGET
    yum erase ansible
    yum install python-docker

Run the following test command on TARGET:
    $ python -c "from docker import __version__"
    $

If you do not receive an error, it means the docker python module is present and was loaded successfully. Run your Ansible playbook on ADMINHOST against TARGET. Confirm that you are not seeing the "Failed to import docker or docker-py" error message.

Now let's break things:

    # execute on TARGET
    yum install ansible

Run your ADMINHOST playbook against TARGET again. If you are experiencing the bug you should be seeing the "Failed to import docker or docker-py" message again.

Finally, let's prove without a shadow of a doubt that this is an Ansible bug:

    # execute on TARGET
    $ cd /usr/lib/python2.7/site-packages
    $ mv ansible ansible.bak

Run your ADMINHOST playbook against TARGET again. If the playbook is working again, you've just proven that the only difference between whether or not the playbook succeeds or fails is the presence of the "ansible" directory in site-packages.

**Comment by felixfontein** [comment]
@blightbow I don't have access to RHEL. I've tried the following on my server (has both Python 2 and Python 3) installed: I installed `ansible` and `docker` for both Python 2 and Python 3 (`pip2 install ansible docker`, `pip3 install ansible docker`).

Then I ran Ansible (both `devel` and `stable-2.8`, with simple playbooks which use `docker_container` or `docker_compose`, once with `ansible_python_interpreter=python2` and once with `ansible_python_interpreter=python3`. I always get `Error connecting: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))`, which means that importing the Docker SDK for Python worked but there's no docker daemon running on that server.

Can you also reproduce it when both Python 2 and Python 3 are installed on the same machine? Or does it really needs to have only Python 2 installed to show this behavior?

The playbook I used: (I also removed the `#` to try `docker_container`, with the same result)
```
---
- hosts: my_server
  tasks:
    #- docker_container:
    #    name: test
    - docker_compose:
        services: test
```

**Comment by felixfontein** [comment]
(I've also never seen that behavior with Debian servers having `docker` and `ansible` installed for Python 2 with main Python being Python 2. They also have Python 3 installed though.)

**Comment by blightbow** [comment]
It truly only needs Python2 to show this behavior.

```
[me@redacted ~]$ locate bin/python
/usr/bin/python
/usr/bin/python2
/usr/bin/python2.7
[me@redacted ~]$ which python
/usr/bin/python
[me@redacted ~]$ sudo su -
[sudo] me@redacted's password:
Last login: Fri Oct 18 14:41:37 EDT 2019 on pts/0
[root@redacted ~]# which python
/bin/python
[root@redacted ~]# ls -l /bin/python
lrwxrwxrwx 1 root root 7 Aug 26 13:16 /bin/python -> python2
[root@redacted site-packages]# /usr/bin/python --version
Python 2.7.5
[root@redacted site-packages]# /usr/bin/python2 --version
Python 2.7.5
[root@catl0plas10119 site-packages]# /bin/python --version
Python 2.7.5
[root@catl0plas10119 site-packages]# /bin/python2 --version
Python 2.7.5
```

Here are the ansible versions from ADMINHOST and TARGET;

```
# TARGET
ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 12:19:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

```
# ADMINHOST
[aboling@catl0plas10119 ~]$ logout
Connection to catl0plas10119.iaas.cox.net closed.
aboling@dukessansible01:~$ ansible --version
ansible 2.7.6
  config file = /home/aboling/.ansible.cfg
  configured module search path = [u'/home/aboling/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]
```

Let me know if you want to sync up in an IRC channel or somesuch. This is a work environment and I can't screenshare, but I'm happy to be your hands. This one is just flat out bizarre.

**Comment by thanos1983** [comment]
> For those who experience this problem on RHEL **without** Python3 installed, it appears to be caused by the presence of the ansible libraries in site_packages on the managed system. Here are some steps to reproduce.
> 
> Terms:
> ADMINHOST = Server you executing the playbook on.
> TARGET = Remote server running docker that is being managed by Ansible on ADMINHOST.
> 
> ```
> # execute on TARGET
> yum erase ansible
> yum install python-docker
> python -c "from docker import __version__"
> ```
> 
> If you do not receive an error from the python command, it means the docker python module is present and was loaded successfully. Run your Ansible playbook on ADMINHOST against TARGET. Confirm that you are not seeing the "Failed to import docker or docker-py" error message.
> 
> Now let's break things:
> 
> ```
> # execute on TARGET
> yum install ansible
> ```
> 
> Run your ADMINHOST playbook against TARGET again. If you are experiencing the bug you should be seeing the familiar "Failed to import docker or docker-py" message.
> 
> Finally, let's prove without a shadow of a doubt that this is an Ansible bug:
> 
> ```
> # execute on TARGET
> cd /usr/lib/python2.7/site-packages
> mv ansible ansible.bak
> ```
> 
> Run your ADMINHOST playbook against TARGET again. If the playbook is working again, you've just proven that the only difference between whether or not the playbook succeeds or fails is the presence of the "ansible" directory in site-packages. The fact that it breaks when `site-packages/ansible` exists seems to indicate that the executed ansible playbook is interacting with the remote Ansible libraries and somehow losing its mind.

I had exactly the same problem and I applied the following on target host:

```
sudo pip uninstall ansible -y
sudo pip uninstall docker -y
sudo pip uninstall docker-py -y # if still installed deprecated package
sudo pip uninstall urllib3 -y
sudo pip uninstall websocket -y
```

Then verify that all the relevant packages are installed on target host:

`sudo yum install -y ansible python-websocket-client python-docker python-urllib3`

In case you have installed Python3 on target host (locahost as well) repeat the same procedure (recommended as Python2 will reach end of life on 1/1/2020) :

```
sudo pip3 uninstall ansible -y
sudo pip3 uninstall docker -y
sudo pip3 uninstall docker-py -y # if still installed deprecated package
sudo pip3 uninstall urllib3 -y
sudo pip3 uninstall websocket -y
```
`sudo yum install -y ansible python3-websocket-client python3-docker python3-urllib3`

In case that someone wants to manually install them:
[RPM resource ansible](https://rpmfind.net/linux/rpm2html/search.php?query=ansible&submit=Search+...&system=&arch=)
[RPM resource python3-docker](https://rpmfind.net/linux/rpm2html/search.php?query=python3-docker&submit=Search+...&system=&arch=)
[RPM resource python3-websocket-client](https://rpmfind.net/linux/rpm2html/search.php?query=python3-websocket-client&submit=Search+...&system=&arch=)
[RPM resource python3-urllib3](https://rpmfind.net/linux/rpm2html/search.php?query=python3-urllib3&submit=Search+...&system=&arch=)

**Comment by thanos1983** [comment]
> @blightbow I don't have access to RHEL. I've tried the following on my server (has both Python 2 and Python 3) installed: I installed `ansible` and `docker` for both Python 2 and Python 3 (`pip2 install ansible docker`, `pip3 install ansible docker`).
> 
> Then I ran Ansible (both `devel` and `stable-2.8`, with simple playbooks which use `docker_container` or `docker_compose`, once with `ansible_python_interpreter=python2` and once with `ansible_python_interpreter=python3`. I always get `Error connecting: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))`, which means that importing the Docker SDK for Python worked but there's no docker daemon running on that server.
> 
> Can you also reproduce it when both Python 2 and Python 3 are installed on the same machine? Or does it really needs to have only Python 2 installed to show this behavior?
> 
> The playbook I used: (I also removed the `#` to try `docker_container`, with the same result)
> 
> ```
> ---
> - hosts: my_server
>   tasks:
>     #- docker_container:
>     #    name: test
>     - docker_compose:
>         services: test
> ```

In case you do not have RH distribution available to launch on a VM I assume the same behavior will still apply on Centos7.*

**Comment by felixfontein** [comment]
I've tried replicating this with CentOS 7 as follows:
```.yaml
---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: "Create test container 'centos'"
      docker_container:
        name: centos
        image: centos:7
        command: /bin/bash -c "sleep 1000h"
      register: result
    - when: result is changed
      block:
      - name: Install EPEL
        command: docker exec centos yum install -y epel-release
      - name: Install pip
        command: docker exec centos yum install -y python-pip
      - name: Install docker and ansible
        command: docker exec centos pip install docker ansible
    - name: Test for Python 2
      command: docker exec centos python2 -V
      ignore_errors: yes
      register: py2
    - debug: var=py2
    - name: Test for Python 3
      command: docker exec centos python3 -V
      ignore_errors: yes
      register: py3
    - debug: var=py3
    - name: Make sure Python 2 is available, but Python 3 is not
      assert:
        that:
          - py2 is succeeded
          - py3 is failed
    - add_host:
        name: centos
- hosts: centos
  connection: docker
  gather_facts: no
  tasks:
    - docker_service:
        services: test
    - docker_container:
        name: test
```
This installs ansible 2.8.6 (latest non-prerelease) and docker 4.1.0 on the remote server. If I run this playbook with `devel` or `stable-2.8` (which is essentially 2.8.6), it works: `docker_service` and `docker_container` can import `docker`, but can't talk to the docker daemon (no surprise as there isn't any).

If I try it with `stable-2.7` (which is essentially 2.7.14), I do get:

> Failed to import docker or docker-py - cannot import name __version__. Try `pip install docker` or `pip install docker-py` (Python 2.6)

(Finally :) )

If I switch the remote Ansible from 2.8.6 to 2.7.14 (`docker exec centos pip install ansible==2.7.14`), it does work again (with `stable-2.7`, `stable-2.8` and `devel`). (I didn't test `stable-2.9` since it should behave the same as `devel`, there haven't been any major changes yet.)

And when I upgrade the remote Ansible to 2.8.6 again (`docker exec centos pip install --upgrade ansible`), it still fails for `stable-2.7`, but succeeds for `stable-2.8` and `devel`.

I'm not sure how much I can still do about this now, though, since Ansible 2.7 only receives critical bugfixes (https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#release-status; https://groups.google.com/d/msgid/ansible-devel/CAPrnkaR_ZgsnJDnmAvZca_0FjE1COq_Om8b65tKLk2GNk8R8BQ%40mail.gmail.com), and module bugs usually don't count as critical. That will depend of course on what exactly causes this, though. I'll investigate a bit. Just don't want to make too many promises :)

**Comment by felixfontein** [comment]
One reason for this happening could be:
 - The Python module importing `docker` for Ansible 2.7 is in the package `ansible.module_utils`;
 - In Ansible 2.8 (and newer), there also is a package `docker` in `ansible.module_utils`, and the Python module importing `docker` in Ansible 2.8 (and newer) is in the package `ansible.module_utils.docker`. So it could be that `import docker` will try to import the `ansible.module_utils.docker` package from Ansible 2.8, and not the real (top-level) `docker` package.
 - The `ansible.module_utils` package where the `import docker` is run in is in a different position in the filesystem than the 2.8 `ansible.module_utils` which contains a `docker` package, though.

I don't know how Python module imports work in detail, and how Ansible exactly runs the code on the remote machine, so I'm not sure whether that's indeed the problem. But it might be a good starting point for further investigation.

**Comment by felixfontein** [comment]
(See https://github.com/ansible/ansible/blob/stable-2.7/lib/ansible/module_utils/docker_common.py and https://github.com/ansible/ansible/tree/devel/lib/ansible/module_utils/docker)

**Comment by felixfontein** [comment]
Anyway, there's an obvious solution: upgrade to Ansible 2.8 on the controller, and/or remove Ansible from the target machine (or make sure it is 2.7 or older when you run 2.7 or older on the controller).

**Comment by felixfontein** [comment]
There's another way to fix this: change `module_utils/docker.py` in Ansible 2.7 to contain `from __future__ import absolute_import` in the first line. (The problem is that Python 2.x still allows implicit absolute imports. Python 3 removed them. These are what causes this problem, together with the points mentioned above. And this is also why it will work with Python 3.)

**Comment by xaerowalk** [comment]
> fatal: [10.2.1.9]: FAILED! => {"changed": false, "msg": "Failed to import docker or docker-py - cannot import name **version**. Try `pip install docker` or `pip install docker-py` (Python 2.6)"}

Centos 7.6
install pip and then
`pip install docker`

fixed for me but usually I don't need and don't want pip at target machine

**Comment by ansibot** [comment]
Files identified in the description:
* [`contrib/inventory/docker.py`](https://github.com/ansible/ansible/blob/devel/contrib/inventory/docker.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [`test/support/integration/plugins/module_utils/docker/__init__.py`](https://github.com/ansible/ansible/blob/devel/test/support/integration/plugins/module_utils/docker/__init__.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @mattclay
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sergioisidoro** [comment]
Confirming another instance of this problem.
Removing ansible from target machine solved the issue (while running `ansible 2.7.5` locally).

**Comment by mkrizek** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general.

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
