### ISSUE TITLE
ansible fails on gather when using --diff

### ISSUE THREAD

**Issue by bcoca** [ansible/ansible#4499]
sample playbook (test.yml):

```
  - hosts: localhost
    tasks:
      - debug: msg="fail"
```

invoked (works normally just removing --diff):

```
 ansible-playbook test.yml --check --diff -i 'localhost,' -c local
```

result:

```
fatal: [localhost] => Traceback (most recent call last):
  File "/home/bcoca/work/ansible/lib/ansible/runner/__init__.py", line 384, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/home/bcoca/work/ansible/lib/ansible/runner/__init__.py", line 469, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/home/bcoca/work/ansible/lib/ansible/runner/__init__.py", line 726, in _executor_internal_inner
    self.callbacks.on_file_diff(conn.host, result.diff)
  File "/home/bcoca/work/ansible/lib/ansible/callbacks.py", line 563, in on_file_diff
    display(utils.get_diff(diff), runner=self.runner)
  File "/home/bcoca/work/ansible/lib/ansible/utils/__init__.py", line 866, in get_diff
    with warnings.catch_warnings():
AttributeError: 'dict' object has no attribute 'catch_warnings'
```

**Comment by bcoca** [comment]
seems to be caused by: 61d01f549f2143fd9adfa4ffae42f09d24649c26

but python docs indicate catch_warnings was included in 2.6 and I'm running 2.7.3 (no other versions installed)

**Comment by leucos** [comment]
@bcoca  : experiencing same issue here, but I don't think this is the commit the introduced the problem. It's 8 months old . I'm running from git and had this only recently.

**Comment by leucos** [comment]
Bisected this to a45494a

**Comment by bcoca** [comment]
ah, yes, bad paste on my side, I had both the 'commit where this line was
added' and 'bisect'. Micheal points to the correct one that introduced the
bug.

**Comment by bcoca** [comment]
pulled and confirmed it works now

**Comment by leucos** [comment]
Works here too. Thanks @bcoca !
