### PR TITLE
Add duplicate set filter and documentation

### PR DESCRIPTION
**Pull request by bmillemathias**
##### SUMMARY
Add duplicate filter
Took the WIP patch from #50977 from @flatline-studios and applied the suggestion from @sivel 
close fix #50977

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
filter

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by bmillemathias** [comment]
I wonder if `duplicated` name would be better than `duplicate`.
any opinion ?

**Comment by acozine** [comment]
@bmillemathias I like `duplicated`, which is clearly an adjective; `duplicate` is less clear because it can be an adjective or a verb.

**Comment by bmillemathias** [comment]
> @bmillemathias I like `duplicated`, which is clearly an adjective; `duplicate` is less clear because it can be an adjective or a verb.

yep indeed

**Comment by acozine** [comment]
Sorry this has been hanging for a while. Could you add a changelog fragment @bmillemathias?

**Comment by bmillemathias** [comment]
> Sorry this has been hanging for a while. Could you add a changelog fragment @bmillemathias?

No problem. I forgot to include the changelog file in the commit, this is fixed.

**Comment by acozine** [comment]
rebuild_merge /azp run

**Comment by felixfontein** [comment]
@acozine @bmillemathias I'm not sure that this should have been merged now during feature freeze - the stable-2.11 branch will be branched on Monday (AFAIK), and ansible-core 2.11.0rc1 is planned for next week.

For me specifically, this broke some Python 2.6 integration tests (`ansible-test integration --docker --python 2.6`):
```
TASK [felixfontein.acme.acme_certificate : Creating private key for example.org] ***
[WARNING]: Skipping plugin (/root/ansible/lib/ansible/plugins/filter/mathstuff.py) as it seems to be invalid: cannot import name Counter
[WARNING]: an unexpected error occurred during Jinja2 environment setup: cannot import name Counter   line 0
fatal: [testhost]: FAILED! => {"msg": "template error while templating string: cannot import name Counter\n  line 0. String: {{ [acme_certificate_keys_path, acme_certificate_key_name ~ '.key'] | felixfontein.tools.path_join }}"}
```

**Comment by felixfontein** [comment]
This PR also breaks the CentOS 6 tests in devel: https://dev.azure.com/ansible/ansible/_build/results?buildId=10031&view=logs&jobId=be67d8ce-cac5-5f74-4090-b44f5044b2d6&j=be67d8ce-cac5-5f74-4090-b44f5044b2d6&t=5d25c2d4-19e2-51b7-0721-474ec61d1ca7
```
09:02 TASK [test complex templated condition] ****************************************
09:02 task path: /root/ansible/test/results/.tmp/integration/conditionals-R7beSw-ÅÑŚÌβŁÈ/test/integration/targets/conditionals/play.yml:326
09:03 [WARNING]: Skipping plugin
09:03 (/root/ansible/lib/ansible/plugins/filter/mathstuff.py) as it seems to be
09:03 invalid: cannot import name Counter
09:03 [WARNING]: an unexpected error occurred during Jinja2 environment setup: cannot
09:03 import name Counter   line 0
09:03 exception during Jinja2 environment setup: Traceback (most recent call last):
09:03   File "/root/ansible/lib/ansible/template/__init__.py", line 537, in __getitem__
09:03     raise TemplateSyntaxError(to_native(e), 0)
09:03 TemplateSyntaxError: cannot import name Counter
09:03   line 0
09:03 fatal: [testhost]: FAILED! => {
09:03     "msg": "The conditional check 'vars_file_var in things1|union([vars_file_var])' failed. The error was: template error while templating string: cannot import name Counter\n  line 0. String: {% if vars_file_var in things1|union([vars_file_var]) %} True {% else %} False {% endif %}\n\nThe error appears to be in '/root/ansible/test/results/.tmp/integration/conditionals-R7beSw-ÅÑŚÌβŁÈ/test/integration/targets/conditionals/play.yml': line 326, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: test complex templated condition\n      ^ here\n"
09:03 }
```

**Comment by felixfontein** [comment]
CC @relrod

**Comment by relrod** [comment]
I'm curious how/why this passed in the first place. /cc @mattclay

**Comment by felixfontein** [comment]
@relrod I looked at that yesterday, the reason is that while the filter has unit and integration tests, the integration tests are marked with `skip/python2.6`, so they are not run on CentOS 6.

But there are *other* integration tests (which belong to other components) which *do* run on CentOS 6 that use filters (or tests). Now `mathstuff.py` is not importable on Python 2.6 (this PR adds an import that only works with Python 2.7+), which makes the jinja2 environment setup fail on Python 2.6 (well, Ansible does not support Python 2.6 on the controller, but so far it still mostly works there - that's needed for the CentOS 6 tests until we have split-controller testing). This causes *all* Ansible-provided (core and collections) filters and tests to not work. So all the other integration tests running on CentOS 6 that use filters (or tests) will now fail (even if they don't use anything from `mathstuff.py`).

**Comment by acozine** [comment]
@felixfontein sorry about that. I'll revert it if need be.

**Comment by s-hertel** [comment]
We have been redirecting most new plugins to collections. The issue it caused aside, I'm not sure this should have been merged. I think it should have been voted on during an IRC meeting.

**Comment by mattclay** [comment]
This was reverted in https://github.com/ansible/ansible/pull/74053
