### PR TITLE
Change line 172 to reflect lower Python version

### PR DESCRIPTION
**Pull request by jfrappier**
##### ISSUE TYPE

- Docs Pull Request
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Current documentation states ansible_winrm_server_cert_validation: ignore is required for Python 2.7.9+. Confirmed with Python 2.7.5 this is required as well.

```
[root@vxprt-ansible group_vars]# ansible --version
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
[root@vxprt-ansible group_vars]# python -V
Python 2.7.5
[root@vxprt-ansible group_vars]# cat dc.yml
ansible_user: administrator@xxxxx
ansible_password: xxxxx
ansible_port: 5986
ansible_connection: winrm
[root@vxprt-ansible group_vars]# ansible dc -m win_ping
vxprt-dc01.vxprt.local | UNREACHABLE! => {
    "changed": false,
    "msg": "kerberos: __init__() got an unexpected keyword argument 'hostname_override', ssl: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)",
    "unreachable": true
}
[root@vxprt-ansible group_vars]# vi dc.yml
[root@vxprt-ansible group_vars]# cat dc.yml
ansible_user: administrator@xxxxx
ansible_password: xxxxx
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
[root@vxprt-ansible group_vars]# ansible dc -m win_ping
vxprt-dc01.vxprt.local | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
[root@vxprt-ansible group_vars]#

```

Confirmed Python 2.7.5 requires ansible_winrm_server_cert_validation: ignore for self signed certificates

### CODE REVIEW

**Comment by alikins** [comment]
Is there a reference for this change appearing in python 2.7.5?

As far as I can tell, the version here is based on https://github.com/diyan/pywinrm/pull/74 
"allows server certificate validation to be ignored for SSLContext-aware Python (>= 2.7.9)"

I suspect the change in 2.7.9 that matters was related to http://bugs.python.org/issue22927 

> - Issue #22927: Allow urllib.urlopen to take a _context_ parameter to control
>   SSL settings for HTTPS connections.
> - Issue #22921: Allow SSLContext to take the _hostname_ parameter even if
>   OpenSSL doesn't support SNI.

I don't see any python 2.7.5 change that would effect this.  If this is working in a python 2.7.5, is it upstream python or a distro vendor patched version (for, RHEL7/CentOS is python 2.7.5 but with lots of ssl related backports (mostly related to https://www.python.org/dev/peps/pep-0466/ and https://www.python.org/dev/peps/pep-0476/)

**Comment by jfrappier** [comment]
It is for Python that ships with CentOS7, all I can comment on is that ansible_winrm_server_cert_validation: ignore was needed with Python 2.7.5 using self signed certs, where the documentation states it is required for 2.7.9+ - cost me a couple of hours so thought I'd try to save others.

**Comment by MadelineRitchie** [comment]
On CentOS 7 I had this same issue; same error, same versions, identical. I attempted adding the `ansible_winrm_server_cert_validation: ignore`, but it was ineffective. I uninstalled pywinrm 2 and installed pywinrm 1 and winrm was successful.

ansible 2.1.0.0
Python 2.7.5

**Comment by nitzmahone** [comment]
Python 2.7.9 was the first Python version that changed the SSLContext behavior in this way, but some distros backported the fixes to older Python versions. Adjusted docs text to clarify.
