### PR TITLE
module_utils/mysql: Fixing unexpected keyword argument 'cursorclass' error after migratio…

### LINKED ISSUE #47736: mysql_user broken in 2.7.1 when using /root/.my.cnf
##### SUMMARY

When upgrading from 2.7.0 to 2.7.1 we started seeing this error from `mysql_user` module

```
unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1698, \"Access denied for user 'root'@'localhost'\")
```

The task is following:

```
# Write password to root home as readable only by root so future mysql
# operations can function.
- name: Write root login credentials
  copy:
      dest: /root/.my.cnf
      owner: root
      group: root
      mode: 0600
      content: |
          # {{ ansible_note }}
          [client]
          user=root
          password={{ db_root_password }}

# By default the root user has no password. Set one.
- name: Set root user password
  mysql_user:
      host: "{{ item }}"
      name: root
      password: "{{ db_root_password }}"
      # Login without credentials
      check_implicit_admin: yes
      state: present
  with_items:
      - localhost
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
```

The latter one fails.

Ansible 2.7.0 works fine.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mysql_user

##### ANSIBLE VERSION

```paste below
ansible 2.7.1
  config file = None
  configured module search path = ['/Users/esamatti/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.0 (default, Oct  2 2018, 09:18:58) [Clang 10.0.0 (clang-1000.11.45.2)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/Users/epeli/code/playbooks/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/Users/epeli/code/playbooks/ansible.cfg) = -o ForwardAgent=yes
DEFAULT_FORKS(/Users/epeli/code/playbooks/ansible.cfg) = 100
DEFAULT_HOST_LIST(/Users/epeli/code/playbooks/ansible.cfg) = ['/Users/epeli/code/playbooks/tools/dynamic-inventory']
DEFAULT_REMOTE_USER(/Users/epeli/code/playbooks/ansible.cfg) = root
DEFAULT_SUDO_FLAGS(/Users/epeli/code/playbooks/ansible.cfg) = -HE
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /Users/epeli/.ansible-vault-password
```

##### OS / ENVIRONMENT

macOS Mojave version 10.14 (18A391)

And Ubuntu 18.04 server

##### STEPS TO REPRODUCE

See SUMMARY

##### ACTUAL RESULTS

```paste below
TASK [mariadb : Set root user password] ********************************************************************************************************************************************************************************
failed: [1.2.3.4] (item=localhost) => {"changed": false, "item": "localhost", "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1698, \"Access denied for user 'root'@'localhost'\")"}
failed: [1.2.3.4] (item=customer) => {"changed": false, "item": "customer", "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1698, \"Access denied for user 'root'@'localhost'\")"}
failed: [1.2.3.4] (item=127.0.0.1) => {"changed": false, "item": "127.0.0.1", "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1698, \"Access denied for user 'root'@'localhost'\")"}
failed: [1.2.3.4] (item=::1) => {"changed": false, "item": "::1", "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1698, \"Access denied for user 'root'@'localhost'\")"}
```

### PR DESCRIPTION
**Pull request by timorunge**
…n from MySQLdb to PyMySQL

##### SUMMARY

With Ansible 2.7.1 and the migration from MySQLdb to PyMySQL all my MySQL related tasks failed since the call `db_connection.cursor(cursorclass=mysql_driver.cursors.DictCursor)` is trying to trigger https://github.com/PyMySQL/PyMySQL/blob/v0.9.2/pymysql/connections.py#L483 which has no argument cursorclass. 

```
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1540904667.96-27683954372616 `" && echo ansible-tmp-1540904667.96-27683954372616="` echo /root/.ansible/tmp/ansible-tmp-1540904667.96-27683954372616 `" ) && sleep 0'
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/database/proxysql/proxysql_backend_servers.py
<localhost> PUT /root/.ansible/tmp/ansible-local-4588xiOIZd/tmpPPDmmb TO /root/.ansible/tmp/ansible-tmp-1540904667.96-27683954372616/AnsiballZ_proxysql_backend_servers.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1540904667.96-27683954372616/ /root/.ansible/tmp/ansible-tmp-1540904667.96-27683954372616/AnsiballZ_proxysql_backend_servers.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1540904667.96-27683954372616/AnsiballZ_proxysql_backend_servers.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1540904667.96-27683954372616/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1540904667.96-27683954372616/AnsiballZ_proxysql_backend_servers.py", line 113, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1540904667.96-27683954372616/AnsiballZ_proxysql_backend_servers.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1540904667.96-27683954372616/AnsiballZ_proxysql_backend_servers.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_proxysql_backend_servers_payload_3rvJlX/__main__.py", line 504, in <module>
  File "/tmp/ansible_proxysql_backend_servers_payload_3rvJlX/__main__.py", line 450, in main
  File "/tmp/ansible_proxysql_backend_servers_payload_3rvJlX/ansible_proxysql_backend_servers_payload.zip/ansible/module_utils/mysql.py", line 81, in mysql_connect
TypeError: cursor() got an unexpected keyword argument 'cursorclass'
```

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

module_utils/mysql.py

##### ANSIBLE VERSION

```paste below
ansible --version
ansible 2.7.1
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

### CODE REVIEW

**Comment by gundalow** [comment]
bot_status

**Comment by esamattis** [comment]
@gundalow  Oh, sorry I didn't notice this PR earlier. But unfortunaly no. I'm getting the same error as in #47736

Not familiar how Ansible dev versions are best installed but I installed it manually into a Python 3 virtual env using the `setup.py` file. Directly from this commit https://github.com/timorunge/ansible/commit/1b4c66a8adf595139674fbdaef1575ba41fbc80e

```
ansible --version
ansible 2.8.0.dev0
  config file = /Users/esamatti/code/playbooks/ansible.cfg
  configured module search path = ['/Users/esamatti/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/esamatti/Envs/ansibleenv/lib/python3.7/site-packages/ansible-2.8.0.dev0-py3.7.egg/ansible
  executable location = /Users/esamatti/Envs/ansibleenv/bin/ansible
  python version = 3.7.0 (default, Oct  2 2018, 09:18:58) [Clang 10.0.0 (clang-1000.11.45.2)]
```

**Comment by anniemelen** [comment]
Applying patch from #47809  (https://patch-diff.githubusercontent.com/raw/ansible/ansible/pull/47809.patch) not worked for me.

```
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

```
fatal: [node03]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "append_privs": false,
            "check_implicit_admin": false,
            "config_file": "/root/.my.cnf",
            "connect_timeout": 30,
            "encrypted": false,
            "host": "localhost",
            "host_all": true,
            "login_host": "localhost",
            "login_password": "",
            "login_port": 3306,
            "login_unix_socket": null,
            "login_user": "root",
            "name": "root",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "priv": "*.*:ALL,GRANT",
            "sql_log_bin": true,
            "ssl_ca": null,
            "ssl_cert": null,
            "ssl_key": null,
            "state": "present",
            "update_password": "always",
            "user": "root"
        }
    },
    "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1698, u\"Access denied for user 'root'@'localhost'\")"
}
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_mysql_user_payload_6FXkHz/__main__.py", line 588, in main
    connect_timeout=connect_timeout)
  File "/tmp/ansible_mysql_user_payload_6FXkHz/ansible_mysql_user_payload.zip/ansible/module_utils/mysql.py", line 78, in mysql_connect
    db_connection = mysql_driver.connect(**config)
  File "/usr/lib/python2.7/dist-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 699, in __init__
    self.connect()
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 936, in connect
    self._request_authentication()
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 1156, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/lib/python2.7/dist-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
```

**Comment by timorunge** [comment]
@epeli: Can you send me some verbose output? 

@anniemelen: If this is the actual output I think your problem is now different to the one which is described in this PR:
`"msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1698, u\"Access denied for user 'root'@'localhost'\")"`

**Comment by anniemelen** [comment]
@timorunge Yes, it's actual and related to #47736.

**Comment by timorunge** [comment]
@anniemelen: Sorry, didn't notice that. Can you send me some verbose output?

**Comment by anniemelen** [comment]
@timorunge Unfortunately, this is all. Other information in '-vvvvv' mode is related to establishing SSH connection.
I can provide module list which Ansible using during a task:
```
Using module_utils file /usr/lib/python2.7/dist-packages/ansible/module_utils/mysql.py
Using module_utils file /usr/lib/python2.7/dist-packages/ansible/module_utils/database.py
Using module_utils file /usr/lib/python2.7/dist-packages/ansible/module_utils/basic.py
Using module_utils file /usr/lib/python2.7/dist-packages/ansible/module_utils/_text.py
Using module_utils file /usr/lib/python2.7/dist-packages/ansible/module_utils/six/__init__.py
Using module_utils file /usr/lib/python2.7/dist-packages/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /usr/lib/python2.7/dist-packages/ansible/module_utils/common/_collections_compat.py
Using module_utils file /usr/lib/python2.7/dist-packages/ansible/module_utils/common/file.py
Using module_utils file /usr/lib/python2.7/dist-packages/ansible/module_utils/parsing/__init__.py
Using module_utils file /usr/lib/python2.7/dist-packages/ansible/module_utils/pycompat24.py
Using module_utils file /usr/lib/python2.7/dist-packages/ansible/module_utils/common/process.py
Using module_utils file /usr/lib/python2.7/dist-packages/ansible/module_utils/common/__init__.py
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/database/mysql/mysql_user.py
```

Task:
```
   - name: Setting Root Password
      mysql_user:
        login_user: '{{ mysql_db_user }}'
        login_password: ''
        login_host: 'localhost'
        name: '{{ mysql_db_user }}'
        password: '{{ mysql_db_pass }}'
        priv: '*.*:ALL,GRANT'
        host_all: yes
        state: present
```

**Comment by esamattis** [comment]
@timorunge 	Here's the verbose output with `-vvvv`

https://gist.github.com/epeli/cad6e4c7b4f380816c63f164b865eaa7

**Comment by timorunge** [comment]
@anniemelen, @epeli: I've rechecked everything on my side locally - before applying the patch and afterwards. Everything is working fine for me in a similar setup (just testing the MySQL connection itself):

python 2.7:
```
# ansible --version
ansible 2.7.1
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

python 3.6:
```
# ansible --version
ansible 2.7.1
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
```

Since both of you are facing problems with setting a root password for MySQL itself:

- Can you connect via command line without a password defined and without the config file?
- Can you connect via command line without a password defined and with a defined config file?
- Have you tried to disable `check_implicit_admin: yes`? 
- Have you tried to add / change another existing user with Ansible?

**Comment by esamattis** [comment]
> Can you connect via command line without a password defined and without the config file?

Actually yes. The intention was to require one... I must re-check this on monday.

> Can you connect via command line without a password defined and with a defined config file?

Yes.

I'll get back to the other questions on monday as well.

**Comment by anniemelen** [comment]
> Can you connect via command line without a password defined and without the config file?

Yes.

> Can you connect via command line without a password defined and with a defined config file?

Yes.

> Have you tried to disable check_implicit_admin: yes?

As you can see above, it's already disabled. https://github.com/ansible/ansible/pull/47809#issuecomment-443204471

> Have you tried to add / change another existing user with Ansible?

Yes, and it works. But the point of task is to initiate standard mysql_secure_installation procedure and set root password when it's not set by default.
I should mention, that task was succeded with Ansible 2.4.4.

**Comment by timorunge** [comment]
@anniemelen: If adding different mysql users is possible with this patch / not failing with the message which is described in this ticket the issues are not related.

You're also mentioning Ansible 2.4.4 (here) and 2.7.0 (in [47736](https://github.com/ansible/ansible/issues/47736)). If you can provide a Dockerfile to re-produce this issue I'm happy to help you further but I think this PR is the wrong place for this. :)

**Comment by anniemelen** [comment]
@timorunge You see, adding different mysql users was possible without this patch...
Yes, my issue does not related to this PR, but it does to #47736, so I continue to talk there. And I can't provide Dockerfile, sorry.

File: lib/ansible/module_utils/mysql.py [hunk 1]
```diff
@@ -75,6 +76,9 @@ def mysql_connect(module, login_user=None, login_password=None, config_file='',
 
     db_connection = mysql_driver.connect(**config)
     if cursor_class is not None:
-        return db_connection.cursor(cursorclass=mysql_driver.cursors.DictCursor)
+        if mysql_driver is sys.modules['pymysql']:
```
Comment (felixfontein) [inline lib/ansible/module_utils/mysql.py]: Please don't do it this way. Set a flag after line 34 resp. 37 (the `import`s) and use that one here.

File: lib/ansible/module_utils/mysql.py [hunk 2]
```diff
@@ -75,6 +76,9 @@ def mysql_connect(module, login_user=None, login_password=None, config_file='',
 
     db_connection = mysql_driver.connect(**config)
     if cursor_class is not None:
-        return db_connection.cursor(cursorclass=mysql_driver.cursors.DictCursor)
```
Comment (felixfontein) [inline lib/ansible/module_utils/mysql.py:78]: I don't really understand why `mysql_driver.cursors.DictCursor` is hardcoded here. `mysql_replication` passes `'mysql_driver.cursors.DictCursor'` as `cursor_class` (and it is the only `mysql_*` module passing it), while most `proxysql_*` modules pass `cursor_class=mysql_driver.cursors.DictCursor` (and one or two doesn't pass it at all).

Either this should be named `use_dict_cursor` (or something like that), or it should be passed to `db_connection.cursor()` directly (and the call in `mysql_replication` should be changed). That's nothing you have to do for this PR, though, it's just a general rant after trying to understand what's going on :-)

**Comment by felixfontein** [comment]
I don't think this is related to #47736, though; it definitely won't fix it, since this PR is about a crash, while that issue is about a connection problem. @timorunge, can you remove the "Fixes #47736" from the PR description? If not, that issue will be closed once this will be merged.

**Comment by jengell** [comment]
I'm seeing the same problem using ansible 2.6.11. After patching ansible/module_utils/mysql.py with the commit, everything works.

File: lib/ansible/module_utils/mysql.py (hunk 1 above)
Comment (timorunge) [reply lib/ansible/module_utils/mysql.py]: Yes, you're right. That's ways better. :)

File: lib/ansible/module_utils/mysql.py (hunk 2 above)
Comment (timorunge) [reply lib/ansible/module_utils/mysql.py:78]: Yeah, I had the same problems trying to understand this; it's not really making sense but I just wanted to fix the problem which I've been facing with this cuserclass madness... :)

**Comment by timorunge** [comment]
> @timorunge, can you remove the "Fixes #47736" from the PR description? If not, that issue will be closed once this will be merged.

Done.

**Comment by felixfontein** [comment]
@timorunge you need to rebase the branch to get rid of the merge commit and all the other commits. Please check [these instructions](https://docs.ansible.com/ansible/devel/dev_guide/developing_rebasing.html).

**Comment by felixfontein** [comment]
Also, you need a changelog fragment (right now I cannot see whether you already have one, in case you have, please ignore this :) ). [Here are some instructions.](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#changelogs-how-to)

**Comment by timorunge** [comment]
@felixfontein Thanks. Both changes are done. :)

Actually I think this - if it's getting merged - should go back to 2.7.x and not only to 2.8.x.

**Review by felixfontein — APPROVED** [review]
LGTM shipit

Yep, it should be backported to at least 2.7 (maybe even 2.6).

**Comment by gundalow** [comment]
@epeli @anniemelen Hi, does this work for you now?

**Comment by cahlchang** [comment]
This fix was very helpful for me.
Now that part of the mysql driver is broken, I want to agree to capture this PR.
So many things go well.

**Comment by Xyon** [comment]
Code LGTM - I couldn't reproduce the initial issue in the first place, so can't test the fix here, but the logic seems reasonable. shipit

**Review by dagwieers — APPROVED** [review]
LGTM, did not test.

**Comment by bmalynovytch** [comment]
@ansibot label shipit

**Comment by bmalynovytch** [comment]
+label shipit

**Comment by dagwieers** [comment]
bot_status

**Comment by gundalow** [comment]
Ansibullbot is current taking a nap.

Thanks to everybody that's help with this, merged.

**Comment by gundalow** [comment]
If you'd like this fixed in Ansible 2.7 feel free to raise a backport PR.

**Comment by dsjagoda** [comment]
Github newbie trying to understand what's going on here.  Is this fix going to make it into 2.7.9 (if there is one) and/or 2.8?  I applied the code to my Ansible installation and it did fix the error I was receiving.

**Comment by felixfontein** [comment]
@dsjagoda it will definitely be in 2.8; it will only be in 2.7.9 (or later) if someone creates a backport PR for this. I don't know how active the mysql WG is, can someone from them comment on this?

**Comment by timorunge** [comment]
It should go along with #53445 (which needs to be merged).

**Comment by bmalynovytch** [comment]
@felixfontein I seem to be the only one for now

**Comment by felixfontein** [comment]
@timorunge are you interested in becoming part of the mysql WG? (https://github.com/ansible/community/wiki/MySQL)

**Comment by timorunge** [comment]
If nobody is taking it, I took the 5 minutes: #53483 :)

**Comment by timorunge** [comment]
@felixfontein I rarely have time (or basically just some spare time).
I can help if required but I see that we already have 5 people in the MySQL WG. :)

**Comment by felixfontein** [comment]
@timorunge that's a known problem, I guess most people here have it ;) Also, the number of people in a WG doesn't say that much, it depends on how many people are actively doing something. It looks that for the mysql WG, it's mainly @bmalynovytch. So you could also become another idling member ;) Being in the WG also has the advantage that you're pinged for all MySQL-related PRs and issues. If you can comment from time to time, or help reproducing something or can test PRs whether they do as promised, that would probably already be a great help.

If you don't want to spend that time on this, I understand, I was just asking since you seem to be somewhat interested :)

**Comment by timorunge** [comment]
New Backport PR: #53519 (in combination with #53445).
