### ISSUE TITLE
ec2_vpc_route_table fails with "AttributeError: 'dict' object has no attribute 'tags'" on route table creation

### ISSUE THREAD

**Issue by jrko** [ansible/ansible#38570]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2_vpc_route_table

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/vagrant/repo/v2-ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### CONFIGURATION

```
ANSIBLE_SSH_ARGS(/home/vagrant/repo/v2-ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
DEFAULT_HOST_LIST(/home/vagrant/repo/v2-ansible/ansible.cfg) = [u'/home/vagrant/repo/v2-ansible/environment/test']
DEFAULT_REMOTE_USER(/home/vagrant/repo/v2-ansible/ansible.cfg) = {{ ansible_username | default('ansible') }}
HOST_KEY_CHECKING(/home/vagrant/repo/v2-ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/vagrant/repo/v2-ansible/ansible.cfg) = False
```
##### OS / ENVIRONMENT

Debian 9.1
`Linux dojo 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux`

##### SUMMARY

The `ec2_vpc_route_table` module crashes on route table creation. The AWS Console shows that the route table is created successfully however.

The error appears to be related to the `tags` attribute not being recognized. The AWS Console shows that the route table is tagged successfully however.

Subsequent runs fail in the same fashion. 

Omitting the `tags` parameter creates an untagged route table, but still crashes the same way.

##### STEPS TO REPRODUCE

Create a new route table:

```yaml
- name: Create subnet routes
  ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpcs.0.id }}"
    region: "{{ ec2_region }}"
    tags:
      Name: "{{ subnet_name }}"
    subnets:
      - "{{ subnet_name }}"
    routes:
      - dest: "{{ cidr_ip_all }}"
        gateway_id: "{{ igw.internet_gateways.0.internet_gateway_id }}"
```

##### EXPECTED RESULTS

Route table is created without errors. This works in `2.4.3`.
##### ACTUAL RESULTS

MODULE FAILURE

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_hbuePJ/ansible_module_ec2_vpc_route_table.py", line 724, in <module>
    main()
  File "/tmp/ansible_hbuePJ/ansible_module_ec2_vpc_route_table.py", line 716, in main
    result = ensure_route_table_present(connection, module)
  File "/tmp/ansible_hbuePJ/ansible_module_ec2_vpc_route_table.py", line 674, in ensure_route_table_present
    associated_subnets = find_subnets(connection, module, vpc_id, subnets)
  File "/tmp/ansible_hbuePJ/ansible_module_ec2_vpc_route_table.py", line 295, in find_subnets
    matching_count = len([1 for s in subnets_by_name if s.tags.get('Name') == name])
AttributeError: 'dict' object has no attribute 'tags'

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_hbuePJ/ansible_module_ec2_vpc_route_table.py\", line 724, in <module>\n    main()\n  File \"/tmp/ansible_hbuePJ/ansible_module_ec2_vpc_route_table.py\", line 716, in main\n    result = ensure_route_table_present(connection, module)\n  File \"/tmp/ansible_hbuePJ/ansible_module_ec2_vpc_route_table.py\", line 674, in ensure_route_table_present\n    associated_subnets = find_subnets(connection, module, vpc_id, subnets)\n  File \"/tmp/ansible_hbuePJ/ansible_module_ec2_vpc_route_table.py\", line 295, in find_subnets\n    matching_count = len([1 for s in subnets_by_name if s.tags.get('Name') == name])\nAttributeError: 'dict' object has no attribute 'tags'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/ec2_vpc_route_table.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_vpc_route_table.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @willthames @wimnat
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ZuZuD** [comment]
@jrko can you try this out #38707 and give us a feedback? Thanks!

**Comment by jrko** [comment]
@ZuZuD working for me as well :+1:
