### PR TITLE
evaluate_tags: add `None` as fallback in case `_parent` is not existing

### PR DESCRIPTION
**Pull request by mabezi**
##### SUMMARY
Not every `Taggable` object has a `_parent`.
Due to the changes introduced in commit a05d254ca29e59d7e315fac1212d8708bdde8af7, this now leads to errors when using `evaluate_tags`. In our case, this affected [`Role`-objects](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/role/__init__.py#L99).

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

Error message that occurred due to the commit in our callback plugin:
```
[WARNING]: Failure using method (v2_playbook_on_start) in callback plugin (<ansible.plugins.callback.magic_vault.CallbackModule object at 0x7ffa3604c810>): 'Role' object has no attribute '_parent'
Callback Exception: 
  File "/usr/lib/python3.11/site-packages/ansible/executor/task_queue_manager.py", line 465, in send_callback
    method(*new_args, **kwargs)
   File "/.../AGDSN/Ansible/callback_plugins/magic_vault.py", line 117, in v2_playbook_on_start
    pending_roles = self._get_pending_roles(play)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/.../AGDSN/Ansible/callback_plugins/magic_vault.py", line 212, in _get_pending_roles
    if role.evaluate_tags(play.only_tags, play.skip_tags, []):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/lib/python3.11/site-packages/ansible/playbook/taggable.py", line 64, in evaluate_tags
    obj = obj._parent
          ^^^^^^^^^^^
66 plays in site.yml
```

### CODE REVIEW

**Comment by bcoca** [comment]
This is not the proper fix here, all objects that have tags must have a _parent, or _role or _play (which is what we should fix this to check).

**Comment by mabezi** [comment]
> This is not the proper fix here, all objects that have tags must have a _parent, or _role or _play (which is what we should fix this to check).

As I may not have the time to fix it myself at the moment, I've moved this to an issue. #82310
