### ISSUE TITLE
hostvars lookup 

### ISSUE THREAD

**Issue by kkoralsky** [ansible/ansible#62600]
##### SUMMARY

template lookup does not see currently processed hostvars  

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

template lookup

##### ANSIBLE VERSION

```paste below
ansible 2.10.0.dev0
  config file = /home/koral/projects/ansible-lookup-hostvars-bug/ansible.cfg
  configured module search path = ['/home/koral/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/koral/workspace/ansible/lib/ansible
  executable location = /home/koral/.virtualenvs/ansdev3/bin/ansible
  python version = 3.7.3rc1 (default, Mar 13 2019, 11:01:15) [GCC 8.3.0]

```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/koral/projects/ansible-lookup-hostvars-bug/ansible.cfg) = ['/home/koral/projects/ansible-lookup-hostvars-bug/inventory.yaml']
DEFAULT_STDOUT_CALLBACK(/home/koral/projects/ansible-lookup-hostvars-bug/ansible.cfg) = yaml
RETRY_FILES_ENABLED(/home/koral/projects/ansible-lookup-hostvars-bug/ansible.cfg) = False

```

##### OS / ENVIRONMENT

- Debian 10, 
- ansible 2.9, 2.10.dev, 
- Python 2.7 &  3.7

##### STEPS TO REPRODUCE

https://github.com/kkoralsky/ansible-lookup-hostvars-bug

playbook:
```yaml
- hosts: localhost
  # gather_facts: no
  tasks:
    - debug: msg='{{ hostvars.localhost.var }}'
    - debug: msg='{{ lookup("template", "template.j2") }}'
```
inventory:
```yaml
all:
  vars:
    var: hello world
  hosts:
    localhost: {ansible_host: 127.0.0.1}
```
template:
```
{{ hostvars.localhost.var }}
```

##### EXPECTED RESULTS

both tasks should return 'hello world' as it works on current stable version (2.8.5)

##### ACTUAL RESULTS

it returns `'ansible.vars.hostvars.HostVars object' has no attribute 'localhost'`
if you leave `{{ hostvars }}` alone in template: 

```
fatal: [localhost]: FAILED! =>
  msg: 'An unhandled exception occurred while running the lookup plugin ''template''. Error was a <class ''AttributeError''>, original message: ''VariableManager'' object has no attribute ''_loader'''
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/plugins/lookup/template.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/template.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sapajune** [comment]
Looks like I ran into this bug immediately after upgrading Ansible to 2.9.0 so it does affect that as well. Downgrading to 2.8.6 avoids the problem.

**Comment by tremble** [comment]
I'm hitting this on 2.9 and 2.10:

```
ansible 2.9.0
  config file = /home/mchappel/.ansible.cfg
  configured module search path = [u'/home/mchappel/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mchappel/vcs/redhat/ansicloud-full/ansible-2.9/lib/python2.7/site-packages/ansible
  executable location = /home/mchappel/vcs/redhat/ansicloud-full/ansible-2.9/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 12:19:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

```
ansible 2.10.0.dev0
  config file = /home/mchappel/.ansible.cfg
  configured module search path = [u'/home/mchappel/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mchappel/vcs/ansible/ansible-review/lib/ansible
  executable location = /home/mchappel/vcs/ansible/ansible-review/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 12:19:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

@samdoran Suggested trying the fix from #64401 unfortuantely this does *not* appear to fix the issue.

**Comment by samdoran** [comment]
@tremble Thank you for trying. I'll look into it some more.

**Comment by sivel** [comment]
I believe this is a duplicate of https://github.com/ansible/ansible/issues/63940

**Comment by tremble** [comment]
I concur that this looks like #63940

Even better #64070 appears to fix this.  (at least it fixes my playbooks)

**Comment by mkrizek** [comment]
I tested the provided playbook with PR https://github.com/ansible/ansible/pull/64070 which fixes the issue. I am going to go ahead and close this as a duplicate of https://github.com/ansible/ansible/issues/63940.

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
