### PR TITLE
Fix named include handler (#15915)

### LINKED ISSUE #15915: Cannot use include in task handlers (AttributeError)
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

**Affected :**

```
ansible 2.2.0
  config file = /home/pistache/.ansible.cfg
  configured module search path = Default w/o overrides
```

```
ansible 2.1.0.0
  config file = /home/pistache/.ansible.cfg
  configured module search path = Default w/o overrides

```

**Not affected :** Ansible 2.0.2
##### CONFIGURATION

None
##### OS / ENVIRONMENT

Debian Unstable (on my workstation, bug was also reproduced with Ansible 2.1 on Jessie)
##### SUMMARY

I cannot use `include` in a task handler with Ansible 2.1 or 2.2 (`stable-2.1` and `devel`), the same code that was working with Ansible 2.0 now raises an AttributeError.

It seems like the task handler code was modified in such a way that it does not allow `include` anymore.
##### STEPS TO REPRODUCE

Create a role, and use `include` in a task handler.

`handlers/main.yml`

```
- name: Test
  include: test.yml
```

`handlers/test.yml`

```
- debug: msg="Test handler notified."
```

`tasks/main.yml`

```
- name: Test task
  debug: msg="Notifying test handler"
  changed_when: yes
  notify:
    - Test
```
##### EXPECTED RESULTS

No errors, should print out "Test handler notified."
##### ACTUAL RESULTS

```
ERROR! Unexpected Exception: 'TaskInclude' object has no attribute 'has_triggered'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 92, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 142, in run
    result = self._tqm.run(play=play)
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 253, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/strategy/linear.py", line 215, in run
    self._execute_meta(task, play_context, iterator)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/strategy/__init__.py", line 707, in _execute_meta
    self.run_handlers(iterator, play_context)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/strategy/__init__.py", line 589, in run_handlers
    result = self._do_handler_run(handler, handler_name, iterator=iterator, play_context=play_context)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/strategy/__init__.py", line 621, in _do_handler_run
    if not handler.has_triggered(host) and (host.name not in self._tqm._failed_hosts or play_context.force_handlers):
AttributeError: 'TaskInclude' object has no attribute 'has_triggered'

```

### PR DESCRIPTION
**Pull request by mvdbeek**
##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

playbook/helpers.py
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

and

```
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

This fixes #15915, which is that static named includes as handlers don't work.
I have added a failing test as the [first commit](fac59ef86140a29f8bf6b4d421d4345adfe2ac2e).
This is because the name of the include is ignored when the included tasks are loaded.
Instead I am adding the name (given to the included task) to each named include task.

before: 

```
TASK [test_includes : test handlers with includes] *****************************
ERROR! The requested handler 'named_include_handler' was not found in any of the known handlers
make: *** [includes] Error 1
```

after

```
RUNNING HANDLER [test_includes : named_include_handler] ************************
ok: [testhost]
```

### CODE REVIEW

**Comment by mvdbeek** [comment]
I am unable to figure out which tests are failing (and consequently why).
I suspect it is [these tests](https://app.shippable.com/runs/57ae11a811c0681000c817f6/21/tests)
~~But running this test locally does not change if I include my PR ... any help appreciated~~.

FWIW, the local test output:

```
/Users/marius/src/ansible/test/integration/test_blocks
(.venv)mariuss-MacBook-Pro:test_blocks marius$ ansible-playbook main.yml
statically included: /Users/marius/src/ansible/test/integration/test_blocks/fail.yml
statically included: /Users/marius/src/ansible/test/integration/test_blocks/fail.yml

PLAY [simple block test] *******************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [set block tasks run flag] ************************************************
ok: [localhost]

TASK [EXPECTED FAILURE fail in tasks] ******************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed as requested from task"}

TASK [set block rescue run flag] ***********************************************
ok: [localhost]

TASK [EXPECTED FAILURE fail in rescue] *****************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed as requested from task"}

TASK [set block always run flag] ***********************************************
ok: [localhost]

TASK [assert] ******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "TEST COMPLETE"
}

PLAY [block with includes] *****************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [EXPECTED FAILURE] ********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "failed from tasks"}

TASK [set_fact] ****************************************************************
ok: [localhost]

TASK [EXPECTED FAILURE] ********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "failed from rescue"}

TASK [set_fact] ****************************************************************
ok: [localhost]

TASK [assert] ******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "TEST COMPLETE"
}

PLAY RECAP *********************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=1
```

**Comment by mvdbeek** [comment]
OK, so actually the failing test was slightly different, without a1b5314 named task includes would also have their name changed to the name of the include, and so instead of `[EXPECTED FAILURE]` the task would be named `[include fail.yml in tasks]`.

I think this is ready for review now.

**Comment by jimi-c** [comment]
Hi @mvdbeek, I fixed this in another way. Thanks though!
