### PR TITLE
[stable-2.7] Migrate from MySQLdb to PyMySQL (#40123)

### LINKED ISSUE #29887: mysql_* modules are implicitly Python3 incompatible
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
* mysql_* module

##### ANSIBLE VERSION
```
ansible 2.3.2.0 / master
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Python 3 target

##### SUMMARY
mysql_* modules always depend on `MySQLdb`, which does not support Python 3.
This inherently creates incompatibility with Python 3. Raising this as bug per [Python 3 support policy](https://docs.ansible.com/ansible/latest/python_3_support.html).

Possible solutions:
* switch all mysql_* modules to use PyMySQL all the time
* allow all mysql_* modules to use whatever MySQL driver is available (MySQLdb, PyMySQL, etc)

##### STEPS TO REPRODUCE
* use mysql_* module on a target host with Python 3

##### EXPECTED RESULTS
mysql_* modules should be able to use a Python 2/3-compatible drivers, such as PyMySQL

##### ACTUAL RESULTS
```
the python mysqldb module is required
```

### PR DESCRIPTION
**Pull request by DSpeichert**
* Migrate from MySQLdb to PyMySQL
* Deduplicate driver loading and failure message
* Explain requirements
* Apply requirements docs change to proxysql too
* Add changelog.
(cherry picked from commit d34cf93f1a7f96a14da1354b8f88a90c058e3e86)

Co-authored-by: Daniel Speichert <DSpeichert@users.noreply.github.com>

##### SUMMARY
Fixes #29887

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
mysql_db

##### ANSIBLE VERSION
2.7

##### ADDITIONAL INFORMATION
Backport of #40123

### CODE REVIEW

**Comment by abadger** [comment]
Looks good.  I'll get this merged to stbale-2.7 once 2.7.0 is out (and it will appear in 2.7.1)

**Review by odyssey4me — APPROVED** [review]

**Comment by abadger** [comment]
Merged for the 2.7.1 release.

**Comment by matt-horwood-mayden** [comment]
Afternoon,

Have just run our proxysql role to configure 2 new nodes, this has been working fine. But after an update to 2.7.1, I now get an error.

```failed: [ps07b.iaptus.ukc.far.uk.mayden.com] (item={u'port': 3306, u'hostgroup': 2, u'address': u'10.3.100.64'}) => {"changed": false, "item": {"address": "10.3.100.64", "hostgroup": 2, "port": 3306}, "module_stderr": "Shared connection to 10.3.100.163 closed.\r\n", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/mayhealthv_mho/.ansible/tmp/ansible-tmp-1543327459.08-40750051886508/AnsiballZ_proxysql_backend_servers.py\", line 113, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/mayhealthv_mho/.ansible/tmp/ansible-tmp-1543327459.08-40750051886508/AnsiballZ_proxysql_backend_servers.py\", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/mayhealthv_mho/.ansible/tmp/ansible-tmp-1543327459.08-40750051886508/AnsiballZ_proxysql_backend_servers.py\", line 48, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_proxysql_backend_servers_payload_yTxxSk/__main__.py\", line 504, in <module>\r\n  File \"/tmp/ansible_proxysql_backend_servers_payload_yTxxSk/__main__.py\", line 450, in main\r\nAttributeError: 'module' object has no attribute 'cursors'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}```

ansible 2.7.1
  config file = /Users/mattho/.ansible.cfg
  configured module search path = [u'/Users/mattho/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Aug 17 2018, 17:41:52) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]

**Comment by abadger** [comment]
Could you open a new issue and link to this pr in the new issue?  No one is actively looking at closed issues so new problems can be missed without a new issue.

**Comment by matt-horwood-mayden** [comment]
sure @abadger 
[Module ProxySQL - Backend_servers error #49191](https://github.com/ansible/ansible/issues/49191)
