### ISSUE TITLE
ansible-playbook -O is broken

### ISSUE THREAD

**Issue by jkleint** [ansible/ansible#332]
Apologies if this is dust from some work in progress, but -O hasn't worked for a couple days:

```
$ ansible-playbook anything.yml -O myhost
Traceback (most recent call last):
  File "/home/jkleint/progs/ansible/bin/ansible-playbook", line 109, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/jkleint/progs/ansible/bin/ansible-playbook", line 86, in main
    extra_vars=extra_vars
  File "/home/jkleint/progs/ansible/lib/ansible/playbook.py", line 113, in __init__
    if not self.inventory._is_script:
AttributeError: 'PlayBook' object has no attribute 'inventory'
```

Git bisect tells me it stopped working in SHA: c80475283593cf57095f71726396d683641757b4

Looking at playbook.py, the obvious fix makes the `if` and `else` branches identical, so I will assume it must be more complicated than that and let someone who knows more take a look.

**Comment by mpdehaan** [comment]
this is #308 or can be worked on together

patches to fix welcome, I don't use -O myself
