### PR TITLE
Support python < 2.6 in urls.py

### PR DESCRIPTION
**Pull request by sivel**
`module_utils/urls.py` uses `socket.create_connection` for HTTPS connections, however `socket.create_connection` was not added until python 2.6.  This results in tracebacks on Python < 2.6 such as RHEL 5.

```
  File "/home/sivel/.ansible/tmp/ansible-tmp-1409930019.36-92123499720727/get_url", line 2210, in ?
    main()
  File "/home/sivel/.ansible/tmp/ansible-tmp-1409930019.36-92123499720727/get_url", line 222, in main
    tmpsrc, info = url_get(module, url, dest, use_proxy, last_mod_time, force)
  File "/home/sivel/.ansible/tmp/ansible-tmp-1409930019.36-92123499720727/get_url", line 146, in url_get
    rsp, info = fetch_url(module, url, use_proxy=use_proxy, force=force, last_mod_time=last_mod_time)
  File "/home/sivel/.ansible/tmp/ansible-tmp-1409930019.36-92123499720727/get_url", line 2196, in fetch_url
    r = urllib2.urlopen(request, None)
  File "/usr/lib64/python2.4/urllib2.py", line 130, in urlopen
    return _opener.open(url, data)
  File "/usr/lib64/python2.4/urllib2.py", line 358, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.4/urllib2.py", line 376, in _open
    '_open', req)
  File "/usr/lib64/python2.4/urllib2.py", line 337, in _call_chain
    result = func(*args)
  File "/home/sivel/.ansible/tmp/ansible-tmp-1409930019.36-92123499720727/get_url", line 1861, in https_open
    return self.do_open(CustomHTTPSConnection, req)
  File "/usr/lib64/python2.4/urllib2.py", line 1089, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib64/python2.4/httplib.py", line 810, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.4/httplib.py", line 833, in _send_request
    self.endheaders()
  File "/usr/lib64/python2.4/httplib.py", line 804, in endheaders
    self._send_output()
  File "/usr/lib64/python2.4/httplib.py", line 685, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.4/httplib.py", line 652, in send
    self.connect()
  File "/home/sivel/.ansible/tmp/ansible-tmp-1409930019.36-92123499720727/get_url", line 1852, in connect
    sock = socket.create_connection((self.host, self.port), self.timeout)
AttributeError: 'module' object has no attribute 'create_connection'
```

This pull request backports `create_connection` from python 2.7 (not python 2.6 due to create_connection being enhanced in python 2.7) and made compatible with python < 2.7.

Additionally an `__init__` method was added to `CustomHTTPSConnection` to ensure that we have the required instance attributes for python < 2.6.

I have tested these changes with Python 2.4 (RHEL5), Python 2.6 (RHEL5) as well as Python 2.7 (Mac OS X 10.9)

### CODE REVIEW

**Comment by abadger** [comment]
Will it cause problems to use the system create_connection on py2.6?  If not, doing something like:

``` python
if socket.create_connection:
    create_connection = socket.create_connection
else:
   create_connection = _create_connection

def _create_connection[...]
```

Would let us pick up any additional bugfixes from the system python.

In the new constructor, should we set self.timeout and self._tunnel_host before we call the base class constructor?  That would let the base class constructor override those values if how they're set there should change in the future.

**Comment by jimi-c** [comment]
Or just monkey-patch it:

<pre>
if not hasattr(socket, "create_connection"):
    socket.create_connection = _create_connection
</pre>

**Comment by sivel** [comment]
My testing showed that the replacement that I added works fine on python 2.4-2.7.  The function signature has changed between python 2.6 and python 2.7 to include a 'source_address' kwarg, however the functionality to bind to a source address works back to python 2.4. This would allow us to potentially even use source_address functionality in versions earlier than 2.7.

This would standardize the function we use to work the same from python 2.4-2.7.

I am up for monkey patching when socket doesn't have create_connection.  Just let me know what you think of my points above.  I do understand the benefit of bug fixes in upstream, but I think these functions are pretty stable at this point.

As for moving the creation of the instance attributes, I have done so.

**Comment by jimi-c** [comment]
I think being as noninvasive as possible is probably the safer route, so I'd say go ahead and monkey-patch it only if it doesn't exist.

**Comment by sivel** [comment]
Ok, the PR has been updated to monkey patch socket if the system python provided socket does not include create_connection.

I've re-tested on Python 2.4-2.7

**Comment by mpdehaan** [comment]
Not sure I'm ok with monkey patching.

is there perhaps a more simple way to do this?  (fallback to pycurl?, etc?)

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We have merged in the alternate solution above, so we're closing this PR.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by abadger** [comment]
Just a note for anyone looking at this bug later: We discussed the overall situation here and decided that at the moment it made the most sense to disable the new feature on older pythons where socket.create_connection() was unavailable.  If this becomes a problem for those older pythons in the future we would probably want to base off of the original patch from @sivel rather than monkey patching.
