### PR TITLE
new HandlerTaskInclude Class which can run TaskIncludes inside Handlers

### LINKED ISSUE #15915: Cannot use include in task handlers (AttributeError)
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

**Affected :**

```
ansible 2.2.0
  config file = /home/pistache/.ansible.cfg
  configured module search path = Default w/o overrides
```

```
ansible 2.1.0.0
  config file = /home/pistache/.ansible.cfg
  configured module search path = Default w/o overrides

```

**Not affected :** Ansible 2.0.2
##### CONFIGURATION

None
##### OS / ENVIRONMENT

Debian Unstable (on my workstation, bug was also reproduced with Ansible 2.1 on Jessie)
##### SUMMARY

I cannot use `include` in a task handler with Ansible 2.1 or 2.2 (`stable-2.1` and `devel`), the same code that was working with Ansible 2.0 now raises an AttributeError.

It seems like the task handler code was modified in such a way that it does not allow `include` anymore.
##### STEPS TO REPRODUCE

Create a role, and use `include` in a task handler.

`handlers/main.yml`

```
- name: Test
  include: test.yml
```

`handlers/test.yml`

```
- debug: msg="Test handler notified."
```

`tasks/main.yml`

```
- name: Test task
  debug: msg="Notifying test handler"
  changed_when: yes
  notify:
    - Test
```
##### EXPECTED RESULTS

No errors, should print out "Test handler notified."
##### ACTUAL RESULTS

```
ERROR! Unexpected Exception: 'TaskInclude' object has no attribute 'has_triggered'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 92, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 142, in run
    result = self._tqm.run(play=play)
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 253, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/strategy/linear.py", line 215, in run
    self._execute_meta(task, play_context, iterator)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/strategy/__init__.py", line 707, in _execute_meta
    self.run_handlers(iterator, play_context)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/strategy/__init__.py", line 589, in run_handlers
    result = self._do_handler_run(handler, handler_name, iterator=iterator, play_context=play_context)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/strategy/__init__.py", line 621, in _do_handler_run
    if not handler.has_triggered(host) and (host.name not in self._tqm._failed_hosts or play_context.force_handlers):
AttributeError: 'TaskInclude' object has no attribute 'has_triggered'

```

### PR DESCRIPTION
**Pull request by Schnitzel**
##### ISSUE TYPE

- Bugfix Pull Request
##### ANSIBLE VERSION

```
ansible 2.2.0 (taskinclude_handler e700a173ec) last updated 2016/05/22 15:43:44 (GMT +200)
  lib/ansible/modules/core: (detached HEAD a64d72d7bc) last updated 2016/05/22 15:36:48 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD d2900e856b) last updated 2016/05/22 15:36:48 (GMT +200)
  config file = /Users/Michael/git/amazeeio-ansible/ansible.cfg
  configured module search path = ['./ansible-modules-extras']
```
##### SUMMARY

With 2c20579a a new `TaskInclude` Class got introduced. Unfortunately this class cannot handle being used inside a Handler (regular Tasks have a special `Handler` Class which is used when a Task should be used inside a Handler). 
So this commit adds a new `HandlerTaskInclude` which is very similary to `Handler` Class, but just inherits from `TaskInclude`.
This fixes #15915

### CODE REVIEW

**Comment by jimi-c** [comment]
Merged, thanks!

**Comment by jimi-c** [comment]
Also cherry-picked to stable-2.1.
