### ISSUE TITLE
cs_instance "user_data" error only when using python3 working in python2

### ISSUE THREAD

**Issue by nbari** [ansible/ansible#37112]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

cs_instance

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /Users/nbari/projects/ansible/ansible.cfg
  configured module search path = ['/Users/nbari/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/nbari/Library/Python/3.6/lib/python/site-packages/ansible
  executable location = /Users/nbari/Library/Python/3.6/bin/ansible
  python version = 3.6.4 (default, Mar  1 2018, 18:36:50) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]

```

##### OS / ENVIRONMENT

macOS High Sierra, brew instal python

##### SUMMARY

Error when running the playbook only using python3

##### STEPS TO REPRODUCE

Run playbook using python 3 ` ansible-playbook play.yml`

```yaml
 - name: Creat VM
      cs_instance:
        name: cloudinit-test
        template: Linux CentOS 7.4 64-bit 10G Disk (2018-01-08-d617dd)
        service_offering: Micro
        ssh_key: devops
        api_region: exoscale
        state: started
        tags:
          - key: provisioner
            value: ansible
        user_data: |
            #cloud-config
            package_upgrade: true
            packages:
              - tmux
```

##### EXPECTED RESULTS

no error

##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: a bytes-like object is required, not 'str'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_j03a0m9f/ansible_module_cs_instance.py\", line 1088, in <module>\n    main()\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_j03a0m9f/ansible_module_cs_instance.py\", line 1068, in main\n    acs_instance.present_instance()\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_j03a0m9f/ansible_module_cs_instance.py\", line 668, in present_instance\n    instance = self.update_instance(instance=instance, start_vm=start_vm)\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_j03a0m9f/ansible_module_cs_instance.py\", line 765, in update_instance\n    args_instance_update['userdata'] = self.get_user_data()\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_j03a0m9f/ansible_module_cs_instance.py\", line 682, in get_user_data\n    user_data = base64.b64encode(str(user_data))\n  File \"/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/base64.py\", line 58, in b64encode\n    encoded = binascii.b2a_base64(s, newline=False)\nTypeError: a bytes-like object is required, not 'str'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
!component cs_instance

**Comment by gundalow** [comment]
bot_status

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/cloudstack/cs_instance.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/cloudstack/cs_instance.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dpassante @resmo
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
### Components
[lib/ansible/modules/cloud/cloudstack/cs_instance.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/cloudstack/cs_instance.py)
support: community
maintainers: dpassante resmo

### Metadata
**waiting_on**: maintainer
[needs_info](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_info): False

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by nbari** [comment]
While testing with python 2 and changing the `state` to `destroyed` is giving this error:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'id'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_b9HigX/ansible_module_cs_instance.py\", line 1088, in <module>\n    main()\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_b9HigX/ansible_module_cs_instance.py\", line 1078, in main\n    result = acs_instance.get_result(instance)\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_b9HigX/ansible_module_cs_instance.py\", line 973, in get_result\n    self.result['user_data'] = self._get_instance_user_data(instance)\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_b9HigX/ansible_module_cs_instance.py\", line 544, in _get_instance_user_data\n    res = self.cs.getVirtualMachineUserData(virtualmachineid=instance['id'])\nKeyError: 'id'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

**Comment by resmo** [comment]
@nbari 1 bug report per issue, please file a new issue with exact workflow what you did so we can reproduce and handle cover it in integration tests.

**Comment by resmo** [comment]
status:reproducing

**Comment by nbari** [comment]
Hi @resmo I created a new issue here https://github.com/ansible/ansible/issues/37138

**Comment by resmo** [comment]
resolved_by_pr #37135 

@nbari could you verify, if the fix solves the issue?

**Comment by nbari** [comment]
@resno  How could I test?

I did a `git checkout -b testing_PR37135` following http://docs.ansible.com/ansible/2.3/dev_guide/developing_test_pr.html but I need more help if you could please give me more guidelines I will give a try.

**Comment by resmo** [comment]
@nbari 

Probably the easiest way to quick tests  is to download the module into a directory called library along with your playbooks and run the playbooks again.

~~~
cd <to where your playbooks are>
mkdir -p library
cd library
wget https://raw.githubusercontent.com/resmo/ansible/06090a4d36037082b95767838167717c84de6761/lib/ansible/modules/cloud/cloudstack/cs_instance.py

cd <to where your playbooks are>
ansible-playbook your_playbook.yml
~~~

**Comment by nbari** [comment]
Hi @resmo I am getting now this error:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'AnsibleCloudStackInstance' object has no attribute 'get_disk_offering'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_uk1jwsz0/ansible_module_cs_instance.py\", line 959, in <module>\n    main()\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_uk1jwsz0/ansible_module_cs_instance.py\", line 944, in main\n    acs_instance.present_instance()\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_uk1jwsz0/ansible_module_cs_instance.py\", line 584, in present_instance\n    instance = self.deploy_instance(start_vm=start_vm)\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_uk1jwsz0/ansible_module_cs_instance.py\", line 632, in deploy_instance\n    args['diskofferingid'] = self.get_disk_offering(key='id')\nAttributeError: 'AnsibleCloudStackInstance' object has no attribute 'get_disk_offering'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

**Comment by resmo** [comment]
ok, the module is not fully compatible with 2.4 anymore. My fault. 

Try:
~~~
(remove the library directory again)
cd /tmp
git clone --depth 1 git@github.com:resmo/ansible.git -b fix/cs_instance_user_data_py3
cd ansible
source ./hacking/env-setup
cd <to your playbooks>
ansible-playbook <your playbook>
~~~

**Comment by nbari** [comment]
Hi @resmo I still having errors:

I am testing by clothing into my `library` this: https://raw.githubusercontent.com/resmo/ansible/06090a4d36037082b95767838167717c84de6761/lib/ansible/modules/cloud/cloudstack/cs_instance.py

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'AnsibleCloudStackInstance' object has no attribute 'get_disk_offering'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_57dothvo/ansible_module_cs_instance.py\", line 959, in <module>\n    main()\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_57dothvo/ansible_module_cs_instance.py\", line 944, in main\n    acs_instance.present_instance()\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_57dothvo/ansible_module_cs_instance.py\", line 584, in present_instance\n    instance = self.deploy_instance(start_vm=start_vm)\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_57dothvo/ansible_module_cs_instance.py\", line 632, in deploy_instance\n    args['diskofferingid'] = self.get_disk_offering(key='id')\nAttributeError: 'AnsibleCloudStackInstance' object has no attribute 'get_disk_offering'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

**Comment by resmo** [comment]
@nbari The module won't work with 2.4. You have to test with 2.5 or devel branch.

**Comment by nbari** [comment]
@resno what is the best/easy way to get 2.5 for now and test?

**Comment by resmo** [comment]
~~~
cd /tmp
git clone --depth 1 git@github.com:ansible/ansible.git -b stable-2.5
cd ansible
source ./hacking/env-setup
cd <to your playbooks/project>
ansible-playbook <your playbook>
~~~

**Comment by nbari** [comment]
@resmo  Any fix for the 2.4? version, that will simplify/share ansible among other colleagues by just need to install ansible via pip and add into `library` the fixed  `cs_instance.py`
