### ISSUE TITLE
get_url returns: AttributeError: 'function' object has no attribute 'urlsplit'

### ISSUE THREAD

**Issue by rbbrasil** [ansible/ansible#23040]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
get_url

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 6fa3cb55e1) last updated 2017/03/28 11:27:00 (GMT -300)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.11 (default, Sep 29 2016, 13:33:00) [GCC 5.3.1 20160406 (Red Hat 5.3.1-6)]
```

##### CONFIGURATION
ansible.cfg mods:
```
sudo_flags=-H -S
control_path = %(directory)s/ansible-ssh-%%C
```
##### OS / ENVIRONMENT
Master: Fedora 23
Node: RHEL 6.6 

##### SUMMARY
Module get_url fails with "AttributeError: 'function' object has no attribute 'urlsplit'" error.

This same task/playbook is working with Ansible 2.2.0.0.

##### STEPS TO REPRODUCE
main.yml:
```yaml
- name: 4.5. Download do instalador
  get_url: url="{{ wls_installation_file_url }}"
           dest={{ wls_download_path }}
           owner={{ wls_user }} group={{ wls_group }}
  become: true
```

vars.yml:
```yaml
wls_user: oracle
wls_group: oinstall
wls_download_path: /u01/install
wls_installation_file: fmw_{{ wls_version }}.0_wls.jar
wls_installation_file_url: "http://pkg.localdomain/{{ wls_installation_file }}"
```

The {{ wls_version }} is set from the command line.

##### EXPECTED RESULTS
Download the .jar file to {{ wls_download_path }} dir.

##### ACTUAL RESULTS
```
fatal: [client.localdomain]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "OpenSSH_7.2p2, OpenSSL 1.0.2j-fips  26 Sep 2016\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 10107\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to client.localdomain closed.\r\n", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_lQ8hkx/ansible_module_get_url.py\", line 439, in <module>\r\n    main()\r\n  File \"/tmp/ansible_lQ8hkx/ansible_module_get_url.py\", line 359, in main\r\n    filename = url_filename(info['url'])\r\n  File \"/tmp/ansible_lQ8hkx/ansible_module_get_url.py\", line 192, in url_filename\r\n    fn = os.path.basename(urlparse.urlsplit(url)[2])\r\nAttributeError: 'function' object has no attribute 'urlsplit'\r\n", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```

**Comment by ansibot** [comment]
cc @jpmens
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by rbbrasil** [comment]
I'm not sure, but apparently this is a incompatibility with my OS Python (2.7.11) module version.

Excerpt from the module file running on version 2.2.0.0 which was installed by `dnf` package manager
`/usr/lib/python2.7/site-packages/ansible/modules/core/network/basics/get_url.py`:
```python
from ansible.module_utils.six.moves.urllib.parse import urlsplit

def url_filename(url):
    fn = os.path.basename(urlsplit(url)[2])
    if fn == '':
        return 'index.html'
    return fn
```


And now from the module file running on version 2.4.0, installed from github
`~/Apps/ansible/lib/ansible/modules/core/network/basics/get_url.py`:
```python
import urlparse

def url_filename(url):
    fn = os.path.basename(urlparse.urlsplit(url)[2])
    if fn == '':
        return 'index.html'
    return fn
```

EDIT: on my 2.4.0 installation there is another `get_url.py` file under `~/Apps/ansible/lib/ansible/modules/network/basics/` that calls the `urlsplit` in the same way that 2.2 do:
```python
import shutil
import datetime
import re
import tempfile
from ansible.module_utils.six.moves.urllib.parse import urlsplit

def url_filename(url):
    fn = os.path.basename(urlsplit(url)[2])
    if fn == '':
        return 'index.html'
    return fn
```
**Using this last module file, the task worked as it should.**

**Comment by abadger** [comment]
@rbbrasil I believe what's happening is that there's an old version of the modules in ~/Apps/ansible/lib/ansible/modules/core/ (and possibly ~/Apps/ansible/lib/ansible/modules/extras/ as well).  The Ansible stable-2.2 branch and earlier used git submodules to pull in the modules.  Ansible 2.3 and later have merged the modules into the same repo as Ansible itself.  The modules for the merged repositories live directly in ~/Apps/ansible/lib/ansible/modules/.  If you've switched between checked out versions (or this clone started before the 2.3 merging of the module repos) then you may still have old module directories that git did not clean up.

Try removing the two directories ~/Apps/ansible/lib/ansible/modules/core/ and ~/Apps/ansible/lib/ansible/modules/extras/ and then doing a ```git checkout devel ; git pull --rebase``` to see if that fixes things.

needs_info

**Comment by rbbrasil** [comment]
You were right @abadger ! 

I've been updating this repository since devel-1.9.x and after the 2.3 release this task stopped to work properly. Removing those dirs and updating again solved the problem. Thanks! :-)
