### ISSUE TITLE
v2 false delegate_to error

### ISSUE THREAD

**Issue by tkinz27** [ansible/ansible#11521]
# Issue Type:

Bug Report
# Ansible Version:

ansible 2.0.0 (devel 2e5dfd57cc) last updated 2015/07/08 01:53:45 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 8257053756) last updated 2015/07/08 04:17:56 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 639902ff20) last updated 2015/07/08 04:17:56 (GMT +000)
  v1/ansible/modules/core:  not found - use git submodule update --init v1/ansible/modules/core
  v1/ansible/modules/extras:  not found - use git submodule update --init v1/ansible/modules/extras
  configured module search path = /usr/share/ansible:./modules
# Ansible Configuration:

Running devel from git 
# Environment:

Using the latest ubuntu docker image

Dockerfile

```
FROM ubuntu

# Setup Mongodb apt respository
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
RUN echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' > /etc/apt/sources.list.d/mongodb.list

RUN apt-get update && apt-get install -y software-properties-common
RUN add-apt-repository ppa:git-core/ppa

# Remove python-setuptools from base image
RUN apt-get remove python-setuptools

RUN apt-get update \
    && apt-get install -y --force-yes \
        build-essential man expect \
        git vim ssh nmap socat \
        libmysqlclient-dev libffi-dev \
        libxml2-dev libxslt1-dev \
        python-dev python-antlr \
        python-matplotlib python-pip \
        libcurl4-openssl-dev \
        mongodb-org nodejs \
        bc \
    && apt-get autoclean \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*

RUN pip install -U pip
RUN mkdir /tmp/staging
```

Running docker

```
docker run -ti --rm -v ~/experiments/os-actions:/os-actions -v ~/experiments/ansible:/ansible devtools bash --login ${@}

# then within the docker container
pip install -e /ansible
. /ansible/hacking/dev-env
pip install shade
```
# Summary:

When running my playbooks, I'm getting 

```
TASK [os_setup : os_setup : create node in nova] ********************************
ESTABLISH LOCAL CONNECTION FOR USER: root
localhost EXEC mkdir -p $HOME/.ansible/tmp/ansible-tmp-1436331014.54-165132444419197 && echo $HOME/.ansible/tmp/ansible-tmp-1436331014.54-165132444419197
localhost PUT /tmp/tmpURG3ki TO /cip/.ansible/tmp/ansible-tmp-1436331014.54-165132444419197/os_server
localhost EXEC LANG=C LC_MESSAGES=C LC_CTYPE=C /usr/bin/python /cip/.ansible/tmp/ansible-tmp-1436331014.54-165132444419197/os_server; rm -rf /cip/.ansible/tmp/ansible-tmp-1436331014.54-165132444419197/ >/dev/null 2>&1

 [ERROR]: Unexpected Exception: 'unicode' object has no attribute 'delegate_to'

the full traceback was:

Traceback (most recent call last):
  File "/experiments/ansible/bin/ansible-playbook", line 77, in <module>
    sys.exit(cli.run())
  File "/experiments/ansible/lib/ansible/cli/playbook.py", line 163, in run
    results = pbex.run()
  File "/experiments/ansible/lib/ansible/executor/playbook_executor.py", line 142, in run
    result = self._tqm.run(play=play)
  File "/experiments/ansible/lib/ansible/executor/task_queue_manager.py", line 258, in run
    return strategy.run(iterator, connection_info)
  File "/experiments/ansible/lib/ansible/plugins/strategies/linear.py", line 207, in run
    results = self._wait_on_pending_results(iterator)
  File "/experiments/ansible/lib/ansible/plugins/strategies/__init__.py", line 269, in _wait_on_pending_results
    results = self._process_pending_results(iterator)
  File "/experiments/ansible/lib/ansible/plugins/strategies/__init__.py", line 231, in _process_pending_results
    if task.delegate_to is not None:
AttributeError: 'unicode' object has no attribute 'delegate_to'
```

And here it is again with pdb printnig out result. Looks like commit 

```
(Pdb) result
('set_host_var', os-test, u'cloud', {u'invocation': {u'module_name': u'os_server', u'module_args': {u'name': u'os-test', u'key_name': u'mykey', u'image': u'CentOS-7-x86_64-gold-v1', u'state': u'present', u'security_groups': u'default', u'nics': [{u'net-name': u'nic1'}], u'flavor': u'm1.tiny.m1g.d10g', u'auto_floating_ip': False}}, u'openstack': {u'OS-EXT-STS:task_state': None, u'addresses': {u'nic1': [{u'OS-EXT-IPS-MAC:mac_addr': u'fa:16:3e:62:d5:5b', u'version': 4, u'addr': u'10.17.216.195', u'OS-EXT-IPS:type': u'fixed'}]}, u'image': {u'id': u'15ad7fc5-0cd6-4f5b-b373-9a2d5bc2f01c', u'name': u'CentOS-7-x86_64-gold-v1'}, u'OS-EXT-STS:vm_state': u'active', u'OS-EXT-SRV-ATTR:instance_name': u'instance-0000fa95', u'OS-SRV-USG:launched_at': u'2015-06-26T00:29:38.000000', u'NAME_ATTR': u'name', u'flavor': {u'id': u'43f47db3-030b-40fd-8492-c8242866788c', u'name': u'm1.tiny.m1g.d10g'}, u'az': u'compute', u'networks': {u'nic1': [u'10.17.216.195']}, u'security_groups': [{u'name': u'default'}], u'user_id': u'svc_automation', u'OS-DCF:diskConfig': u'MANUAL', u'id': u'0dd751dc-40cd-4445-aff5-57090a219130', u'accessIPv4': u'', u'accessIPv6': u'', u'cloud': u'envvars', u'public_v4': u'', u'progress': 0, u'OS-EXT-STS:power_state': 1, u'OS-EXT-AZ:availability_zone': u'compute', u'config_drive': u'', u'status': u'ACTIVE', u'updated': u'2015-06-26T03:15:15Z', u'hostId': u'6a2af3b920b328e26d43923da254c8734e67ea7bc39bdbce671c9f1f', u'OS-EXT-SRV-ATTR:host': u'oscomp045', u'OS-SRV-USG:terminated_at': None, u'key_name': u'mykey', u'public_v6': u'', u'private_v4': u'', u'OS-EXT-SRV-ATTR:hypervisor_hostname': u'oscomp045', u'name': u'os-test', u'created': u'2015-06-26T00:29:24Z', u'tenant_id': u'921bb014ef11431baf9d0601ac3ed484', u'region': u'RegionOne', u'os-extended-volumes:volumes_attached': [], u'volumes': [], u'metadata': {}, u'human_id': u'os-test', u'HUMAN_ID': True}, u'changed': False, u'id': u'0dd751dc-40cd-4445-aff5-57090a219130', u'server': {u'OS-EXT-STS:task_state': None, u'addresses': {u'nic1': [{u'OS-EXT-IPS-MAC:mac_addr': u'fa:16:3e:62:d5:5b', u'version': 4, u'addr': u'10.17.216.195', u'OS-EXT-IPS:type': u'fixed'}]}, u'image': {u'id': u'15ad7fc5-0cd6-4f5b-b373-9a2d5bc2f01c', u'name': u'CentOS-7-x86_64-gold-v1'}, u'OS-EXT-STS:vm_state': u'active', u'OS-EXT-SRV-ATTR:instance_name': u'instance-0000fa95', u'OS-SRV-USG:launched_at': u'2015-06-26T00:29:38.000000', u'NAME_ATTR': u'name', u'flavor': {u'id': u'43f47db3-030b-40fd-8492-c8242866788c', u'name': u'm1.tiny.m1g.d10g'}, u'az': u'compute', u'networks': {u'nic1': [u'10.17.216.195']}, u'security_groups': [{u'name': u'default'}], u'user_id': u'svc_automation', u'OS-DCF:diskConfig': u'MANUAL', u'id': u'0dd751dc-40cd-4445-aff5-57090a219130', u'accessIPv4': u'', u'accessIPv6': u'', u'cloud': u'envvars', u'public_v4': u'', u'progress': 0, u'OS-EXT-STS:power_state': 1, u'OS-EXT-AZ:availability_zone': u'compute', u'config_drive': u'', u'status': u'ACTIVE', u'updated': u'2015-06-26T03:15:15Z', u'hostId': u'6a2af3b920b328e26d43923da254c8734e67ea7bc39bdbce671c9f1f', u'OS-EXT-SRV-ATTR:host': u'oscomp045', u'OS-SRV-USG:terminated_at': None, u'key_name': u'mykey', u'public_v6': u'', u'private_v4': u'', u'OS-EXT-SRV-ATTR:hypervisor_hostname': u'oscomp045', u'name': u'os-test', u'created': u'2015-06-26T00:29:24Z', u'tenant_id': u'921bb014ef11431baf9d0601ac3ed484', u'region': u'RegionOne', u'os-extended-volumes:volumes_attached': [], u'volumes': [], u'metadata': {}, u'human_id': u'os-test', u'HUMAN_ID': True}})
(Pdb) type(result )
<type 'tuple'>
(Pdb) c
 [ERROR]: Unexpected Exception: 'unicode' object has no attribute 'delegate_to'

the full traceback was:

Traceback (most recent call last):
  File "/experiments/ansible/bin/ansible-playbook", line 77, in <module>
    sys.exit(cli.run())
  File "/experiments/ansible/lib/ansible/cli/playbook.py", line 163, in run
    results = pbex.run()
  File "/experiments/ansible/lib/ansible/executor/playbook_executor.py", line 142, in run
    result = self._tqm.run(play=play)
  File "/experiments/ansible/lib/ansible/executor/task_queue_manager.py", line 258, in run
    return strategy.run(iterator, connection_info)
  File "/experiments/ansible/lib/ansible/plugins/strategies/linear.py", line 207, in run
    results = self._wait_on_pending_results(iterator)
  File "/experiments/ansible/lib/ansible/plugins/strategies/__init__.py", line 271, in _wait_on_pending_results
    results = self._process_pending_results(iterator)
  File "/experiments/ansible/lib/ansible/plugins/strategies/__init__.py", line 233, in _process_pending_results
    if task.delegate_to is not None:
AttributeError: 'unicode' object has no attribute 'delegate_to'
```

I have also verified that I have the changes from commit 293dd38d05e53570fe394e646167ae4449c5aa94, specifically the changes to executor/process/result.py

My playbook is just calling a role to setup some openstack VMs. I described it more https://groups.google.com/forum/#!topic/ansible-devel/a4oGoLteON0

**Comment by jamiehannaford** [comment]
I'm also seeing this error. I can't run any playbooks on the current `devel` branch.

**Comment by Pallokala** [comment]
This is breaking my all playbooks. The error is exactly same.

**Comment by sheldonh** [comment]
Here is a small how-to-repeat:

``` yaml
---
-
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    -
      name: Provision Consul instances
      ec2:
        key_name: heisenberg
        group: default
        instance_type: t2.micro
        image: ami-234ecc54
        wait: true
        exact_count: 3
        count_tag:
          Name: Consul
        instance_tags:
          Name: Consul
      register: ec2
```

The thing that triggers the issue here is the `register: ec2`. Without that, the playbook applies. But once you add it, you get:

```
$ ansible-playbook -vvv -i /dev/null instances.yml 
Using  as config file
 [WARNING]: provided hosts list is empty, only localhost is available

2 plays in instances.yml

PLAY: ***************************************************************************

TASK [Provision Consul instances] ***********************************************
ESTABLISH LOCAL CONNECTION FOR USER: sheldonh
127.0.0.1 EXEC mkdir -p $HOME/.ansible/tmp/ansible-tmp-1436359440.02-150131822582767 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1436359440.02-150131822582767 && echo $HOME/.ansible/tmp/ansible-tmp-1436359440.02-150131822582767
127.0.0.1 PUT /tmp/tmpThhIUC TO /home/sheldonh/.ansible/tmp/ansible-tmp-1436359440.02-150131822582767/ec2
127.0.0.1 EXEC LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/sheldonh/.ansible/tmp/ansible-tmp-1436359440.02-150131822582767/ec2; rm -rf /home/sheldonh/.ansible/tmp/ansible-tmp-1436359440.02-150131822582767/ >/dev/null 2>&1
 [ERROR]: Unexpected Exception: 'unicode' object has no attribute 'delegate_to'

the full traceback was:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.0.0-py2.7.egg/EGG-INFO/scripts/ansible-playbook", line 77, in <module>
    sys.exit(cli.run())
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.0.0-py2.7.egg/ansible/cli/playbook.py", line 163, in run
    results = pbex.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.0.0-py2.7.egg/ansible/executor/playbook_executor.py", line 142, in run
    result = self._tqm.run(play=play)
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.0.0-py2.7.egg/ansible/executor/task_queue_manager.py", line 258, in run
    return strategy.run(iterator, connection_info)
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.0.0-py2.7.egg/ansible/plugins/strategies/linear.py", line 207, in run
    results = self._wait_on_pending_results(iterator)
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.0.0-py2.7.egg/ansible/plugins/strategies/__init__.py", line 269, in _wait_on_pending_results
    results = self._process_pending_results(iterator)
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.0.0-py2.7.egg/ansible/plugins/strategies/__init__.py", line 231, in _process_pending_results
    if task.delegate_to is not None:
AttributeError: 'unicode' object has no attribute 'delegate_to'
```

**Comment by jimi-c** [comment]
Thanks @sheldonh, I was just about to ask for that.

**Comment by jstasiak** [comment]
I'm seeing very similar issue when using `digital_ocean` module except the error is `AttributeError: 'AnsibleUnicode' object has no attribute 'delegate_to'` (the stack trace is the same though).

I can provide playbook to reproduce but I think this thread already has that.

PS. I'm using Ansible 2e5dfd57cc9c1a806a0ac3a23f8036f6f32127af + core modules updated to e3c774be6f51968ed262caebf4c4f75e13fe30fe with a small module patch on top of it.

**Comment by sheldonh** [comment]
Bisected to 293dd38d05e53570fe394e646167ae4449c5aa94.

**Comment by jimi-c** [comment]
I see the problem, I'll have a patch pushed shortly.

**Comment by jimi-c** [comment]
Sorry about this, with the change mentioned above I missed another use of the `set_host_var` message used when setting a variable when registering results. This has been fixed now and pushed to devel.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by sheldonh** [comment]
Fixed for me. Thanks!

**Comment by jstasiak** [comment]
Thank you, works for me too.

**Comment by jimi-c** [comment]
Great, thanks for confirming!
