### ISSUE TITLE
gce doesn't work with libcloud 2.0 (or fails badly) - AttributeError: 'GCEFailedNode' object has no attribute 'extra'

### ISSUE THREAD

**Issue by wenottingham** [ansible/ansible#31063]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
gce

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

nothing special

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY
```
  - name: Launch GCP instances
    gce:
      name: "foo-wheeee"
      num_instances: "{{ gcp_count }}"
      state: present
      zone: us-west1-a
      image_family: centos-7
      machine_type: n1-standard-1
      tags:
      - "foo-wheeee"
    register: gce
```
yields:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'GCEFailedNode' object has no attribute 'extra'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n File \"/tmp/ansible_jYxrOm/ansible_module_gce.py\", line 778, in <module>\n main()\n File \"/tmp/ansible_jYxrOm/ansible_module_gce.py\", line 738, in main\n module, gce, inames, number, lc_zone)\n File \"/tmp/ansible_jYxrOm/ansible_module_gce.py\", line 586, in create_instances\n d = get_instance_info(inst)\n File \"/tmp/ansible_jYxrOm/ansible_module_gce.py\", line 356, in get_instance_info\n if 'metadata' in inst.extra and 'items' in inst.extra['metadata']:\nAttributeError: 'GCEFailedNode' object has no attribute 'extra'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```

##### STEPS TO REPRODUCE

See above

##### EXPECTED RESULTS

No traceback - either success, or an actual error message if I screwed something up.

**Comment by ansibot** [comment]
cc @erjohnso @supertom
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by erjohnso** [comment]
Sorry for the late reply @wenottingham 

I received a different error trying to reproduce.  The error I saw, which is valid, is that `image_family` is not supported in the `gce` module.  I changed your snippet to `image` instead and I was able to create the instances correctly.  Note that `image_family` *is* supported, but only in the `gce_instance_template` module.

```
erjohnso@ansible$ cat test-issue31063.yml; ansible-playbook -v test-issue31063.yml
- name: Create instance(s)
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: instance
      gce:
        project_id: graphite-demos
        credentials_file: /home/erjohnso/ansible-demo.json
        name: "foo-wheeee"
        num_instances: 2
        state: present
        zone: us-central1-a
        image: centos-7
        machine_type: n1-standard-1
        tags:
        - "foo-wheeee"
      register: gce

Using /home/erjohnso/.ansible.cfg as config file

PLAY [Create instance(s)] ********************************************************************************************************************************************

TASK [instance] ******************************************************************************************************************************************************
changed: [localhost] => {"changed": true, "failed": false, "instance_data": [{"disks": ["foo-wheeee-000"], "image": "centos-7-v20171003", "machine_type": "n1-standard-1", "metadata": {}, "name": "foo-wheeee-000", "network": "default", "private_ip": "10.240.0.3", "public_ip": "35.194.2.5", "status": "RUNNING", "subnetwork": null, "tags": ["foo-wheeee"], "zone": "us-central1-a"}, {"disks": ["foo-wheeee-001"], "image": "centos-7-v20171003", "machine_type": "n1-standard-1", "metadata": {}, "name": "foo-wheeee-001", "network": "default", "private_ip": "10.240.0.4", "public_ip": "35.184.87.167", "status": "RUNNING", "subnetwork": null, "tags": ["foo-wheeee"], "zone": "us-central1-a"}], "name": "foo-wheeee", "state": "present", "zone": "us-central1-a"}                                                                           

PLAY RECAP ***********************************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

I'm also running 2.4,

```
ansible 2.4.0 (devel b818e986b6) last updated 2017/08/17 13:55:22 (GMT +000)
  config file = /home/erjohnso/.ansible.cfg
  configured module search path = [u'/home/erjohnso/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/erjohnso/ansible/lib/ansible
  executable location = /home/erjohnso/ansible/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

**Comment by erjohnso** [comment]
Will try against 2.4.0.0 (versus devel)

**Comment by victorock** [comment]
Hitting this issue when using:

**environment**
```
ansible-playbook 2.4.0.0
  config file = /Users/jdacosta/Devel/darkbulb/provisionner/ansible.cfg
  configured module search path = [u'/Users/jdacosta/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

**Input for GCE:**
```
    base_name: "whatever"
    num_instances: "4"
    zone: "europe-west1-d"
    machine_type: "n1-highmem-4"
    image: "nested-image-centos-7"
    service_account_email: "{{ gce_cloud_instance_service_account_email }}"
    credentials_file: "{{ gce_cloud_instance_credentials_file }}"
    project_id: "{{ gce_cloud_instance_project_id }}"
    tags: [ 'mytag' ]
    state: present
```

**Output:**
```
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/jv/29pmt_2j39ngz8ftz40j1mn00000gn/T/ansible_agh1W6/ansible_module_gce.py", line 778, in <module>
    main()
  File "/var/folders/jv/29pmt_2j39ngz8ftz40j1mn00000gn/T/ansible_agh1W6/ansible_module_gce.py", line 738, in main
    module, gce, inames, number, lc_zone)
  File "/var/folders/jv/29pmt_2j39ngz8ftz40j1mn00000gn/T/ansible_agh1W6/ansible_module_gce.py", line 586, in create_instances
    d = get_instance_info(inst)
  File "/var/folders/jv/29pmt_2j39ngz8ftz40j1mn00000gn/T/ansible_agh1W6/ansible_module_gce.py", line 356, in get_instance_info
    if 'metadata' in inst.extra and 'items' in inst.extra['metadata']:
AttributeError: 'GCEFailedNode' object has no attribute 'extra'

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/jv/29pmt_2j39ngz8ftz40j1mn00000gn/T/ansible_agh1W6/ansible_module_gce.py\", line 778, in <module>\n    main()\n  File \"/var/folders/jv/29pmt_2j39ngz8ftz40j1mn00000gn/T/ansible_agh1W6/ansible_module_gce.py\", line 738, in main\n    module, gce, inames, number, lc_zone)\n  File \"/var/folders/jv/29pmt_2j39ngz8ftz40j1mn00000gn/T/ansible_agh1W6/ansible_module_gce.py\", line 586, in create_instances\n    d = get_instance_info(inst)\n  File \"/var/folders/jv/29pmt_2j39ngz8ftz40j1mn00000gn/T/ansible_agh1W6/ansible_module_gce.py\", line 356, in get_instance_info\n    if 'metadata' in inst.extra and 'items' in inst.extra['metadata']:\nAttributeError: 'GCEFailedNode' object has no attribute 'extra'\n", 
    "module_stdout": "", 
    "rc": 0
}
```

**RESOLUTION:**
```
Instances are created in GCE, but module fails...
I've got much more helpful message when using **instance_names**
The error in my case was due quota of free tier (8 CPUs).
The error message is not helpful when adopting **base_name** and **num_instances**
```

**Comment by erjohnso** [comment]
I'm not able to reproduce the error and I've tried a couple different combinations of `base_name`, `name`, `instance_names`.  I *think* the issue is that if something goes wrong, the code path assumes a node was created, but something went wrong and an exception is thrown. Without being able to repro, the next best thing I can assume would help would be to skip the failed nodes,

https://github.com/erjohnso/ansible/commit/2afa94f98f5f4bd65cc90f940e9845734564c61b

I do think it merits closer examination @victorock @wenottingham since it sounds like the VMs are actually created?

**Comment by victorock** [comment]
I've noted that when i specify tags in a non-valid format, i also get this error:

AttributeError: 'GCEFailedNode' object has no attribute 'extra'

**Comment by ansibot** [comment]
cc @rambleraptor
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by byronyi** [comment]
I'm porting a new feature from libcloud 2.0 to ansible GCE module. Let me try if I could fix this unfriendly error message.

**Comment by yeroc** [comment]
I just ran into the same unhelpful error message with Ansible 2.5.3 + apache-libcloud 2.3.0.  Haven't figured out what's wrong yet...

**Comment by victorock** [comment]
The few times yhat i've ran into this:
1- quota issue
2- payment issue (quota)
3- permission issue

**Comment by yeroc** [comment]
Thanks for the tips @victorock I'll do more digging.  Is this an issue with the apache-libcloud API or are the Google Cloud Endpoints returning no information for these failures?

**Comment by yeroc** [comment]
Did some more digging and for anyone else who runs into this libcloud allows you to turn on debugging to see the actual requests/responses sent to and from the GCE API.  All you need to do is:
```
export LIBCLOUD_DEBUG=<log_file>
ansible-playbook ...
```
From there I could see the error from GCE which was quite helpful.  In this case, my service account needed the iam.serviceAccountUser role. 

In any case, I'm not sure whether the nice error message provided by GCE is being swallowed up in libcloud or in Ansible?

**Comment by rambleraptor** [comment]
libcloud is probably swallowing the error messages.

Since this issue was filed, we've deprecated the `gce` module for the `gcp_compute_instance` module. It doesn't use libcloud and has fuller API support as such. We recommend that you use this module in the future.

close_me
