### ISSUE TITLE
check_mode breaks on junos_banner

### ISSUE THREAD

**Issue by newswangerd** [ansible/ansible#37208]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

junos_banner

##### ANSIBLE VERSION

```
ansible 2.6.0 (junos_smoke 155adb1631) last updated 2018/03/08 09:16:06 (GMT -400)
  config file = None
  configured module search path = [u'/Users/david/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/david/code/ansible/lib/ansible
  executable location = /Users/david/code/ansible/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### SUMMARY

`check_mode: yes` causes junos_banner tasks to fail

##### STEPS TO REPRODUCE

Run the following task

```
- name: check mode
  junos_banner:
    banner: login
    text: this is not the banner you're looking for
    state: present
    provider: "{{ netconf }}"
  register: result
  check_mode: yes

- assert:
    that:
      - result.changed == false
```

```yaml

```

##### EXPECTED RESULTS

Module should run and not change the login banner

##### ACTUAL RESULTS

```
TASK [junos_smoke : check mode] *******************************************************************************************
task path: /Users/david/code/ansible/test/integration/targets/junos_smoke/tests/netconf/module_utils_junos.yaml:46
<junos01> attempting to start connection
<junos01> using connection plugin netconf
<junos01> found existing local domain socket, using it!
<junos01>
<junos01> local domain socket path is /Users/david/.ansible/pc/0319a6a111
 [WARNING]: provider is unnecessary when using connection=netconf and will be ignored

Using module file /Users/david/code/ansible/lib/ansible/modules/network/junos/junos_banner.py
<junos01> ESTABLISH LOCAL CONNECTION FOR USER: david
<junos01> EXEC /bin/sh -c 'echo ~ && sleep 0'
<junos01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/david/.ansible/tmp/ansible-tmp-1520531921.38-75952063324716 `" && echo ansible-tmp-1520531921.38-75952063324716="` echo /Users/david/.ansible/tmp/ansible-tmp-1520531921.38-75952063324716 `" ) && sleep 0'
<junos01> PUT /Users/david/.ansible/tmp/ansible-local-65800g9taGD/tmpXZT5uE TO /Users/david/.ansible/tmp/ansible-tmp-1520531921.38-75952063324716/junos_banner.py
<junos01> EXEC /bin/sh -c 'chmod u+x /Users/david/.ansible/tmp/ansible-tmp-1520531921.38-75952063324716/ /Users/david/.ansible/tmp/ansible-tmp-1520531921.38-75952063324716/junos_banner.py && sleep 0'
<junos01> EXEC /bin/sh -c '/tmp/ansible-test-coverage-V8NjOc/coverage/injector.py /Users/david/.ansible/tmp/ansible-tmp-1520531921.38-75952063324716/junos_banner.py && sleep 0'
<junos01> EXEC /bin/sh -c 'rm -f -r /Users/david/.ansible/tmp/ansible-tmp-1520531921.38-75952063324716/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_TzxF82/ansible_module_junos_banner.py", line 180, in <module>
    main()
  File "/tmp/ansible_TzxF82/ansible_module_junos_banner.py", line 171, in main
    discard_changes(module)
  File "/tmp/ansible_TzxF82/ansible_modlib.zip/ansible/module_utils/network/junos/junos.py", line 185, in discard_changes
  File "/tmp/ansible_TzxF82/ansible_modlib.zip/ansible/module_utils/network/common/netconf.py", line 70, in __rpc__
  File "/tmp/ansible_TzxF82/ansible_modlib.zip/ansible/module_utils/network/common/netconf.py", line 102, in parse_rpc_error
ansible.module_utils.connection.ConnectionError: request() got an unexpected keyword argument 'exit'

fatal: [junos01]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_TzxF82/ansible_module_junos_banner.py\", line 180, in <module>\n    main()\n  File \"/tmp/ansible_TzxF82/ansible_module_junos_banner.py\", line 171, in main\n    discard_changes(module)\n  File \"/tmp/ansible_TzxF82/ansible_modlib.zip/ansible/module_utils/network/junos/junos.py\", line 185, in discard_changes\n  File \"/tmp/ansible_TzxF82/ansible_modlib.zip/ansible/module_utils/network/common/netconf.py\", line 70, in __rpc__\n  File \"/tmp/ansible_TzxF82/ansible_modlib.zip/ansible/module_utils/network/common/netconf.py\", line 102, in parse_rpc_error\nansible.module_utils.connection.ConnectionError: request() got an unexpected keyword argument 'exit'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/junos/junos_banner.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/junos/junos_banner.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Qalthos @ganeshrn
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by matthewrees** [comment]
I am having the same issue with junos_config in --check mode with Ansible 2.5.0.0 and Python 2.7.14:

```
2018-03-25 16:53:45,047 p=28200 u=matthewr |  network_os is set to junos
2018-03-25 16:53:45,105 p=28200 u=matthewr |  ssh connection done, starting ncclient
2018-03-25 16:53:45,843 ncclient.transport.ssh Connected (version 2.0, client OpenSSH_6.9)
2018-03-25 16:53:47,821 ncclient.transport.ssh Authentication (publickey) failed.
2018-03-25 16:53:48,570 ncclient.transport.ssh Authentication (password) successful!
2018-03-25 16:53:49,853 ncclient.transport.session initialized: session-id=11854 | server_capabilities=<dictionary-keyiterator object at 0x7ff868c683c0>
2018-03-25 16:53:49,853 p=28200 u=matthewr |  ncclient manager object created successfully
2018-03-25 16:53:49,855 p=28200 u=matthewr |  loaded netconf plugin for network_os junos
2018-03-25 16:53:49,980 p=28201 u=matthewr |  network_os is set to junos
2018-03-25 16:53:50,007 p=27962 u=matthewr |  Using module file /home/matthewr/git/cloud-networking/venv/local/lib/python2.7/site-packages/ansible/modules/network/junos/junos_config.py
2018-03-25 16:53:50,044 p=28201 u=matthewr |  ssh connection done, starting ncclient
2018-03-25 16:53:50,091 ncclient.operations.rpc Requesting 'ExecuteRpc'
2018-03-25 16:53:50,782 ncclient.transport.ssh Connected (version 2.0, client OpenSSH_6.9)
2018-03-25 16:53:51,010 ncclient.operations.rpc Requesting 'Lock'
2018-03-25 16:53:51,478 ncclient.operations.rpc Requesting 'LoadConfiguration'
2018-03-25 16:53:51,995 ncclient.operations.rpc Requesting 'Validate'
2018-03-25 16:53:52,754 ncclient.transport.ssh Authentication (publickey) failed.
2018-03-25 16:53:52,963 ncclient.operations.rpc Requesting 'ExecuteRpc'
2018-03-25 16:53:53,429 ncclient.operations.rpc Requesting 'Unlock'
2018-03-25 16:53:53,509 ncclient.transport.ssh Authentication (password) successful!
2018-03-25 16:53:53,972 p=27962 u=matthewr |  The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_o6GZT9/ansible_module_junos_config.py", line 394, in <module>
    main()
  File "/tmp/ansible_o6GZT9/ansible_module_junos_config.py", line 377, in main
    discard_changes(module)
  File "/tmp/ansible_o6GZT9/ansible_modlib.zip/ansible/module_utils/network/junos/junos.py", line 185, in discard_changes
  File "/tmp/ansible_o6GZT9/ansible_modlib.zip/ansible/module_utils/network/common/netconf.py", line 70, in __rpc__
  File "/tmp/ansible_o6GZT9/ansible_modlib.zip/ansible/module_utils/network/common/netconf.py", line 102, in parse_rpc_error
ansible.module_utils.connection.ConnectionError: request() got an unexpected keyword argument 'exit'
```

The module works in check mode in 2.4.3.0 and today I updated to 2.5.0.0 and ran the playbook to test the update and this is the result. I will test the commit by @ganeshrn to see if it resolves the issue.

**Comment by matthewrees** [comment]
I can confirm that https://github.com/ganeshrn/ansible/commit/9354ba3b0143d64536fed0287e50947a8cbafd08 fixes the issue.

**Comment by ganeshrn** [comment]
@matthewrees Thank you for verifying the patch.

**Comment by gundalow** [comment]
Fixed in devel & cherry-picked into `stable-2.5` in https://github.com/ansible/ansible/pull/37918
