### ISSUE TITLE
Unsafe attribute access in templates

### ISSUE THREAD

**Issue by NightTsarina** [ansible/ansible#85204]
### Summary

Since neither ansible nor jinja provide operators or filters to perform bitwise operations, the only alternative is to use `int.__and__`, `int.__or__`, etc.

The changes introduced in https://github.com/ansible/ansible/pull/84621 broke this by restricting access to underscore-prefixed attributes, even though those operations are safe.

Currently, there does not seem to be any way to replace this functionality, except writing a custom filter.

### Issue Type

Bug Report

### Component Name

templating

### Ansible Version

```console
$ ansible --version
ansible [core 2.19.0b4]
  config file = None
  configured module search path = ['/home/tina/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/tina/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.13.3 (main, May 21 2025, 07:49:52) [GCC 14.2.0] (/usr/bin/python3)
  jinja version = 3.1.6
  pyyaml version = 6.0.2 (with libyaml v0.2.5)
```

### Configuration

```console
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None

GALAXY_SERVERS:
```

### OS / Environment

Debian testing

### Steps to Reproduce

```shell
$ ansible -m debug -a msg='{{ (0x20).__or__(0xf) }}' localhost
```

### Expected Results

```shell
$ ansible --version
ansible [core 2.18.3]
  config file = None
  configured module search path = ['/home/tina/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/tina/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.13.3 (main, Apr 10 2025, 21:38:51) [GCC 14.2.0] (/usr/bin/python3)
  jinja version = 3.1.6
  libyaml = True

$ ansible -m debug -a msg='{{ (0x20).__or__(0xf) }}' localhost
[WARNING]: No inventory was parsed, only implicit localhost is available
localhost | SUCCESS => {
    "msg": "47"
}
```

### Actual Results

```console
$ ansible -m debug -a msg='{{ (0x20).__or__(0xf) }}' localhost
[WARNING]: No inventory was parsed, only implicit localhost is available
[ERROR]: Task failed: Finalization of task args for 'ansible.builtin.debug' failed: Error while resolving value for 'msg': access to attribute '__or__' of 'int' object is unsafe.

Task failed.
Origin: <adhoc 'debug' task>

{'action': {'module': 'debug', 'args': {'msg': '{{ (0x20).__or__(0xf) }}'}}, 'timeout': 0, 'async_val': 0, 'poll': 15}

<<< caused by >>>

Finalization of task args for 'ansible.builtin.debug' failed.
Origin: <CLI option '-m'>

debug

<<< caused by >>>

Error while resolving value for 'msg': access to attribute '__or__' of 'int' object is unsafe.
Origin: <CLI option '-a'>

{{ (0x20).__or__(0xf) }}

localhost | FAILED! => {
    "changed": false,
    "msg": "Task failed: Finalization of task args for 'ansible.builtin.debug' failed: Error while resolving value for 'msg': access to attribute '__or__' of 'int' object is unsafe."
}
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:

None

If these files are incorrect, please update the `component name` section of the description or use the [component](https://github.com/ansible/ansibotmini#commands) bot command.

**Comment by kirkzhangtech** [comment]
it looks like also impact `ansible-playbook`
```shell
[ERROR]: Task failed: Finalization of task args for 'ansible.builtin.debug' failed: Error while resolving value for 'msg': object of type 'int' has no attribute 'or'

Task failed.
Origin: /home/kirkzhang/CodeSpace/ansibleTestSpace/data_tagging_playbook.yml:3:7

1 - hosts: localhost
2   tasks:
3     - name: Debug bitwise operation
        ^ column 7

<<< caused by >>>

Finalization of task args for 'ansible.builtin.debug' failed.
Origin: /home/kirkzhang/CodeSpace/ansibleTestSpace/data_tagging_playbook.yml:4:7

2   tasks:
3     - name: Debug bitwise operation
4       debug:
        ^ column 7

<<< caused by >>>

Error while resolving value for 'msg': object of type 'int' has no attribute 'or'
Origin: /home/kirkzhang/CodeSpace/ansibleTestSpace/data_tagging_playbook.yml:5:14

3     - name: Debug bitwise operation
4       debug:
5         msg: "{{ (0x20).or(0xf)  }}"
               ^ column 14

fatal: [localhost]: FAILED! => {"msg": "Task failed: Finalization of task args for 'ansible.builtin.debug' failed: Error while resolving value for 'msg': object of type 'int' has no attribute 'or'"}
```

**Comment by bcoca** [comment]
And if you really want this going forward, this is a quick draft of 'bitwise filters' https://github.com/bcoca/misc-collection/blob/devel/plugins/filter/bitwise.py

**Comment by mattclay** [comment]
@kirkzhangtech Yes, all ansible commands are affected. However, the example you provided uses `or`, which does not work under any version of ansible -- it needs to be `__or__` to work in 2.18 or earlier.

**Comment by nitzmahone** [comment]
The Jinja sandbox was enabled for a number of important reasons, but we didn't realize how many things were in common use that would run afoul of the mutation- and dunder-method blocks.

We've prototyped some tweaks to make several of these things much nicer (e.g., simpler comprehension-style projections, easier access to bitwise operators, getting rid of the set + default block hack for mutation calls), but have run out of time to get them in for 2.19, so we've deferred the mutation block and restored access to integer bitwise operators in the meantime. These changes should appear in 2.19.0b8 or rc1.

Thanks for the detailed examples- we've added more of those to our test suites so they're represented in the future, and hopefully we can polish up the improved ways to do these things and get them shipped with 2.20.
