### ISSUE TITLE
Listing a playbook's tasks fails

### ISSUE THREAD

**Issue by bitmensch** [ansible/ansible#14144]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible@devel (commit 78d49914)
##### Ansible Configuration:

no changes
##### Environment:

MacOS X 10.11.3
##### Summary:

`ansible-playbook --list-tasks ...` call fails with exception `Unexpected Exception: 'NoneType' object has no attribute '_failed_hosts'`. This bug has been introduced with commit 78d49914.
##### Steps To Reproduce:

```
# inventory
127.0.0.1
```

```
# playbook.yml

---
- hosts: 127.0.0.1
  tasks:
    - name: hello localhost
      ping:
```

Running the command

```
ansible-playbook -vvv --list-tasks -i inventory playbook.yml
```

... results in:

```
Using /Users/benjixx/.ansible.cfg as config file
1 plays in playbook.yml
ERROR! Unexpected Exception: 'NoneType' object has no attribute '_failed_hosts'
the full traceback was:

Traceback (most recent call last):
  File "/Users/benjixx/.virtualenvs/ansiblebug/bin/ansible-playbook", line 86, in <module>
    sys.exit(cli.run())
  File "/Users/benjixx/.virtualenvs/ansiblebug/lib/python2.7/site-packages/ansible/cli/playbook.py", line 150, in run
    results = pbex.run()
  File "/Users/benjixx/.virtualenvs/ansiblebug/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 177, in run
    retries = list(set(self._tqm._failed_hosts.keys() + self._tqm._unreachable_hosts.keys()))
AttributeError: 'NoneType' object has no attribute '_failed_hosts'
```
##### Expected Results:

No errors.
##### Actual Results:

Exception is being raised.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by bitmensch** [comment]
@jimi-c This makes things working again. Thanks.

**Comment by jimi-c** [comment]
Great, thanks for the follow-up!
