### ISSUE TITLE
Jinja groupby behaves differently on ansible 2.2.2.0

### ISSUE THREAD

**Issue by jschwend** [ansible/ansible#23495]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible 2.2.2.0
  config file = /home/ubuntu/MckMhaHadoop/automatedConfig/hssaprod2/ansible.cfg
  configured module search path = ['/usr/share/ansible']
```

##### OS / ENVIRONMENT
Ubuntu 14.04

##### SUMMARY
Jinja template using groupby used to return named variables .list and .grouper. With 2.2.2.0 these are no longer named and must be accessed by index.

##### STEPS TO REPRODUCE
jinja template that works on 2.2.0 but fails on 2.2.2.0
{%- for group in cluster_users.values() | groupby('uidNumber') -%}
  {%- if (group.list | length) > 1 -%}
  NO, uidNumber {{ group.grouper }} is used {{ group.list | length }} times.
  {%- endif -%}
{%- endfor -%}

jinja template that works on 2.2.2.0
{%- for group in cluster_users.values() | groupby('uidNumber') -%}
  {%- if (group[1] | length) > 1 -%}
  NO, uidNumber {{ group[0] }} is used {{ group[1] | length }} times.
  {%- endif -%}
{%- endfor -%}

See here for docs from Jinja, search for groupby....
http://jinja.pocoo.org/docs/2.9/templates/

##### EXPECTED RESULTS
That it works with named variables .list and .grouper

##### ACTUAL RESULTS
```
fatal: [10.212.170.42]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'tuple object' has no attribute 'list'"}

```

**Comment by sivel** [comment]
The `groupby` filter was updated in https://github.com/ansible/ansible/pull/20362 to allow it to work with newer versions of jinja2 within direct templating in playbooks.

You now will only get back a plain tuple instead of a namedtuple from `groupby`.

You will need to reference the element, instead of the named element.

**Comment by jschwend** [comment]
Thanks Sivel. Good to know that our "fix" is the correct course of action.
How could I best find things that are affected by new versions instead of opening an issue? I feel I could/should have been able to find this myself?

**Comment by abadger** [comment]
In general you can look at the CHANGELOG.md file in the relevant branch https://github.com/ansible/ansible/blob/stable-2.2/CHANGELOG.md

It looks like we forgot to update that for 2.2.2, though... probably because we were releasing across all the 2.x branches at that time and we missed a few steps that we normally take.

note that we only record major bugfixes in the CHANGELOG so sometimes there will be a fix without an entry in there.
