### ISSUE TITLE
please allow duplicate parameter in raw module too.

### ISSUE THREAD

**Issue by aikomastboom** [ansible/ansible#10043]
please add 'raw' to modules allowed to have duplicate parameters.

https://github.com/ansible/ansible/blob/be4dbe76b9fbdd7e377f0d0c3ace61fa6e855e04/lib/ansible/runner/__init__.py#L444

```
- is_shell_module = self.module_name in ('command', 'shell')
+ is_shell_module = self.module_name in ('command', 'shell', 'raw')
```

thank you.

**Comment by ianclegg** [comment]
+1
Ansible definitely should not be trying to infer semantics when using raw. Command and Shell are not available on Windows; so there is currently no way to invoke commands which legitimately require duplicate arguments on Windows

**Comment by bcoca** [comment]
Can you show examples of the issue this is causing?

**Comment by ianclegg** [comment]
Hey Brian,

Lets look at the 'appcmd' command used to configure IIS on Windows takes multiple parameters that all start with the same characters.

For example, to configure the credentials for an app pool:
(https://technet.microsoft.com/en-us/library/cc771170%28v=ws.10%29.aspx)

appcmd set config /section:applicationPools /[name='MyAppPool'].processModel.identityType:SpecificUser /[name='MyAppPool'].processModel.userName:MyDomain\MyAccount /[name='MyAppPool'].processModel.password:MyAccountPassword

Since the 'shell' and 'command' modules are not available on windows; we have to use raw. Ansible fails with the following error:

a duplicate parameter was found in the argument string (/[name)

**Comment by groggemans** [comment]
+1

Also useful for managing special devices like my MikroTik router witch is running Router OS and has no standard linux tools.

Commands often need sub commands to get certain value's and all commands have a common API. This often results in duplicate parameters.

**Comment by bcoca** [comment]
can you check against current devel, the code has changed a lot and this may already be the case

**Comment by groggemans** [comment]
Devel wont even run a raw command without duplicate parameters. I'm getting following error when running a playbook that's working in 1.9.2:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/groggemans/workdir/ansible/lib/ansible/executor/process/worker.py", line 118, in run                                                                                    
    executor_result = TaskExecutor(host, task, job_vars, new_connection_info, self._new_stdin, self._loader, shared_loader_obj).run()                                                 
  File "/home/groggemans/workdir/ansible/lib/ansible/executor/task_executor.py", line 111, in run                                                                                     
    res = self._execute()
  File "/home/groggemans/workdir/ansible/lib/ansible/executor/task_executor.py", line 281, in _execute                                                                                
    result = self._handler.run(task_vars=variables)
  File "/home/groggemans/workdir/ansible/lib/ansible/plugins/action/raw.py", line 32, in run                                                                                          
    result = self._low_level_execute_command(self._task.args.get('_raw_params'), tmp=tmp, executable=executable)                                                                      
TypeError: _low_level_execute_command() got an unexpected keyword argument 'executable'

fatal: [rb]: FAILED! => {
    "failed": true, 
    "stdout": ""
}
```

The task in question:

```
- name: Get current groups
  raw: /user group print terse
  register: mtros_current_groups
```

I'll try to see if I can get it to work again with a simpler playbook.

**Comment by groggemans** [comment]
It seems there's a problem in the raw module of devel. Even this simple playbook fails with the same error. (Other modules work just fine)

```
---                                                                                    
- hosts: home1
   sudo: yes
   tasks:
   - raw: apt-get update
```

**Comment by bcoca** [comment]
so fixed that latest error via 24b830bbc8f228015841bc20ba423af6f04129a0, please test the original issue

**Comment by groggemans** [comment]
It seems that devel can't properly run commands on my router. It just hangs after complaining about paramiko. But I will do some more tests on this and start a separate issue for it. (this works in 1.9.2)

```
TASK [raw] **********************************************************************
<192.168.11.22> ESTABLISH CONNECTION FOR USER: admin on PORT 22 TO 192.168.11.22
<192.168.11.22> EXEC /system health print
No handlers could be found for logger "paramiko.transport"
```

But a test on another host revealed that there is still a parameter check in the raw module.

```
---
- hosts: home1
  tasks:
  - raw: test=test test=test  # should do nothing
```

still gives

```
TASK: [raw test=test test=test] *********************************************** 
fatal: [localhost] => a duplicate parameter was found in the argument string (test)

FATAL: all hosts have already failed -- aborting
```

**Comment by bcoca** [comment]
weird, seems to work for me

```
ansible -m raw -a 'test=test test=test'  testhost
testhost | SUCCESS => {
    "changed": false, 
    "stderr": "", 
    "stdout": ""
}
```

also that paramiko error should not be present in current devel, are you sure you are not running an older version? make sure the dirs are clean of .pyc files from older versions

**Comment by groggemans** [comment]
Just tried on a completely clean system, and can confirm that the raw module does support duplicate parameters now! So this issue can be closed.

I do however still get the same error when trying to use the raw module on the router.

```
 TASK [raw] **********************************************************************
<192.168.11.22> ESTABLISH CONNECTION FOR USER: admin on PORT 22 TO 192.168.11.22
<192.168.11.22> EXEC /system health print
No handlers could be found for logger "paramiko.transport"
```

And then it just hangs.

I'm using paramiko for the connection because ansibles default ssh settings for OpenSSH don't work. Maybe its time to switch to OpenSSH with custom parameters. 

I'll do some more tests and if needed, i'll open a new issue for this problem.

**Comment by bcoca** [comment]
closing this as per above

@groggemans the parmiko message is a warning and can be ignored, but still it should not hang, drop by IRC or the mailing list if you still need help with the ssh connection issues.

**Comment by aikomastboom** [comment]
@bcoca I am not familiar with the dev branch but does it have a testsuite, to which a regressing test for this issue can be added?

regression test can simply be: eg.

```
ansible -m raw -a 'test=test test=test'  testhost
```

**Comment by bcoca** [comment]
under test/integration, i added a raw duplicate under test_good_parsing
