### ISSUE TITLE
Regression: Template.__new__() Error with ansible-core 2.19+

### ISSUE THREAD

**Issue by bhouse-nexthop** [ansible/ansible#86723]
#### Summary

When using ansible-core 2.19+, playbooks that use the `ansible.builtin.template` module to render templates containing Jinja2 macro imports fail with:

```
Template.__new__() missing 1 required positional argument: 'source'
```

**This is NOT specific to `ansible.utils` filters** - it affects **any module or plugin** that uses `ArgumentSpecValidator` when Template objects are present in the input parameters.

#### Environment

- **Python:** 3.13.12, 3.14.3 (both tested and affected)
- **ansible:** 13.4.0 (latest as of 2026-03-24)
- **ansible-core:** 2.19.8, 2.20.4 (latest)
- **Jinja2:** 3.1.6 (stock)
- **Working version:** ansible-core 2.18.9 + Python 3.14.3 + Jinja2 3.1.6 ✅

##### ❌ The Specific Trigger

The issue is triggered by **Jinja2 macro imports** in templates rendered by `ansible.builtin.template`:

```jinja2
{% import 'macros/ip_funcs.j2' as ipfn %}  ← This creates a Template object!
```

When a template imports a macro, ansible-core 2.19+ leaves the Template object in the variable context, which then gets passed to filters/modules and causes the deepcopy error.

##### ✅ What DOESN'T Trigger the Issue

**Simple filter usage in tasks** (works fine):
```yaml
- debug:
    msg: "{{ test_addresses | ansible.utils.ipv4 }}"

- set_fact:
    ipv4_only: "{{ test_addresses | ansible.utils.ipv4 }}"
```

**Inline template content without macro imports** (works fine):
```yaml
- copy:
    dest: "/tmp/test.j2"
    content: |
      {% if iface.addresses|default([])|ansible.utils.ipv4|length == 0 %}
      method=disabled
      {% endif %}

- template:
    src: "/tmp/test.j2"
    dest: "/tmp/test.conf"
```

**External templates WITH macro imports** (FAILS):
```yaml
- template:
    src: "roles/myapp/templates/config.j2"  # This file has {% import ... %}
    dest: "/tmp/config.conf"
```

#### Root Cause

1. **ansible-core 2.19 templating changes** introduced lazy evaluation and native Jinja mode
2. When a template imports a macro: `{% import 'macros/ip_funcs.j2' as ipfn %}`
3. A Jinja2 `Template` object is created and stored in the variable context as `ipfn`
4. When filters (like `ansible.utils.ipv4`) are used in the template, the variable context (including the Template object) is passed to the filter
5. The filter's `ArgumentSpecValidator` in `ansible/module_utils/common/arg_spec.py` calls `deepcopy(parameters)` on line 64
6. In Python, `deepcopy` uses `copyreg.__newobj__` which calls `Template.__new__(cls)` with **no arguments**
7. But `Template.__new__` requires a `source` argument → **ERROR**

##### Why This Didn't Happen in ansible-core 2.18.9

- Different templating system that didn't leave Template objects in the variable context
- Parameters dict contained only primitive types and data structures
- `deepcopy(parameters)` worked fine

#### Scope of Impact

**Affected scenarios:**
- Any playbook using `ansible.builtin.template` module
- With external template files that import Jinja2 macros
- That use ANY filter or plugin using `ArgumentSpecValidator`
- Running on ansible-core 2.19+

**Examples of affected filters/modules:**
- `ansible.utils.ipv4`, `ansible.utils.ipv6`, `ansible.utils.ipaddr`
- Any custom filter using `ArgumentSpecValidator`
- Any module using `ArgumentSpecValidator`

##### File Structure
```
test_exact_replica.yml
roles/network_vxlanevpn/templates/
  ├── iface.nmconnection.j2
  └── macros/
      └── ip_funcs.j2
```

##### test_exact_replica.yml
```yaml
---
- name: Reproduce Template deepcopy error
  hosts: localhost
  gather_facts: false
  connection: local
  
  vars:
    network_interfaces:
      - name: "enp3s0"
        addresses:
          - "10.252.0.10/24"
        nameservers:
          addresses:
            - "8.8.8.8"
  
  tasks:
    - name: Write interface configuration
      ansible.builtin.template:
        src: "roles/network_vxlanevpn/templates/iface.nmconnection.j2"
        dest: "/tmp/test_output_{{ item.name }}.nmconnection"
        mode: "0600"
      vars:
        iface: "{{ item }}"
      with_items: "{{ network_interfaces }}"
```

##### roles/network_vxlanevpn/templates/iface.nmconnection.j2
```jinja2
{% import 'macros/ip_funcs.j2' as ipfn %}

[connection]
id={{ iface.name }}

[ipv4]
{% if iface.addresses|default([])|ansible.utils.ipv4|length == 0 %}
method=disabled
{% else %}
method=manual
{% endif %}
{% for ip in iface.addresses|default([])|ansible.utils.ipv4 %}
address{{ loop.index }}={{ ip }}
{% endfor %}
{% if iface.nameservers.addresses|default([])|ansible.utils.ipv4|length > 0 %}
dns={{ iface.nameservers.addresses|default([])|ansible.utils.ipv4|join(";") }};
{% endif %}
```

##### roles/network_vxlanevpn/templates/macros/ip_funcs.j2
```jinja2
{% macro orig_ifname(namemap, name) %}
{{- namemap[name]|default(name) -}}
{% endmacro -%}
```

##### Run the test
```bash
ansible-playbook test_exact_replica.yml
```

##### Expected Error
```
[ERROR]: The filter plugin 'ansible.utils.ipv4' failed:
Template.__new__() missing 1 required positional argument: 'source'
```

#### Proposed Fix

Modify `ansible/module_utils/common/arg_spec.py` to use a custom copy function that preserves Template objects by reference instead of deep-copying them.

**Why this is the correct fix:**
- Jinja2's API documentation explicitly states: **"A template object should be considered immutable"**
- Immutable objects don't need deep copying - sharing references is safe
- This avoids the Python deepcopy issue entirely
- No changes to Jinja2 required

**Why the fix belongs in ansible-core (not Jinja2):**
- ansible-core 2.19 introduced the templating changes that put Template objects in parameter dicts
- Jinja2 doesn't promise that Template objects are deep-copyable, only that they're immutable
- Ansible's `ArgumentSpecValidator` is calling `deepcopy()` on parameters it created
- The fix should be where the problem was introduced

##### Implementation

**File:** `ansible/module_utils/common/arg_spec.py`

**Change line 64 from:**
```python
self._validated_parameters = deepcopy(parameters)
```

**To:**
```python
self._validated_parameters = self._safe_deepcopy(parameters)
```

**Add this method to the `ValidationResult` class:**
```python
@staticmethod
def _safe_deepcopy(obj, memo=None, _recursion_guard=None):
    """
    Deep copy that preserves Jinja2 Template objects by reference.

    Template objects are immutable and cannot be deep-copied in Python 3.14+
    due to changes in how copyreg reconstructs objects. Since they're immutable,
    it's safe to preserve them by reference rather than copying.

    This fixes compatibility with ansible-core 2.19+ templating changes that
    can include Template objects in parameters.
    """
    if _recursion_guard is None:
        _recursion_guard = set()

    obj_id = id(obj)
    if obj_id in _recursion_guard:
        return obj

    # Check if this is a Jinja2 Template object (or subclass like AnsibleTemplate)
    # We check the class name to avoid importing jinja2 if not needed
    if hasattr(obj, '__class__'):
        class_name = obj.__class__.__name__
        # Match Template and any subclasses (like AnsibleTemplate)
        if 'Template' in class_name and hasattr(obj, 'environment'):
            # This looks like a Jinja2 Template, preserve by reference
            return obj

    # For containers, recursively copy while preserving Templates
    if isinstance(obj, dict):
        _recursion_guard.add(obj_id)
        return {k: ValidationResult._safe_deepcopy(v, memo, _recursion_guard) for k, v in obj.items()}
    elif isinstance(obj, (list, tuple)):
        _recursion_guard.add(obj_id)
        result = [ValidationResult._safe_deepcopy(item, memo, _recursion_guard) for item in obj]
        return type(obj)(result) if isinstance(obj, tuple) else result

    # Use standard deepcopy for everything else (primitives, custom objects, etc.)
    from copy import deepcopy
    return deepcopy(obj, memo)
```

#### Testing

I have tested this fix successfully on:
- ✅ **ansible 13.4.0** (latest as of 2026-03-24)
- ✅ **ansible-core 2.20.4** (latest)
- ✅ **ansible-core 2.19.8**
- ✅ **Jinja2 3.1.6** (stock, no modifications)
- ✅ **Python 3.14.3**
- ✅ **Python 3.13.12**

**Test results:**
- Before patch: `Template.__new__() missing 1 required positional argument: 'source'`
- After patch: `PLAY RECAP: localhost ok=7 changed=1 unreachable=0 failed=0`

The patch fixes the issue without requiring any changes to Jinja2.

**Python version testing:**
- Confirmed the deepcopy issue occurs on both Python 3.13.12 and 3.14.3
- Python 3.12 and earlier have not been tested but may also be affected

#### Additional Information

**Complete patch file available:** I can provide a complete unified diff patch if needed.

**Workarounds until fixed:**
1. Downgrade to ansible-core 2.18.9 (works with Python 3.13 and 3.14)
2. Avoid using Jinja2 macro imports in templates (not practical for complex templates)
3. Use Python 3.12 or earlier (if the issue doesn't affect those versions)

**Related ansible-core changes:**
- ansible-core 2.19 porting guide: https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_core_2.19.html
- Mentions "significant templating changes" including lazy templating and native Jinja mode

### Issue Type

Bug Report

### Component Name

ansible-core

### Ansible Version

```console
ansible [core 2.20.4]
  config file = /Users/bhouse/svn/ansible-scripts/ansible.cfg
  configured module search path = ['/Users/bhouse/svn/ansible-scripts/library']
  ansible python module location = /Users/bhouse/svn/ansible-scripts/venv13/lib/python3.14/site-packages/ansible
  ansible collection location = /Users/bhouse/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/bhouse/svn/ansible-scripts/venv13/bin/ansible
  python version = 3.14.3 (main, Feb  3 2026, 15:32:20) [Clang 17.0.0 (clang-1700.6.3.2)] (/Users/bhouse/svn/ansible-scripts/venv13/bin/python3.14)
  jinja version = 3.1.6
  pyyaml version = 6.0.3 (with libyaml v0.2.5)
```

### Configuration

```console
CACHE_PLUGIN(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = memory
COLOR_CHANGED(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = yellow
COLOR_DEBUG(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = dark gray
COLOR_DEPRECATE(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = purple
COLOR_DIFF_ADD(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = green
COLOR_DIFF_LINES(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = cyan
COLOR_DIFF_REMOVE(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = red
COLOR_ERROR(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = red
COLOR_HIGHLIGHT(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = white
COLOR_OK(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = green
COLOR_SKIP(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = cyan
COLOR_UNREACHABLE(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = red
COLOR_VERBOSE(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = cyan
COLOR_WARN(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = bright purple
CONFIG_FILE() = /Users/bhouse/svn/ansible-scripts/ansible.cfg
DEFAULT_ASK_VAULT_PASS(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = True
DEFAULT_BECOME(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = False
DEFAULT_BECOME_METHOD(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = root
DEFAULT_FORKS(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = 50
DEFAULT_GATHERING(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = implicit
DEFAULT_HOST_LIST(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = ['/Users/bhouse/svn/ansible-scripts/inventory/testenv']
DEFAULT_JINJA2_EXTENSIONS(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = ['jinja2.ext.do', 'jinja2.ext.i18n', 'jinja2.ext.loopcontrols']
DEFAULT_LOG_PATH(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = /Users/bhouse/ansible.log
DEFAULT_MANAGED_STR(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_MODULE_PATH(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = ['/Users/bhouse/svn/ansible-scripts/library']
DEFAULT_REMOTE_PORT(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = 22
DEFAULT_STRATEGY(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = mitogen_linear
DEFAULT_STRATEGY_PLUGIN_PATH(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = ['/Users/bhouse/svn/ansible-scripts/venv13/lib/python3.14/site>
DEFAULT_TIMEOUT(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = 10
EDITOR(env: EDITOR) = /usr/bin/nano
HOST_KEY_CHECKING(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = False
INTERPRETER_PYTHON(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = auto_silent
RETRY_FILES_ENABLED(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = False

GALAXY_SERVERS:


BECOME:
======

runas:
_____
become_user(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = root

su:
__
become_user(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = root

sudo:
____
become_user(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = root

CONNECTION:
==========

paramiko_ssh (DEPRECATED):
_________________________
host_key_checking(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = False
port(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = 22
timeout(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = 10

paramiko_ssh:
____________
host_key_checking(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = False
port(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = 22
timeout(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = 10

ssh:
___
control_path(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = %(directory)s/%%C
control_path_dir(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = ~/.ansible/cp
host_key_checking(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = False
pipelining(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = True
port(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = 22
ssh_args(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=2m
ssh_transfer_method(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = smart
timeout(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = 10

SHELL:
=====

sh:
__
remote_tmp(/Users/bhouse/svn/ansible-scripts/ansible.cfg) = ~/.ansible/tmp
```

### OS / Environment

MacOS

### Steps to Reproduce

see detailed description

### Expected Results

see detailed description

### Actual Results

```console
see detailed description
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
