### ISSUE TITLE
pamd failing on documented example

### ISSUE THREAD

**Issue by xcorvis** [ansible/ansible#35629]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
pamd module

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = /home/adam/code/ansible-mta/ansible.cfg
  configured module search path = ['/home/adam/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/adam/venv/ansible-mta-py3/lib/python3.6/site-packages/ansible
  executable location = /home/adam/venv/ansible-mta-py3/bin/ansible
  python version = 3.6.3 (default, Oct  3 2017, 21:45:48) [GCC 7.2.0]
```
I also noticed this on 2.4.2.0 and upgraded to 2.4.3.0 to try and resolve it.

##### CONFIGURATION
ANSIBLE_NOCOWS(/home/adam/code/ansible-mta/ansible.cfg) = True
ANSIBLE_PIPELINING(/home/adam/code/ansible-mta/ansible.cfg) = True
CACHE_PLUGIN(/home/adam/code/ansible-mta/ansible.cfg) = memory
COMMAND_WARNINGS(/home/adam/code/ansible-mta/ansible.cfg) = False
DEFAULT_FORKS(/home/adam/code/ansible-mta/ansible.cfg) = 50
DEFAULT_GATHERING(/home/adam/code/ansible-mta/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/home/adam/code/ansible-mta/ansible.cfg) = ['/home/adam/code/ansible-mta/environments/local']
DEFAULT_LOG_PATH(/home/adam/code/ansible-mta/ansible.cfg) = /tmp/ansible-mta-adam.log
DEFAULT_MANAGED_STR(/home/adam/code/ansible-mta/ansible.cfg) = Ansible Managed
DEFAULT_ROLES_PATH(/home/adam/code/ansible-mta/ansible.cfg) = ['/home/adam/code/ansible-mta/roles']
HOST_KEY_CHECKING(/home/adam/code/ansible-mta/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/adam/code/ansible-mta/ansible.cfg) = False

##### OS / ENVIRONMENT
Host: Ubuntu 17.10
Targets: Ubuntu 16.04 and CentOS 6 (identical errors)

##### SUMMARY
When running one of the "example" items from the pamd module documentation ( https://docs.ansible.com/ansible/latest/pamd_module.html#examples ), I get a stack trace. I also independently verified the commands (which are appropriate to my configuration) so I believe the example is correct.

##### STEPS TO REPRODUCE
Run the following playbook against a clean Ubuntu 16.04 machine.

Example playbook, functionally equivalent to one of the examples in the module docs:
```yaml
---
- hosts: test
  tasks:
    - name: Prevent su except by wheel group
      become: true
      pamd:
        name: su
        type: auth
        control: sufficient
        module_path: pam_rootok.so
        new_type: auth
        new_control: required
        new_module_path: pam_wheel.so
        module_arguments: 'use_uid'
        state: after
```

##### EXPECTED RESULTS
Should add a line to the pam config like `auth required pam_wheel.so use_uid`.

##### ACTUAL RESULTS
Module fails and traceback.

Just the traceback:
```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_TpFc0r/ansible_module_pamd.py", line 651, in <module>
    main()
  File "/tmp/ansible_TpFc0r/ansible_module_pamd.py", line 606, in main
    pamd.load_rules_from_file()
  File "/tmp/ansible_TpFc0r/ansible_module_pamd.py", line 328, in load_rules_from_file
    self.load_rules_from_string(stringline)
  File "/tmp/ansible_TpFc0r/ansible_module_pamd.py", line 344, in load_rules_from_string
    self.rules.append(PamdRule.rulefromstring(stringline))
  File "/tmp/ansible_TpFc0r/ansible_module_pamd.py", line 279, in rulefromstring
    rule_type = result.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

```
$ ansible-playbook -vvvv -l test-ubuntu16, --diff --vault-id local@prompt roles/users/tests/test.yml

ansible-playbook 2.4.3.0
  config file = /home/adam/code/ansible-mta/ansible.cfg
  configured module search path = ['/home/adam/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/adam/venv/ansible-mta-py3/lib/python3.6/site-packages/ansible
  executable location = /home/adam/venv/ansible-mta-py3/bin/ansible-playbook
  python version = 3.6.3 (default, Oct  3 2017, 21:45:48) [GCC 7.2.0]
Using /home/adam/code/ansible-mta/ansible.cfg as config file 
Vault password (local): 
setting up inventory plugins
Parsed /home/adam/code/ansible-mta/environments/local/vagrant_ansible_inventory inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /home/adam/venv/ansible-mta-py3/lib/python3.6/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: test.yml *************************************************************************************************************************
1 plays in roles/users/tests/test.yml

PLAY [test] ********************************************************************************************************************************
META: ran handlers
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x7fcafece3080> for vault_id=local

TASK [Prevent su except by wheel group] ****************************************************************************************************
task path: /home/adam/code/ansible-mta/roles/users/tests/test.yml:8
Using module file /home/adam/venv/ansible-mta-py3/lib/python3.6/site-packages/ansible/modules/system/pamd.py
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2022 -o 'IdentityFile="/home/adam/code/ansible-mta/.vagrant/machines/test-ubuntu16/virtualbox/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 -o ControlPath=/home/adam/.ansible/cp/8752954ab8 127.0.0.1 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-cmbfaaexzpdzxcuupxemlrwmjffbgeku; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<127.0.0.1> (1, b'', b'OpenSSH_7.5p1 Ubuntu-10ubuntu0.1, OpenSSL 1.0.2g  1 Mar 2016\r\ndebug1: Reading configuration data /home/adam/.ssh/config\r\ndebug1: /home/adam/.ssh/config line 58: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 4 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 24030\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\nTraceback (most recent call last):\n  File "/tmp/ansible_qMwnEL/ansible_module_pamd.py", line 651, in <module>\n    main()\n  File "/tmp/ansible_qMwnEL/ansible_module_pamd.py", line 606, in main\n    pamd.load_rules_from_file()\n  File "/tmp/ansible_qMwnEL/ansible_module_pamd.py", line 328, in load_rules_from_file\n    self.load_rules_from_string(stringline)\n  File "/tmp/ansible_qMwnEL/ansible_module_pamd.py", line 344, in load_rules_from_string\n    self.rules.append(PamdRule.rulefromstring(stringline))\n  File "/tmp/ansible_qMwnEL/ansible_module_pamd.py", line 279, in rulefromstring\n    rule_type = result.group(1)\nAttributeError: \'NoneType\' object has no attribute \'group\'\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\n')
fatal: [test-ubuntu16]: FAILED! => {
    "changed": false,
    "module_stderr": "OpenSSH_8.5p1 Ubuntu-10ubuntu0.1, OpenSSL 1.0.2g  1 Mar 2016\r\ndebug1: Reading configuration data /home/adam/.ssh/config\r\ndebug1: /home/adam/.ssh/config line 58: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 4 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 24030\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\nTraceback (most recent call last):\n  File \"/tmp/ansible_qMwnEL/ansible_module_pamd.py\", line 651, in <module>\n    main()\n  File \"/tmp/ansible_qMwnEL/ansible_module_pamd.py\", line 606, in main\n    pamd.load_rules_from_file()\n  File \"/tmp/ansible_qMwnEL/ansible_module_pamd.py\", line 328, in load_rules_from_file\n    self.load_rules_from_string(stringline)\n  File \"/tmp/ansible_qMwnEL/ansible_module_pamd.py\", line 344, in load_rules_from_string\n    self.rules.append(PamdRule.rulefromstring(stringline))\n  File \"/tmp/ansible_qMwnEL/ansible_module_pamd.py\", line 279, in rulefromstring\n    rule_type = result.group(1)\nAttributeError: 'NoneType' object has no attribute 'group'\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}

PLAY RECAP *********************************************************************************************************************************
test-ubuntu16              : ok=0    changed=0    unreachable=0    failed=1   
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/system/pamd.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/pamd.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @kevensen
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by kevensen** [comment]
@xcorvis can you please share your pam_rootok.so file?
needs_info

**Comment by xcorvis** [comment]
pam_rootok.so is a binary and shouldn't be affected by this operation. I think you're actually wanting to look at the /etc/pam.d/su file. Either way, they're default for ubuntu 16.04, I have not changed them at all.

/etc/pam.d/su:
```
#
# The PAM configuration file for the Shadow `su' service
#

# This allows root to su without passwords (normal operation)
auth       sufficient pam_rootok.so

# Uncomment this to force users to be a member of group root
# before they can use `su'. You can also add "group=foo"
# to the end of this line if you want to use a group other
# than the default "root" (but this may have side effect of
# denying "root" user, unless she's a member of "foo" or explicitly
# permitted earlier by e.g. "sufficient pam_rootok.so").
# (Replaces the `SU_WHEEL_ONLY' option from login.defs)
# auth       required   pam_wheel.so

# Uncomment this if you want wheel members to be able to
# su without a password.
# auth       sufficient pam_wheel.so trust

# Uncomment this if you want members of a specific group to not
# be allowed to use su at all.
# auth       required   pam_wheel.so deny group=nosu

# Uncomment and edit /etc/security/time.conf if you need to set
# time restrainst on su usage.
# (Replaces the `PORTTIME_CHECKS_ENAB' option from login.defs
# as well as /etc/porttime)
# account    requisite  pam_time.so

# This module parses environment configuration file(s)
# and also allows you to use an extended config
# file /etc/security/pam_env.conf.
# 
# parsing /etc/environment needs "readenv=1"
session       required   pam_env.so readenv=1
# locale variables are also kept into /etc/default/locale in etch
# reading this file *in addition to /etc/environment* does not hurt
session       required   pam_env.so readenv=1 envfile=/etc/default/locale

# Defines the MAIL environment variable
# However, userdel also needs MAIL_DIR and MAIL_FILE variables
# in /etc/login.defs to make sure that removing a user 
# also removes the user's mail spool file.
# See comments in /etc/login.defs
#
# "nopen" stands to avoid reporting new mail when su'ing to another user
session    optional   pam_mail.so nopen

# Sets up user limits according to /etc/security/limits.conf
# (Replaces the use of /etc/limits in old login)
session    required   pam_limits.so

# The standard Unix authentication modules, used with
# NIS (man nsswitch) as well as normal /etc/passwd and
# /etc/shadow entries.
@include common-auth
@include common-account
@include common-session
```

**Comment by kevensen** [comment]
@xcorvis Silly me.  Yes, I meant the /etc/pam.d/su file.  Thanks.  I'll take a look.

**Comment by kevensen** [comment]
@xcorvis As it turns out, the module invocation you provided works just fine.  What was failing was the **@include** statements at the end.  I had failed to consider that case.  Thanks for the bug report.

I've tested this against an Ubuntu machine.  If you get a chance, do you mind testing the PR to see if it works for you?

**Comment by xcorvis** [comment]
Thanks for the quick response @kevensen. I can confirm that with the fix, my ubuntu 16.04 box is working as expected.

However, I went back and tried my CentOS 6 box and it still returns the same error (identical to the ubuntu error I listed above). I've added the CentOS 6 version of the pam su file, it looks like it has an unusual line continuation.

CentOS 6 /etc/pam.d/su:
```
#%PAM-1.0
auth		sufficient	pam_rootok.so
# Uncomment the following line to implicitly trust users in the "wheel" group.
#auth		sufficient	pam_wheel.so trust use_uid
# Uncomment the following line to require a user to be in the "wheel" group.
#auth		required	pam_wheel.so use_uid
auth		include		system-auth
account		sufficient	pam_succeed_if.so uid = 0 use_uid quiet
# allow vagrant to use su, but prevent others from becoming root or vagrant
account		[success=1 default=ignore] \
				pam_succeed_if.so user = vagrant use_uid quiet
account		required	pam_succeed_if.so user notin root:vagrant
account		include		system-auth
password	include		system-auth
session		include		system-auth
session		optional	pam_xauth.so
```

**Comment by kevensen** [comment]
@xcorvis Yup, another case not considered.  Do you mind trying it again with the latest commit?

**Comment by xcorvis** [comment]
@kevensen I grabbed the version here, is this correct?
https://github.com/ansible/ansible/commit/8229a2934251ae23780a7bead5b4152782dff778

Unfortunately it does not seem to work.
```
...
<127.0.0.1> (1, b'', b'Traceback (most recent call last):\n  File "/tmp/ansible_6X936Q/ansible_module_pamd.py", line 693, in <module>\n    main()\n  File "/tmp/ansible_6X936Q/ansible_module_pamd.py", line 648, in main\n    pamd.load_rules_from_file()\n  File "/tmp/ansible_6X936Q/ansible_module_pamd.py", line 359, in load_rules_from_file\n    lines = open(self.fname, \'r\').replace(\'\\\\\\n\',\'\')\nAttributeError: \'file\' object has no attribute \'replace\'\n')
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_6X936Q/ansible_module_pamd.py", line 693, in <module>
    main()
  File "/tmp/ansible_6X936Q/ansible_module_pamd.py", line 648, in main
    pamd.load_rules_from_file()
  File "/tmp/ansible_6X936Q/ansible_module_pamd.py", line 359, in load_rules_from_file
    lines = open(self.fname, 'r').replace('\\\n','')
AttributeError: 'file' object has no attribute 'replace'

fatal: [test-centos6]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_6X936Q/ansible_module_pamd.py\", line 693, in <module>\n    main()\n  File \"/tmp/ansible_6X936Q/ansible_module_pamd.py\", line 648, in main\n    pamd.load_rules_from_file()\n  File \"/tmp/ansible_6X936Q/ansible_module_pamd.py\", line 359, in load_rules_from_file\n    lines = open(self.fname, 'r').replace('\\\\\\n','')\nAttributeError: 'file' object has no attribute 'replace'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```
I also got an identical error with my Ubuntu 16.04 vm.

I should amend my previous statement that this is a default OS. It's an official virtualbox vagrant vm provided by centos, so it does have some vagrant specific customizations. 
https://app.vagrantup.com/centos/boxes/6

**Comment by xcorvis** [comment]
I see your updated commit now. That one produces the same error on both boxes.

**Comment by kevensen** [comment]
@xcorvis Third times a charm....  Please test the latest commit at your convenience.  I actually tested it myself and it seems to work.

**Comment by xcorvis** [comment]
@kevensen That seems to have worked, it's running correctly on both my test systems. Thanks for the help!

**Comment by kevensen** [comment]
@xcorvis Awesome!  Happy to help.

**Comment by faoiseamh** [comment]
I'm still getting this same crash after upgrading to 2.5.0b1 which includes 5cce024 running on latest Amazon Linux (essentially CentOS):
```
Traceback (most recent call last):
 File "/tmp/ansible_kgFx_y/ansible_module_pamd.py", line 691, in <module>
 main()
 File "/tmp/ansible_kgFx_y/ansible_module_pamd.py", line 645, in main
 pamd.load_rules_from_file()
 File "/tmp/ansible_kgFx_y/ansible_module_pamd.py", line 361, in load_rules_from_file
 self.load_rules_from_string(stringline.replace("\\\n", ""))
 File "/tmp/ansible_kgFx_y/ansible_module_pamd.py", line 380, in load_rules_from_string
 self.rules.append(PamdRule.rulefromstring(stringline))
 File "/tmp/ansible_kgFx_y/ansible_module_pamd.py", line 312, in rulefromstring
 rule_type = result.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by kevensen** [comment]
@faoiseamh can you provide details about your sceniario?

1. Your playbook
2. The target host o/s
3. The original Pam module file

**Comment by faoiseamh** [comment]
@kevensen Sure, sorry. I'm just getting into Ansible so I'm not too familiar. Playbook is essentially just using this role: https://github.com/anthcourtney/ansible-role-cis-amazon-linux and I'm running this on the latest amazon linux which is essentially centos. I'm running this with some automation so it will take me a bit to extract the original pam file, but it is whatever is freshly installed by `pip install ansible==2.5.0b1`.

I'll update this in an hour or two when I have some time with any more details that will help.

**Comment by faoiseamh** [comment]
@kevensen The task that leads to this error is https://github.com/anthcourtney/ansible-role-cis-amazon-linux/blob/master/tasks/level-1/5.3.3.yml

**Comment by kevensen** [comment]
@faoiseamh Thanks for the extra info.  I’ll take a look at this In the next day or two.

**Comment by faoiseamh** [comment]
@kevensen Awesome, thanks. I'm working around it for now. Happy to help test at a minimum and provide any other context that would help.

**Comment by ideologysec** [comment]
I'm still having this issue on Ubuntu 16.04.
My control laptop is python 3.6.5 and Ansible 2.5.3.

Here's the pamd play:
```
- name: "UBUNTU | Ensure PAM sshd config is correct for Duo UNIX"
  block:
    - name: "Insert pam_permit into PAM sshd"
      pamd:
        name: sshd
        type: account
        control: 'required'
        module_path: pam_nologin.so
        new_type: auth
        new_control: required
        new_module_path: pam_permit.so
        state: before

    - name: "Insert pam_deny into PAM sshd"
      pamd:
        name: sshd
        type: auth
        control: 'required'
        module_path: pam_permit.so
        new_type: auth
        new_control: requisite
        new_module_path: pam_deny.so
        state: before

    - name: "Insert pam_duo into PAM sshd"
      pamd:
        name: sshd
        type: auth
        control: 'requisite'
        module_path: pam_deny.so
        new_type: auth
        new_control: '[success=1 default=ignore]'
        new_module_path: /lib64/security/pam_duo.so
        state: before
  when: ansible_os_family == "Debian"
```

and the (default) /etc/pam.d/sshd:
```
# PAM configuration for the Secure Shell service

# Standard Un*x authentication.
@include common-auth

# Disallow non-root logins when /etc/nologin exists.
account    required     pam_nologin.so

# Uncomment and edit /etc/security/access.conf if you need to set complex
# access limits that are hard to express in sshd_config.
# account  required     pam_access.so

# Standard Un*x authorization.
@include common-account

# SELinux needs to be the first session rule.  This ensures that any
# lingering context has been cleared.  Without this it is possible that a
# module could execute code in the wrong domain.
session [success=ok ignore=ignore module_unknown=ignore default=bad]        pam_selinux.so close

# Set the loginuid process attribute.
session    required     pam_loginuid.so

# Create a new session keyring.
session    optional     pam_keyinit.so force revoke

# Standard Un*x session setup and teardown.
@include common-session

# Print the message of the day upon successful login.
# This includes a dynamically generated part from /run/motd.dynamic
# and a static (admin-editable) part from /etc/motd.
session    optional     pam_motd.so  motd=/run/motd.dynamic
session    optional     pam_motd.so noupdate

# Print the status of the user's mailbox upon successful login.
session    optional     pam_mail.so standard noenv # [1]

# Set up user limits from /etc/security/limits.conf.
session    required     pam_limits.so

# Read environment variables from /etc/environment and
# /etc/security/pam_env.conf.
session    required     pam_env.so # [1]
# In Debian 4.0 (etch), locale-related environment variables were moved to
# /etc/default/locale, so read that as well.
session    required     pam_env.so user_readenv=1 envfile=/etc/default/locale

# SELinux needs to intervene at login time to ensure that the process starts
# in the proper default security context.  Only sessions which are intended
# to run in the user's context should be run after this.
session [success=ok ignore=ignore module_unknown=ignore default=bad]        pam_selinux.so open

# Standard Un*x password updating.
@include common-password
```

and the error message:
```
[localhost] TASK: duo-ssh : Insert pam_permit into PAM sshd (debug)> p result._result
{'_ansible_no_log': False,
 '_ansible_parsed': False,
 'changed': False,
 'failed': True,
 'module_stderr': 'Shared connection to localhost closed.\r\n',
 'module_stdout': 'Traceback (most recent call last):\r\n'
                  '  File "/tmp/ansible_LsSq6T/ansible_module_pamd.py", line '
                  '691, in <module>\r\n'
                  '    main()\r\n'
                  '  File "/tmp/ansible_LsSq6T/ansible_module_pamd.py", line '
                  '645, in main\r\n'
                  '    pamd.load_rules_from_file()\r\n'
                  '  File "/tmp/ansible_LsSq6T/ansible_module_pamd.py", line '
                  '361, in load_rules_from_file\r\n'
                  '    '
                  'self.load_rules_from_string(stringline.replace("\\\\\\n", '
                  '""))\r\n'
                  '  File "/tmp/ansible_LsSq6T/ansible_module_pamd.py", line '
                  '380, in load_rules_from_string\r\n'
                  '    '
                  'self.rules.append(PamdRule.rulefromstring(stringline))\r\n'
                  '  File "/tmp/ansible_LsSq6T/ansible_module_pamd.py", line '
                  '312, in rulefromstring\r\n'
                  '    rule_type = result.group(1)\r\n'
                  "AttributeError: 'NoneType' object has no attribute "
                  "'group'\r\n",
 'msg': 'MODULE FAILURE',
 'rc': 1}
```
