### ISSUE TITLE
'os_server_facts' module fails with Ansible 2.6

### ISSUE THREAD

**Issue by benjdudas** [ansible/ansible#43275]
##### SUMMARY

After upgrading to 2.6 from 2.5.6 our `os_server_facts` task fails with:

`AttributeError: 'module' object has no attribute 'version'`

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

os_server_facts
##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

Default settings:
```
user@tower ~]$ ansible-config dump --only-changed
user@tower ~]$
```

##### STEPS TO REPRODUCE

```yaml
- name: Gather Openstack Facts
  os_server_facts:
    auth: "{{ item }}"
    server: "{{ snap_filter }}"
  register: osi_result
  no_log: False
  with_items: "{{ prj_list }}"
  tags:
    - always
```

##### EXPECTED RESULTS

Facts retrieved from the OpenStack instances as with 2.5

##### ACTUAL RESULTS

```
TASK [snapshot : Gather Openstack Facts] ***************************************13:53:30
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'module' object has no attribute 'version'
failed: [localhost] (item={u'username': u' < REMOVED FOR CASE > ', u'project_name': u'Openshift-OCD04-SKY', u'user_domain_name': u'AD', u'auth_url': u'https://example.com:13000/v3', u'password': u'< REMOVED FOR CASE >', u'project_domain_name': u'AD'}) => {"changed": false, "item": {"auth_url": "https://example.com:13000/v3", "password": "< REMOVED For CASE >", "project_domain_name": "AD", "project_name": "Openshift-OCD04-SKY", "user_domain_name": "AD", "username": "< REMOVED FOR CASE >"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_4m6oiI/ansible_module_os_server_facts.py\", line 89, in <module>\n    main()\n  File \"/tmp/ansible_4m6oiI/ansible_module_os_server_facts.py\", line 70, in main\n    sdk, cloud = openstack_cloud_from_module(module)\n  File \"/tmp/ansible_4m6oiI/ansible_modlib.zip/ansible/module_utils/openstack.py\",…
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/openstack/os_server_facts.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/openstack/os_server_facts.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagnello @emonty @juliakreger @omgjlk @rcarrillocruz @shrews @thingee
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Shrews** [comment]
Odd. What versions of openstacksdk and distutils do you have installed?

**Comment by ansibot** [comment]
@benjdudas: thank you for submitting this issue!

cc @mnaser
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mnaser** [comment]
needs_info

Can you please provide the full traceback?

**Comment by benjdudas** [comment]
@mnaser This was opened on a customers behalf, and at this time the only traceback I have on this is the following:

```
Identity added: /tmp/awx_6185_vvzwLN/credential_12 (/tmp/awx_6185_vvzwLN/credential_12)
Using /etc/ansible/ansible.cfg as config file
Vault password: 
[DEPRECATION WARNING]: 'include' for playbook includes. You should use 
'import_playbook' instead. This feature will be removed in version 2.8. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
PLAY [localhost] ***************************************************************13:53:28
TASK [Gathering Facts] *********************************************************13:53:28
ok: [localhost]
TASK [snapshot : debug] ********************************************************13:53:29
ok: [localhost] => {
    "msg": "/tmp/awx_6185_vvzwLN/tmp1HAwhD"
}
TASK [snapshot : stat] *********************************************************13:53:29
ok: [localhost] => {"changed": false, "stat": {"atime": 1532552006.102405, "attr_flags": "", "attributes": [], "block_size": 4096, "blocks": 8, "charset": "us-ascii", "checksum": "bdfd11d8438322b4b17d71cdf58040d5c435e150", "ctime": 1532552006.103405, "dev": 2049, "device_type": 0, "executable": false, "exists": true, "gid": 991, "gr_name": "awx", "inode": 125887524, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": false, "isreg": true, "issock": false, "isuid": false, "mimetype": "text/plain", "mode": "0600", "mtime": 1532552006.103405, "nlink": 1, "path": "/tmp/awx_6185_vvzwLN/tmp1HAwhD", "pw_name": "awx", "readable": true, "rgrp": false, "roth": false, "rusr": true, "size": 196, "uid": 994, "version": "81724534", "wgrp": false, "woth": false, "writeable": true, "wusr": true, "xgrp": false, "xoth": false, "xusr": false}}
TASK [snapshot : include_vars] *************************************************13:53:30
ok: [localhost] => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
TASK [snapshot : Gather Openstack Facts] ***************************************13:53:30
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'module' object has no attribute 'version'
failed: [localhost] (item={u'username': u' < REMOVED FOR CASE > ', u'project_name': u'Openshift-OCD04-SKY', u'user_domain_name': u'AD', u'auth_url': u'https://auriga.ssc.lmco.com:13000/v3', u'password': u'< REMOVED FOR CASE >', u'project_domain_name': u'AD'}) => {"changed": false, "item": {"auth_url": "https://auriga.ssc.lmco.com:13000/v3", "password": "< REMOVED For CASE >", "project_domain_name": "AD", "project_name": "Openshift-OCD04-SKY", "user_domain_name": "AD", "username": "< REMOVED FOR CASE >"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_4m6oiI/ansible_module_os_server_facts.py\", line 89, in <module>\n    main()\n  File \"/tmp/ansible_4m6oiI/ansible_module_os_server_facts.py\", line 70, in main\n    sdk, cloud = openstack_cloud_from_module(module)\n  File \"/tmp/ansible_4m6oiI/ansible_modlib.zip/ansible/module_utils/openstack.py\",…
PLAY RECAP *********************************************************************13:53:30
localhost                  : ok=4    changed=0    unreachable=0    failed=1   

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by mnaser** [comment]
Unfortunately, I'm not able to get any more information because there's no traceback and the *good stuff* seems to trimmed off

**Comment by ansibot** [comment]
cc @cloudnull @evrardjp @odyssey4me
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @gtema
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@benjdudas Could you please provide the additional information required for @mnaser to work on ? Thanks

needs_info

**Comment by Akasurde** [comment]
!component =lib/ansible/modules/cloud/openstack/os_server_info.py

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/openstack/os_server_info.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/openstack/os_server_info.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@benjdudas This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@benjdudas You have not responded to information requests in this issue so we will assume it no longer affects you. If you are still interested in this, please create a new issue with the requested information.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)
