### ISSUE TITLE
bug in resolving/templating keys for dict variables

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#4719]
Given this playbooklet:

``` yaml
- hosts: localhost
  gather_facts: false
  connection: local

  vars:
    name: app-dev-2
    node_num: "{{ name|last }}"
    datastore:
      "1": one 
      "2": two 

  tasks:
  - debug: msg="{{ datastore[node_num] }}" 
```

This fails with 

`fatal: [localhost] => One or more undefined variables: 'dict object' has no attribute '{{name|last}}'`

Expected result:

``ok: [localhost] => {    "msg": "two" }`

This faulty behaviour was introduced in 35cb9dc and still exist on latest devel 0faecdf7d1e8b2af1e69a7a67fffa3731ef130e3

**Comment by mpdehaan** [comment]
Still exploring options on the devel branch -- I believe when resolving the filters we need to run them for at least one pass, but not more, yet there are issues if we run them too many times.

Hope to have this resolved in a few days.  The temporary workaround for now is to filter inside the msg line.

**Comment by srgvg** [comment]
Just bumped into another issue, which probably will be the same.

Playbook:

``` yaml
- hosts: localhost
  gather_facts: false
  connection: local

  vars:
    admins:
    - paul
    - george
    - ringo
    - john
    devs:
    - mary
    - kate

    users:
    - "{{ admins }}"
    - "{{ devs }}"
  tasks:
  - debug: msg={{item}}
    with_flattened: users
```

With 35cb9dc~1 the full list is resolved and iterated.
With 35cb9dc I get 

```
ok: [localhost] => (item=users) => {
    "item": "users", 
    "msg": "users"
}
```

**Comment by mpdehaan** [comment]
We're looking at reverting some of this tomorrow so this should all self-resolve soon.

I have some ideas about making references work nicely in other ways after that is done.

**Comment by jctanner** [comment]
@sergevanginderachter as of d154bf87812209409a673fd7f9848d75701e2f32 both of your examples are working:

Test playbook:

```
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    name: app-dev-2
    #node_num: "{{ name|last }}"
    node_num: "{{ name }}"
    datastore:
      "1": one 
      "2": two 
    admins:
    - paul
    - george
    - ringo
    - john
    devs:
    - mary
    - kate

    users:
    - "{{ admins }}"
    - "{{ devs }}"

  tasks:
  - debug: msg="{{ datastore }}" 
  - debug: msg="{{ datastore['1'] }}" 
  - debug: msg="{{ datastore[node_num|last] }}" 

  - debug: msg="{{ admins + devs  }}"
  - debug: msg="{{ users  }}"
  - debug: msg="{{ item  }}"
    with_flattened: users
```

Results:

```
jtanner@u1304:~/issues/4719-debug-dict-keys$ ansible-playbook -i inventory site.yml 

PLAY [localhost] ************************************************************** 

TASK: [debug msg="{'1': 'one', '2': 'two'}"] ********************************** 
ok: [localhost] => {
    "msg": "{'1': 'one', '2': 'two'}"
}

TASK: [debug msg="one"] ******************************************************* 
ok: [localhost] => {
    "msg": "one"
}

TASK: [debug msg="two"] ******************************************************* 
ok: [localhost] => {
    "msg": "two"
}

TASK: [debug msg="['paul', 'george', 'ringo', 'john', 'mary', 'kate']"] ******* 
ok: [localhost] => {
    "msg": "['paul', 'george', 'ringo', 'john', 'mary', 'kate']"
}

TASK: [debug msg="[u"['paul', 'george', 'ringo', 'john']", u"['mary', 'kate']"]"] *** 
ok: [localhost] => {
    "msg": "[u[paul,"
}

TASK: [debug msg="{{item}}"] ************************************************** 
ok: [localhost] => (item=paul) => {
    "item": "paul", 
    "msg": "paul"
}
ok: [localhost] => (item=george) => {
    "item": "george", 
    "msg": "george"
}
ok: [localhost] => (item=ringo) => {
    "item": "ringo", 
    "msg": "ringo"
}
ok: [localhost] => (item=john) => {
    "item": "john", 
    "msg": "john"
}
ok: [localhost] => (item=mary) => {
    "item": "mary", 
    "msg": "mary"
}
ok: [localhost] => (item=kate) => {
    "item": "kate", 
    "msg": "kate"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=6    changed=0    unreachable=0    failed=0  
```

**Comment by srgvg** [comment]
:+1: double checked, and all works!
Also check ed `node_num: "{{ name|last }}"`definition you commented out with `debug: msg="{{ datastore[node_num] }}"` And that still works.

Thanks!
