### PR TITLE
GCE: Fix AttributeError in ex_create_multiple_nodes API

### LINKED ISSUE #31063: gce doesn't work with libcloud 2.0 (or fails badly) - AttributeError: 'GCEFailedNode' object has no attribute 'extra'
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
gce

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

nothing special

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY
```
  - name: Launch GCP instances
    gce:
      name: "foo-wheeee"
      num_instances: "{{ gcp_count }}"
      state: present
      zone: us-west1-a
      image_family: centos-7
      machine_type: n1-standard-1
      tags:
      - "foo-wheeee"
    register: gce
```
yields:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'GCEFailedNode' object has no attribute 'extra'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n File \"/tmp/ansible_jYxrOm/ansible_module_gce.py\", line 778, in <module>\n main()\n File \"/tmp/ansible_jYxrOm/ansible_module_gce.py\", line 738, in main\n module, gce, inames, number, lc_zone)\n File \"/tmp/ansible_jYxrOm/ansible_module_gce.py\", line 586, in create_instances\n d = get_instance_info(inst)\n File \"/tmp/ansible_jYxrOm/ansible_module_gce.py\", line 356, in get_instance_info\n if 'metadata' in inst.extra and 'items' in inst.extra['metadata']:\nAttributeError: 'GCEFailedNode' object has no attribute 'extra'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```

##### STEPS TO REPRODUCE

See above

##### EXPECTED RESULTS

No traceback - either success, or an actual error message if I screwed something up.

### PR DESCRIPTION
**Pull request by byronyi**
Currently there is no way we could get detailed error message for each instance that failed to create when calling `ex_create_multiple_nodes`. 

We mistakenly thought that it fails only because the instances have been created, which is not always the case as reported in #31063. 

Now when we cannot find created instances, we fail the task.

### CODE REVIEW

**Comment by byronyi** [comment]
@jbaublitz Any suggestions?

**Comment by jbaublitz** [comment]
@byronyi Take what I say with a grain of salt because I no longer use GCE but as I remember, this comes down to libcloud's handling of exceptions. At one point I dug into libcloud pretty heavily and it seemed that it raised exceptions whenever an instance was created _or_ if the instance failed to come up. My decision was to favor idempotence over detailed error messaging which might be a less helpful decision for Ansible at this juncture. Regardless, there is potentially a way to handle the exception in a way that distinguishes between failure cases and existing nodes but I do think that what you're proposing here will break idempotence which, even in multinode cases, seems to go against what Ansible wanted from me when I was a more active contributor.

Going to defer to @erjohnso here. Eric, if you can get me access to GCE credits for testing Ansible work, I'm happy to finish up the Dataproc module testing (ansible#19446) and look at this module as well. If that seems like something that can't happen, I'll let you take it from here.

**Comment by byronyi** [comment]
If you take a closer look at #31063, it breaks without this change, only more mysteriously.

**Comment by byronyi** [comment]
In other word, this CL only rings the bell right at the place where the error occurred, rather than fails later on at seemingly irrelevant locations.

**Comment by jbaublitz** [comment]
@byronyi My concern mainly is that this will also fail if a node exists which does break idempotence. Beyond this, I did look at the issue and the metadata error is one I encountered in libcloud in many different contexts but it was not always evident what the cause was. I usually had to debug the raw API endpoint response to see what was actually going on. This is a libcloud issue around error reporting and I do think that while there's room for improvement in the module changes I made, it's probably best to discuss with @erjohnso about where we go from here, particularly since he was unable to reproduce the issue from what I saw.

**Comment by byronyi** [comment]
I do not get it. The exception only occurs when we cannot find the instance after we created it:

```diff
                 try:
                      n = gce.ex_get_node(n.name, lc_zone)
                  except ResourceNotFoundError:
 -                    pass
 +                    module.fail_json(msg='Unexpected error attempting to create ' +
 +                                         'instance %s, error: %s' % (instance_names, resp))
 ```

How could we possibly "fail if a node exists which does break idempotence"?

**Comment by jbaublitz** [comment]
After looking at your code, I see where my confusion was. I can see how this might help but can't comment on this without testing it as it's been a while since I have done anything with libcloud. I'm happy to help however I can but am unsure that I will be the best resource moving forward without being able to actually run the code against the API.

**Comment by byronyi** [comment]
I will close this for now as it seems to me that `ex_create_multiple_nodes` is not actively maintained upstream in `libcloud`. One should resist using `num_instances` and `base_name`, in favour of `instance_names` which is implemented using actively maintained `create_node` API.

See https://github.com/apache/libcloud/pull/1163 for your reference.

**Comment by byronyi** [comment]
Re-open to coordinate [refurnishing of `gce.ex_create_multiple_nodes` and `gce.ex_create_instancetemplate` APIs](https://github.com/apache/libcloud/pull/1204) for the new keyword parameters available in GCE.

**Comment by ryansb** [comment]
cc/ @erjohnso @rambleraptor

**Comment by rambleraptor** [comment]
Is there a way to log this information instead of immediately failing the module? I'd prefer not to crash the module, seeing as we're depending on libcloud, which has an API we don't control.
