### PR TITLE
fixes nxos_evpn_vni and unittest

### LINKED ISSUE #24167: nxos_evpn_vni and nxos_interface module failures
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

nxos_evpn_vni
nxos_interface

##### ANSIBLE VERSION

```

ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### CONFIGURATION

no changes

##### OS / ENVIRONMENT

RHEL 7.2

##### SUMMARY

I recently upgraded ansible from 2.2 to 2.4 to fix an NXOS module issue where nxos_vlan_vtep_vni was not deleting the interface when putting it on an absent state. However now I get errors when I try to create objects using nxos_evpn_vni and nxos_interface. 

##### STEPS TO REPRODUCE

```
    - name: Configure EVPN
      nxos_evpn_vni:
        vni: "{{ vnid }}"
        route_distinguisher: auto
        route_target_import: auto
        route_target_export: auto
        username: ""
        password: ""
        host: "{{ item }}"
      with_items:
        - "{{ leaf1ip }}"
      register: evpnconfig
      ignore_errors: yes

    - name: Configure fabric forwarding anycast gateway
      nxos_interface:
        interface: vlan {{vlan_id}}
        description: "{{ vlan_name }}"
        transport: cli
        state: present
        username: ""
        password: ""
        host: "{{ item }}"
        fabric_forwarding_anycast_gateway: true
      with_items:
        - "{{ leaf1ip }}"
      ignore_errors: yes
      register: fabforconfig



```

##### EXPECTED RESULTS

Creation of the objects, worked in version 2.2

##### ACTUAL RESULTS

```
TASK [Configure EVPN] ***********************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not iterable
failed: [localhost] (item=x.x.x.x) => {"failed": true, "item": "x.x.x.x", "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_DplDrg/ansible_module_nxos_evpn_vni.py\", line 363, in <module>\n    main()\n  File \"/tmp/ansible_DplDrg/ansible_module_nxos_evpn_vni.py\", line 346, in main\n    result = execute_config(module, candidate)\n  File \"/tmp/ansible_DplDrg/ansible_module_nxos_evpn_vni.py\", line 272, in execute_config\n    result.update(response)\nTypeError: 'NoneType' object is not iterable\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}


TASK [Configure fabric forwarding anycast gateway] ******************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'dict' object has no attribute 'split'
failed: [localhost] (itemx.x.x.x) => {"failed": true, "item": "x.x.x.x", "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_E1__fU/ansible_module_nxos_interface.py\", line 711, in <module>\n    main()\n  File \"/tmp/ansible_E1__fU/ansible_module_nxos_interface.py\", line 637, in main\n    existing, is_default = smart_existing(module, intf_type, normalized_interface)\n  File \"/tmp/ansible_E1__fU/ansible_module_nxos_interface.py\", line 536, in smart_existing\n    existing = get_interface(normalized_interface, module)\n  File \"/tmp/ansible_E1__fU/ansible_module_nxos_interface.py\", line 303, in get_interface\n    attributes = get_manual_interface_attributes(intf, module)\n  File \"/tmp/ansible_E1__fU/ansible_module_nxos_interface.py\", line 228, in get_manual_interface_attributes\n    command_list = body.split('\\n')\nAttributeError: 'dict' object has no attribute 'split'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

```

### PR DESCRIPTION
**Pull request by trishnaguha**
Signed-off-by: Trishna Guha <trishnaguha17@gmail.com>

##### SUMMARY

- Refactor nxos_evpn_vni
- fixes #24167 (Fixes return of `NoneType` object)
- Unittest 

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

```modules/network/nxos/nxos_evpn_vni```

##### ANSIBLE VERSION

```
devel
```

### CODE REVIEW

**Comment by trishnaguha** [comment]
Ignore **CI error** for now as this is going to be merged after https://github.com/ansible/ansible/pull/24270 is merged which has a new method defined in ```module_utils/netcfg.py``` and the method is implemented in this PR.

**Review by Qalthos — APPROVED** [review]
