### ISSUE TITLE
 Failed to parse openstack.yaml with openstack plugin: 'NoneType' object has no attribute 'set'

### ISSUE THREAD

**Issue by ITD27M01** [ansible/ansible#50082]
##### SUMMARY

The bug explained in https://github.com/ansible/ansible/issues/45431 does not resolved. Openstack inventory plugin does not work starting at 2.6.4
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

openstack
##### ANSIBLE VERSION

```paste below
ansible 2.7.5
  config file = /Users/igor.tiunov/Sources/ansible-inventory-demo/ansible.cfg
  configured module search path = [u'/Users/igor.tiunov/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/igor.tiunov/Sources/ansible-inventory-demo/venv/lib/python2.7/site-packages/ansible
  executable location = /Users/igor.tiunov/Sources/ansible-inventory-demo/venv/bin/ansible
  python version = 2.7.10 (default, Aug 17 2018, 19:45:58) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]

```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/Users/igor.tiunov/Sources/ansible-inventory-demo/ansible.cfg) = [u'/Users/igor.tiunov/Sources/ansible-inventory-demo/inventory']
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /Users/igor.tiunov/tmp/.vault
HOST_KEY_CHECKING(/Users/igor.tiunov/Sources/ansible-inventory-demo/ansible.cfg) = False
INVENTORY_ENABLED(/Users/igor.tiunov/Sources/ansible-inventory-demo/ansible.cfg) = [u'openstack', u'yaml']
RETRY_FILES_ENABLED(/Users/igor.tiunov/Sources/ansible-inventory-demo/ansible.cfg) = False

```

##### OS / ENVIRONMENT

Mac OS X
##### STEPS TO REPRODUCE

create configuration based on documentation. Try to ansible-inventory --list

```yaml
plugin: openstack
expand_hostvars: no
```

##### EXPECTED RESULTS

Ansible OpenStack inventroy plugin should work.

##### ACTUAL RESULTS

```
> ansible-inventory --list
 [WARNING]:  * Failed to parse openstack.yaml with openstack plugin: 'NoneType' object has no attribute 'set'
```

```paste below

```

**Comment by ITD27M01** [comment]
https://github.com/ansible/ansible/blob/v2.7.5/lib/ansible/plugins/inventory/openstack.py#L199

**Comment by ansibot** [comment]
cc @Shrews @cloudnull @dagnello @emonty @evrardjp @juliakreger @mnaser @odyssey4me @rcarrillocruz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ghost** [comment]
Fixed here, just needs to be brought in to 2.7
https://github.com/ansible/ansible/pull/45759/commits/17d868f4b81c289428f251af8fcf84d6b39159ae

**Comment by Akasurde** [comment]
@leigh-j @ITD27M01 @jgeorgeson Could you please check if backport PRs works for you ? Thanks.

**Comment by Akasurde** [comment]
!component =lib/ansible/plugins/inventory/openstack.py

**Comment by ITD27M01** [comment]
@Akasurde 
The fix works on 2.6.11 and 2.7.5 for me.

**Comment by Akasurde** [comment]
@ITD27M01 Thanks for feedback.

**Comment by ansibot** [comment]
cc @gtema
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
Closing as per https://github.com/ansible/ansible/issues/50082#issuecomment-448904967
