### ISSUE TITLE
Getting 'module' object has no attribute 'OrderedDict' after upgrading Ansible from 2.0 to 2.2 though it is there in 'pip list'

### ISSUE THREAD

**Issue by usharaniyerra** [ansible/ansible#42550]
##### SUMMARY
We have recently upgraded Ansible version from 2.0 to 2.2. Later when we run the playbooks ..it is giving the error 'module' object has no attribute 'OrderedDict' . We have Python2.6 version. And as 'OrderedDict' is not there in python 2..6 collections..we have installed it seperatly using 'pip install ordereddict'. But still we are getting the issue..Please help to fix it. 

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

"OrderedDict"

##### ANSIBLE VERSION

```ansible --version
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 6.7 

##### STEPS TO REPRODUCE

```yaml
ansible windows -i hyphosts -m win_ping -k
SSH password:
ERROR! Unexpected Exception: 'module' object has no attribute 'OrderedDict'
to see the full traceback, use -vvv

```

##### EXPECTED RESULTS

YML's should be executed same as it executed before upgrade.

##### ACTUAL RESULTS

```
 ansible windows -i hyphosts -m win_ping -k -vvv
Using /etc/ansible/ansible.cfg as config file
SSH password:
ERROR! Unexpected Exception: 'module' object has no attribute 'OrderedDict'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible", line 103, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python2.6/site-packages/ansible/cli/adhoc.py", line 202, in run
    result = self._tqm.run(play)
  File "/usr/local/lib/python2.6/site-packages/ansible/executor/task_queue_manager.py", line 209, in run
    self.load_callbacks()
  File "/usr/local/lib/python2.6/site-packages/ansible/executor/task_queue_manager.py", line 195, in load_callbacks
    self._callback_plugins.append(callback_plugin())
  File "/usr/local/lib/python2.6/site-packages/ansible/plugins/callback/profile_tasks.py", line 78, in __init__
    self.stats = collections.OrderedDict()
AttributeError: 'module' object has no attribute 'OrderedDict'
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
This is not Ansible in general but the `profile_tasks` callback plugin, which requires OrderedDict, you can disable it for now as a work around.

Also note that 2.2 is currently not supported.

**Comment by usharaniyerra** [comment]
Thanks for the update.. My issue is resolved.. we have installed "ordereddict' and tried again. Its worked.
