### PR TITLE
Set serialization of hostvars to pickle all the object attributes

### PR DESCRIPTION
**Pull request by tiangolo**
Set serialization of hostvars to pickle all the object attributes to fix issue #12005, about the raising of the exception:

```
AttributeError: 'HostVars' object has no attribute '_inventory'
```

Here I copy my last comment in that issue describing the problem and the solutions.

In this Pull Request I'm implementing what I described as "**Option to fix it B**".

---

As @Pallokala said, the issue was introduced in commit e7b2308, specifically, in the file:

```
ansible/lib/ansible/vars/hostvars.py
```

In the last section of the class `HostVars`:

``` python
    def __getstate__(self):
        return self._lookup

    def __setstate__(self, data):
        self._lookup = data
```

starting from [this line](https://github.com/ansible/ansible/blob/e7b2308b66c7930df87d77232d5e48769ab03f58/lib/ansible/vars/hostvars.py#L64).

Those methods are [meant to be used by Pickle](https://docs.python.org/2/library/pickle.html#object.__getstate__) to generate the data to pickle and then unpickle it.

**Description of the error**:

I'm not an expert in Ansible internals, but it seems that that object is being created, then pickled and then unpickled, and after being unpickled, by the `__getstate__` and `__setstate__` methods, it only preserves its `_lookup` attribute and it doesn't have the other attributes that are created in the `__init__`.

Thereafter the object is being consulted for a host, calling the `__getitem__` method, that method checks if the host is in the `_lookup` dictionary, and as it doesn't find it, it looks for it in `host = self._inventory.get_host(host_name)`, and there is when the attribute error is raised.

**Option to fix it A**:

Remove the section for pickling and unpickling (`__getstate__` and `__setstate__`).

**Option to fix it B**:

Add all the other attributes to the return of the `__getstate__` and use them in the `__setstate__` to generate the new unpiclked object, as all the other objects are used in the method `__getitem__`.

The initial commit says that the intention was to "Speed up serialization of hostvars by simply using the internal" but I'm not sure how much this would help now, as the only thing that wouldn't be pickled would be the methods, I'm not sure that the speed up would be as much as originally intended since all the other attributes would also be pickled.

I plan on submitting a PR with the option B which is the more complex, in case the maintainers don't want it, the other option will be simpler to implement.

### CODE REVIEW

**Comment by bcoca** [comment]
he, I'm in the middle of testing 'option A' but I think this merits testing in case we can achieve a speedup and keep the correctness. cc @ansible/core

**Comment by jimi-c** [comment]
Hi @tiangolo, I fixed this in a different way via https://github.com/ansible/ansible/commit/635fa0757b06b560a7812053f8de298fc5fc2c4c. Thanks for the contribution though!

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
