### ISSUE TITLE
_ansible_delegated_vars not working in ansible 2.8.0

### ISSUE THREAD

**Issue by soori123456** [ansible/ansible#57166]
##### SUMMARY

_ansible_delegated_vars not working with ansible 2.8.0 and with ansible 2.7.9 and 2.7.10 there no any issue.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

set_fact

##### ANSIBLE VERSION

```paste below

ansible 2.8.0

```

##### CONFIGURATION

```paste below

nill
```
##### OS / ENVIRONMENT

rhel 7.6

##### STEPS TO REPRODUCE

```yaml

In a playbook we are trying a set_fact as mentioned below. this tasks is failed because of _ansible_delegated_vars
- set_fact:
     ip_hostname1_dict: "{{ ip_hostname1_dict | combine({item._ansible_delegated_vars.ansible_host : item.ansible_facts.ansible_nodename}) }}"
  with_items: "{{ host1_facts.results }}"
```

##### EXPECTED RESULTS

it should work set_fact

##### ACTUAL RESULTS

```paste below

  fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute '_ansible_delegated_vars'\n\nThe error appears to be in 'sample.yml': line 25, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- set_fact:\n  ^ here\n"
}
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by soori123456** [comment]
!component set_fact

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/utilities/logic/set_fact.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/set_fact.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
This bug was introduced in b793f08a922ebc9ad1034e47b4d364d3914822d0

Here is a reproducer:

```
- hosts: localhost
  gather_facts: false
  tasks:
    - debug:
      register: result
      delegate_to: localhost
      loop:
        - 1

    - debug:
        var: item._ansible_delegated_vars.ansible_host
      loop: "{{ result.results }}"
```

Interestingly, we have a test (`test/integration/targets/delegate_to/test_loop_control.yml`) that relies on  `_ansible_delegated_vars` but with the following note:

```
# this test is not doing what it says it does, also relies on var that should not be available
```

This indicates this change was purposeful.

**Comment by sivel** [comment]
I have confirmed with @bcoca that this change is purposeful.  `_ansible_*` vars were never meant to be exposed and were specifically named that way to indicate that they were private.

A fix was applied to Ansible 2.8 to appropriately remove this internal variables from user access.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
