### ISSUE TITLE
'dict object' has no attribute 'ansible_job_id'

### ISSUE THREAD

**Issue by skanagal** [ansible/ansible#22157]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
async_status

##### ANSIBLE VERSION
2.2.1.0

##### CONFIGURATION

```
    - name: remkaring test - tcpdump for traffic sent with DSCP for
      eos_command:
        commands:
          - bash timeout 10 tcpdump -i vlan12 -C 2 -v
        provider: "{{ provider|default(omit) }}"
      when: item ['role']=='dev2'
      with_items:
        - "{{ hostvars[inventory_hostname] }}"
      register: async_result
      async: 4000
      poll: 0
      tags:
        - mkng

    - name: checking previous task
      async_status: jid={{ async_result.ansible_job_id }}
      register: markingtest_marked_result
      until: markingtest_marked_result.finished
      #when: inventory_hostname=="device3"
      when: item ['role']=='dev2'
      with_items:
        - "{{ hostvars[inventory_hostname] }}"
      retries: 30
      tags:
```

##### OS / ENVIRONMENT
macOS - Sierra

##### SUMMARY

So basically what I am trying to do is run a tcpdump on a device. While the tcpdump is running, I am running a ‘pinging’ task from another device. Once this task is complete, I go back and check what the tcpdump has captured. However I am hitting an issue wherein ansible_job_id is having issues.

This was working on 2.1.2.0. 

Kindly take a look and let me know. The error attachment is here:
[error.txt](https://github.com/ansible/ansible/files/811750/error.txt)

##### EXPECTED RESULTS

I expect the async_status to check on the status of the " tcpdump task" and return me the results.

##### ACTUAL RESULTS
I get the following error

"msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'ansible_job_id'\n\n

**Comment by jhawkesworth** [comment]
Not a windows issue

bot_broken

**Comment by bcoca** [comment]
can you use a debug to show what async_result has?

**Comment by skanagal** [comment]
Looks like the logic that I have for "when" statement is what's causing the problem here. For example, if I have "when: inventory_hostname=="172.30.155.25" the task seems to work. But when I have a two statement logic that maps a variable in host_vars the task fails.

**TEST 1**
Output when I have "when: inventory_hostname=="172.30.155.25" is attached. 
[logs.txt](https://github.com/ansible/ansible/files/827843/logs.txt)


My host_vars is:

```
---
vlans:
  - vlanid: 12
    name: acl_test_vlan

role: dev2

switchports:
  - name: Ethernet33
    mode: access
    access_vlan: 12

  - name: Ethernet20
    mode: access
    access_vlan: 12

```

**TEST 2**

The when statement logic now:

   ```
   when: item ['role']=='dev2'
      with_items:
        - "{{ hostvars[inventory_hostname] }}"
```

**The error when playbook is now run**:

_async_task debug output_:

```
_TASK [debug] *******************************************************************
ok: [172.30.155.25] => {
    "async_result": {
        "changed": false,
        "msg": "All items completed",
        "results": [
            {
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "_ansible_parsed": true,
                "ansible_job_id": "256047833499.879",
                "finished": 0,
                "item": {
                    "ansible_check_mode": false,
                    "ansible_python_interpreter": "python",
                    "ansible_version": {
                        "full": "2.2.1.0",
                        "major": 2,
                        "minor": 2,
                        "revision": 1,
                        "string": "2.2.1.0"
                    },
                    "eos_purge_vlan_trunk_groups": true,
                    "eos_users": [
                        {
                            "encryption": "md5",
                            "name": "superadmin",
                            "privilege": 15,
                            "role": "network-admin",
                            "secret": "$1$J0auuPhz$Pkr5NnHssW.Jqlk17Ylpk0"
                        },
                        {
                            "name": "simplebob",
                            "nopassword": true,
                            "privilege": 0,
                            "role": "network-operator"
                        }
                    ],
                    "group_names": [
                        "eos_demo_group"
                    ],
                    "groups": {
                        "all": [
                            "172.30.155.25"
                        ],
                        "eos_demo_group": [
                            "172.30.155.25"
                        ],
                        "ungrouped": []
                    },
                    "inventory_dir": "/ansible-sample/Desktop/new certs /l2_eth_bridging",
                    "inventory_file": "/ansible-sample/Desktop/new certs /l2_eth_bridging/hosts",
                    "inventory_hostname": "172.30.155.25",
                    "inventory_hostname_short": "172",
                    "omit": "__omit_place_holder__f8142e3c95e933e6034dc037eb7d0ff80550d333",
                    "playbook_dir": "/ansible-sample/Desktop/new certs /l2_eth_bridging",
                    "provider": {
                        "authorize": true,
                        "host": "172.30.155.25",
                        "password": "admin",
                        "transport": "cli",
                        "username": "admin"
                    },
                    "role": "dev2",
                    "switchports": [
                        {
                            "mode": "trunk",
                            "name": "Ethernet33"
                        },
                        {
                            "mode": "trunk",
                            "name": "Ethernet20"
                        }
                    ],
                    "vlans": [
                        {
                            "name": "acl_test_vlan",
                            "vlanid": 12
                        }
                    ]
                },
                "results_file": "/root/.ansible_async/256047833499.879",
                "started": 1
            }
        ]
    }
}



TASK [checking previous task] **************************************************
fatal: [172.30.155.25]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'ansible_job_id'\n\nThe error appears to have been in '/ansible-sample/Desktop/new certs /l2_eth_bridging/cleanup.yml': line 27, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: checking previous task\n      ^ here\n"}_
```

Is there a known caveat around using the "when" logic in conjunction with async?

**Comment by bcoca** [comment]
I see you have an extra space in  ```item ['role']=='dev2'```, it should be ```item['role'] == 'dev2'```  or ```item.role == 'dev2'```

**Comment by skanagal** [comment]
Hey Brian,

I removed the space, yet it did not work. I am able to run other tasks but async_status with or without that space. I have attached logs.
[logs_withoutspace.txt](https://github.com/ansible/ansible/files/828081/logs_withoutspace.txt)
[logs_withspace.txt](https://github.com/ansible/ansible/files/828082/logs_withspace.txt)

**Comment by jimi-c** [comment]
Hi @skanagal, sorry for the late follow-up but the issue here is that, when using a loop + async, the async_job_id is contained within the `results: []` list in the registered value. So, to access it in your second task, you need to loop over those results instead of the inventory hostvars.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
