### PR TITLE
pacman: fix closing parenthesis

### LINKED ISSUE #32733: Pacman module crashes with get_bin_path error
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

pacman

##### ANSIBLE VERSION

```
ansible 2.5.0 (devel 4464635787) last updated 2017/11/09 12:50:13 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/thom/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/thom/git/ansible/lib/ansible
  executable location = /home/thom/.pythonenvs/ansible/bin/ansible
  python version = 3.6.3 (default, Oct 24 2017, 14:48:20) [GCC 7.2.0]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT
ArchLinux

##### SUMMARY
The pacman module crashes with Python 2 and 3.
 
##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  become: yes
  tasks:
    - pacman: name=subversion state=present
```

##### EXPECTED RESULTS

SVN is installed.

##### ACTUAL RESULTS

```
Using module file /home/thom/git/ansible/lib/ansible/modules/packaging/os/pacman.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: thom
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/thom/.ansible/tmp/ansible-tmp-1510228783.2242217-178302118505177 `" && echo ansible-tmp-1510228783.2242217-178302118505177="` echo /home/thom/.ansible/tmp/ansible-tmp-1510228783.2242217-178302118505177 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmprmvh2gkm TO /home/thom/.ansible/tmp/ansible-tmp-1510228783.2242217-178302118505177/pacman.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/thom/.ansible/tmp/ansible-tmp-1510228783.2242217-178302118505177/ /home/thom/.ansible/tmp/ansible-tmp-1510228783.2242217-178302118505177/pacman.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-; /home/thom/.pythonenvs/ansible/bin/python3 /home/thom/.ansible/tmp/ansible-tmp-1510228783.2242217-178302118505177/pacman.py; rm -rf "/home/thom/.ansible/tmp/ansible-tmp-1510228783.2242217-178302118505177/" > /dev/null 2>&1'"'"' && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_6sla8yao/ansible_module_pacman.py", line 437, in <module>
    main()
  File "/tmp/ansible_6sla8yao/ansible_module_pacman.py", line 391, in main
    pacman_path = module.get_bin_path('pacman', True)
AttributeError: 'tuple' object has no attribute 'get_bin_path'

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_6sla8yao/ansible_module_pacman.py\", line 437, in <module>\n    main()\n  File \"/tmp/ansible_6sla8yao/ansible_module_pacman.py\", line 391, in main\n    pacman_path = module.get_bin_path('pacman', True)\nAttributeError: 'tuple' object has no attribute 'get_bin_path'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
```

### PR DESCRIPTION
**Pull request by mkrizek**
##### SUMMARY

Introduced in https://github.com/ansible/ansible/pull/30913
Fixes https://github.com/ansible/ansible/issues/32733

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
pacman

##### ANSIBLE VERSION

```
devel
```

##### ADDITIONAL INFORMATION

### CODE REVIEW

**Comment by mkrizek** [comment]
cc @dagwieers

**Comment by dagwieers** [comment]
Maybe we need integration tests so the module is actually tested ?
