### ISSUE TITLE
delegate_facts to remote hosts 2.3.1.0_1

### ISSUE THREAD

**Issue by AngryBeaver** [ansible/ansible#26274]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
delegate_facts

##### ANSIBLE VERSION
2.3.1.0_1

##### SUMMARY
delegate_facts is broken on 2.3.1.0_1 same still works on 2.3.0.0_1

##### STEPS TO REPRODUCE
Use an Inventory with one local and one ssh host
...hosts
test1 ansible_connection=local
test2 ansible_connection=ssh (+ credentials + port + etc)
....

```playbook2.yaml
---
- hosts: test2
  tasks:
    - name: Set_Fact
      set_fact:
        foo: "bar"
      delegate_to: test1
      delegate_facts: true
    - name: Gather DB server IP address
      setup: filter=ansible_default_ipv4
      delegate_to: test1
      delegate_facts: true
    - assert:
        that: "{{ hostvars['test1']['foo'] == 'bar' }}"
        msg: "Server foo is {{ hostvars['test1']['foo'] }}, expected : bar"
    - assert:
        that: "{{ hostvars['test1']['ansible_default_ipv4'] is defined }}"
        msg: "Server ipv4 is {{ hostvars['test1']['ansible_default_ipv4'] }}, expected: not empty"
    - debug: msg="{{ hostvars['test1']['ansible_default_ipv4'] }}"
```
##### EXPECTED RESULTS
Should be fine as it was in 2.3.0.0_1

##### ACTUAL RESULTS
TASK [assert] ***************************************************************************************
fatal: [test2]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'foo'\n\nThe error appears to have been in '/ansible/playbook2.yml': line 13, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n      delegate_facts: true\n    - assert:\n      ^ here\n"}

##### FURTHER HINTS
inverting the hosts d.h. run on remote host and delegate to localhost works fine.
```
```playbook1.yaml
---
- hosts: test1
  tasks:
    - name: Set_Fact
      set_fact:
        foo: "bar"
      delegate_to: test2
      delegate_facts: true
    - name: Gather DB server IP address
      setup: filter=ansible_default_ipv4
      delegate_to: test2
      delegate_facts: true
    - assert:
        that: "{{ hostvars['test2']['foo'] == 'bar' }}"
        msg: "Server foo is {{ hostvars['test2']['foo'] }}, expected : bar"
    - assert:
        that: "{{ hostvars['test2']['ansible_default_ipv4'] is defined }}"
        msg: "Server ipv4 is {{ hostvars['test2']['ansible_default_ipv4'] }}, expected: not empty"
    - debug: msg="{{ hostvars['test2']['ansible_default_ipv4'] }}"
```
this works as expected
So it is only broken with remote hosts.

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Sorry to say `set_fact` is not a fact, so `delegate_facts` does not apply to it.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
