### PR TITLE
Use .code instead of .getcode() as py24 does not have .getcode()

### LINKED ISSUE #3608: get_url fails on rhel5 hosts using ansible 2.0.2.0
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

get_url
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /home/icansible/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

[defaults]
callback_whitelist = profile_tasks,timer
forks = 50
host_key_checking = false
inventory = ~/ansible/hosts-dev
pattern = NONE  
retry_files_enabled = false
transport = ssh
##### OS / ENVIRONMENT

control host rhel6
target hosts rhel5
##### SUMMARY

get_url fails with error on rhel5 targets when using 2.0.2.0, but works on rhel6 targets.
revert back to 2.0.1.0 and the get_url module works on both rhel5 and rhel6 targets
##### STEPS TO REPRODUCE

```

---
- hosts: someRhel5Server:someRhel6Server
  tasks:

    - name: demo the error
      get_url:
        url: "https://github.com/ansible/ansible/blob/devel/README.md"
        dest: /tmp/
        validate_certs: no
```
##### EXPECTED RESULTS

expected file to be downloaded to both target hosts
##### ACTUAL RESULTS

on the rhel5 target

```
fatal: [rhel5server]: FAILED! => {"changed": false, "dest": "/tmp/", "failed": true, "gid": 0, "group": "root", "mode": "01777", "msg": "Request failed", "owner": "root", "response": "An unknown error occurred: addinfourl instance has no attribute 'getcode'", "secontext": "system_u:object_r:tmp_t:s0", "size": 69632, "state": "directory", "status_code": -1, "uid": 0, "url": "https://github.com/ansible/ansible/blob/devel/README.md"}
```

on the rhel6 target

```
changed: [rhel6server]
```

Note: -vvvv and ANSIBLE_DEBUG=y produced no additional useful information

### PR DESCRIPTION
**Pull request by sivel**
##### ISSUE TYPE
- Bugfix Pull Request
##### ANSIBLE VERSION

```
v2.0/v2.1/v2.2
```
##### SUMMARY

Python 2.4 does not have `r.getcode()`.  `.getcode()` was introduced in 2.6.  Use `r.code` instead, which works in py2.4-py2.7

This will need cherry picked into stable-2.1 also.

Fixes https://github.com/ansible/ansible-modules-core/issues/3608

### CODE REVIEW

**Comment by sivel** [comment]
cc @alikins

**Comment by Idanatcox** [comment]
Thanks for this fix
Any idea when it's going to be backported to stable-2,0?
