### ISSUE TITLE
elb_target_group modules sometimes throws a TypeError

### ISSUE THREAD

**Issue by ramonamis** [ansible/ansible#36628]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
elb_target_group

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/Users/ramonamis/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ramonamis/.virtualenvs/devops/lib/python2.7/site-packages/ansible
  executable location = /Users/ramonamis/.virtualenvs/devops/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### SUMMARY
While trying to create a target group with ansible most of the time works, sometimes it throws the following error:
```
TASK [lb-route53-create : Create lb target group] ******************************
Friday 23 February 2018  10:24:20 +0000 (0:00:00.037)       0:19:28.899 ******* 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object has no attribute '__getitem__'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_pBY2Rv/ansible_module_elb_target_group.py\", line 672, in <module>\n    main()\n  File \"/tmp/ansible_pBY2Rv/ansible_module_elb_target_group.py\", line 667, in main\n    create_or_update_target_group(connection, module)\n  File \"/tmp/ansible_pBY2Rv/ansible_module_elb_target_group.py\", line 541, in create_or_update_target_group\n    current_tg_attributes = get_tg_attributes(connection, module, tg['TargetGroupArn'])\nTypeError: 'NoneType' object has no attribute '__getitem__'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```
Re-running works like a charm, with exactly the same code

##### STEPS TO REPRODUCE

This is the code I am using to create the target groups:
```yaml
        elb_target_group:
          name: "{{ lb_target_group_name }}"
          protocol: "{{ lb_protocol }}"
          port: "{{ lb_port }}"
          vpc_id: "{{ aws_vpc }}"
          health_check_path: "{{ lb_health_check_path }}"
          health_check_protocol: "{{ lb_health_check_protocol }}"
          health_check_interval: 5
          health_check_timeout: 2
          healthy_threshold_count: 2
          unhealthy_threshold_count: 2
          successful_response_codes: "200-299"
          stickiness_enabled: "{{ lb_stickiness_enabled }}"
          stickiness_lb_cookie_duration: "{{ lb_stickiness_cookie_duration }}"
          deregistration_delay_timeout: "{{ lb_deregistration_delay_timeout }}"
          targets: "{{ lb_targets }}"
          modify_targets: "{{ lb_modify_targets }}"
          state: present
```

I only notice this issue when we deploy multiple target groups in a row, for instance, we have a loop which deploys multiple customers and this happens after a few loops. Re-running works like a charm.

##### EXPECTED RESULTS

target group is created
##### ACTUAL RESULTS

```
TASK [lb-route53-create : Create lb target group] ******************************
Friday 23 February 2018  10:24:20 +0000 (0:00:00.037)       0:19:28.899 ******* 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object has no attribute '__getitem__'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_pBY2Rv/ansible_module_elb_target_group.py\", line 672, in <module>\n    main()\n  File \"/tmp/ansible_pBY2Rv/ansible_module_elb_target_group.py\", line 667, in main\n    create_or_update_target_group(connection, module)\n  File \"/tmp/ansible_pBY2Rv/ansible_module_elb_target_group.py\", line 541, in create_or_update_target_group\n    current_tg_attributes = get_tg_attributes(connection, module, tg['TargetGroupArn'])\nTypeError: 'NoneType' object has no attribute '__getitem__'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/elb_target_group.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/elb_target_group.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @willthames @wimnat
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by s-hertel** [comment]
Just making a note that a custom waiter would fix this. Going to try to work on that soon.

**Comment by Akasurde** [comment]
@ramonamis Could you please check if PR #37079 works for you and let us know? Thanks,

needs_info

**Comment by Akasurde** [comment]
resolved_by_pr #37079

**Comment by ramonamis** [comment]
@Akasurde this is pretty hard to reproduce, but I will try my best

**Comment by ansibot** [comment]
cc @jillr @tremble
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by yravid** [comment]
Had the same issue first time after upgrading from ansible 2.7.18 to 2.9.11

**Comment by ansibot** [comment]
Thank you very much for your interest in Ansible. Ansible has migrated much of the content into separate repositories to allow for more rapid, independent development. We are closing this issue/PR because this content has been moved to one or more collection repositories.

* lib/ansible/modules/cloud/amazon/elb_target_group.py -> https://galaxy.ansible.com/community/aws

For further information, please see:
https://github.com/ansible/ansibullbot/blob/master/docs/collection_migration.md
