### ISSUE TITLE
Jinja template evaluation fails on undefined variables even when error_on_undefined_vars = False

### ISSUE THREAD

**Issue by rrtj3** [ansible/ansible#4025]
I have some jinja templates that I make use of variables that may or may not be defined, but have Jinja if/elif statements that deal with this correctly. Using git bisect I was able to track down the first bad commit to this:

62b39d3de535370ae7e98a3fbdcd1799819523ee is the first bad commit
commit 62b39d3de535370ae7e98a3fbdcd1799819523ee
Author: Michael DeHaan michael@ansibleworks.com
Date:   Sun Jul 21 08:52:00 2013 -0400

```
Fix for saving conditionals in variable expressions.
```

After this commit creation of the template fails with this error:

fatal: [127.0.0.1] => {'msg': "One or more undefined variables: 'dict' object has no attribute 'facts'", 'failed': True}
fatal: [127.0.0.1] => {'msg': "One or more undefined variables: 'dict' object has no attribute 'facts'", 'failed': True}

even when the "error_on_undefined_vars = False" is set in the ansible.cfg file.  Here is an example of such template:

``` jinja2
{% for nic in virtual_machine.vm_nic|dictsort %}
{% if nic[1].kickstart == "yes" %}
{% if loop.index0 == 0 %}
network --onboot yes --device=eth0 --bootproto=static --ip={{ eth0.facts.network_ipaddress }} --netmask={{ eth0.facts.network_netmask }} --gateway={{ eth0.facts.network_gateway }} --nameserver={{ eth0.facts.network_nameservers[0] }} --noipv6 --activate
{% elif loop.index0 == 1 %}
network --onboot yes --device=eth1 --bootproto=static --ip={{ eth1.facts.network_ipaddress }} --netmask={{ eth1.facts.network_netmask }} --gateway={{ eth1.facts.network_gateway }} --nameserver={{ eth1.facts.network_nameservers[0] }} --noipv6 --activate
{% elif loop.index0 == 2 %}
network --onboot yes --device=eth2 --bootproto=static --ip={{ eth2.facts.network_ipaddress }} --netmask={{ eth2.facts.network_netmask }} --gateway={{ eth2.facts.network_gateway }} --nameserver={{ eth2.facts.network_nameservers[0] }} --noipv6 --activate
{% endif %}
{% endif %}
{% endfor %}
```

Please let me know if you need any more information.
