### ISSUE TITLE
Fail module error when using variables as items in EL6

### ISSUE THREAD

**Issue by rmfitzpatrick** [ansible/ansible#20309]
Ansible is throwing the following during a conditional check for the fail module:
```
    "msg": "The conditional check '{{ item }} is not defined' failed.
The error was: 'AnsibleEnvironment' object has no attribute '_generate'
The error appears to have been in '.../roles/role_one/tasks/main.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
```

bisect shows that this was introduced in 86eadc58140df09fe4e06e7e6e555e091c059d07.

This is causing failures in Tower 3.0.3 installs.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### OS / ENVIRONMENT
EL6.  Not observed in EL7.

##### SUMMARY
The condition that uses variables for items is incorrectly parsed. 

##### STEPS TO REPRODUCE
```
# repro.yml
---
- hosts: my_group
  roles:
    - role: role_one
      used_vars:
        - var_one
        - var_two
```
```
# roles/role_one/tasks/main.yml:
---
- name: Ensure expected variables are defined
  fail: msg="{{ item }} value missing and is required"
  when: "{{ item }} is not defined"
  with_items: '{{ used_vars }}'
```
`ansible-playbook -i inventory -e "var_one=123 var_two=234" repro.yml`

**Comment by alikins** [comment]
ping @jimi-c

**Comment by bcoca** [comment]
that condition does not make much sense, the following would be the correct way to write it
```
when: item is not defined
```

but that would never execute as `with_items` will always define an item if it gets a list, if not it will skip the task anyways.

**Comment by alikins** [comment]
What version of jinja2 is installed?  (the Environment._generate() method causing the error was added in jinja 2.5)

**Comment by rmfitzpatrick** [comment]
@alikins `python-jinja2-2.2.1-2.el6_5.x86_64`.  Has the version requirement changed?

**Comment by rmfitzpatrick** [comment]
@bcoca, I agree the condition is not ideal but has worked with 2.2 until the most recent rc.  Is it invalid syntax?

**Comment by bcoca** [comment]
Ansible is not currently working with the latest jinja2 (2.9), but we have not set bottom version requirements (which we might need now due to the fix for the security issue).

**Comment by bcoca** [comment]
@rmfitzpatrick it violates the 'no moustaches when when:' rule as it does double interpolation, which is not guaranteed to work.

**Comment by bcoca** [comment]
IF you need the double interpolation, look at doing:

```when: hostvars[inventory_hostname][item] is defined```

possibly user the `vars` dictionary instead.

**Comment by alikins** [comment]
Looks like jinja2.2 jinja2.environment.Template doesnt have _generate(), but there is a jinja2.environment.generate() which could be used.  And it looks like newer jinja2 still has the jinja2.environment.generate() so it could potentially be used from conditional.py

**Comment by jimi-c** [comment]
Closing This Ticket
===================

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jimi-c** [comment]
Also cherry-picked to stable-2.2 and 2.1.
