### ISSUE TITLE
cannot import name AnsibleOptionsError

### ISSUE THREAD

**Issue by ksingh7** [ansible/ansible#13361]
I am willing to use ansible 2.0 for this reason i cloned ansible repository and source /hacking/env-setup and getting this error.

Does someone has any clue

Note : I am happily using ansible 1.9 on the same machine , and also wants ansible 2.0. OS -- OSX

all of these are installed `paramiko PyYAML Jinja2 httplib2 six`

```
teeri:ansible ksingh$
teeri:ansible ksingh$  git pull --rebase
Current branch devel is up to date.
teeri:ansible ksingh$
teeri:ansible ksingh$
teeri:ansible ksingh$ git submodule update --init --recursive
Submodule path 'lib/ansible/modules/core': checked out '0e043f8c588a9cf3de63151fce5ae5afc03eb951'
teeri:ansible ksingh$
teeri:ansible ksingh$
teeri:ansible ksingh$
teeri:ansible ksingh$ git branch
* devel
  stable-2.0
teeri:ansible ksingh$
teeri:ansible ksingh$
teeri:ansible ksingh$
teeri:ansible ksingh$ source ./hacking/env-setup
running egg_info
creating lib/ansible.egg-info
writing requirements to lib/ansible.egg-info/requires.txt
writing lib/ansible.egg-info/PKG-INFO
writing top-level names to lib/ansible.egg-info/top_level.txt
writing dependency_links to lib/ansible.egg-info/dependency_links.txt
writing manifest file 'lib/ansible.egg-info/SOURCES.txt'
reading manifest file 'lib/ansible.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'v2'
no previously-included directories found matching 'docsite'
no previously-included directories found matching 'ticket_stubs'
no previously-included directories found matching 'packaging'
no previously-included directories found matching 'test'
no previously-included directories found matching 'hacking'
no previously-included directories found matching 'lib/ansible/modules/core/.git'
no previously-included directories found matching 'lib/ansible/modules/extras/.git'
writing manifest file 'lib/ansible.egg-info/SOURCES.txt'

Setting up Ansible to run out of checkout...

PATH=/Users/ksingh/ansible-2.0/ansible/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/opt/X11/bin
PYTHONPATH=/Users/ksingh/ansible-2.0/ansible/lib:
MANPATH=/Users/ksingh/ansible-2.0/ansible/docs/man:

Remember, you may wish to specify your host file with -i

Done!

teeri:ansible ksingh$
teeri:ansible ksingh$
teeri:ansible ksingh$ ansible --version
Traceback (most recent call last):
  File "/Users/ksingh/ansible-2.0/ansible/bin/ansible", line 39, in <module>
    from ansible.errors import AnsibleError, AnsibleOptionsError, AnsibleParserError
ImportError: cannot import name AnsibleOptionsError
teeri:ansible ksingh$
```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  T

**Comment by kikicarbonell** [comment]
I have the same problem installing ansible 2.0.0.2-1~trusty on Ubuntu 14.04

**Comment by bhavicp** [comment]
I'm having this issue after upgrading from 1.9.3 to 2.0. I've run the ./hacking/env-setup as well. Debian Jessie.

**Comment by stevejarvis** [comment]
@bcoca Why is this not a bug? Following the directions [here](http://docs.ansible.com/ansible/intro_installation.html#running-from-source) end in error for us. I see the same going from 1.9.2 -> 2.0.1 on Centos6.

**Comment by puneetjindal** [comment]
@ksingh7 I am having a similar issue. Please help me out if anybody has a solution to this
I get the following error while running the playbook

> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named callbacks
> fatal: [suspicious_einstein]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
> I install Ansible through apt-get  and pip as well

**Comment by sivel** [comment]
The problem occurs when ansible 1.9 is installed alongside 2.0, and something is inserting additional paths into PYTHONPATH (such as easy_install) ahead of the paths needed by 2.0 which causes 2.0 to import 1.9 files.

**Comment by tskarthick** [comment]
I got the below error. could some one tell how to fix it?

Traceback (most recent call last):
  File "/x/home/auto/ansible/bin/ansible-playbook", line 39, in <module>
    from ansible.errors import AnsibleError, AnsibleOptionsError, AnsibleParserError
ImportError: cannot import name AnsibleOptionsError

**Comment by devops-dude** [comment]
+1  I get the same thing on OSX even after running env-setup.  I removed 1.9.

**Comment by jianga** [comment]
I had this error too. I had a previous version (1.5.4) installed a long while back that I had forgotten about, so I uninstalled it: sudo apt-get remove ansible.

**Comment by astorije** [comment]
FYI, having the same issue after installing with brew: `brew update && brew install ansible`.

``` sh
$ ansible --version
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/2.1.0.0/libexec/bin/ansible", line 45, in <module>
    from ansible.errors import AnsibleError, AnsibleOptionsError, AnsibleParserError
ImportError: cannot import name AnsibleOptionsError
```

@bcoca, I know you closed this as a user question, but this thread is what appears first when Googling the error message, so it would be great to see a solution or a link to one here. Thanks :-)
I'll post one here if I can find one.

**Comment by astorije** [comment]
Of course, it's right when I post that I solve it...

I had `ansible` installed with both `brew` and `pip`. To solve this, I did something along the lines of:

``` sh
sudo pip uninstall ansible
brew update
brew uninstall ansible19
brew uninstall ansible
brew cleanup -s
brew install ansible
```

Definitely some superfluous ones, but that gives some idea.

**Comment by devops-dude** [comment]
When I was getting similar errors to the above most of my issues were due to a corrupt Python uninstall.  I believe I used 

```
brew uninstall python
brew install python
```

I then used pip to reinstall Ansible etc as it seems to work better on El Capitan for me than brew.

More information on Python for OSX is located here:

http://docs.python-guide.org/en/latest/starting/install/osx/

**Comment by willthames** [comment]
Another way to find clashing Ansible versions is with

```
python -c 'import sys; print sys.path'
```

You may find an unexpected version of ansible in there (you might have to look inside the site-packages directories)

**Comment by crater9893** [comment]
sudo pip uninstall ansible
sudo pip install ansible

Worked for me...
